### ISSUE TITLE
Is it possible to create documents with fixed/undeletable blocks?

### ISSUE THREAD

**Issue by laszbalo** [facebook/draft-js#100]

**Comment by hellendag** [comment]
One high-level way to do this would be to check for the undeletable block(s) in `onChange`. If they were removed during some operation, you could discard the incoming `EditorState`. There isn't anything currently built into the framework to prevent blocks from being deleted during editing, but you have control over the `EditorState`, so you can handle edits as you see fit.

I think it mostly depends what your UI and use case are. What are these fixed blocks?

**Comment by laszbalo** [comment]
Thanks for your answer! After checking the docs and some examples, the onChange callback seemed the right place to start with, however I haven't had a chance to actually try it out yet.

I am building a résumé builder and, at the moment, users have to fill in a long dynamic form built with Bootstrap. I want users have the ability to add block level and inline styling. E.g. emphasize a keyword with bold, or with slightly bigger point size etc., and to show linting information while editing.
I am wondering, if instead of the simple form, I would just use one draft-js editor instance with undeletable blocks.

For example a sample document would look like this, where the **Professional Experience** and *Used technologies* blocks are undeletable but editable, they are expected to show up the same way in the final document.
The other blocks in brackets must be edited, but could not be deleted, otherwise they will be omitted from the final doc.

> 
> **Professional Experience**
> 
> [Title]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Start Date–End Date]
> [Company Name]
> [Location]
> [Description]
> *Used technologies:*
> [List of technologies]

In this example, users could add new blocks by hitting enter, or pasting content only if they are editing the [Description] block, since I do not  expect the other blocks to expand into multiple blocks.

Also, it would be nice, if the blocks with brackets would behave like html form controls with place-holders.

Based on what I have read, this seems doable on user-land, so I just need to give it a try.
With thanks,
Laszlo

**Comment by hellendag** [comment]
Sounds like you may just want a series of separate Draft components, each with their own `EditorState` objects. Then you can define placeholders for each.

You can style it to look like a single editor if you'd like, and perhaps manage up/arrow key movement to jump forward or backward.

**Comment by laszbalo** [comment]
Thanks for your suggestion, though I am a bit puzzled, how to handle selection in this case(when the app is styled as a single doc). Ctrl-A, Shift-[Up|Down] and mouse selection seems to work only inside the active div.

**Comment by hellendag** [comment]
If you have separate Draft components for each block, then yes, selection behavior can only work within the active editor component. If everything is a single Draft editor component, then select-all and mouse selection would involve the whole editor.

**Comment by laszbalo** [comment]
Sorry, what I meant, was if there is a separate Draft component for each blocks, then trying to mimic the selection could be quite difficult.

**Comment by cgestes** [comment]
Wrote some logic to handle that case.

What I did was to define entities for what I want to be read-only, then in handleBeforeInput, handleKeyCommand, etc.. I discard the change when the selection match a read-only entity.

**Comment by hellendag** [comment]
> Sorry, what I meant, was if there is a separate Draft component for each blocks, then trying to mimic the selection could be quite difficult.

Right, if there are separate components, then you can't have a selection state that includes more than one of them. Is that what you mean?

**Comment by hellendag** [comment]
@cgestes For your read-only entities, you might also consider using the `IMMUTABLE` mutability setting on them. While selection can still occur on these, edits are disallowed. http://facebook.github.io/draft-js/docs/advanced-topics-entities.html#mutability

**Comment by cgestes** [comment]
They are `IMMUTABLE` already, but I also want to protect from deletion.

It's more `READONLY` than just `IMMUTABLE` that I need.

**Comment by hellendag** [comment]
Got it. In that case, yeah, you'll want to enforce that the deletion can't occur. Your approach sounds fine.

Another option might be to add a check within your `onChange` handler to scan for your expected entities. If any are removed or affected, you could reject the change and not set the new `editorState`.

**Comment by laszbalo** [comment]
@hellendag 

> Right, if there are separate components, then you can't have a selection state that includes more than one of them. Is that what you mean?

Yes, that's what I meant. So if I used many Draft.js instances, styled to look like just one editor, then I would have to mimic the native selection behaviour in order not to confuse my users. E.g. in the case of the 'Select-All' action on the active Draft.js instance, I should manually set the selection state inside the onChange handler for each Draft.js siblings, etc.
I think I'll just stick to your first suggestion.

@cgestes 

Thanks for your input. That looks a viable approach as well. I'll definitely keep it in mind.

**Comment by jaulz** [comment]
@cgestes Could you please share your code? Thanks!
