### ISSUE TITLE
Press 'enter', type in Chinese, the videos inserted from youtube.com would rerender

### ISSUE THREAD

**Issue by geng890518** [facebook/draft-js#1000]
Now my version is 0.9.1. I insert video from youtube.com. When I press 'enter' and type in Chinese, the video would rerender. How to solve it?

**Comment by houkanshan** [comment]
Draft.js will force a re-render while using IME at the first of a line, i.e. "press `enter`, and type Chinese".

According to the [comment](https://github.com/facebook/draft-js/blob/master/src/component/handlers/composition/DraftEditorCompositionHandler.js#L121...L125):

> We also re-render when the composition occurs at the beginning of a leaf, to ensure that if the browser has created a new text node for the composition, we will discard it.

https://github.com/facebook/draft-js/blob/master/src/component/handlers/composition/DraftEditorCompositionHandler.js#L149...L158

**Comment by geng890518** [comment]
@Is there any way to prevent it ? Thanks!

**Comment by jlotus** [comment]
I encountered the same problem，How did you finally solve the problem?

**Comment by Marckon** [comment]
at this moment, has anyone kindly post a solution
