### ISSUE TITLE
Initial paste from menu in Firefox doesn't work

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1005]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
On the first try, with multi-block content, the 'paste' option in the menu in Firefox doesn't insert text that was copied.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
Steps to reproduce:
1. Open the 'plaintext' example in Firefox on the master branch of Draft (v0.10.0 or so)
2. Type:
```
testing 123
testing
```
3. Drag to select all the text that was entered.
4. In the menu options choose 'copy'.
5. Move the cursor to somewhere in the middle of the first line.
6. In the menu optoins choose 'paste'.
7. Notice that nothing was inserted.

**What is the expected behavior?**
The copied text should be inserted.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
It *is* present in Firefox, is *not* present in Chrome, and I haven't verified other browsers yet.
Does not seem to happen with Draft v0.9.0, but we should double-check.

**Comment by thibaudcolas** [comment]
I can't reproduce this issue with my test editor (https://jsfiddle.net/thibaudcolas/Lo2zL37h/), in Firefox 57 – Draft.js v0.10.4. This may be due to the big Firefox update that happened sometime between now and february, or?

GIF:

![firefox-paste-draftjs](https://user-images.githubusercontent.com/877585/34992462-f613e452-fad5-11e7-88c2-82cece44802e.gif)

**Comment by flarnie** [comment]
Thanks for looking into this @thibaudcolas !
You are absolutely right - I just double-checked and both 0.10.0 and the lastest master branch no longer have this issue. 🎉
