### ISSUE TITLE
auto-correct creates bad state in Android 5.0

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1010]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
Entering text that triggers auto-correct and then deleting it leaves things in a weird state.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
You can reproduce this on Android 5.0 on the 'try draft' demo page.
1) enter 'aaa' and then hit 'space'. Notice autocorrect will change it to something.
2) delete all those characters. Notice it deletes it all at once and unfocuses the editor.
3) enter 'bbb' and hit 'space'. Notice the previously deleted characters reappear.

Disabling 'autocorrect' and 'spellcheck' in android 5.0 chrome either doesn't work or doesn't fix this bug.

**What is the expected behavior?**
Characters should be gone forever if we delete them, unless we 'undo'.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

Draft 0.9.1
Draft 0.10.0

Android 5.0 chrome
(thankfullly not Androit 6.0 or 7.0 I don't think)

**Comment by flarnie** [comment]
![android5_autocorrect_bug](https://cloud.githubusercontent.com/assets/1114467/22945663/d340e4fa-f2a9-11e6-8ae6-a39cbff367ed.gif)

**Comment by Guardiannw** [comment]
I have seen this as well

**Comment by flarnie** [comment]
Note - I'm only seeing this in Android 5.0.2. Android 5.1 shows issue #888 instead.

**Comment by Guardiannw** [comment]
I am on android 5.1.0 and chrome 55 and am seeing this issue, not #888.

**Comment by will-hart** [comment]
I have this issue in Chrome 55 on Android 7.1.1, Nexus 6P. Are this issue and #1011 duplicates of #911?

**Comment by flarnie** [comment]
Basically we don't have resources to tackle Android support right now - still open to PRs for this, but not actively working on mobile web support.

**Comment by flarnie** [comment]
Merging this into a general Android bug issue - see https://github.com/facebook/draft-js/issues/1895
