### ISSUE TITLE
Deleting composition and starting new one results in extra character appearing

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1011]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
In Android 5.1 (not 5.0 or other versions afaik);
When you write a word, delete it, and then write another word, the first character of the previously deleted word appears after the focus/cursor.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
1) Visit https://facebook.github.io/draft-js/ on an Android 5.1 device (not 5.0 or 6.* or 7.*)
2) Enter non-whitespace characters, then press 'space'.
3) Delete all the characters entered.
4) Again enter non-whitespace characters, and press 'space'.
5) Notice that the first character of the characters you deleted earlier will appear right after the focus/cursor.

![draftjs_extra_char_bug_android_5point1](https://cloud.githubusercontent.com/assets/1114467/22955143/6b093506-f2cf-11e6-9616-09c32c5b0d81.gif)

**What is the expected behavior?**
There should be no random extra character appearing after the cursor.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

Only Android 5.1 as far as I have been able to test. I don't have access to every version of Android yet, but have tested on Android 5.0, 6.0.1, and 7.1.1. None of those reproduce this bug, but 5.0 does have a similar bug related to autocomplete - see #1010.

**Comment by Guardiannw** [comment]
Is this one tied to #1010?  It seems like the same problem

**Comment by flarnie** [comment]
Perhaps - looking into it. If the same fix works for both that will be most excellent. :)

**Comment by flarnie** [comment]
Merging this into a general Android bug issue - see https://github.com/facebook/draft-js/issues/1895
