### ISSUE TITLE
How to mock text selection in test environment

### ISSUE THREAD

**Issue by eessex** [facebook/draft-js#1041]
Is there a way to mock selecting of an editor's existing text within a test environment?  

For example, I'd like select any text, then click a button that applies a link, in order to determine if the correct block type was applied. 

I attempted manipulating the selectionState using Immutable's toJS and fromJS, but then lost functions available to selectionState. 

Are there other methods by which I could manually set my selection?

**Comment by kedromelon** [comment]
I like to use `merge` to update selection. For example:

```es6
const selection = editorState.getSelection();

const newSelection = selection.merge({
  anchorKey: key,
  anchorOffset: 0,
  focusKey: key,
  focusOffset: 0
});

const newEditorState = EditorState.forceSelection(editorState, newSelection);
```

Apologies if I misunderstood the question!

**Comment by eessex** [comment]
Yes, this seems like it will do it - thanks!

**Comment by hellendag** [comment]
🎉
