### ISSUE TITLE
how to set style (margin-top:10px) on a paragraph?

### ISSUE THREAD

**Issue by bojoyzhou** [facebook/draft-js#1043]
I am going to control the paragraph spacing before and after with a value that user input.

I known that `setInlineStyleOverride` can set `inlineStyle` on a `span` tags, but how to deal with a `unstyled block`?

I have viewed the `Block Styling` document, but what if the value(10px) is by user input?

Maybe passing the `margin` to an entitiy is a workaround, what else can I do?

**Comment by spicyj** [comment]
See custom blocks: https://draftjs.org/docs/advanced-topics-custom-block-render-map.html#content.

**Comment by elie222** [comment]
I struggled with the options in that link as 'unstyled' gets overridden easily.

Another solution (not perfect, but may fit your needs) is:

Add this to your CSS is also an option:

```css
.public-DraftStyleDefault-block {
  margin-bottom: 1em;
}
```
