### ISSUE TITLE
Feature Request: multiple cursor support

### ISSUE THREAD

**Issue by snnsnn** [facebook/draft-js#1046]
Draft.js is a great product, it is here to stay and certainly change our text editing habits forever.

I was wondering if is there a way to make Draft.js multi cursor compliant. Some point in time there will be use cases but I am afraid at that time community will be too large and with so many people depending on it, changing API will be almost impossible.

Multi cursor editing is very common especilly in code editing. New and very practical use cases, such as real time collaborative editing over internet, is emerging. Some examples could be:

* [https://togetherjs.com](https://togetherjs.com)
* [https://floobits.com](https://floobits.com)
* [http://etherpad.org](http://etherpad.org)

One can add many features by extending the API but having multiple cursors is not one of them. Please can you consider it, it will open windows to many possibilities.

**Comment by niveditc** [comment]
>  Some point in time there will be use cases but I am afraid at that time community will be too large and with so many people depending on it, changing API will be almost impossible.

I guess we have reached that point! I don't think adding multiple cursor support is feasible & will be a pain to add to the API in a compatible way.
