### ISSUE TITLE
Double <br> in quote breaks it

### ISSUE THREAD

**Issue by Nikcrysis** [facebook/draft-js#1049]
I'm trying to create a quote from HTML code like this:

        const {editorState} = this.state;
        const contentState = editorState.getCurrentContent();
        data.text = 'This is the first line<br>This is the second line and it\'s ok<br><br>This should be the third line';
        const blocksFromHTML = convertFromHTML(data.text);
        const state = ContentState.createFromBlockArray(
            blocksFromHTML.contentBlocks,
            blocksFromHTML.entityMap,
        );

        let newState = EditorState.push(editorState, state, 'added-quote')
        newState = RichUtils.toggleBlockType(
            newState,
            'blockquote'
        );

        this.setState({
            editorState: newState,
        });

And I'm getting this result:

![default](https://cloud.githubusercontent.com/assets/7072251/23513889/493e8984-ff6e-11e6-95d0-12404123fd57.PNG)

What is going on:
Blockquote element correctly process one '\<br\>' tag, but when it finds double '\<br\>' tag it breaks blockquote and paste least part of text in normal block.

Are there any solutions to resolve this problem, because quote can contain differet number of newline?

p.s. '\n' symbols instaed of '\<br\>' are ignored.

**Comment by colinjeanne** [comment]
The reason here is that `<br>` and `<br><br>` are interpreted as different things. `<br>` is a soft line break - it acts as a line break within a single block. `<br><br>` acts as a break between blocks. This is a pretty reasonable heuristic, in my opinion, given the visual difference between `<br>` and `<br><br>`.

Finally, `\n` is ignored because it is interpreted as a single whitespace character in HTML.

**Comment by Nikcrysis** [comment]
So is there any way to insert double newline?

**Comment by colinjeanne** [comment]
It depends on what your goal is. The difference between `<br>` and `<br><br>` is handled as part of the conversion from HTML. There are no hooks to change this. However, depending on your needs have various avenues available:

1. If you want everything in the same block always then you can generate combine the various blocks after converting from HTML while being sure to separate them with a `\n`.

2. If you just want `<br><br>` to be interpreted as two newlines you could override the second parameter of `convertFromHTML` with a function that converts the string to a DOM and, in the process, separate all consecutive `<br>` tags with some sentinel text. Once you get the blocks back from the conversion you remove the sentinel text.

There's probably other options available as well.

**Comment by Nikcrysis** [comment]
Thank you for reply, solved this by replacing `<br><br>` with `<br><span></span><br>`!
