### ISSUE TITLE
Paste improvement

### ISSUE THREAD

**Issue by Heilemann** [facebook/draft-js#105]
I've looked around to find a discussion around why paste strips out all style, but haven't been able to find anything. I'd love to read more about the issues around this.

It is less than optimal for many scenarios, but in particular it's problematic with things like anchors I think, where recovering what's lost is more of a problem.

One approach to solving some of the problems to occur might be solved with something like this?

1. When user copies from draftjs, the selection is stored in a 'virtual clipboard', if you will.
2. When the user pastes, the pasted content is compared to the virtual clipboard content, if it is identical, it can be pasted with styles without funky after effects. If it isn't identical it's from another source, and style should be stripped out.

**Comment by spicyj** [comment]
We already do that if `stripPastedStyles` is false:

https://github.com/facebook/draft-js/blob/1e099d4aa4e626a21f420ad5ee25c3236aa5cc6b/src/component/handlers/edit/editOnPaste.js#L95-L102

Does that solve your problem?

**Comment by Heilemann** [comment]
It sounds perfect.
