### ISSUE TITLE
Document available ContentBlock types

### ISSUE THREAD

**Issue by wyqydsyq** [facebook/draft-js#1051]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Docs don't contain a reference list of available ContentBlock types, leaving new users to guess or dig through the source to find them.

**What is the expected behavior?**
Docs should contain a reference list of available ContentBlock types so new users can implement block styling functionality easily.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Current live docs

**Comment by hellendag** [comment]
Sounds useful! The docs sort of touch on it and denote the Flow type `DraftBlockType`, but you're right that it would be good to have a clearer enumeration in `ContentBlock` docs.
