### ISSUE TITLE
Possible

### ISSUE THREAD

**Issue by hoffmannjan** [facebook/draft-js#1053]
Hi,

I'm wondering is it possible to get state from convertToRaw method as Immutable.js structure?
I've got whole project setted up in Immutable, also converter for my own format from RAW operates on Immutable.js data, but I noticed that data from convertToRaw is just POJO.

Possible to change It or have another method?

**Comment by fisx** [comment]
"POJO"?

also, could you update the subject line of this issue so that people who search the issue list can decide whether they want to click on it?

thanks!

**Comment by tobiasandersen** [comment]
Why do you want that? The data is an Immutable.js structure before you're run it through `convertToRaw`. The whole point of using `convertToRaw` is to convert it FROM immutable.js to a plain json structure (likely because you need to store it somewhere).

**Comment by spicyj** [comment]
I'm going to close this but happy to reopen if you can articulate your use case more concretely. As others said, EditorState is already an Immutable.js object.
