### ISSUE TITLE
0.10.0 DefinitelyTyped Types

### ISSUE THREAD

**Issue by benshope** [facebook/draft-js#1056]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
0.10.0 types are not included or available in https://github.com/benshope/DefinitelyTyped
which means the new syntax passed to `new CompositeDecorator([` throws an error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
npm i --save @types/draft-js@0.10.0

**What is the expected behavior?**
It would be great if types were included in the package or updated in DefinitelyTyped - I feel uneasy about updating types in DefinitelyTyped myself

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
N/A

**Comment by mitermayer** [comment]
Hi @benshope  please feel free to create an issue on the DefinitelyTyped repository itself.
