### ISSUE TITLE
How to get an entity data in blockRendererFn if DraftEntity.get is deprecated?

### ISSUE THREAD

**Issue by bojoyzhou** [facebook/draft-js#1061]
I want to bulid some custom block components ( like image ).
Then, I hope they are in their own file.

Below is a approach I found in [draft-js-image-plugin](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-image-plugin/src/index.js)

![image](https://cloud.githubusercontent.com/assets/5258697/23691753/5bbd1cb0-0405-11e7-8fbd-2772138b49ac.png)

But, how to get an entity data in blockRendererFn if DraftEntity.get is deprecated?

**Comment by tobiasandersen** [comment]
You could make use of currying, and pass a getter function for your editorState:

```
blockRendererFn: (getEditorState) => (block) => {
  const editorState = getEditorState()
  const contentState = editorState.getCurrentContent()
  // Now you can use your existing code, but with contentState.getEntity() instead
}
```

Use it like this with your editor component:

`<Editor blockRendererFn={blockRenderFn(this.getEditorState)} {...yourOtherProps} />`

Where the `getEditorState` function only returns the editorState:
  `getEditorState = () => this.props.editorState`

**Comment by bojoyzhou** [comment]
Good idea. I will try it,thank you very much.
