### ISSUE TITLE
Draft example files don't render in IE and Edge in windows 10

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1062]
**Do you want to request a *feature* or report a *bug*?**
This is a bug

**What is the current behavior?**
After cloning the master branch of the Draft.js repository, running `npm update` and `npm run build` in the main directory, and opening the example file `examples/draft-0-10-0/color/color.html` the example editor does not render and the console shows an error:
```
'Draft' is undefined
Function code (4) (15, 1)
```
The same example file will render fine in Chrome and Firefox on the same Windows 10 laptop.

**What is the expected behavior?**
I expect the example to render with no errors.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Master branch of Draft.js on Internet Explorer and Edge in Windows 10.

**Comment by flarnie** [comment]
This is blocking me from testing the v0.11.0-alpha branch of Draft before releasing it on npm.

**Comment by nsfmc** [comment]
in the course of debugging something else i tried triggering this from the latest `master` commit using the steps outlined here and proxying localhost through browserstack, one time the build failed i got exactly the `'Draft' is undefined error`, the second time i reran the build and now i just get the unique key error. i'm not sure why the draft build failed though. ¯\_(ツ)_/¯

![](http://dl.dropboxusercontent.com/u/406291/Screenshots/nZLE.png)

**Comment by flarnie** [comment]
For better or worse, it seems to persist on my laptop. I have re-run the build a couple of times. But it gives me a chance to figure out the cause at least.

**Comment by flarnie** [comment]
So I was editing the path to the `Draft.js` file and it just started working. I still don't know why. For now I am unblocked to manually test the 0.10.1 and 0.11.0@next releases, but still want to figure out why this was happening.

I had tried clearing my browser cache, and that didn't help, but something like that could be the cause.

**Comment by flarnie** [comment]
Haven't run into this again - I assume it was related to the browser caching.
