### ISSUE TITLE
Get generated HTML

### ISSUE THREAD

**Issue by schmi85** [facebook/draft-js#1071]
Is there any way to retrieve the full html, which is generated by the editor? So I am basically searching for a way to do the opposite of `convertFromHTML()`.

I searched the whole API pages, but I could not find anything beyond: `convertToRaw(this.state.editor.getCurrentContent())`

Thanks for Help!

**Comment by tylercraft** [comment]
Hey @schmi85. This isn't a feature that we plan on adding to Draft. 

@sstur said it well in issue #683  

>  I think the reason this is not in Draft core is because the principles behind Draft discourage using HTML at all. React in general wants you to think of the browser/DOM as an implementation detail and work with state and declarative views instead of HTML.
> 
> In many ways HTML is sub-optimal for storing/serializing this kind of structured content. I think many modern apps that use Draft probably render to DOM or native views without producing any intermediate HTML.

All that said, there are some open source Draft plugins that do allow this, for instance:
https://github.com/sstur/draft-js-export-html
