### ISSUE TITLE
Doesn't work in IE11 with es6-shim

### ISSUE THREAD

**Issue by nasrullahs** [facebook/draft-js#1073]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
On IE11, using es6-shim, any page with the draft js editor is blank and has the error:
    "ReferenceError: 'Symbol' is undefined
Installing babel-polyfill fixes the issue, even when es6-shim is not used.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
IE11 on Windows 10

**Comment by spicyj** [comment]
We don't reference Symbol anywhere in the Draft codebase. Do you have a stack trace to indicate where the error is coming from?

**Comment by flarnie** [comment]
Looks like this has gotten stale - please open a new issue if you are still running into this, and help us reproduce it with a stack trace and more info. Thanks!
