### ISSUE TITLE
Wrong editorState after deleting (Android)

### ISSUE THREAD

**Issue by Nikcrysis** [facebook/draft-js#1076]
On android device Chrome browser if I type some text like:

```
Qweqwe
Asdasd
Zxczxc
```

Then i press and hold backspace to clear all text.
Then write `Yui`, press whitspace and get
```
Yui Q
A
```

Seems like editorState doesn't save it's state correctly.

**Comment by iEchoic** [comment]
+1, I'm seeing the same thing. Deleting on Android is quite broken in my experience.

**Comment by flarnie** [comment]
Merging this into a general Android bug issue - see https://github.com/facebook/draft-js/issues/1895
