### ISSUE TITLE
Triple click selects next block as well as current block

### ISSUE THREAD

**Issue by dburrows** [facebook/draft-js#108]
![image](https://cloud.githubusercontent.com/assets/44306/13373236/9d1bdb8e-dd59-11e5-8f2d-c54e671e5d3e.png)

Bug present in OS X, Chrome 48 & Safari 9.0.3 - not present in Firefox 41.0.1
![draft js rich text editor framework for react]

**Replication Steps**

Using the demo editor on frontpage of the Draft website

* enter 4 lines of text
* triple click on second line
* click H1 to turn this block into a H1 block
* both second and third block will be converted to H1

Expected: only second block should be converted to H1

**Comment by hellendag** [comment]
Same as #86 :)

**Comment by hellendag** [comment]
Awesome detailed bug report, btw. Thanks.

**Comment by dburrows** [comment]
No problem, sorry about the duplicate, will search properly next time ;)
