### ISSUE TITLE
Image in quote

### ISSUE THREAD

**Issue by Nikcrysis** [facebook/draft-js#1080]
Is there any way to insert entity like image in quoteblock?

**Comment by flarnie** [comment]
Hi @Nikcrysis - can you explain more about your use case? I'm guessing that there isn't, but I'd like to hear more and see if we can figure something out.

**Comment by flarnie** [comment]
I would need more info in order to help with this question - closing for now, since we use issues as a bug tracker and this isn't a reproducible bug.
