### ISSUE TITLE
Update comments in `editOnInput.js`

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1085]
The [inline comments about `editOnInput` are no longer accurate](https://github.com/facebook/draft-js/blob/07892ba479bd4dfc6afd1e0ed179aaf51cd138b1/src/component/handlers/edit/editOnInput.js#L30-L39) - this method is called on every keystroke and is the main way that we update editorState ever since https://github.com/facebook/draft-js/commit/07892ba479bd4dfc6afd1e0ed179aaf51cd138b1

If you're trying to understand how events are handled and updates are processed in Draft.js this could be a good first bug.

**Comment by morrme** [comment]
I'm new but I'd like to help.

**Comment by flarnie** [comment]
Hi @morrme - thanks for commenting. Were you still interested in this? Any questions?

**Comment by itssujan** [comment]
@flarnie if this is still open, I can take a stab..
