### ISSUE TITLE
How to give a focus effect to my Draft JS Editor border?

### ISSUE THREAD

**Issue by jackmatrix** [facebook/draft-js#1088]
I understand that the draft js editor is not a classic textarea element. I applied some styles to make it look better. However, i can't find this little trick that doing a natural html focus effect when i'm focusing on my draftjs editor. I am not a css expert, i've tried to using the :active pseudo class the effect disappear once a release the click.

I just want the borders to be like a classic html input focus effect.

How can a set up this ?

thanks

**Comment by tobiasandersen** [comment]
Answered the same question yesterday on SO, I'll just link that here for future reference: http://stackoverflow.com/questions/42921101/how-to-give-a-focus-effect-to-my-draft-js-editor-border

**Comment by ambewas** [comment]
Thanks for the info @tobiasandersen , I've submitted a [PR to include this information](https://github.com/facebook/draft-js/pull/1179) in the editor API reference, as it was missing.

**Comment by flarnie** [comment]
Just merged https://github.com/facebook/draft-js/pull/1179 - thanks @ambewas
