### ISSUE TITLE
onFocus of Editor doesn't gets fired everytime in IE11

### ISSUE THREAD

**Issue by abhijeetahuja** [facebook/draft-js#1091]
The onFocus event gets called intermittently on ie11

**Comment by hellendag** [comment]
Can you provide a jsfiddle with a minimal repro?

**Comment by flarnie** [comment]
Looks like this has gotten stale, and we need more info in order to reproduce the bug. Closing for now - please do open a new issue with more details if you can @abhijeetahuja since we want to document and fix any browser bugs. :)
