### ISSUE TITLE
Error when deleting character before an entity on master branch

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1093]
**Do you want to request a *feature* or report a *bug*?**
This is a bug.

**What is the current behavior?**
If you put the cursor just before an entity and try to delete, an error is thrown:
```
Uncaught Error: There should only be one entity range within this removal range.
    at invariant (Draft.js:751)
    at getEntityRemovalRange (Draft.js:9847)
    at getCharacterRemovalRange (Draft.js:9821)
    at Object.removeRange (Draft.js:868)
    at removeTextWithStrategy (Draft.js:1997)
    at keyCommandPlainBackspace (Draft.js:10570)
    at onKeyCommand (Draft.js:9127)
    at editOnKeyDown (Draft.js:9218)
    at Draft.js:6239
    at Object.ReactErrorUtils.invokeGuardedCallback (react-dom.js:9017)
invariant @ Draft.js:751
getEntityRemovalRange @ Draft.js:9847
getCharacterRemovalRange @ Draft.js:9821
removeRange @ Draft.js:868
removeTextWithStrategy @ Draft.js:1997
keyCommandPlainBackspace @ Draft.js:10570
onKeyCommand @ Draft.js:9127
editOnKeyDown @ Draft.js:9218
(anonymous) @ Draft.js:6239
ReactErrorUtils.invokeGuardedCallback @ react-dom.js:9017
executeDispatch @ react-dom.js:3006
executeDispatchesInOrder @ react-dom.js:3029
executeDispatchesAndRelease @ react-dom.js:2431
executeDispatchesAndReleaseTopLevel @ react-dom.js:2442
forEachAccumulated @ react-dom.js:15423
processEventQueue @ react-dom.js:2645
runEventQueueInBatch @ react-dom.js:9041
handleTopLevel @ react-dom.js:9052
handleTopLevelImpl @ react-dom.js:9129
perform @ react-dom.js:14724
batchedUpdates @ react-dom.js:8805
batchedUpdates @ react-dom.js:12852
dispatchEvent @ react-dom.js:9204
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

This can be reproduced on the master branch in the 'entity' example.

**What is the expected behavior?**
The character should delete as expected.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
This is just on the master branch because it was introduced by https://github.com/facebook/draft-js/commit/413e63a12e0a145e7d05c993b825e19c4ece2996

**Comment by flarnie** [comment]
Going to re-test this but I think it should be fixed now.

**Comment by spicyj** [comment]
Verified 543831d9e40b360bd82d350b3cc7afb9b7c060a8 fixed this.
