### ISSUE TITLE
EditorState.undo() doesn't works

### ISSUE THREAD

**Issue by jackmatrix** [facebook/draft-js#1097]
I'm trying to create a simple undo button when undo content hen clicking on it.

`<button onClick={EditorState.undo(this.state.editorstate)} >Undo</button>`

But nothing happens. Yet when i do ctrl+z, the content is undo. 

So how to trigger an undo event by simply clicking on a button.

PS : i don't want to use the undo plugin because, i don't know why but, it causes me some focus/blur issues (not good for the rendering)

Anny suggestions ?

**Comment by ngocanhaptech** [comment]
<button onClick={EditorState.undo(this.state.editorstate)} >Undo</button>
should be : 
<button onClick={ ()=> { this.setState({ editorState: EditorState.undo(this.state.editorState)}) }} >Undo</button>
