### ISSUE TITLE
Editor moves document to last position of block when in big block of text and hitting enter

### ISSUE THREAD

**Issue by MarkSMT** [facebook/draft-js#1110]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Document moves to end of textblock.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
- paste big block of text
- hit enter anywhere
- document will move to end of block instead of staying put

**What is the expected behavior?**
Staying put.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Error also is reproducible in the demo editor on draft-js.org

**Comment by michelson** [comment]
this is a dupe of #304 , please check this issue 🙏 
best regards

**Comment by MarkSMT** [comment]
@michelson thx! closed!
