### ISSUE TITLE
Merge `examples/draft-0-10-0/universal/.gitignore` into top level `.gitignore`

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1111]
I think keeping everything in the top level `.gitignore` is cleaner and easier to follow. Feel free to argue if there is a reason to keep nested `.gitignore` files around.

It would be nice to have:
 - `examples/draft-0-10-0/universal/.gitignore` merged into top level .`gitignore`
 - `examples/draft-0-9-1/universal/.gitignore` merged into top level .`gitignore`
 - add `examples/draft-0-<9-1 and 10-0>/universal/yarn.lock` to the `.gitignore`

**Comment by flarnie** [comment]
@nsfmc you might be interested. nbd either way - I'll get to it eventually.

**Comment by morrme** [comment]
I'd like to help with this one as well @flarnie

**Comment by oscarmorrison** [comment]
@flarnie I had a crack at this one. Let me know your thoughts: #1218
