### ISSUE TITLE
Link example not rendering link when rich text is pasted

### ISSUE THREAD

**Issue by brijeshb42** [facebook/draft-js#112]
In the [link example](https://github.com/facebook/draft-js/blob/master/examples/link/link.html), the links are only rendered when explicitly created through `Add Link` button but not when rich text containing links are pasted.
Also, when pasting rich text, the raw data of the block map contains entity data as
```
data: {
  url: "https://facebook.github.io/draft-js/docs/api-reference-editor-state.html#getblocktree",
}
```
Here, the key is `url` but the link example creates and uses key `href`. At first I thought this was the problem, but even after fixing the key usage, the links are not rendered on pasting.

**Comment by hellendag** [comment]
Sorry, the link example wasn't really built with the paste case in mind. I should have thought of that. :)

> Here, the key is url but the link example creates and uses key href.

Good catch, I should have been consistent about that. I was also inconsistent about the entity type, using `link` instead of `LINK`.

Fixing these two items will repair the example.

**Comment by brijeshb42** [comment]
This [PR](https://github.com/facebook/draft-js/pull/114) tries to fix the above issue that I created by adding the consistency you suggested. It can now render pasted link in rich text successfully.
