### ISSUE TITLE
ace

### ISSUE THREAD

**Issue by christophepas** [facebook/draft-js#1129]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

**What is the expected behavior?**

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

**Comment by flarnie** [comment]
It seems like this issue may have been submitted by mistake? Feel free to reopen or open a new issue if that is not the case.

**Comment by christophepas** [comment]
Wow indeed, very sorry about that, no idea how I did this. Sorry again flarnie
