### ISSUE TITLE
Uncaught Invariant Violation: There should only be one entity range within this removal range

### ISSUE THREAD

**Issue by bkniffler** [facebook/draft-js#113]
I'm having trouble deleting immutable entities with removeRange sometimes. This can be reproduced by cloning this https://github.com/bkniffler/draft-wysiwyg and changing example/draft/data.js entities to be immutable, and running `node example`. Then try to drag/drop the youtube video with its handle.

![ohne titel](https://cloud.githubusercontent.com/assets/4349324/13378517/640a3682-de09-11e5-9b54-3274472e6e51.jpg)

It is triggered by https://github.com/bkniffler/draft-wysiwyg/blob/master/src/draft.js#L104

```jsx
drop(e) {
      var blockKey = e.dataTransfer.getData("text");
      // Set timeout to allow cursor/selection to move to drop location
      setTimeout(()=> {
         // Get content, selection, block
         var block = this.state.value.getCurrentContent().getBlockForKey(blockKey);
         var editorStateAfterInsert = DraftWysiwyg.AddBlock(this.state.value, null, block.getType(), Entity.get(block.getEntityAt(0)).data);

         block = editorStateAfterInsert.getCurrentContent().getBlockForKey(blockKey);
         // Get block range and remove dragged block
         var targetRange = new SelectionState({
            anchorKey: block.getKey(),
            anchorOffset: 0,
            focusKey: block.getKey(),
            focusOffset: block.getLength()
         });
         var afterRemoval = Modifier.removeRange(editorStateAfterInsert.getCurrentContent(), targetRange, 'backward');

         // Workaround, revious removeRange removed entity, but not the block
         var rawContent = convertToRaw(afterRemoval);
         rawContent.blocks = rawContent.blocks.filter(x=>x.key !== block.getKey());
         var newState = EditorState.push(this.state.value, ContentState.createFromBlockArray(convertFromRaw(rawContent)), 'remove-range');
         this.setState({value: newState});
      }, 1);
   }
```

The error is being thrown in https://github.com/facebook/draft-js/blob/06891490069d3ccfb89caf53f33a7545d39fc3ec/src/model/modifier/getCharacterRemovalRange.js#L57
```jsx
  // Find the entity range that overlaps with our removal range.
  var entityRanges = getRangesForDraftEntity(block, entityKey).filter(function (range) {
    return start < range.end && end > range.start;
  });

  invariant(
    entityRanges.length == 1,
    'There should only be one entity range within this removal range.'
  );
```

With MUTABLE entities, these lines are not reached, thus no error is thrown. 

Is this a bug? Or is there an issue with my code?

**Comment by hellendag** [comment]
Awesome start to this demo. I'm really excited about this -- I think it will help us define the right patterns for drag/drop behavior in the framework.

I'm not sure what's up with the invariant being thrown there. That function should only be called if there is an entity and the start and end entities of the target are the same, so I'm not really sure how it would end up at that state. I'll see if I can track down what the entity values are.

I think we'll need a `handleDrop` method instead of using `onDrop` directly. That way we can reasonably access the target `SelectionState` without needing the `setTimeout` (https://gist.github.com/hellendag/6cd425613caabb7f238d#file-gistfile1-txt-L169). This may be part of the cause of the issue above.

Also, for your toolbar, if your objective is just to render the toolbar when the selection is non-collapsed, you can pass the `SelectionState` through to your toolbar component as a prop. Then do something like:

```
class MyToolbar ... {
  render() {
    if (this.props.selectionState.isCollapsed()) {
      return <span />;
    }
    const position = /* calculate position based on DOM selection */
    return /* fancy toolbar at position */;
  }
}
```

This is what I did for Notes, and it has worked well for us. Because the current `SelectionState` is always up-to-date via `onChange`, it should always be accurate for the `render` call. It's a nice benefit of having the selection information within the model.

I have a couple of selection utilities that I'm going to add to the repo here so that you guys don't have to solve that stuff from scratch.

**Comment by bkniffler** [comment]
I agree with having a handleDrop prop on Editor would be beneficial and cleaner than using onDrop on a wrapper div.

I've implemented your suggestion, and eliminated changing the components state in a onMouseUp handler. Though the selectionState checks and position calculations still remain in the editor component, not in the toolbar component, as I find it more suitable in case someone wants to overwrite renderToolbar to serve those props. Maybe I'll create a toolbar wrapper that will take care of that.

```jsx
// Render the default-toolbar
   renderToolbar(){
      const editorState = this.state.value;
      const onChange = ::this.updateValue;
      // Get current selection (from draft)
      const selectionState = this.state.value.getSelection();
      // Nothing selected? No toolbar please.
      if (selectionState.isCollapsed()) {
         return null;
      }

      // Get current selection (natively)
      var selected = getSelected();
      // Get selection rectangle (position, size) and set to state
      var rect = selected.getRangeAt(0).getBoundingClientRect();

      var info = {left: rect.left, top: rect.top, width: rect.width};
      return this.props.renderToolbar
          ? this.props.renderToolbar({...info, editorState, selectionState, onChange})
          : <Toolbar {...info} editorState={editorState} selectionState={selectionState} onChange={onChange}/>;
   }
   
   render() {
      // Set drag/drop handlers to outer div as editor won't fire those
      return (
         <div onClick={::this.focus} onDrop={::this.drop} onBlur={::this.blur}>
            <Editor customStyleMap={styleMap} 
                    editorState={this.state.value} 
                    onChange={::this.updateValue}
                    ref="editor"
                    blockRendererFn={::this.blockRenderer}/>
            {this.renderToolbar()}
         </div>
      );
   }
```

There is a lot of things to tackle. Besides obvious stuff like browser compatibility for drag/drop and resizing (which doesn't yet work too well in firefox and ie), blocks/entities don't currently feel much like parts of the document flow, for example removing them via backspace is really clumsy.

**Comment by bkniffler** [comment]
Not occurring any more with latest version, thanks.

**Comment by rpmonteiro** [comment]
I'm getting exactly the same problem - but when I change the entity to a 'MUTABLE' one, as you say, it doesn't get to that part of the code and it runs fine.

Any ideas?

**Comment by MarkSMT** [comment]
I had a similar issue when removing an entity..

```JS
// data variable contains blockKey
const selectionState = new SelectionState({
        anchorKey: data.blockKey,
        anchorOffset: 0,
        focusKey: data.blockKey,
        focusOffset: 1,
      });

      // IMPORTANT NOTE: contentStateBefore.getBlockForKey(data.blockKey).getLength() instead of focusOffset: 1 throws errors.. while the prev mentioned fn returns 0.. 
      
      const contentAfterRemoval = Modifier.removeRange(contentStateBefore, selectionState, 'backward');
```

This is basicly how i fixed it.. not sure why the fn to get the focusOffset returned 0 instead of 1.
