### ISSUE TITLE
Not working correctly when used Grammarly plugin.

### ISSUE THREAD

**Issue by unixzii** [facebook/draft-js#1130]
When I enabled **Grammarly** on the page that used draft.js, it will sometimes perform wrongly.

Follow steps below to reproduce the bug:
1. Enable Grammarly.
2. Make some typo in an existing article or text fragment.
3. Open the popup window by clicking Grammarly suggestion bubble.
4. Close the popup window and you won't be able to type anything then.

**Comment by colinjeanne** [comment]
Grammarly mucks around with the HTML. https://github.com/facebook/draft-js/issues/616

**Comment by unixzii** [comment]
Yep, things can be a lot more complex when other libraries modified the DOM. But actually, Grammarly just make a new `div` and pull everything to it, leaving the **React Root** untouched. I guess it's the `EditorState` itself has some bugs.

**Comment by unixzii** [comment]
Since the same issue is mentioned before, I decide to close this.
