### ISSUE TITLE
spacebar remove whole previous text line in multi line text

### ISSUE THREAD

**Issue by GenesisSam** [facebook/draft-js#1146]
**Do you want to request a *feature* or report a *bug*?**
a bug!

**What is the current behavior?**
when i typed multi line text -> move cursor to start of second line -> hit the `spacebar` -> removed whole previous text lines

it's happend on `facebook.com`, `draftjs.org` and my own project

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

![draft-spacebar-error](https://cloud.githubusercontent.com/assets/7623883/25080179/6e3c6b56-237d-11e7-9d65-a28fb5737323.gif)

**What is the expected behavior?**
just regular `space` append. same like office program.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

i tested, and some browser, OS happens different bug.
MacBook pro(version 10.12.4)
* chrome 57.0.2987.133 (64-bit) ==> remove previous text line
* safari ==> 'space' is input but didn't render anything

Windows 11
* IE11 ==> work fine
* Chrome 56.0.2924.87 ==> 'space' is input but didn't render anything
* FF 51.0.1 (32bit) ==> 'space' is input but didn't render anything

**Comment by MadebyAe** [comment]
Same here... Only in Chrome

**Comment by MadebyAe** [comment]
I think the v0.7.0 is working fine but >=0.9.x is failing.

**Comment by GenesisSam** [comment]
@MadebyAe thx let me know fine version.
but i have done things on version "0.10.0". i couldn't downgrade :(

**Comment by MadebyAe** [comment]
@GenesisSam I am planning migrate to https://github.com/draft-js-plugins/draft-js-plugins this version is using your same version

**Comment by flarnie** [comment]
Fixed by #1155  - We can close this issue once the fix is in a released version of Draft. Thanks for reporting!

**Comment by MadebyAe** [comment]
@flarnie Great! Thank you!

**Comment by GenesisSam** [comment]
@familom Thx!
can i ask when next version Draft.js release? approximately...

**Comment by flarnie** [comment]
This should be fixed in [Draft v0.10.1](https://github.com/facebook/draft-js/releases/tag/v0.10.1).
