### ISSUE TITLE
Changelog not updated?

### ISSUE THREAD

**Issue by iEchoic** [facebook/draft-js#1147]
I've been trying to decide if I should upgrade to 0.10, but the changelog hasn't been updated in 7 months. Is this file being maintained, or is the best way to understand the changes to try to read through the commits?

**Comment by mmmoussa** [comment]
We should update the changelog, but in the meantime take a look at the [release page](https://github.com/facebook/draft-js/releases) and the [v0.10 API Migration guide](https://draftjs.org/docs/v0-10-api-migration.html).

**Comment by flarnie** [comment]
Thanks for flagging this - we released v0.10.0 from a branch and didn't mirror the commit updating the changelog to master. I'll update it now.
