### ISSUE TITLE
Copy/paste unstyled blocks between editors merges blocks

### ISSUE THREAD

**Issue by DawnWright** [facebook/draft-js#1153]
When copying from one draft editor and then pasting into another, I am seeing neighboring unstyled blocks (`<div>`) merged together. Here is a small test that can be added to `convertFromHTMLToContentBlocks-test.js` which demonstrates the problem:

```
  it(`must not merge tags when converting adjacent <div />`, () => {
    const html_string = `
      <h1>a</h1>
      <div>a</div>
      <div>b</div>
    `;

    const blocks = convertFromHTMLToContentBlocks(html_string);

    expect(blocks.contentBlocks.length).toBe(3);
  });
```
result:
```
    Expected value to be (using ===):
      3
    Received:
      2
```

Note that the existing test in that file already tests neighboring divs:
```
    const html_string = `
      <div>a</div>
      <div>b</div>
    `;
```
That test passes on account of the following special case, which adds `div` to the `workingBlocks`:
https://github.com/facebook/draft-js/blob/507925ad60638734872dba52efa2d0b66cd94e4b/src/model/encoding/convertFromHTMLToContentBlocks.js#L558
But in my new test case, the additional `h1` causes the divs to merge.

I'm wondering, why do we filter out `unstyledElement` here?
https://github.com/facebook/draft-js/blob/507925ad60638734872dba52efa2d0b66cd94e4b/src/model/encoding/convertFromHTMLToContentBlocks.js#L173
Removing this filter fixes the problem, but I imagine there was a reason for this code, so I'm hoping someone more familiar with the code could help me understand this a little better.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

0.11.0-alpha
Chrome, MacOS

**Comment by colinjeanne** [comment]
Dupe of #738?

**Comment by DawnWright** [comment]
> Dupe of #738?

Indeed, it looks like it! Can we get https://github.com/facebook/draft-js/pull/927 merged up?
