### ISSUE TITLE
Update `createClass` use in Draft website code

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1160]
In React v15.5 a warning was added for the impending deprecation of the `createClass` syntax. We have several calls to the deprecated `createClass` in the website code, and it should be updated.

[Check out the notes about how to update the syntax](https://facebook.github.io/react/blog/#migrating-from-react.createclass), and then please update each place we call it:

https://github.com/facebook/draft-js/search?utf8=%E2%9C%93&q=createClass&type=

**Comment by morrme** [comment]
I'm on it!

**Comment by niveditc** [comment]
I'm going to claim this one as a first fix to figure out the process of contributing to open source :)

**Comment by niveditc** [comment]
This is no longer needed after the Docusaurus migration in #1759
