### ISSUE TITLE
"The syntax of the command is incorrect." when running "universal" example in windows 10

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1166]
I get an error with "The syntax of the command is incorrect." in Windows 10 when running either `npm run demo` or `yarn run demo` in the `universal` example.

Hopefully folks who are used to Windows can help out here. I'm sure it's just a different syntax that I don't know off the top of my head to get this running. @Daniel15 ?

**Comment by Daniel15** [comment]
Interesting... I'll try to take a look soon and work out what's happening!

**Comment by Daniel15** [comment]
#1168

**Comment by flarnie** [comment]
Thanks @Daniel15 :)
