### ISSUE TITLE
inlineStyle didn't render properly on compositional language.

### ISSUE THREAD

**Issue by GenesisSam** [facebook/draft-js#1169]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when able or disable inlineStyle on compositional language didn't render properly
i am using Korean.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

it happens on ```draftjs.org```
![draf-inlinestyle-bug](https://cloud.githubusercontent.com/assets/7623883/25324833/0f4051c2-2903-11e7-874a-e60a2036f7bb.gif)

**What is the expected behavior?**
in this case, inlineStyle(bold) disabled properly typing next word.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

MacBook pro(Sierra 10.12.4)
Safari: works fine.
FF 52.0.2: same happen
Chrome 57.0.2987.133 (64-bit): same happen(i recorded video by use this)

Windows 7
IE11: weird..
FF 51.0.1(32bit): same happen
Chrome 57.0.2987.133: same happen

Thank you.

**Comment by flarnie** [comment]
Thank you for reporting this! Sounds like it's reproducible in Firefox. It would be great to get this resolved.

**Comment by flarnie** [comment]
I just tried and was unable to reproduce this in Firefox v56, and so either it was a browser bug that they fixed or the latest version of Draft has fixed it. Please feel free to reopen if you're still seeing this, with more details about how I can trigger the problem.
Thanks!
