### ISSUE TITLE
Slow on large documents

### ISSUE THREAD

**Issue by mitermayer** [facebook/draft-js#117]
When editing larger documents it struggles a bit. A possible solution would be to implement a diff algorithm.

**Comment by hellendag** [comment]
How large is your document, and how complex is your behavior? Can you give repro steps?

Since we use persistent data and aggressively avoid re-rendering, the size of the document should generally not be a problem unless there is a bottleneck somewhere.

**Comment by hellendag** [comment]
Also, some more details on the structure of your document would help pinpoint any issues. Do you have especially long paragraphs?

**Comment by Fleur520** [comment]
good

**Comment by mitermayer** [comment]
Sorry that I haven't posted an example yet, attempting to figure out exactly the root cause so that I can avoid giving extra work. Once I can pin point i will create a paste bin with an example.

**Comment by hellendag** [comment]
Awesome, thanks!

**Comment by mitermayer** [comment]
I will close the issue for the time being, since I identified that the bottleneck was on integration layer not on draftjs iteself.

**Comment by hellendag** [comment]
Cool, thanks for following up.

**Comment by phucvinhng** [comment]
Creating new content with 9999 "hello" words in both Draft homepage and Facebook Notes, then editing text. The slow performance appear.
I tried with [contenteditable](https://www.w3schools.com/tags/att_global_contenteditable.asp), it's okay when editing.
How can I void this? :smile:
