### ISSUE TITLE
Can not paste html content to custom block

### ISSUE THREAD

**Issue by tuan072090** [facebook/draft-js#1180]
Draft js can help me create custom block content with all custom class and style.
I was very happy to export contentState to html string to store in Database. But the problem is when I try to paste this html content to state, "convertFromHTML" auto remove all my class and replace some tags in my content.

For instance: 
I has this html content: `<figure><div class="block branch"><a class="block" href="http://google.com"><span class="name block">google</span><span class="address block">ABC, XYZ</span><i class="arrow ion-ios-arrow-forward"></i></a></div></figure>`

How can I prevent Draft remove all my class name and remove my "a tag"?

**Comment by xgzl87** [comment]
How did it work out
