### ISSUE TITLE
New line after and before IMMUTABLE.

### ISSUE THREAD

**Issue by leniartek** [facebook/draft-js#1182]
Hi,
How to get rid of a break after and before every IMMUTABLE object in editor.
When I add image for example.
```
const contentStateWithEntity = contentState.createEntity(
            "image",
            "IMMUTABLE",
            { src: urlValue }
        );
```
I place cursor where the red mark is and add image, I got line break after and before.
![image](https://cloud.githubusercontent.com/assets/10237525/25479064/e5ce7808-2b43-11e7-8fcb-3a167cf11b0e.png)

Same with custom entity, I am not abble to even place cursor to the right of the icon (red square), how to fix that?

![image](https://cloud.githubusercontent.com/assets/10237525/25479177/4681a0bc-2b44-11e7-9c96-08201ee0adfa.png)

**Comment by gocreating** [comment]
same problem + 1

**Comment by zhiquan-yu** [comment]
This https://github.com/facebook/draft-js/issues/327 explains.

**Comment by thibaudcolas** [comment]
This is a duplicate of #850 (and #327 in a sense).

**Comment by niveditc** [comment]
Closing since this is a duplicate
