### ISSUE TITLE
how to limit the maximum input length?

### ISSUE THREAD

**Issue by LiaoSept** [facebook/draft-js#119]

**Comment by hellendag** [comment]
You could check the size of the contents in `onChange` if the `ContentState` has changed, and slice off the contents that go beyond the limit.

**Comment by LiaoSept** [comment]
to solve the problem, as follows:
```javascript
onChange(editorState) {
    const contentState = editorState.getCurrentContent();
    if (contentState.getPlainText().length > this.props.maxLength) {
        editorState = EditorState.undo(editorState);
    }
    this.setState({editorState});
}
```

**Comment by hellendag** [comment]
Well, I don't know if I would recommend using `undo` for this, since it may jump you back to a previous boundary state that you don't want.

Ideally, you'd be able to do:

```
onChange(editorState) {
  const contentState = editorState.getCurrentContent();
  const oldContent = this.state.editorState.getCurrentContent();
  const {maxLength} = this.props;
  if (contentState === oldContent || contentState.getPlainText().length <= maxLength) {
      this.setState({editorState});
  }
}
```

But I think `beforeInput` native rendering might cause trouble for this, so for now, to be really safe, you'd also want to implement `handleBeforeInput`:

```
handleBeforeInput(chars) {
  const totalLength = this.state.editorState.getCurrentContent().getPlainText().length + chars;
  return totalLength > this.props.maxLength;
}
```

By returning true, we prevent the `beforeInput` event from rendering the new character or from executing `onChange`.

**Comment by LiaoSept** [comment]
chars type is String `chars.length ` ?

**Comment by hellendag** [comment]
That's correct, thanks. Fixed my comment.

**Comment by LiaoSept** [comment]
```handleBeforeInput(chars)```
when `chars` will be greater than an length?

**Comment by hellendag** [comment]
Sorry, I don't understand the question.

**Comment by AnasRezk** [comment]
@hellendag i tried your solution, but it dose not work for me and this is work for me 
your solution prevent setState, but it still writing.
`onChange = editorState => {
        const contentState = editorState.getCurrentContent();
        const oldContent = this.state.editorState.getCurrentContent();
        if(contentState === oldContent || contentState.getPlainText().length <= 255) {
            this.setState({ editorState });
        } else {
            const editorState = EditorState.moveFocusToEnd(
                EditorState.push(
                    this.state.editorState,
                    ContentState.createFromText(oldContent.getPlainText())
                )
            );
            this.setState({ editorState });
        }
    }`

**Comment by Larsrdev** [comment]
@AnasRezk to prevent focus move to end, use following solution. This also doesn't jump as mentioned from @hellendag 

```
onChange = editorState => {
        const contentState = editorState.getCurrentContent();
        const oldContent = this.state.editorState.getCurrentContent();
        if(contentState === oldContent || contentState.getPlainText().length <= 25) {
            this.setState({ editorState });
        } else {
            const editorState = EditorState.undo(
                EditorState.push(
                    this.state.editorState,
                    ContentState.createFromText(oldContent.getPlainText()),
                    'delete-character'
                )
            );
            this.setState({ editorState });
        }
    }
```
here some typescript solution: 

```
getStateWithMaxLengthEnsured(oldState: Draft.EditorState, newState: Draft.EditorState, maxLength: number): Draft.EditorState {
        const contentState = newState.getCurrentContent();
        const oldContent = oldState.getCurrentContent();
        if (contentState === oldContent || contentState.getPlainText().length <= maxLength) {
            return newState;
        } else {
            return Draft.EditorState.undo(
                Draft.EditorState.push(
                    oldState,
                    Draft.ContentState.createFromText(oldContent.getPlainText()),
                    'delete-character'
                )
            );
        }
    }
```

**Comment by alx-ppv** [comment]
When pasting text:
```js
function handlePastedText(text: string, _: string, state: EditorState): DraftHandleValue {
    const overflowChars = text.length + state.getCurrentContent().getPlainText().length - MAX_LENGTH;

    if (overflowChars > 0) {
      if (text.length - overflowChars > 0) {
        const newContent = Modifier.insertText(
          state.getCurrentContent(),
          state.getSelection(),
          text.substring(0, text.length - overflowChars)
        );
        setEditorState(EditorState.push(state, newContent, 'insert-characters'));
      }
      return 'handled';
    } else {
      return 'not-handled';
    }
  }
```

**Comment by fnlearner** [comment]
Emm, I found I cannot intercept the onCompositionEnd event, 
```
el?.addEventListener("compositionend", handler);
```
```
e.stopPropagation()
e.preventDefault()
//...
setEditorState(newEditorState)
```
the code above is useless.Becase the source code still invoke the onCompositionEnd event after I invoke the custom event,so what can I do to intercept the onCompositionEnd like handleBeforeInput returned either handled or not-handled.
like the code below:
````
 handleBeforeInput={(chars) => {
          const totalLength = chars.length +editorState.getCurrentContent().getPlainText().length;
          const flag = totalLength > max ? "handled" : "not-handled"
          return flag
}}
```
