### ISSUE TITLE
Text color is lost after converting raw content / HTML back to EditorState

### ISSUE THREAD

**Issue by jasonfoy99** [facebook/draft-js#1196]
Report a bug.

The draftjs I am using is version 0.10.0. JSFiddle: https://jsfiddle.net/wc4cxnvx/

I typed "this is very interesting thing" and made the text green color in Draft Editor and then saved as raw content using convertToRaw as the following:
```
{
    "entityMap":{},
    "blocks":[{"key":"5bbf7",
               "text":"this is very interesting thing", 
               "type":"unstyled",
               "depth":0,    
               "inlineStyleRanges":[{"offset":0,"length":30,  "style":"color-rgb(26,188,156)"}],
               "entityRanges":[], 
               "data":{}}]
 }
```
The raw data is equivalent to HTML:
`<p><span style="color: rgb(26,188,156);">this is very interesting thing</span></p>`

I tried to restore EditorState using raw content or HTML, neither displayed text color. In either case, only plain "this is very interesting thing" without green color was shown.

The code I use to restore EditorState:

From raw:
`EditorState.createWithContent(convertFromRaw(raw));`

From Html
```
let htmlBlockArray = convertFromHTML(html);
let editorState = EditorState.createWithContent(ContentState.createFromBlockArray(htmlBlockArray.contentBlocks, htmlBlockArray.entityMap));
```

**Comment by hari4125862** [comment]
HI @jasonfoy99 can you tell me the fix for this solution
