### ISSUE TITLE
Should I include draft-js styles?

### ISSUE THREAD

**Issue by uiii** [facebook/draft-js#1197]
Hi, is it necessary to include a `dist/Draft.css` styles? I see examples are doing so, but I didn't find any mention about it in the docs. Thanks

**Comment by flarnie** [comment]
Hello @uiii - generally you do need to include the styles. It's noted under 'Issues and Pitfalls' - https://draftjs.org/docs/advanced-topics-issues-and-pitfalls.html#missing-draft-css -  but we could probably mention it in the 'getting started' sections too. I'll open a separate issue for that.
