### ISSUE TITLE
Mention including Draft CSS in 'getting started'

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1201]
Since this was not clear, (see https://github.com/facebook/draft-js/issues/1197), I think we could update the docs to mention this in the 'Quick Start', 'Overview' section. https://draftjs.org/docs/overview.html#content

**Comment by jackyho112** [comment]
@flarnie Hello, I have given this one a go. Please let me know if there is any improvement required. We use `draft.js` a lot. I look forward to doing more contribution and `0.11.0`!
