### ISSUE TITLE
the style probleam in ie 9 with ordered-list-item

### ISSUE THREAD

**Issue by HamburgerTwo** [facebook/draft-js#1202]
when i typing text to draftjs in ie9, i found the style is error, the number order and the text separate but excepted in one line
![qq 20170511103302](https://cloud.githubusercontent.com/assets/12133215/25929932/bfa733ca-3635-11e7-9b44-9660d9a117c7.png)

**Comment by HamburgerTwo** [comment]
I temporary solve the problem with hack css style ,   i use js to judge the browser is ie9 or not, and give the lineheight and position , it looks worked. the hack css is below
![qq 20170511154016](https://cloud.githubusercontent.com/assets/12133215/25937988/57944630-3660-11e7-9572-1060a2b7d8b9.png)

**Comment by paloobi** [comment]
Closing, as it seems you've found a workaround.
