### ISSUE TITLE
Ability to update text from decorator

### ISSUE THREAD

**Issue by ashleyw** [facebook/draft-js#1206]
Hi,

Is it possible to update/replace the text decorated by an entity?

Context: http://stackoverflow.com/questions/43918557/editing-an-entitys-decorated-text

I've posted my issue on SO but after 2 days of searching I'm wondering if it's a limitation of Draft or that I'm just going about this the wrong way.

Any assistance would be greatly appreciated!

Thanks!

**Comment by ashleyw** [comment]
Turns out all I needed to do was inject a reference to my `editorState` into my decorator and keep track of the `selectionState` when I created the Entity, then I could use `Modifier.replaceText()`!

**Comment by roundrobin** [comment]
Hey @ashleyw. I'm struggling with the same issue and wasn't able solve it from your SA question, would you be so able to show me your solution in a JSFiddle?

**Comment by roundrobin** [comment]
@ashleyw I actually figured it out. It seems that the interface slightly changed. So in order to get the key I had to do this `var blockKey = props.children[0].props.block.getKey();` and in order to get the startOffset this `var startOffset = props.children[0].props.start;`
