### ISSUE TITLE
How to insert spaces/tabs with onTab (Keydown keyCode=8 to action)

### ISSUE THREAD

**Issue by ohm2kohm2k** [facebook/draft-js#121]
How to insert spaces/tabs with onTab (Keydown keyCode=8 to action)

**Comment by hellendag** [comment]
Use the `onTab` prop.

```javascript
const MyComponent extends React.Component {
  constructor(props) {
    // etc.
    this.onTab = this.onTab.bind(this);
  }

  onTab(e) {
    // Use `Modifier` API to insert spaces
    // e.preventDefault() if successful
    this.setState({editorState: stateWithSpacesInserted});
  }

  render() {
    return <Editor onTab={this.onTab} ... />;
  }
}
```

**Comment by avk** [comment]
Here's a more fleshed out example with the Modifier API, adapted from [draft-js-code](https://github.com/SamyPesse/draft-js-code/blob/master/lib/handleTab.js):

```js
  const tabCharacter = "    ";
  // ...
  handleTab(e) {
    e.preventDefault();

    let currentState = this.state.editorState;
    let newContentState = Modifier.replaceText(
      currentState.getCurrentContent(),
      currentState.getSelection(),
      tabCharacter
    );

    this.setState({ 
      editorState: EditorState.push(currentState, newContentState, 'insert-characters')
    });
  }
```

**Comment by voidstarfire** [comment]
Just a note. 
This won't work with auto indenting lists as tab is supposed too. It will actually break the functionality.

**Comment by CristianoYL** [comment]
@MichaelCPell Could you explain what it does with lists? The code can't seem to work. But it does capture the tab on both list block types.

**Comment by MichaelCPell** [comment]
It defaults to the onTab behavior if your cursor is in a list.

**Comment by flq** [comment]
In latest version "onTab" is deprectaed and it is said that we should use the stuff with the key / command dispatching - but I'm not sure how to put it together properly, bcs RichUtils wants the event in the onTab call which isn't around when you're handling commands...

**Comment by chrisrobbins** [comment]
@flq Like this:

```
function handleKeyBindings(e: KeyboardEvent<HTMLDivElement>) {
      if (e.key === 'Tab') {
        const newEditorState = RichUtils.onTab(
          e,
          editorState,
          6 /* maxDepth */,
        );
        if (newEditorState !== editorState) {
          handleChange(newEditorState);
        }
        return 'handle-tab';
      }

      return getDefaultKeyBinding(e);
    }

    function handleKeyCommand(command: string): DraftHandleValue {
      if (command === 'handle-tab') {
        return 'handled';
      }
      return 'not-handled';
    }
    
    return (
        <Editor
            handleKeyCommand={handleKeyCommand}
            keyBindingFn={handleKeyBindings} 
         />
    )
    ```

**Comment by aaronncfca** [comment]
Can I add the point here that my keyBindingFn _isn't even called_ when I hit the tab key? (Testing in chrome.) So I'm having a hard time understanding why onTab is said to be deprecated. Any comments?

**Comment by aaronncfca** [comment]
> In latest version "onTab" is deprectaed and it is said that we should use the stuff with the key / command dispatching - but I'm not sure how to put it together properly, bcs RichUtils wants the event in the onTab call which isn't around when you're handling commands...

The `event` passed to `keyBindingFn` seems to work just fine for `RichUtils.onTab`, although it seems the "correct" thing to do in the keyBindingFn is to just return a command string, to be executed in `handleKeyCommand` (which does not seem to have any event param, as @flq observes). Any reason why I can't just handle the command in my keyBindingFn and return null?
