### ISSUE TITLE
Atomic block can't be removed with remove-range

### ISSUE THREAD

**Issue by lukephills** [facebook/draft-js#1212]
I'm unsure how to remove an atomic block selection. This is for a delete button on an image.

Here's my code:
```
deleteImage = () => {
  const editorState = this.props.blockProps.getEditorState();
  const contentState = editorState.getCurrentContent();
  const key = this.props.block.getKey();
  const rangeToRemove = SelectionState.createEmpty(key);
  const newContentState = Modifier.removeRange(contentState, rangeToRemove, 'forward');
  EditorState.push(editorState, newContentState, 'remove-range');
}
```

This throws an error and doesn't delete the block:
`Uncaught Error: There should only be one entity range within this removal range.`

**Comment by paloobi** [comment]
Could you provide more context? If you could go ahead and fork this fiddle and to include your code so we can see how you're using this method? https://jsfiddle.net/stopachka/m6z0xn4r/
Thanks!

**Comment by flarnie** [comment]
Looks like this issue has gotten stale - we need more info to reproduce this bug, and for now I'll close this. Please open a new issue with a jsfiddle if this is still happening.
