### ISSUE TITLE
Add ariaLabelledBy prop

### ISSUE THREAD

**Issue by basham** [facebook/draft-js#1213]
**FEATURE REQUEST**

As of Draft `v0.10.1`, [there is an `ariaLabel` prop](https://github.com/facebook/draft-js/blob/v0.10.1/src/component/base/DraftEditorProps.js#L98), but there is no `ariaLabelledBy` prop (see [`aria-labelledby` documentation](https://www.w3.org/TR/wai-aria/states_and_properties#aria-labelledby)).

Right now, if you want to have a visible label and also provide a label for screen readers, you have to repeat the label text twice.

```jsx
<label>Usernames and IDs<label>
<Editor ariaLabel="Usernames and IDs"/>
```

Ideally, the label text can be referenced instead of repeated.

```jsx
<label id="editorLabel">Usernames and IDs<label>
<Editor ariaLabelledBy="editorLabel"/>
```

**Comment by jackyho112** [comment]
I will have a crack at it. 😄
