### ISSUE TITLE
I can not use Editor when I reset the editorState

### ISSUE THREAD

**Issue by HsuTing** [facebook/draft-js#1216]
I try to reset the `editorState` when user enters `whitespace`. It will make a problem after I reset `editorState`. I can not use `backspace` until I use `Control + A` to remove text.

Here is my simple example: [codepen](http://codepen.io/HsuTing/pen/rmZWZe?editors=0010)

**Comment by danneu** [comment]
I think I got yours working: https://codepen.io/anon/pen/WOwKYZ?editors=0010

```javascript
onChange(editorState) {
    const html = editorState.getCurrentContent().getPlainText();
    
    let newContentState = ContentState.createFromText('')
    let firstBlock = newContentState.getBlockMap().first()
    let newEditorState = EditorState.set(editorState, {
      currentContent: newContentState,
      selection: new SelectionState({
        anchorKey: firstBlock.getKey(),
        anchorOffset: 0,
        focusKey: firstBlock.getKey(),
        focusOffset: 0,
        hasFocus: true
      })
    })
    
    const check = html.slice(-1) === ' ' && html.replace(/ /g, '') !== ''
    
    this.setState({editorState: check ? newEditorState : editorState})
  }
}
```

I think one issue is that you aren't resetting the selectionState. 

I'm not sure if there's a simpler snippet that works, I tend to just flail around until it seems to work.
