### ISSUE TITLE
How to forceSelect specific string in ContentState.getPlainText()

### ISSUE THREAD

**Issue by flyingpath** [facebook/draft-js#1221]
Feature Request

Hello:

Do you know how to forceSelect a specific string in the Editor?

Ex. The PlainText now is "Today is a good day". I want to forceSelect 'good' by click a button.

Thanks a Lot !!!

**Comment by colinjeanne** [comment]
You can create a [SelectionState](https://draftjs.org/docs/api-reference-selection-state.html#content) that points to the section that you want and pass that in to [forceSelection](https://draftjs.org/docs/api-reference-editor-state.html#forceselection).

**Comment by flyingpath** [comment]
Hi:

Is that  means using createEmpty(blockKey)?
Do you have any idea about getting the blockKey of 'good' in "Today is a good day"?

Thanks for answering!!

**Comment by flyingpath** [comment]
Got it!!
