### ISSUE TITLE
Can't save Draft.js state to indexeddb

### ISSUE THREAD

**Issue by teod** [facebook/draft-js#1226]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
Can't save Draft.js state to indexeddb.

I think it's a regression between version 0.9.0 and 0.10.0, because it works using the prior.
Fiddle using 0.10.1 (FAILING): https://jsfiddle.net/jhybq8ar/5/
Fiddle using 0.9.0 (SUCCEEDING): https://jsfiddle.net/jhybq8ar/6/

**What is the expected behavior?**
Being able to save the Draft.js state to indexeddb, using convertToRaw is not an option.
**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Draft.js 0.10.1 / 0.10.0
This was tested on a macOS System:  Google Chrome 58.0.3029.110 browser / Firefox 53.0.3

**Comment by flarnie** [comment]
Thanks for reporting this! I am hopeful that the error could be solved with a little digging - it looks like it's related to the new API for draft entity in v0.10.1. I will try to look again when I am next online.

**Comment by davidchang** [comment]
a few months late and not directly the answer to the question, but errors from the 0.10.1 Fiddle shows there is a function on DraftEntity that just can't be cloned. Looking into it a little more, you probably wouldn't actually even want to clone the exact EditorState, rather, the raw contentState, like this: https://jsfiddle.net/2om59ycv/

Just trying to add editorState.getCurrentContent() produced the same error

**Comment by teod** [comment]
The purpose of saving the EditorState to indexedDB is that its data is shared among the main window and workers, I don't want to save the raw contentState in the db, I want to use it where I need it in a separate a worker and let the main thread use directly the EditorState. This was working with older versions of Draft.js, so I thought therefore that this is indeed a regression.
