### ISSUE TITLE
Wrong `insertFragmentIntoContentState` behavior

### ISSUE THREAD

**Issue by StGeass** [facebook/draft-js#1231]
**Bug report**

I add an atomic block, with a special `key` (I predefine it via the `genKey`).

I do this with a custom function (based on `AtomicBlockUtils. InsertAtomicBlock`), which uses inside` Modifier.replaceWithFragment`, which in turn uses `insertFragmentIntoContentState`.

However, after inserting a fragment, the `key` of this block differs from the predefined one.

**What is the current behavior?**

When inserting a fragment, the block from the current `blockMap` extend everything (text, type, data, etc) except `key` from the fragment block.

```
      const modifiedHead = block.merge({
        text: headText + appendToHead.getText(),
        characterList: headCharacters.concat(appendToHead.getCharacterList()),
        type: headText ? block.getType() : appendToHead.getType(),
        data: appendToHead.getData(),
      });
```

**Demo**

https://jsfiddle.net/tta8s0zx/1/

**What is the expected behavior?**

The block must extend the fragment `key` as well. So that we can predetermine the key of the new block.

```
      const modifiedHead = block.merge({
        key: appendToHead.getKey(), // New behavior
        ...
      });
```

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

Version 0.10.0, browser does not matter

**Updated**

A bit mistaken in the reason of this behavior. Now the description is actual.

**Comment by StGeass** [comment]
The question is, is this really wrong behavior and is there any important reason why we do not take `key` from the fragment?

**Comment by colinjeanne** [comment]
If `insertFragmentIntoContentState` kept the keys from the fragment then you could get your ContentState into a bad state. For example, if you were to duplicate your content by inserting its block map at the end of your existing content and if the function kept the keys from the inserted block map then all of the keys in your content would be duplicated. By generating ignoring the keys it pushes the problem of ensuring keys are unique into the key generation function.

For the code you quoted, the key from the fragment is not used because that code is updating an existing block within the existing ContentState. It's not generating a new block.

**Comment by StGeass** [comment]
> For the code you quoted, the key from the fragment is not used because that code is updating an existing block within the existing ContentState. It's not generating a new block.

Y, I know, just this part is used in `AtomicBlockUtils.InsertAtomicBlock`.

But I understand you, thanks for the explanation. It turns out this function is very low-level, and the problem is not in its behavior, but in the fact that I'm trying to use it for other purposes.

@colinjeanne Can you explain, please, the logic of the `InsertAtomicBlock`?

Why do we first divide the block through `Modifier.splitBlock`, then update his type through `Modifier.setBlockType`, and then update it with the fragment data through `Modifier.replaceWithFragment` (by `insertFragmentIntoContentState` inside) , instead of simply inserting a new block with the desired data after the selection?

**Comment by colinjeanne** [comment]
That's a good question. It seems from my brief reading here that that method would also work.
