### ISSUE TITLE
Get entities from selection

### ISSUE THREAD

**Issue by taniko13** [facebook/draft-js#1236]
Hi,
How I can get entities from selection state?
I need to get all entities that exist in current selection.

Thanks.

**Comment by spacedust** [comment]
You can do this by using [findEntityRanges](https://draftjs.org/docs/api-reference-content-block.html#findentityranges)
I've created a function to get all entities with their corresponding ranges... it shouldn't be that hard to modify this to your needs...
`export default function getEntities(editorState, entityType = null) {
  const content = editorState.getCurrentContent();
  const entities = [];
  content.getBlocksAsArray().forEach((block) => {
    let selectedEntity = null;
    block.findEntityRanges(
      (character) => {
        if (character.getEntity() !== null) {
          const entity = content.getEntity(character.getEntity());
          if (!entityType || (entityType && entity.getType() === entityType)) {
            selectedEntity = {
              entityKey: character.getEntity(),
              blockKey: block.getKey(),
              entity: content.getEntity(character.getEntity()),
            };
            return true;
          }
        }
        return false;
      },
      (start, end) => {
        entities.push({ ...selectedEntity, start, end });
      });
  });
  return entities;
}
`

**Comment by taniko13** [comment]
Thanks, I already tried this method.
By I need entities of selected blocks.
Selection state holds only keys of start and end blocks, and if I select more then 2 blocks I don't know keys of block that between start and end.

**Comment by Aaronik** [comment]
I'm getting past this by forcing all the text in my editor into a single block. I haven't found any down sides and it makes operations like this significantly more easy to manage.

**Comment by alexeychikk** [comment]
@taniko13 `getBlocksAsArray` method returns blocks sorted by index so you can slice them by startKey and endKey of the selection like this:
``` javascript
function getEntitiesInSelection(contentState, selection, type) {
	const entities = [];

	let blocksArray = contentState.getBlocksAsArray();
	const startKey = selection.getStartKey();
	const endKey = selection.getEndKey();

	if (startKey === endKey) {
		blocksArray = [blocksArray.find(block => block.getKey() === startKey)];
	} else {
		blocksArray = blocksArray.slice(
			blocksArray.findIndex(block => block.getKey() === startKey),
			blocksArray.findIndex(block => block.getKey() === endKey)
		);
	}

	blocksArray.forEach(block => {
		let entity;
		block.findEntityRanges(char => {
			const entityKey = char.getEntity();
			if (entityKey === null) return false;

			entity = Entity.get(entityKey);
			const entityType = entity.getType();

			return !type || type === entityType;
		}, () => entities.push(entity));
	});

	return entities;
}
```

**Comment by richardson-trevor** [comment]
I'd like to be able to do this as well.

**Comment by richardson-trevor** [comment]
It looks like what we're looking for is [hidden behind the transactions api](https://github.com/facebook/draft-js/blob/aca0861e6dd10e921a75aabac9ec0206ae61010a/src/model/transaction/modifyBlockForContentState.js). To my knowledge, the maintainers have been [considering opening up the transactions api](https://github.com/facebook/draft-js/pull/265), but decided 'not now'.

**Comment by jeongsd** [comment]
this looks like useful https://github.com/jpuri/draftjs-utils

**Comment by richardson-trevor** [comment]
@jeongsd I found that recently as well. That's the option I'll be going with.

**Comment by adamlibusa** [comment]
@jeongsd I can't believe that some functions from `draftjs-utils` aren't actually part of `draft-js`'s API.

**Comment by niveditc** [comment]
The draft utils workaround seems like a good one.
