### ISSUE TITLE
Package "immutable" should be placed in "peerDependencies".

### ISSUE THREAD

**Issue by lixiaoyan** [facebook/draft-js#1237]

**Comment by arshadkazmi42** [comment]
taking this up 👍

**Comment by TrySound** [comment]
Should it be? What if I use another package with older immutable version? My app will be completely broken and I won't be able to fix it.

What problem are you trying to solve here? It's not clear from your issue.

**Comment by arshadkazmi42** [comment]
@TrySound I am new to this repo, I thought its already discussed issue, so I took it up.
not sure why this is needed? 
My be @lixiaoyan can help us understand, why we need this change

**Comment by niveditc** [comment]
@flarnie, @claudiopro, @mrkev, @elboman - would any of you happen to know if this is needed? My guess is that it is fine as is, but I don't know too much about dependencies :)

**Comment by niveditc** [comment]
Okay, looks like this might not actually be needed. @arshadkazmi42 - apologies for the mislabeled issue!

**Comment by arshadkazmi42** [comment]
Ok. No issues at all. I will explore through the other open bugs
