### ISSUE TITLE
Buttons in Custom Block Wrapper for 'code-block' passed to blockRenderMap cannot be clicked

### ISSUE THREAD

**Issue by xiaopow** [facebook/draft-js#1241]
**Do you want to request a *feature* or report a *bug*?**
Buttons in Custom Block Wrapper for 'code-block' passed to blockRenderMap cannot be clicked
**What is the current behavior?**
Buttons in Custom Block Wrapper passed to blockRenderMap cannot be clicked
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: 
```
class CodeBlock extends React.Component {
  render() {
    return (
      <pre
        className="public-DraftStyleDefault-pre"
        data-offset-key={this.props["data-offset-key"]}
      >
        <button
          label={'Copy'}
          onClick={() => {console.log('clicked')}}
        />
        {this.props.children}
      </pre>
    );
  }
}

const blockRenderMap = Map({
  'code-block': {
    // element is used during paste or html conversion to auto match your component;
    // it is also retained as part of this.props.children and not stripped out
    element: 'code',
    wrapper: <CodeBlock />
  },
});

<Editor
  readOnly={true}
  blockRenderMap={blockRenderMap}
/>
```

**What is the expected behavior?**
Buttons should be clickable
**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
0.10

**Comment by hellendag** [comment]
Thanks for the report. Can you provide a link to a jsfiddle with a simple repro?

Off the top of my head, I can't think of a reason this would fail, especially with the editor set to `readOnly`.

**Comment by flarnie** [comment]
Working on a fiddle to reproduce this bug, since the code sample above is pretty close to a repro fiddle. https://jsfiddle.net/m6z0xn4r/236/

Just need to get some code blocks into the initial editor state. Going to come back to that. But for now not sure either way if this works.

**Comment by xiaopow** [comment]
Hi people, sorry I forgot to update. I managed to find the cause of the issue. I am using highlight.js to hightlight the component on mount and that seemed to have messed up buttons. Didn't look into why. But once I removed the highlight function call. The buttons are clickable again.

**Comment by reynacortez2** [comment]
```
// element is used during paste or html conversion to auto match your component;
                // it is also retained as part of this.props.children and not stripped out
```

**Comment by reynacortez2** [comment]
```
// element is used during paste or html conversion to auto match your component;
                // it is also retained as part of this.props.children and not stripped out
```
