### ISSUE TITLE
Bug: ContentState.prototype.getEntityMap() does not return map of entities

### ISSUE THREAD

**Issue by juliankrispel** [facebook/draft-js#1264]
**What is the current behavior?**

`ContentState.prototype.getEntityMap()` does not return map of entities, currently, it returns just the DraftEntity object, whose methods are already attached to `ContentState.prototype`.

```js
  getEntityMap(): any {
    // TODO: update this when we fully remove DraftEntity
    return DraftEntity;
  }
```

so this is what I get from `getEntityMap`

![image](https://user-images.githubusercontent.com/1188186/27582404-abbe79be-5b28-11e7-9877-66232916e4b3.png)

To reproduce, please use [this fiddle](https://jsfiddle.net/m6z0xn4r/259/) and open your console

**What is the expected behavior?**

It should return a map of the entities

**Comment by juliankrispel** [comment]
Aha, I saw that this is actually getting fixed [here in `0.11`](https://github.com/facebook/draft-js/blob/0.11.0-alpha/src/model/immutable/ContentState.js#L53)

**Comment by lightninglu10** [comment]
@juliankrispel is there a fix for this in DraftJS `.10.2`? I need to view my entityMap but I can't access it

**Comment by juliankrispel** [comment]
@lightninglu10 
```
convertToRaw(editorState.getCurrentContent())
```

If you're looking for the logic behind how convertToRaw gets the entitymap  - you can [see this here ](https://github.com/facebook/draft-js/blob/514490b1322e1c123524eae97d4aea25b4da16ce/src/model/encoding/convertFromDraftStateToRaw.js#L30) - it basically searches for all entities in the tree and builds a map...

Not super nice :D

**Comment by moontails** [comment]
Is there a work around to update entities? I am able to access the entityMap through `convertToRaw` , but the keys in this map are different from the ones created by Draft and as such I am unable to update the right entity

**Comment by juliankrispel** [comment]
hey @moontails - the way you'd update entities is by using Modifiers. You shouldn't need a workaround or access the entities directly. Here's a link [to the docs on modifiers](https://draftjs.org/docs/api-reference-modifier.html#content).

Also feel free to join the draft js community on slack https://draftjs.herokuapp.com
