### ISSUE TITLE
"handlePastedFiles" trigger conditions?

### ISSUE THREAD

**Issue by LiaoSept** [facebook/draft-js#127]
<kbd>Ctrl + V</kbd> does not trigger

**Comment by LiaoSept** [comment]
![](https://cloud.githubusercontent.com/assets/15375011/13420362/887c06b8-dfc0-11e5-8649-3ca0e9cf6f6e.png)

**Comment by LiaoSept** [comment]
HACK: [Monkey-patch](https://en.wikipedia.org/wiki/Monkey_patch)
```javascript
(function () {
    const PhotosMimeType = require('fbjs/lib/PhotosMimeType');
    const DataTransfer = require('fbjs/lib/DataTransfer');
    DataTransfer.prototype.isImage = function () {
        const isImage = this.types.some(type => type.indexOf('application/x-moz-file') !== -1);
        if (isImage) return true;

        const items = this.getFiles();
        for (let i = 0; i < items.length; i++) {
            const type = items[i].type;
            if (!(new PhotosMimeType(type)).isImage()) return false;
        }

        return true;
    };
}());
```

**Comment by hellendag** [comment]
The fix will be pushed to `fbjs` soon. :)

**Comment by LiaoSept** [comment]
@hellendag when will repair?

**Comment by zpao** [comment]
https://github.com/facebook/fbjs/commit/b907f914994dce1e814838240c2af3ddb88d59fc. We'll ship a new version of fbjs with that soon.

**Comment by hellendag** [comment]
Passing to @zpao now that this has landed. Once we've got a new fbjs version out, this can be closed. :)

**Comment by zpao** [comment]
We published alpha.2 so new install should be getting it already but also just added https://github.com/facebook/draft-js/pull/193 which will make sure

**Comment by hellendag** [comment]
Merged.
