### ISSUE TITLE
Flow types bug in getTextContentFromFiles.js

### ISSUE THREAD

**Issue by KROT47** [facebook/draft-js#1272]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
```sh
node_modules/draft-js/lib/getTextContentFromFiles.js.flow:67
 67:     callback(reader.result);
                  ^^^^^^^^^^^^^ ArrayBuffer. This type is incompatible with the expected param type of
 46: function readFile(file: File, callback: (contents: string) => void): void {
                                                        ^^^^^^ string
```

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
draft-js@0.10.1
flow-bin@0.49.1

**Comment by aurbano** [comment]
Until this is resolved you can get around it by ignoring that one file:

In your .flowconfig
```
[ignore]
.*/node_modules/draft-js/lib/getTextContentFromFiles.js.flow
```

**Comment by mitermayer** [comment]
We are using `"flow-bin": "^0.53.1"` on the main repo and can no longer be able to reproduce this issue
