### ISSUE TITLE
Copying into a code block doesn't retain code block formatting.

### ISSUE THREAD

**Issue by ChuckIrvine** [facebook/draft-js#1276]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

It is not possible to paste a code snippet into a Draftjs code block. When you try, the text on the clipboard is copied into the editor, but the code block formatting is lost.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. **

1) From a code editor, copy some code into the clipboard.
2) Go to https://draftjs.org/
3) Click in the editor window.
4) Click on "Code Block" in the toolbar.
5) Try to paste the code on the clipboard into the editor code block.

**What is the expected behavior?**

The expectation is that the code copied from the text editor would be inserted into a Draftjs code block. 

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

I'm using Chrome Version 59.0.3071.115 (Official Build) (64-bit) on MacOS version 10.12.5.

I'm new to Draft.js so I don't know if this was working previously.

**Comment by sophiebits** [comment]
e8d101121fb9dd9203a46d899124a7be4b0b2936 should fix this!
