### ISSUE TITLE
how to define roller wheel behavior?

### ISSUE THREAD

**Issue by LiaoSept** [facebook/draft-js#128]
[DraftEditorProps](https://github.com/facebook/draft-js/blob/master/src/component/base/DraftEditorProps.js) not provide [wheel event](https://developer.mozilla.org/en-US/docs/Web/Events/wheel).

see https://developer.mozilla.org/en-US/docs/Web/Events/wheel
see https://github.com/facebook/draft-js/blob/master/src/component/base/DraftEditorProps.js

**Comment by qq296776435** [comment]
1

**Comment by hellendag** [comment]
We haven't had a need for it yet, but it seems like it is probably reasonable to have it. What is your use case?
