### ISSUE TITLE
convertToRaw is removing inline styles

### ISSUE THREAD

**Issue by farhansalam** [facebook/draft-js#1309]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Editor state has some inline styles but `convertToRaw` is removing them.

EditorState (in json) which has the first three characters as **BOLD**
```JSON
{"_immutable":{"allowUndo":true,"currentContent":{"entityMap":{},"blockMap":{"4p3m0":{"key":"4p3m0","type":"unstyled","text":"asd qwe","characterList":[{"style":["BOLD"],"entity":null},{"style":["BOLD"],"entity":null},{"style":["BOLD"],"entity":null},{"style":[],"entity":null},{"style":[],"entity":null},{"style":[],"entity":null},{"style":[],"entity":null}],"depth":0,"data":{}}},"selectionBefore":{"anchorKey":"4p3m0","anchorOffset":0,"focusKey":"4p3m0","focusOffset":3,"isBackward":false,"hasFocus":true},"selectionAfter":{"anchorKey":"4p3m0","anchorOffset":0,"focusKey":"4p3m0","focusOffset":3,"isBackward":false,"hasFocus":true}},"decorator":{"decorators":[{"_decorators":[{}]},{"_decorators":[{}]}]},"directionMap":{"4p3m0":"LTR"},"forceSelection":false,"inCompositionMode":false,"inlineStyleOverride":null,"lastChangeType":"change-inline-style","nativelyRenderedContent":null,"redoStack":[],"selection":{"anchorKey":"4p3m0","anchorOffset":0,"focusKey":"4p3m0","focusOffset":3,"isBackward":false,"hasFocus":false},"treeMap":{"4p3m0":[{"start":0,"end":7,"decoratorKey":null,"leaves":[{"start":0,"end":3},{"start":3,"end":7}]}]},"undoStack":[{"entityMap":{},"blockMap":{"4p3m0":{"key":"4p3m0","type":"unstyled","text":"asd qwe","characterList":[{"style":[],"entity":null},{"style":[],"entity":null},{"style":[],"entity":null},{"style":[],"entity":null},{"style":[],"entity":null},{"style":[],"entity":null},{"style":[],"entity":null}],"depth":0,"data":{}}},"selectionBefore":{"anchorKey":"4p3m0","anchorOffset":0,"focusKey":"4p3m0","focusOffset":0,"isBackward":false,"hasFocus":true},"selectionAfter":{"anchorKey":"4p3m0","anchorOffset":7,"focusKey":"4p3m0","focusOffset":7,"isBackward":false,"hasFocus":true}},{"entityMap":{},"blockMap":{"4p3m0":{"key":"4p3m0","type":"unstyled","text":"","characterList":[],"depth":0,"data":{}}},"selectionBefore":{"anchorKey":"4p3m0","anchorOffset":0,"focusKey":"4p3m0","focusOffset":0,"isBackward":false,"hasFocus":false},"selectionAfter":{"anchorKey":"4p3m0","anchorOffset":0,"focusKey":"4p3m0","focusOffset":0,"isBackward":false,"hasFocus":false}}]}}
```
`convertToRaw` output: 

```JSON
{
  "entityMap": {},
  "blocks": [
    {
      "key": "6t4k4",
      "text": "asd qwe",
      "type": "unstyled",
      "depth": 0,
      "inlineStyleRanges": [],
      "entityRanges": [],
      "data": {}
    }
  ]
}
```

**What is the expected behavior?**

The convert to Raw output should have styling inside `inlineStyleRanges` array.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

0.10.0

**Comment by flarnie** [comment]
Thanks for reporting this @farhansalam - it does sound like a bug.

This could be a problem with the 'encodeInlineStyleRanges' method, [which is pretty thoroughly tested](https://github.com/facebook/draft-js/blob/213cd764f61cc64552bddd672ae1748529d55333/src/model/encoding/__tests__/encodeInlineStyleRanges-test.js). Could you give me a new test or a JSFiddle that reproduces the bug? That will help with fixing it.

**Comment by farhansalam** [comment]
@flarnie sorry about not reporting back, but I found the bug to be in my code which was removing the styles, and actually i was looking at `undoStack` and thinking that it had styles.

This should be closed IMO

**Comment by zachdixon** [comment]
@farhansalam I know it's been a while but I'm running into this issue as well and wondering if you could share what exactly it was that was causing it. I don't think I'm removing the styles like you said you were.

I'm on version 0.11.6

**Comment by farhansalam** [comment]
> @farhansalam I know it's been a while but I'm running into this issue as well and wondering if you could share what exactly it was that was causing it. I don't think I'm removing the styles like you said you were.
> 
> I'm on version 0.11.6

@zachdixon as I said that my code was changing the styles. Tbh I cant remember exactly

**Comment by cathykc** [comment]
@zachdixon Exact same issue here and am wondering if you have any leads for me - am going to step through the convertToRaw code today to figure out why `characterList` styles aren't getting translated into the `inlineStyleRanges` field
- [ ]
