### ISSUE TITLE
Document new parameters added in #1112 and #1113

### ISSUE THREAD

**Issue by colinjeanne** [facebook/draft-js#1316]
Ahead of completing #1312, new documentation should be added for the parameters added in #1112 and #1113.

**Comment by davidchang** [comment]
Thanks for opening this @colinjeanne - I think this can be sufficiently considered a subtask of #1312. We ran into issues before releasing v0.10 where we had updated the documentation way before we actually did the release, resulting in a lot of confusion.

I'm going to close this as it's represented in the checklist on the v0.11 Umbrella task
