### ISSUE TITLE
Setting Selection During onFocus

### ISSUE THREAD

**Issue by justinmc** [facebook/draft-js#1319]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If I set the selection during `onFocus` then the change is not applied.  Wrapping the call to `setState` in a `setTimeout` allows it to work.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
https://jsfiddle.net/justinmc/m6z0xn4r/273/

**What is the expected behavior?**
Updates set during `onFocus` should be applied.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
v0.10.1, Chrome 59, OSX

**Comment by hellendag** [comment]
Thanks for including the jsfiddle, it's super helpful.

I remember running into this one before -- I think we're at the browser's mercy here.

It seems that when the browser refocuses the input, it puts the DOM selection back where it thinks it belongs, e.g. the previous `Selection` state, after focus handlers are complete. This seems to discard the selection state being forced by `forceSelection`.

I'm not sure there's much we can do about this, as it's dependent on when the browser sets its DOM selection in relation to the focus event and handler.

You've found a totally valid workaround here, though, and it seems to handle the issue quite nicely.

**Comment by justinmc** [comment]
Alright, thanks for the thorough response.  I'll stick with the `setTimeout` for now.

**Comment by pfftdammitchris** [comment]
Confirmed the setTimeout works perfectly as a workaround

**Comment by slatkovic** [comment]
It's nasty but it works 👇 
```
focusEditorInput = () => {
  setTimeout(() => this.refs.editor.focus(), 0)
}
```
