### ISSUE TITLE
Bug : editorNode.firstChild is not an HTMLElement

### ISSUE THREAD

**Issue by grinono** [facebook/draft-js#1321]
When i select the draftJS editor in Chrome, the following error  shows up in the console.  Firefox is working just fine.

[https://youtu.be/cp8sbRX1tfo](url)

Editor issues, and console log notification >

`Uncaught Error: editorNode.firstChild is not an HTMLElement`

i'm using a Meteor based infrastructure with
"draft-js": "^0.10.1",
"react": "^15.6.1",
"react-router": "^4.1.1",
 node : 6.11.0
npm : 5.2.0

I'm loading the module on an empty page. 
```
import React from 'react';
import ReactDOM from 'react-dom';
import {Editor, EditorState} from 'draft-js';

export default class MyEditor extends React.Component {
  constructor(props) {
    super(props);
    this.state = {editorState: EditorState.createEmpty()};
    this.onChange = (editorState) => this.setState({editorState});
  }
  render() {
    return (
      <div>
        <br />
        <Editor editorState={this.state.editorState} onChange={this.onChange} />
      </div>
    )
  }
}
```

**Comment by grinono** [comment]
Solution to the above was removing an react create circle package. It was creating a conflict with draftJS somehow

**Comment by flarnie** [comment]
Sounds good!

**Comment by Heet1996** [comment]
I am not using react create circle package still I am getting this error.
