### ISSUE TITLE
TypeError: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by lightninglu10** [facebook/draft-js#1324]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

When trying to run `CharacterMetaData.create()`, get the error:

`Uncaught TypeError: Cannot read property 'create' of undefined`

Seems to not be importing correctly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

https://jsfiddle.net/m6z0xn4r/274/

**What is the expected behavior?**

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

+draft-js@0.10.1, draft-js@^0.10.1:

**Comment by davidchang** [comment]
Hi @lightninglu10 - you actually just have a small typo in your code. JS is type sensitive and you were trying to pull out CharacterMetaData instead of CharacterMetadata - https://jsfiddle.net/7dsv2waw/

Have a good day!

**Comment by lightninglu10** [comment]
Oh wow, totally missed that.. okay thanks for alerting me!
