### ISSUE TITLE
Text typing not working in Safari with draggable parent container

### ISSUE THREAD

**Issue by khannanov** [facebook/draft-js#1326]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When i add attribute `draggable="true"` on parent div text typing is not working

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/Aydar/ztsvbyep/3/.**

**What is the expected behavior?**
text typing works properly

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Safari 10.1.2 (12603.3.8) / macOS Sierra
draft-js 0.10.1 ( i have tried  0.7.0, 0.9.0 )

**Comment by flarnie** [comment]
Thanks for reporting this and including a fiddle to reproduce it! This is absolutely a bug. We'd be happy to get some help resolving it - the core Draft folks are also working on React and are a bit swamped this week.
