### ISSUE TITLE
Add way to disable "extending" of inline style

### ISSUE THREAD

**Issue by Pajn** [facebook/draft-js#133]
I would like for text added just after / at the end an inline style to not be styled.

The simplest way to do that is a new property on the Editor, however that would mean that it's globally on and off. For my use case I think that would be enough but maybe a property on CharacterMetadata would be nicer?

**Comment by hellendag** [comment]
Can you provide a bit more detail? Do you mean that in a case like "**hello** world", if I inserted the cursor after "hello", the next typed characters would not be bold?

**Comment by Pajn** [comment]
Exactly!

**Comment by hellendag** [comment]
Got it. A couple questions to clarify your use case:

- Do you want to disallow the user from doing something like pressing <kbd>cmd</kbd>+<kbd>b</kbd> (or clicking a button) to set bold with a collapsed cursor, then typing multiple characters as bold text? I.e. starting with "", setting the bold command, and typing "**hello**".
- What should happen if I place the cursor within bold text and begin typing?
- What should happen if I select "llo wor" in the example above, overlapping bold and plain, and begin typing?

**Comment by Pajn** [comment]
- Do you want to disallow the user from doing something like pressing cmd+b (or clicking a button) to set bold with a collapsed cursor, then typing multiple characters as bold text? I.e. starting with "", setting the bold command, and typing "hello".

Yes, I don't want any such key-events from Draft, however I doesn't seem to have any. I thought I must enable them by explicitly handle those?
But I see how that may need to be answered if one does use them and also want this feature. I guess that would be allowed if you allow the user arbitrarily make things bold anyway. But if there are some special case one cold probably handle that case yourself by suppressing the event?

- What should happen if I place the cursor within bold text and begin typing?

That would be okay, it's just that I don't want it to arbitrarily extend. My specific use case is a markdown editor, so text between ** should be bold, but currently if the user types just after the last * the text is automatically bold.

- What should happen if I select "llo wor" in the example above, overlapping bold and plain, and begin typing?

As e then would be the last bold character I would expect that the new text isn't bold.

**Comment by hellendag** [comment]
Ok, thanks. The use case helps clarify things.

I think you might actually want to use a decorator, *not* inline styles, to represent these styles within the markdown. By using a decorator, you can scan a `ContentBlock` for regex-matching contents, then style them accordingly. In the `**bold**` case, your search strategy would use a regex (or some other approach) with asterisks and your decorator component would apply bold style to the full text.

The reasoning here is that the contents are what dictate your styling, which is when decorators become useful. Within Draft, built-in inline style behavior is treated as independent of the text or entity metadata. By depending on the actual characters of the text, your use case is more in line with decorator behavior.

Does that make sense?

**Comment by Pajn** [comment]
Oh, I had completely missed/forgot those. After I read through the more "explaining" pages under quick start and advanced topics I have only looked at the API reference pages which I see now was not very good...
I have another use case too which isn't bound by entities instead but it seems like decorators should work for that too.

Thank you for that tip, and sorry for not reading the docs enough.

**Comment by hellendag** [comment]
No problem! :)
