### ISSUE TITLE
Selection state jumping when multiple entities created by decorators

### ISSUE THREAD

**Issue by nburt** [facebook/draft-js#1338]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Selection state will focus to the beginning when creating an entity when there is a second entity after it already. If there are 2 entities and you create a 3rd in between the existing 2, the cursor will skip to the end of the first entity.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

Here is the sample app: https://jsfiddle.net/sy6c3u4f/10/
When there's 1 entity in the editor:
1. Type "Hello world  " (2 spaces at end) into the editor.
2. Move cursor to end of "Hello"
3. Hit the spacebar
4. Entity is created and selection skips to beginning

When there are 2 entities in the editor:
1. Type "Hello  world blah  " (2 spaces in between "Hello" and "world", 2 spaces after "blah"
2. Move cursor to end of "world"
3. Hit the spacebar
4. Entity is created and selection skips to just before "world"

**What is the expected behavior?**
Cursor should move to after the space that was just entered rather than skipping

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
I can reproduce this in Draft.js 0.10.0 in Chrome, Firefox, and Safari on osx Sierra.

**Comment by flarnie** [comment]
Thanks! This does seem like a legitimate bug. Thanks for the nice repro case. If anyone is interested in tracking down what's causing this, that would be really helpful.

**Comment by nburt** [comment]
@flarnie I've spent a little time on this but haven't had much success tracking down the exact cause. I'm seeing that when I first type a space the anchor offset (logged from DraftEditor.js in the render function) is correct however immediately after the selection is reset to 0.

I added `console.log('editor selection anchor offset:', this.props.editorState.getSelection().getAnchorOffset());` to the render function.

This is what I'm seeing:

![image](https://user-images.githubusercontent.com/5788989/29879967-96bf9d8a-8d74-11e7-8835-2bcdb4ca4ec4.png)

the "5" is when I move the cursor to after "hello", "6" when I hit spacebar, and then "0" directly after

Do you have any pointers on where this selection could be getting updated? The only place I'm seeing selection updated in `DraftEditor` is in `_focus` and I've confirmed that isn't being called.

**Comment by flarnie** [comment]
Hi again @nburt - thanks for looking into this more.

I looked again at the jsfiddle you linked, and maybe it was updated, because now I'm not seeing Entities used and the bug doesn't reproduce.

Here is a fork of the version I'm seeing now, which doesn't use entities: https://jsfiddle.net/sy6c3u4f/11/

For this example you don't actually need entities - and I'm not remembering where the entity was being created before. I imagine that if we were creating new entities in the decorator that could cause unexpected behavior - the decorator is called on every render, so we would be creating entities over and over.

**Comment by nburt** [comment]
@flarnie Oops, I think I just mixed up my terminology, we're just noticing this with decorators. I did look at all of our entity creation and haven't noticed any cursor jumping with that.

**Comment by deanchen2013** [comment]
I tried it (https://jsfiddle.net/sy6c3u4f/10/) , the bug show up in my Mac + Chrome 60.0.3/Safari 10.1.1 , so I think the bug exist, and In my project , I meet some problem similar, I will post my code later , maybe is useful for solve this problem .

**Comment by JM-Mendez** [comment]
I think you're entering a race condition because of the callback inside the loop. I modified it to this instead:

```js
highlightDoubleSpace = (mutability) => {
    return (contentBlock, callback, contentState) => {
      const matchRegex = new RegExp(/\s{2,}/gi);
      const text = contentBlock.getText();
      let matchArray;
      let start;
      while ((matchRegex && (matchArray = matchRegex.exec(text)) !== null)) {
        /* Original
        const characters = matchArray[0].split("");
        characters.forEach((character, index) => {
          callback(start + index, start + index + 1);
        }); */
        
        // Modified: Decorate entire matched substring on each pass
        start = matchArray.index;
        callback(start, start + matchArray[0].length)
      }
    };
  }
```


Working copy -> https://jsfiddle.net/Lugf5z04/

**Comment by nburt** [comment]
thanks @JM-Mendez !

We ended up switching from a decorator to a style range to fix this is helpful, I'll keep it in mind for the future.
