### ISSUE TITLE
duplicate blockMap.set

### ISSUE THREAD

**Issue by kgdev** [facebook/draft-js#1339]
https://github.com/facebook/draft-js/blob/00f2cbd1ac51e98c29917bd70a1038f8d7ee4bdc/src/model/transaction/insertFragmentIntoContentState.js#L65

```blockMap = blockMap.set(targetKey, newBlock);```

And then in L71, blockMap is set again. It seems to be duplicate.

**Comment by flarnie** [comment]
Nice catch! I think you're right – would you like to submit a PR for this?

**Comment by mitermayer** [comment]
This has been fixed on a previous commit
