### ISSUE TITLE
Inserting characters adjacent to tab character in latest Chrome/Opera causes errors and visual corruption

### ISSUE THREAD

**Issue by dwighthouse** [facebook/draft-js#1340]
This is a bug.

Problem case: The latest stable version of Draft.js (v0.10.1) cannot correctly handle character insertions near a tab character. The data can become visually corrupted and errors are printed to console.

The issue was observed happening on Chrome (60) and latest Opera (47). The issue did not occur on Firefox (54.0.1 or 55.0.2), Opera version 45, and Safari (10.1.2). All browsers tested were on Mac OS 10.12.6.

To reproduce:

1. Add a tab character to editor
2. Add characters immediately adjacent to that tab character

Expected result: The added characters are inserted as normal.
Actual result: A copy of all existing text is inserted one or more times. The copied text may or may not have the added characters. The cursor position moves around incorrectly. As one continues adding characters, eventually an error like `Uncaught DOMException: Failed to execute 'setStart' on 'Range': The offset 22 is larger than the node's length (19).` occurs in the console. The editor can also lose focus.

Strangely, the version of 0.10.1 of Draft.js included on the homepage of Draft.js ( https://draftjs.org/lib/Draft.js ), does not have this problem. The source differs significantly from the precompiled standalone versions of Draft.js available via CDN, even though they share the same version number.

No other factors appear to be in play, so this is clearly a browser-specific bug with the latest version of Draft.js that is somehow not shared with the latest version built for the Draft.js homepage. I had to process-of-elimination everything to get to this point. If one were to bundle Draft.js normally via browserify, the same issue occurs.

Here is a repository showing both the working and failure cases (which feature identical code, except where Draft.js is included from).

https://github.com/dwighthouse/draftjs-chromeopera-tab-glitch

There is also a video showing the issue in action:

https://youtu.be/U0LxF2bDDps

A quick test with other versions:

* 0.11.0-alpha - Works correctly
* 0.10.0 - Failed in a different way: text after the inserted characters was removed. Errors occur based on focus/blur, not insertions.
* 0.9.1 - Failed the same way as 0.10.0

**Comment by flarnie** [comment]
Thanks for the detailed bug report! We actually fixed this bug recently in https://github.com/facebook/draft-js/commit/5863399a3a1bcbbe9b090249504a70496a7af7cc but it's not in a release yet, like you noticed. We're planning to do a release soon.
