### ISSUE TITLE
Question : Can I use "draft js" in "react native"?

### ISSUE THREAD

**Issue by jungpaeng** [facebook/draft-js#1343]
I want to use "draft js" in "react native".
But I do not know how to do it.
How do I use "draft js" in "react native"?

I do not want to add "draft js render", but I want to add "draft js editor".

**Comment by TheTekton** [comment]
I thought I saw a project with draft-js in an RN WebView recently, although I can't find it at the moment, so maybe not. 😞 This might give you a good start, otherwise: https://github.com/facebook/draft-js/issues/138#issuecomment-261180745

**Comment by stonecold123** [comment]
I create a web page where there is only a draftjs editor and use webview to show it. It's very buggy. The text disappears as you type it. Maybe this PR will fix the problem: https://github.com/facebook/draft-js/pull/1285

**Comment by pedrro** [comment]
Maybe this could help you: https://github.com/globocom/react-native-draftjs-render

**Comment by flarnie** [comment]
Hi!

I don't think we generally support using Draft.js with RN at this time. Internally at Facebook, folks have made similar components to Draft for React Native, but have not actually been using Draft in RN.

Sorry I don't have better news in this area - would be curious whether the `react-native-draftjs-render` project solves the problem.

**Comment by Leadrive** [comment]
https://github.com/rehashstudio/react-native-draft-js
this project support React Native

**Comment by suryakant-t-yadav** [comment]
https://github.com/rehashstudio/react-native-draft-js only support rendering but I want to  add "draft js editor". in my project. alternative  https://github.com/wix/react-native-zss-rich-text-editor is available but it don't support #tags or @user like autocomplete  like feature can. can any one help me with this and how to achieve this.

**Comment by abkr08** [comment]
> I am adding a text-editor feature in my react-native app and https://github.com/rehashstudio/react-native-draft-js only support rendering but I want to add "draft js editor". Alternative https://github.com/wix/react-native-zss-rich-text-editor is available but it don't support #tags or @user like autocomplete like feature can. can any one help me with this and how to achieve this.

Hey man how did you solve this problem?

**Comment by superfilip123** [comment]
maybe it will be helpful: [https://github.com/DaniAkash/react-native-draftjs](https://github.com/DaniAkash/react-native-draftjs)
