### ISSUE TITLE
ctrl+z doesn't call to   handleKeyCommand 

### ISSUE THREAD

**Issue by taniko13** [facebook/draft-js#1347]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I press ctrl+y I got in to handleKeyCommand with parameter command = ''redo''

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
type something in the editor, press ctrl+z and try to stop in handleKeyCommand  (in debug) 

**What is the expected behavior?**
ctrl+z will get in handleKeyCommand with command "undo"

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
ersions of Draft.js is "0.10.1"

**Comment by niveditc** [comment]
You need to override the key binding in `keyBindingFn` & then use that in `handleKeyCommand`:
```
if (
  e.keyCode === 90 /* `Z` key */ &&	
  hasCommandModifier(e) &&	
  !e.shiftKey	
) {
  return 'my-editor-undo';
}
```
