### ISSUE TITLE
DraftEditorBlock does not update if this.props.contentState has been changed.

### ISSUE THREAD

**Issue by kgdev** [facebook/draft-js#1350]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

DraftEditorBlock does not update if this.props.contentState has been changed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

Try to update the sequence of blockMap (i.e. switch two blocks). DraftEditorBlock does not update and then the Decorator component will have the old this.props.contentState.

**What is the expected behavior?**

DraftEditorBlock should rerender itself so that the Decorator component will have the latest contentState.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

All versions.

**Comment by flarnie** [comment]
Hi @kgdev - could you make an example with the JSFiddle link provided in the issue template? We would like to help, and are looking for more info about what triggers this problem.

**Comment by flarnie** [comment]
Since we are blocked on needing more info to address this issue, there are no action items. Closing this for now, but feel free to reopen with a JSFiddle example and more info. Thanks!
