### ISSUE TITLE
Calling CompositeDecorator's strategies manually

### ISSUE THREAD

**Issue by MikeDevice** [facebook/draft-js#1352]
**I want to ask a *question***

I want to make an editor for writing special rules. These rules look something like this:
```
A -> B C e
B -> C
C -> 1
```
All rules have *left* and *right* parts separated by arrow `->`.

I'm using a CompositeDecorator to highlight all left part in one color and *each* non-whitespace strings in rule's right part in another color except strings that have the same in left parts.

Some examples are below.

First example;
**A** -> _a_ _B_ _C_

Second:
**A** -> _a_ **B** _C_
**B** -> _e_ _C_

Third:
**A** -> _a_ **B** **C**
**B** -> _e_ **C**
**C** -> _ab_ _bc_

So, I'm using two decorators for that purpose: for left parts highlighting and for right. First decorator is simple, it's similar to [tweet example](https://github.com/facebook/draft-js/tree/master/examples/draft-0-10-0/tweet). But the second decorator is causing me problems. In strategy I get only `currentBlock` (current line) so how can I understand I need to highlight **B** and **C** in last example if I have only `currentBlock` of first line?

Yes. I can use `contentState`, the third strategy parameter and get all text of editor. But there is a problem. That `contentState` is old that was before I type any new symbol or something else.

Here is a piece of my code:
```jsx
const compositeDecorator = new CompositeDecorator([
  {
    strategy: findLeftParts,
    component: LeftPart,
  },
  {
    strategy: findRightParts,
    component: RightPart,
  },
]);

function findLeftParts(contentBlock, callback) {
  const text = contentBlock.getText();

  findWithRegex(/cool regex for rule's left part/g, text, callback);
}

function findRightParts(contentBlock, callback) {
  const text = contentBlock.getText();

  findWithRegex(/cool regex for rule's right part strings/g, text, (start, end) => {
    /*
      here I can't simple call callback(start, end),
      because I need to undestand does `left part` exists with the same text
      between `start` and `end` in current `contentBlock`.
      If such exists, I need to wrap it in `LeftPart` component otherwise `RightPart`
    */
  });
}
```

Is it possible to do that?
Thanks!

**Comment by MikeDevice** [comment]
I've understood one thing. There is no way to solve this task in one iteration, because on every text changing I need to analyze **entire editor text** after it have been changed and then apply decorators strategies.
Now, when decorator strategies are called, editor still has old text and I can't analyze it. So I need to call decorator strategies again after `editorState` changed.
I tried to find out how to do it and have found one solution: reset decorators in `onChange` method.
```jsx
onChange(editorState) {
  const decorator = new CompositeDecorator([
    {
      strategy: findLeftParts,
      component: LeftPart,
    },
    {
      strategy: findRightParts,
      component: RightPart,
    },
  ]);

  this.setState({
    editorState: EditorState.set(editorState, { decorator })
  });
}
```
It would work, but I think it's not a good idea and it's slow. Also I've found one issue, that possible can be related: https://github.com/facebook/draft-js/issues/458

**Comment by flarnie** [comment]
Hi @MikeDevice - based on what you've written so far, I think your use case may be out of scope from what Draft.js normally supports. For example, if you were trying to write a code editor or something on that level, it's not really what Draft is aimed at enabling.

Can you give more detail about what the user should be able to do? I'd like to give better guidance, and that might help.

**Comment by MikeDevice** [comment]
Thanks for your reply! I want to write an editor for [LL(1) grammar](https://en.wikipedia.org/wiki/LL_grammar), that consists of three types of entity: `terminal`, `nonterminal` and `ε`.

So I want to highlight each of that entity types. It's easy to highlight `ε` with one simple decorator, but situation with `terminal`, `nonterminal` is harder.

In my editor I took as a basis follow rules:
1. Terminal is any non whitespace sequence
2. Nonterminal is any non whitespace sequence which is at the beginning of the rule.

Example:
```
S -> a B A
A -> b c
A -> ε
```
Here is `S`, and `A` are nonterminals, `a`, `B`, `c` are terminals. But if I add another one rule
```
S -> a B A
A -> b c
A -> ε
B -> a b
```
then `B` becomes a `nonterminal`. So I should to re-highlight `B` from `terminal` to `nonterminal`

**Comment by flarnie** [comment]
I have thought about this quite a bit, and this is out of scope for what Draft.js can provide. You would need a more complex data structure to represent the relationship between those pieces of text than the EditorState and BlockMap that Draft.js uses. Closing this since I don't see any action items here, sorry that we aren't able to help.
