### ISSUE TITLE
convertFromHTML document is not defined, server side rendering

### ISSUE THREAD

**Issue by terencechow** [facebook/draft-js#1361]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I get a document is not defined error when attempting to `convertFromHTML` from the server. Specifically I have a universal app where a user is writing in a draft js editor. They may save their work if they are half done. That is saved in HTML on the server (because the end product is HTML). If they later come back to their page, the HTML is grabbed from the database, the HTML should be preloaded to the draft js editor. However to `convertFromHTML` first and then create the editor state requires using the document. Not sure why document is needed? How are we supposed to do server side rendering if the text was html?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
Can't really display this in a jsfiddle because the jsfiddle has access to a document and this issue only occurs in server side rendered code

**What is the expected behavior?**

document should not be required to convert html to state.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

Draft v 0.10.1

**Comment by terencechow** [comment]
came across https://github.com/facebook/draft-js/issues/586 and see that `convertFromHTML` is not expected to be implemented for the server. I copied the information provided in that url to solve this for server side rendering.

1. add `jsdom` to your `package.json`. (It needs to be >= 10 for the code below to work, but you can easily adapt for jsdom <10 by following the jsdom api for < 10)
2. in `webpack.client.js` add the below to the plugins array: (plugins is for webpack >=2)
    {
       ...
       plugins: [
            ...some other plugins
            new webpack.IgnorePlugin(/jsdom$/))
            ],
       ...
    }

This is needed so that webpack doesn't bundle `jsdom` in your client config, where it doesn't have access to `fs`, `net`, `tls` etc packages. (Also theres no reason to have jsdom in the client bundle

3. finally create a file called `stateFromHTML.js` as per below:

```
import { convertFromHTML, ContentState } from 'draft-js'

function serverDOMBuilder (html) {
  const jsdom = require('jsdom')
  const { JSDOM } = jsdom

  const { document: jsdomDocument, HTMLElement, HTMLAnchorElement } = (new JSDOM(`<!DOCTYPE html>`)).window
  // HTMLElement and HTMLAnchorElement needed on global for convertFromHTML to work
  global.HTMLElement = HTMLElement
  global.HTMLAnchorElement = HTMLAnchorElement

  const doc = jsdomDocument.implementation.createHTMLDocument('foo')
  doc.documentElement.innerHTML = html
  const body = doc.getElementsByTagName('body')[0]
  return body
}

export default function stateFromHTML (html) {
  // if DOMBuilder is undefined convertFromHTML will use the browser dom,
  //  hence we set DOMBuilder to undefined when document exist
  let DOMBuilder = typeof document === 'undefined' ? serverDOMBuilder : undefined
  const blocksFromHTML = convertFromHTML(html, DOMBuilder)
  return ContentState.createFromBlockArray(
     blocksFromHTML.contentBlocks,
     blocksFromHTML.entityMap,
   )
}
```

4. use `stateFromHTML` anywhere you want to create a draft js ContentState

**Comment by schneyer** [comment]
It appears that the latest version of Draft-JS also references the `Node` type, which is also available on the `jsdom` package... so it also needs to be imported from `window` and tacked onto `global` for this to still work server-side.

**Comment by ankeshdamahe** [comment]
I am facing issue with span tags and also strong tags are also not working here is my code.
can any one help me for this
```
    const { JSDOM } = jsdom;
    const { window } = new JSDOM();
    const { document } = (new JSDOM(`<!DOCTYPE html>`)).window;
    global.document = document;
    global.navigator = window.navigator
    global.HTMLElement = window.HTMLElement
    const djs = require('draft-js')
    const html = '<p>Hey this <span>editor</span> rocks 😀</p>';
    const json=djs.convertToRaw(djs.ContentState.createFromBlockArray(djs.convertFromHTML(html)))
    console.log("Hello",json);
    var jQuery = require('jquery')(window);
    ```

**Comment by rpavilanis** [comment]
> It appears that the latest version of Draft-JS also references the `Node` type, which is also available on the `jsdom` package... so it also needs to be imported from `window` and tacked onto `global` for this to still work server-side.

Hi there - this is an older comment but I just thought I would check here. I followed @terencechow's recommendations for this, and now I am getting an "Error: Cannot find module 'jsdom' This error happened while generating the page. Any console logs will be displayed in the terminal window." after ignoring jsdom in my next.config.js file.  I'm wondering if I need to follow the steps @schneyer mentioned but I'm not sure how/where to do that.  Could anyone help with this?
