### ISSUE TITLE
api for fontsize

### ISSUE THREAD

**Issue by Amara-Balakrishna1** [facebook/draft-js#137]
is it possible to extend redlining concept in draftjs.
http://nytimes.github.io/ice/demo/....
please mention perfect api for all document options...
https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

**Comment by hellendag** [comment]
You can use inline styles (http://facebook.github.io/draft-js/docs/advanced-topics-inline-styles.html#content) to define various font sizes for your editor.

> please mention perfect api for all document options... execCommand

I'll be direct about this: please do not use `execCommand` to modify a Draft-based editor. You should use the `EditorState` model to define your state, *not* the DOM.

**Comment by Amara-Balakrishna1** [comment]
how about tracking changes
