### ISSUE TITLE
Fix image rendering

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1377]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
In Firefox and Chrome (haven't tested other browsers) since https://github.com/facebook/draft-js/commit/0b22d713d556ccc4820850099ad6231493b3f7aa we don't get the image blocks when using `convertFromHTMLToContentBlocks`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

You can see this in the `examples/draft-0-10-0/convertFromHTML/convert.html` file.

**What is the expected behavior?**

It should render an image.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

Unreleased version of Draft.js, is only on master.

**Comment by flarnie** [comment]
This should have been fixed. :)

**Comment by michelson** [comment]
Hi @flarnie , in which version this is fixed ? Using 0.10.5 we I've hit this behavior .
