### ISSUE TITLE
Comparing EditorState instances

### ISSUE THREAD

**Issue by malcolmredheron** [facebook/draft-js#1379]
**Do you want to request a *feature* or report a *bug*?**

Feature, I think.

**What is the current behavior?**

Creating EditorState instances, at least using createWithContent/createFromText, produces different keys in the block map.

It would be much easier to test my code if my tests could create EditorState instances the same way as the real code and get equal results. Failing that, do you have any guidance on how to test code that creates and modifies an EditorState?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

https://jsfiddle.net/m6z0xn4r/286/ shows the problem.

**What is the expected behavior?**

I would like creation and modifications of EditorState to be deterministic, so that tests are easier to write.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

This happens with Draft 0.7, 0.10 and 0.10.6.

**Comment by nsfmc** [comment]
hi @malcolmredheron , if you do need deterministically created `contentState`, you can get the same effect with convertFromRaw using a very basic rawDraftContentstate as in https://jsfiddle.net/9m3pqwnu/ (this was a ~0.10.1ish change to get ssr not throwing errors)

**Comment by malcolmredheron** [comment]
Good to know! Thank you.
