### ISSUE TITLE
Select all on focus

### ISSUE THREAD

**Issue by yss14** [facebook/draft-js#1386]
Is it possible to select the whole text when the user focuses the editor?
Can't find an approach on the other issues neither on the documentation.

**Comment by zhiquan-yu** [comment]
You can use [Selection.selectAllChildren()](https://developer.mozilla.org/en-US/docs/Web/API/Selection/selectAllChildren)

**Comment by yss14** [comment]
How do I apply this with draft.js? The draft.js `Selection` doesn't support `selectAllChildren()` and applying this to the editors DOM doesn't work.

**Comment by athomann** [comment]
Did you figure this out @yss14? I'm also trying to do this.

**Comment by yss14** [comment]
@athomann Unfortunately not.

**Comment by athomann** [comment]
@yss14 I was able to get the Select all effect by doing 
```
document.execCommand('selectAll', false, null)
```
after calling a `.focus()`.  Might have to debounce the command.

**Comment by cusxio** [comment]
Here's what I did.

```js
select() {
  const { editorState } = this.state;
  const currentContent = editorState.getCurrentContent();
  const firstBlock = currentContent.getBlockMap().first();
  const lastBlock = currentContent.getBlockMap().last();
  const firstBlockKey = firstBlock.getKey();
  const lastBlockKey = lastBlock.getKey();
  const lengthOfLastBlock = lastBlock.getLength();

  const selection = new SelectionState({
    anchorKey: firstBlockKey,
    anchorOffset: 0,
    focusKey: lastBlockKey,
    focusOffset: lengthOfLastBlock,
  });

  this.setState({
    editorState: EditorState.acceptSelection(editorState, selection),
  });
}
```

It works, but I have not tested it thoroughly.

**Comment by qmind1995** [comment]
@cusxioI I tried but it doesn't work for me :(

**Comment by markopol0** [comment]
CSS `user-select: all` 
Only supported in [Chrome and Firefox](https://caniuse.com/#search=user-select%3A%20all)
More info: https://css-tricks.com/almanac/properties/u/user-select/

**Comment by cusxio** [comment]
@qmind1995 

> @cusxioI I tried but it doesn't work for me :(

In some case, you need to use `forceSelection` instead of `acceptSelection` 

i.e.

```js
this.setState({
  editorState: EditorState. forceSelection(editorState, selection),
});
```

**Comment by Developer-53** [comment]
Can someone please help me, how to Select multiple paragraphs in Draftjs editor for indent/outdent?
