### ISSUE TITLE
ordered-list-item doesn't preserve ordering when nesting unordered-list-item

### ISSUE THREAD

**Issue by juliepanda** [facebook/draft-js#1392]
**Do you want to request a *feature* or report a *bug*?**
bug...?

**What is the current behavior?**
Nested `ordered-list-item` resets when there's an `unordered-list-item` in the middle.
You can find the reproduced behavior in the fiddle here: https://jsfiddle.net/pdx57nzg/

Current behavior (CASE 1):
![screen shot 2017-09-18 at 9 53 55 pm](https://user-images.githubusercontent.com/7796312/30572532-3bcc53d0-9cbc-11e7-88e9-06ea4d38c3ab.png)

However, the ordering is preserved when all blocks are` ordered-list-item` (CASE 2):
![screen shot 2017-09-18 at 9 57 42 pm](https://user-images.githubusercontent.com/7796312/30572593-9d25a71c-9cbc-11e7-920f-a138ec9a103e.png)

**What is the expected behavior?**
Not sure if this is expected behavior. I was expecting something more like the screenshot below. Would love to know a workaround if anyone has encountered the same problem, like if there's a way to set order number for `ordered-list-item` on the block.
![screen shot 2017-09-18 at 9 54 03 pm](https://user-images.githubusercontent.com/7796312/30572535-43744dea-9cbc-11e7-9425-d5e6ac08c966.png)

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Chrome 60/Mac OS/draft-js 0.10.1

**Comment by niveditc** [comment]
This is expected behavior at the moment. We may be able to improve upon it with some changes to the data model from a list of blocks to a tree of blocks (currently experimental).
