### ISSUE TITLE
mark 0.10.2 release on github

### ISSUE THREAD

**Issue by nsfmc** [facebook/draft-js#1396]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
only 0.10.1 is shown

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: 
visit https://github.com/facebook/draft-js/releases and see only 0.10.1

**What is the expected behavior?**
visit https://github.com/facebook/draft-js/releases and see 0.10.2

**Comment by flarnie** [comment]
Thanks! Will fix.

**Comment by flarnie** [comment]
You're a lifesaver @nsfmc ✨🌟

**Comment by nsfmc** [comment]
no, you are @flarnie !
