### ISSUE TITLE
No easy way to get decorated text within decorator component

### ISSUE THREAD

**Issue by spicyj** [facebook/draft-js#140]
If you want the decorator styles to be different depending on the text that's decorated, it would be nice to get the text somehow. Best I came up with is:

```js
{
  strategy: ...,
  component: (props) => {
    // This isn't public API.
    const text = props.children.map((leaf) => leaf.props.text).join('');
    ...
  },
}
```

though it looks like `DraftEditorBlock.react` could easily pass down more information about the contained leaves. Maybe a reference to the block and the range would be enough?

`props.offsetKey` currently contains the block key, but `DraftOffsetKey` is not exposed as public API so you can't decode it, plus the block key is not useful without a reference to the editor state which I don't believe you have.

**Comment by hellendag** [comment]
Discussed a bit in #68. We should provide `decoratedText` as a prop to the decorator component. Want to PR it? :)

**Comment by spicyj** [comment]
Ah, I missed that. Is it possible that the text has inline styles that the decorator component might want to read?

**Comment by hellendag** [comment]
Interesting thought. I suppose it's possible, but I can't think of a use case.

**Comment by abdulhannanali** [comment]
:+1:
