### ISSUE TITLE
Allow developing/testing Draft with React 16

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1411]
Updating `devDependencies` to allow React 16 and running the tests leads to some failures. We should debug and fix this, so that we are developing Draft to run with the latest version of React.

**Edit:** Here is more detail about how to fix this, and if you'd like to pick it up please comment on the issue. :)

1. Update `devDependencies` in `package.json` to add `| ^16.0` to the current `react` and `react-dom` versions. *NOTE* that this is a different section from `dependencies` or `peerDependencies`.
2. Update any other dependencies (like Enzyme) which have released a recent version which accepts React 16 as a dependency.
3. Fix any failing tests, lints, flow errors resulting from the changes.

**Comment by itssujan** [comment]
@flarnie I can take this up. Might be a good starter for me

Looks like Enzyme has a major upgrade from 2.x to 3.x and also uses an adapter `enzyme-adapter-react-16 ` for supporting React 16.

And also the ReactTestUtils seems to have been moved out to the ReactDOM package in one of the 2.x revisions.

**Comment by flarnie** [comment]
Thanks @issujan!

**Comment by itssujan** [comment]
https://github.com/facebook/draft-js/pull/1464

**Comment by claudiopro** [comment]
This issue was apparently resolved with 5a965e6.
