### ISSUE TITLE
Receiving support?

### ISSUE THREAD

**Issue by Francolpm** [facebook/draft-js#142]
Hi there!
Sorry about this question here but, are you accepting donations or supports?
Because I want to give some of money to draft-js, but there is no donate button o something like that.
I don't trying to spam you, but I want to invite you to beerpay.io, a simple platform to monetize open source projects, like draft-js. 
I know that the open source is free, but it's okay if someone want to contribute in other way.

Thanks for this work!

**Comment by zpao** [comment]
I appreciate the enthusiasm, but we are not accepting donations (the maintainers right now are paid to work on this) but would encourage you to donate to some organizations who would benefit directly, like [Girls Who Code](http://girlswhocode.com/) or the [OSI](https://opensource.org/donate); or establish specific bounties that community members could claim via something like [bountysource](https://www.bountysource.com/).

**Comment by Francolpm** [comment]
Okay @zpao. 
I'll check the links, thanks for reply!

Cheers!
