### ISSUE TITLE
Composite Decorator not rendering when inserted "on the fly"

### ISSUE THREAD

**Issue by victor-accarini** [facebook/draft-js#1421]
Hi

I implemented a CompositeDecorator to show how many characters exists in each line of my editor.
It adds a \<span\> with the line size and `position: absolute` to keep it out of selection browser behavior.

![linesize](https://user-images.githubusercontent.com/5943663/31185564-ae179c5e-a902-11e7-9f93-518295b5ada4.png)

If I start the editor state with the decorator it will always show the number of characters for each line, but I would like to hide this when the user is typing, so I attached a function to **onFocus** and **onBlur**, where I use the `EditorState.set(myCurrentState, {decorator: null or myDecorator})` and then use the `this.setState` to update the editor state.

Everytime I do this "on the fly" change the component is rendered, the strategy is performed but my decorator component doesn't disappear or in the case that I start the editor without the decorator it doesn't appear.

Am I missing something?

``` js
import React from 'react';
import ReactDOM from 'react-dom';
import { Editor, EditorState, CompositeDecorator } from 'draft-js';

const lineSizeStyle = {
    position: 'absolute',
    userSelect: 'none',
    marginLeft: '10px',
    fontSize: '0.6em',
    verticalAlign: 'top',
};

/* This doesn't render */
class LineSizeDisplay extends React.Component {
    render() {
        let textSize = this.props.decoratedText.length;
        return (
            <span className='line'>
                {this.props.children}
                <span
                    style={lineSizeStyle}
                    className='line-size'
                    contentEditable={false}
                >
                    {'(' + textSize + ')'}
                </span>
            </span>
        );
    }
}

class MyEditor extends React.Component {
    constructor(props) {
        super(props);
        this._addLinesSize = this._addLinesSize.bind(this);
        this._removeLinesSize = this._removeLinesSize.bind(this);

        this.lineSizeDecorator = new CompositeDecorator([
            {
                strategy: this.lineSizeStrategy,
                component: LineSizeDisplay,
            },
        ]);

        this.state = {editorState: EditorState.createEmpty(this.lineSizeDecorator)};
        this.onChange = (editorState) => this.setState({editorState});
    }

    /* This is executed every time I add the CompositeDecorator */
    lineSizeStrategy(contentBlock, callback, contentState) {
        const text = contentBlock.getText();
        callback(0, text.length);
    }

    _addLinesSize(evt) {
        let newEditorState = EditorState.set(
            this.state.editorState,
            {decorator: this.lineSizeDecorator}
        );
        /* This triggers rendering */
        this.setState({
            editorState: newEditorState,
        });
    }

    _removeLinesSize(evt) {
        let newEditorState = EditorState.set(
            this.state.editorState,
            {decorator: null}
        );
        /* This triggers rendering */
        this.setState({
            editorState: newEditorState,
        });
    }

    render() {
        return (
            <Editor
                editorState={this.state.editorState}
                onChange={this.onChange}
                textAlignment='left'
                onBlur={this._addLinesSize}
                onFocus={this._removeLinesSize}
            />
        );
    }
}
```

**Comment by Jarred-Sumner** [comment]
`onChange` will get called when the cursor moves. I would try revising your `onChange` function to also update the `decorator` to be what you'd expect (which probably means tracking `isFocused` within `state` 😢)

**Comment by flarnie** [comment]
@Jarred-Sumner is correct. I will write a quick demo of how this could work. The version you have there will fall into a race condition, as described here - https://draftjs.org/docs/advanced-topics-editorstate-race-conditions.html#content

**Comment by flarnie** [comment]
Here is a working example: https://jsfiddle.net/m6z0xn4r/355/
![working_example_of_managing_focus](https://user-images.githubusercontent.com/1114467/32026128-d16cfe6a-b997-11e7-9371-54d1238edd78.gif)

Hope this is helpful.
