### ISSUE TITLE
Docs use development build of React

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1444]
Not totally sure if this is fixable or worth fixing - we have sort of a convoluted build system for the docs. But I'd like to try and fix it.

Seems like we would just want to use the production package of React.
![screen shot 2017-10-20 at 11 16 44 am](https://user-images.githubusercontent.com/1114467/31835916-56b8fef2-b588-11e7-93da-4ea8ec4a82fe.png)

**Comment by niveditc** [comment]
Fixed with Docusaurus.
