### ISSUE TITLE
Broken down-arrow key in 'link' example on Firefox

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1450]
**Do you want to request a *feature* or report a *bug*?**
A bug!

**What is the current behavior?**
In the "link" example, if you add a link, you can no longer use the down-arrow key to move down to the next line. Tabbing to another tab and returning to the example tab fixes it.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

1. Open the 'link' example'
2. write some text on the first line, and create a link somewhere in the text.
3. Hit 'enter' to create a new line, enter some text, and create a link in that text. Use the arrow keys to move the cursor after you create the link, rather than the mouse. Move the cursor up to the line above.
4. Try hitting the down arrow key. It won't move back down to the below line.

No errors are logged in the console.

**What is the expected behavior?**
The 'down arrow' key should always allow you to move down one line.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

This appears in the newly released 0.10.4 and the previous version, 0.10.3. I didn't test any earlier versions.

I saw this on Firefoxon MacOSX. Also tested on Chrome on MacOSX, and Edge on Windows, and it was *not present* in those two browsers. Only in Firefox.

**Comment by jackyho112** [comment]
A related past issue - https://github.com/facebook/draft-js/issues/1450

**Comment by flarnie** [comment]
This seems like a duplicate of https://github.com/facebook/draft-js/issues/985
