### ISSUE TITLE
Typescript DraftBlockType too strict?

### ISSUE THREAD

**Issue by camurai** [facebook/draft-js#1453]
Its possible that I am missing an obvious way I am supposed to be doing this, but it seems like the DraftBlockType is too specific, making it impossible to add in custom block types in typescript. I was following the example found in the docs here:
https://draftjs.org/docs/advanced-topics-block-components.html#content 

Trying to use the code in the example in a typescript project, I got the following error, coming from the line where the Editor object is created in the render function:
```ts
 Type 'string' is not assignable to type '"unstyled" | "paragraph" | "header-one" | "header-two" | "header-three" | "header-four" | "header...'.
```
This seems to stem from the fact that blockRenderMap is expecting a Immutable.Map<DraftBlockType, any>, while anything I create with the merge will have to be Immutable.Map<string, any>

I've tried setting the types, but since DraftBlockType does not contain my custom block type, and blockRenderMap expects the key to be DraftBlockType, no custom Block types can be added.

To test things out I edited the type for DraftBlockType in the node-module and set it to just be "string" instead of "unstyled" | "paragraph" | ....
This seems to make it so I am able to compile without the error messages.

So is there a different way to create a Custom Block Component that gets around the DraftBlockType, or was DraftBlockType just made too strict when the type file was setup?

**Comment by mitermayer** [comment]
Hi @camurai,

Thanks for reporting this issue

**Comment by mitermayer** [comment]
Hi @xFloooo,

`DefinitelyTyped` is a community driven repository, you should submit an issue/PR to that repo for requesting this changes.
