### ISSUE TITLE
Accepting a spell check correction in chrome on a decorated entity causes an unexpected DOM change.

### ISSUE THREAD

**Issue by DanielAtFaithlife** [facebook/draft-js#1469]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
In Chrome, if a user accepts a spell check correction on a decorated entity, where the structure of the decorator includes a span element, the correction will replace the span in the DOM, leaving the editor in an unusable state.

**Minimal demo, using some code snippets from the Draft examples**
https://jsfiddle.net/y56qt91f/ 
In chrome, simply right-click and accept "Batman" as the correct spelling. The first half of the text is removed, and the entity cannot be deleted. 
If `style={{display:'inline'}}` is added to the `<span>` element, the editor behaves as expected. It also behaves as expected if the element is a `<div>`.

**What is the expected behavior?**
The expected behavior is that the correction would simply replace the text that's being corrected.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Draft.js version: 0.10.4
Chrome 61.0.3163.100 on Windows 10 Build 14393
I have not tested in previous versions of Draft.js.

**Comment by matheusan** [comment]
+1 Having the same issue

**Comment by gmertk** [comment]
Make sure you're using `<span data-offset-key={props.offsetkey}>` as in the `entity.html` example. It seems to be working fine with the latest version.
