### ISSUE TITLE
onEscape not firing in Chrome (editOnKeyDown doesn't seem to be called on escape)

### ISSUE THREAD

**Issue by buob** [facebook/draft-js#1470]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In Chrome, when I bind a function to `onEscape`, it isn't called.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

You can see the issue here - https://jsfiddle.net/h0601Lnc/ (when you hit arrow up it logs to the console fine, but when you hit escape in chrome it doesn't log anything)

If you go to https://draftjs.org and put a breakpoint [here](https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnKeyDown.js#L88), it looks like all of the other keys are triggering `editOnKeyDown`, (i.e. tab, arrows, etc.) but hitting escape isn't even triggering this function.

**What is the expected behavior?**

The above fiddle should log to the console when you hit escape.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

I'm currently testing on Chrome Version 62.0.3202.62 on Mac OS 10.12.6 (I've tested on Safari 11.0 and Firefox 53.0.3 [64-bit] and it works fine).

**Comment by buob** [comment]
🤦‍♂️ 

Don't I feel like an idiot for not testing this incognito (thanks @ismyrnow) -- This happens to be [vimium](https://github.com/philc/vimium) not passing the escape key through to the browser.  Hopefully this helps someone else, but I'm skeptical. 😏  😞

**Comment by flarnie** [comment]
I think it may help someone else @buob - glad you found the cause. We know of several browser extensions that cause issues with Draft, might be good to open an issue to brainstorm about how to handle those cases.
