### ISSUE TITLE
Tooltip functionality in draftjs contain another editor 

### ISSUE THREAD

**Issue by ashokpatidar** [facebook/draft-js#1474]
**Do you want to request a *feature* or report a *bug*?**
We have one requirement where we need to use tooltip for rich text editor but that tooltip panel also have one editor.  
**What is the current behavior?**
unable to store the tooltip panel editor state. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

**What is the expected behavior?**

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

**Comment by ashokpatidar** [comment]
need this functionlity

**Comment by flarnie** [comment]
Hi - could you please give us more info? What is the problem that prevents you from storing the editor state of the nested editor? Hypothetically this should be possible, depending on how you implement it and what features you need.

**Comment by niveditc** [comment]
Closing due to no response.
