### ISSUE TITLE
`blockRenderFn` not called on state changes

### ISSUE THREAD

**Issue by remko** [facebook/draft-js#148]
I have a custom block render function that depends on information from the state. When the state of my component changes, the `blockRenderFn` is not called again, so my component never gets updated. Is this intended behavior? If so, how can I force my custom blocks to be rerendered?

I have tried creating a minimal example below. My editor has a media component that is rendered as an `<img>`; when the image is clicked, it should get a border. I notice that `render` is called on click, but `renderBlock` isn't, and so the `Image` component never gets rerendered with a border.

    const Image = (props) => {
      const { selected, onSelect } = props.blockProps;
      const style = selected ? {border: 'thick solid red'} : {};
      return (
        <img 
          style={style} 
          src="https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png"
          onClick={() => { if (!selected) { onSelect(); } }}
          />
      );
    };

    class App extends React.Component {
      constructor(props) {
        super(props);
        this.state = { 
          selectedComponent: undefined,
          editorState: EditorState.createWithContent(
            ContentState.createFromBlockArray(convertFromRaw({
              blocks: [ { text: ' ', type: 'media' } ],
              entityMap: {}
            })))
        };
      }

      renderBlock(contentBlock) {
        if (contentBlock.getType() === 'media') {
          return {
            component: Image,
            props: { 
              selected: this.state.selectedComponent === contentBlock.getKey(),
              onSelect: () => { 
                this.setState({selectedComponent: contentBlock.getKey()});
              }
            }
          };
        }
      }

      render() {
        return (
          <Editor
            blockRendererFn={this.renderBlock.bind(this)}
            editorState={this.state.editorState}
            onChange={(editorState) => { this.setState({editorState}); }}
          />
        );
      }
    }

**Comment by hellendag** [comment]
My thought is that even though your top-level state value for `selectedComponent` is changing, your `editorState` is not. Since `DraftEditorContents` [won't re-render] (https://github.com/facebook/draft-js/blob/master/src/component/contents/DraftEditorContents.react.js#L73) with the same `editorState` prop, no re-render for your block component can occur.

You could use `EditorState.forceSelection` to "select" your block within the model, though this won't actually set the DOM selection unless you do so within your custom component.

**Comment by remko** [comment]
@hellendag Thanks for pointing this out. Doing a `forceSelection` together with the state change indeed triggers a block re-render, so this seems to solve my problem.

**Comment by hellendag** [comment]
No problem. :)

**Comment by MatthewKosloski** [comment]
Hey, I'm having this same problem, too.  The only way to update the Editor state for me was by either deselecting the Atomic block or typing into the editor.  How and where did you do the `forceSelection`?

**Comment by MeKarina** [comment]
Have documentation on this issue?

**Comment by MatthewKosloski** [comment]
Okay so I spent another day attempting to resolve my issue, but I failed. 

**The Problem:** Custom block component (image) doesn't re-render/update in the Preview component.  When I change the alignment of the image (left, center, right), it responds perfectly; however, when I attempt to resize the image, it doesn't re-render.  In order for it to re-render, I need to update the editorState by typing.

_TL;DR_

I uploaded a [YouTube video](https://www.youtube.com/watch?v=3oKQ7KjtVD4) that demonstrates the issue I have.  Additionally, there are several annotations that describe what's happening, so make sure you turn annotations on.

Also, the [source code](https://github.com/MatthewKosloski/react-text-editor) is available if you'd prefer to look through that.

_Longer Explanation_

So I'm building a text editor and directly underneath it I have a preview.  Essentially what happens is when `onChange` is called from the Editor component, a "Preview" component is rendered and "rawContent" is passed into it.

This is what that looks like:

(app.js)

    const renderOutput = (rawContent) => {
	  render(<Preview rawContent={rawContent} />, document.getElementById('output'));
    };

    render(
	  <div>
		  <TextEditor onChange={renderOutput}/>
 	  </div>
    , document.getElementById('app'));

(TextEditor)

    onChange(editorState) {
		this.props.onChange(convertToRaw(editorState.getCurrentContent()));
	}

This works well, but not for custom block components.  For instance, when I add the image, the image doesn't appear in the preview until I alter the editorState by typing.  Also, when I resize the image, sometimes the preview image's `width` and `height` aren't updated, but sometimes they are.  It's quite bizarre.  The `alignment` property is the only one that updates.

I created a custom block component called "image," which is rendered from a larger single unit component called "Atomic."  This is what the blockRenderer function looks like.  (Preview component has the same function except the `isEditor` prop is false)

    blockRenderer(contentBlock) {
		if (contentBlock.getType() === 'atomic') {
			return {
				component: Atomic,
				editable: false,
				props: {
					isEditor: true
				}
			};
		}
		return null;
	}

This is an excerpt from the Atomic.js file.  The returned node is predicated on the `isEditor` blockProp.  If `isEditor` is set to true, an "ImageWrapper" component is rendered, which allows the user to align and scale the image.  If false, just an image is rendered.

    renderImageComponent(entityData) {
		const {isEditor} = this.props.blockProps;
	    return isEditor ? (
	        <ImageWrapper 
	        	onAlign={this.onAlign}
	        	onResize={this.onResize} 
	        	entityData={entityData}> 
	        </ImageWrapper>
	        ) : (
	        <AtomicImage 
	        	entityData={entityData}
	        />
	    );
	}

    render() {
    	const {block} = this.props;
    	const entity = Entity.get(block.getEntityAt(0));
    	const type = entity.getType();
		switch(type) {
			case 'image': {
				return this.renderImageComponent(entity.getData());
			}
			default:
				return '';
		}
    }

The ImageWrapper is quite involved.  I'll do the best I can to explain. 

There is a component called "ActionBar" inside the ImageWrapper.  All it does is encapsulate the three alignment buttons.  It accepts three props: `onClickLeft`, `onClickRight`, and `onClickCenter`.  When a certain button is clicked, it calls the function that was passed into the ImageWrapper's `onAlign` property.  Here's a quick, summarized excerpt from the ImageWrapper and Atomic components:

(ImageWrapper)
   
    <ActionBar 
	  onClickLeft={onAlign.bind(null, 'left')}
	  onClickCenter={onAlign.bind(null, 'center')}
	  onClickRight={onAlign.bind(null, 'right')}>
    </ActionBar>

(Atomic)

    onAlign(alignment) {
        const {block} = this.props;
        const entityKey = block.getEntityAt(0);
        Entity.mergeData(entityKey, {alignment});
    }

For resizing, there is a property called `onResize` on the ImageWrapper component.  When the image is resized, it calls the function that was passed into the ImageWrapper's `onResize` property.  Here's a quick, summarized excerpt from the ImageWrapper and Atomic components:

(Image Wrapper)

    <Resizable 
	width={stateWidth}
	height={stateHeight} 
	onResize={this.handleResize}
	onResizeStart={this.toggleDimensionsDisplay}
	onResizeStop={this.toggleDimensionsDisplay} 
	lockAspectRatio={true}>
	<div style={editorImgStyle}>
		<img 
			ref="img" 
			src={src} 
			style={editorImgStyle} 
			alt={caption}
			onLoad={this.handleImageLoad}
		/>
	</div>
    </Resizable>

Upon resizing the image, `handleResize` is called:

	handleResize(event, {element, size}) {
		const {width, height} = size;
		this.setState({stateWidth: width, stateHeight: height});
		this.props.onResize(width, height);
	};

It calls the `onResize` function that is found in the Atomic component:

(Atomic)

    onResize(width, height) {
    	const {block} = this.props;
        const entityKey = block.getEntityAt(0);
    	Entity.mergeData(entityKey, {width, height});
    }

As you can see, `onResize` and `onAlign` are very similar.  But why does the `alignment` property on the image always get updated and not the widths and heights?
