### ISSUE TITLE
can't add image in firefox, draft js >=10.0.0 (it work in chrome & opera)

### ISSUE THREAD

**Issue by thuc201995** [facebook/draft-js#1487]
the console log error:
"The above error occurred in the <DraftEditorLeaf> component:
    in DraftEditorLeaf (created by DraftEditorBlock)
    in div (created by DraftEditorBlock)
    in DraftEditorBlock (created by DraftEditorContents)
    in div (created by DraftEditorContents)
    in div (created by DraftEditorContents)
    in DraftEditorContents (created by DraftEditor)
    in div (created by DraftEditor)
    in div (created by DraftEditor)
    in div (created by DraftEditor)
    in DraftEditor (at MediaEditorExample.js:139)
    in div (at MediaEditorExample.js:138)
    in div (at MediaEditorExample.js:114)
    in MediaEditorExample (at App.js:10)
    in App (at index.js:7)

Consider adding an error boundary to your tree to customize error handling behavior.
You can learn more about error boundaries at https://fb.me/react-error-boundaries."

**Comment by mitermayer** [comment]
Hi @thuc201995,

Thanks for reporting, we will check on this soon. In the meantime can you check https://draftjs.org/docs/advanced-topics-issues-and-pitfalls.html#content to see if you may be experiencing due to some those known issues ?

thanks!

**Comment by thibaudcolas** [comment]
Not sure if this helps but I have no trouble inserting images in [my implementation](https://springload.github.io/draftail/). Tested on Firefox 57, macOS 10.13, with React 16.
