### ISSUE TITLE
Inconsistency between FB and Draft configs for linting Flow object types

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1492]
Lint is failing on the master branch of Draft.js because within FB we prefer commas in type definitions, and in Draft prettier requires semicolons.

We should probably update Draft to prefer commas, like we apparently do within Facebook. This will be most easy for someone at FB to fix, but in case other folks want to know why lint is failing I'm opening this issue.

@sophiebits @mitermayer @vjeux seem like the relevant folks to tag here

See failures on https://our.intern.facebook.com/intern/diff/D6246053/?dest_number=37510937 and compare with the master branch of Draft.

I'm digging around for where this setting is configured, but so far things look consistent between Draft.js and FB.

**Comment by vjeux** [comment]
At flow's team request, prettier now uses ; instead of , but I haven't updated www yet to the version that contains this change.
