### ISSUE TITLE
support & example of widgets

### ISSUE THREAD

**Issue by robertleeplummerjr** [facebook/draft-js#150]
Inside contenteditable you can:

``` html
<div contenteditable="true">
  <p>Top</p>
  <div contenteditable="false">
    <p>I'm a widget</p>
    <div contenteditable="true"></div>
  <div>
  <p>Bottom</p>
<div>
```

Can this be achieved with draft.js?  If so, can we get an example?  If not, can you easily achieve this?

**Comment by hellendag** [comment]
What is your use case? Nesting this way can *sort of* work, but there may be other ways to do what you're aiming to accomplish.

**Comment by javan** [comment]
His use case https://github.com/basecamp/trix/issues/191#issuecomment-191908984:
> ... my context would be nested editable elements. Imagine you could insert a tabbed widget, where you could add tabs, and edit their content, but not the tabbed widget structure.

**Comment by hellendag** [comment]
Does the TeX example help suggest how something like this might be done?

Nesting a `contentEditable` within a Draft editor could lead to some significant issues with selection handling, so that would be my main concern. However, by setting the outer editor to `readOnly` while you are providing edit behavior within your widget, as in the TeX example, you can nest inputs.

**Comment by MarkNijhof** [comment]
Related question; could you have an outer editor with readOnly=false and an inner editor with readOnly=true to create non editable elements in text?

**Comment by muneendrakumarc** [comment]
I have an usecase which is same like facebook,  user is having facility to to mention the other users using '@  mention. we have implemented this @mention using angular plugin.  Now we have content editable div where we have to parse the span which has the username after selecting from @mention drop down to apply the required styling.    For doing this can draft.js is useful

**Comment by mitermayer** [comment]
Closing this thread for now, but if there is still interest in this discussion please feel free to reopen/comment or create a new issue around it.
