### ISSUE TITLE
Flow errors with basic Draft.js usage

### ISSUE THREAD

**Issue by bjohn465** [facebook/draft-js#1514]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When creating a very simple Draft.js project, Flow errors within Draft.js code.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
I have a demo of this problem here: https://github.com/bjohn465/draft-and-flow-errors

**What is the expected behavior?**
Draft.js should not cause Flow errors.

As noted [in the demo's README](https://github.com/bjohn465/draft-and-flow-errors#what-i-think-is-wrong), I believe the problem comes from `blockRendererFn` and `blockStyleFn` being defined as optional props to the `DraftEditor` component, when both of these props have default values specified via `defaultProps`. They should be marked as required props, as Flow will figure out that they are optional because of the `defaultProps` property.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
I found this in Draft.js version 0.10.4, using Flow 0.59.0 (the issue is also present using Flow 0.53.1).

**Comment by mitermayer** [comment]
Hi @bjohn465,

Thanks for reporting this issue, could you provide an example of how to replicate this ? Also we would love to upgrade Draft to flow 0.59.0, would you be interested in a submitting a PR for it ?

**Comment by bjohn465** [comment]
Thanks for the response, @mitermayer. I have a demo repository here: https://github.com/bjohn465/draft-and-flow-errors

I can at least get a pull request together for the errors I was seeing. Those were errors when attempting to use Draft.js and not when running Flow on the Draft.js project itself.

**Comment by bjohn465** [comment]
It turned out that there weren't any additional changes needed to upgrade Flow, so I fixed this issue and upgraded Flow in #1520.
