### ISSUE TITLE
Examples are broken locally

### ISSUE THREAD

**Issue by cdriscol** [facebook/draft-js#1516]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Currently examples do not work after we [upgraded the react deps](https://github.com/facebook/draft-js/commit/5a965e66e6f0d8521a2853fb981197854656d7f8) to support react 16.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: 
- Follow instructions on https://github.com/itssujan/draft-js#examples to setup examples
- Look at 404 errors for react.js and react-dom.js in console

**What is the expected behavior?**
Examples work as expected

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
All

**Comment by mitermayer** [comment]
Thank you! will test this tomorrow and add to my to merge list!
