### ISSUE TITLE
Permanently associating metadata with a block

### ISSUE THREAD

**Issue by remko** [facebook/draft-js#152]
I want to ensure that a piece of metadata is permanently associated with all my H1 blocks, and that there is no way that this metadata can get lost without deleting the entire block. 

My initial solution was: when the H1 button is clicked, call `RichUtils.toggleBlockType`, and then apply a mutable entity to the entire resulting block. This works, and the entity is maintained when doing changes to the block, except when characters are put at the beginning of the block (in which case the characters don't get the entity applied; this is confirmed in the entities example by adding characters to the beginning of a mutable entity), or when the block contents is cleared (so the block still exists but is empty). This means that with the right modifications, it's possible to get the entity deleted from the block, so the metadata is lost.

Another solution that comes to mind is listen to onChange on the editor, and for every change walk over all blocks and enforce that H1 blocks have the entity applied entirely, expanding the entity range if not the case (i.e. when the user added characters to the beginning of a block). This feels dirty, still loses the entity if you delete the entire contents of an H1 block, and is probably prone to some other error cases.

Is there another way to enforce that metadata is always kept with a block, and can't be lost without deleting the entire block?

**Comment by hellendag** [comment]
This sounds similar to the discussion in #129. It seems like the proposal there would help resolve this for you.

**Comment by remko** [comment]
That's indeed what I'm looking for! (and it would indeed clean up some other awkward things I'm doing, like the single-character custom blocks)

**Comment by hellendag** [comment]
Awesome! I'm going to close this issue in favor of that one, if you don't mind. :)
