### ISSUE TITLE
covert to Raw stores only default draft styles

### ISSUE THREAD

**Issue by dotcor** [facebook/draft-js#153]
This looks like it is intentional. 
Inside encodeInlineStyleRanges:
```
function encodeInlineStyleRanges(block) {
  var styleList = block.getCharacterList().map(function(c) {
    return c.getStyle();
  }).toList();
  var styles = Object.keys(DefaultDraftInlineStyle);
  var ranges = styles.map(function(style) {
    return getEncodedInlinesForType(block, styleList, style);
  });
  return Array.prototype.concat.apply(EMPTY_ARRAY, ranges);
}
```

customStyleMap styles are simply not saved.

A simple solution would be to pass the customStyleMap as a second parameter to convertToRaw(), since the customStyleMap lives only inside the react component.

**Comment by hellendag** [comment]
Nice catch, this is an oversight. Do you want to send a PR?

**Comment by hellendag** [comment]
cc @ezequiel
