### ISSUE TITLE
Is `onTab` working properly when pressing [Tab] + [Shift]?

### ISSUE THREAD

**Issue by gscottolson** [facebook/draft-js#155]
My Draft editor implementation has five block types and they are hierarchical: **title**, **subtitle**, **paragraph**, **bullet**, **sub-bullet**. Cycling between block types can happen in one of two ways:

1. Promoting a block to a level above it (e.g. moving a **subtitle** to a **title**)
2. Demoting a block to a level below it (e.g. moving a **paragraph** to a **bullet**)

I’m using the `onTab` handler to change block types:
- <kbd>Tab</kbd> demotes the current block
- <kbd>Tab</kbd> + <kbd>Shift</kbd> promotes the current block

~~Currently, Draft calls `preventDefault()` when I <kbd>Tab</kbd> so the focus remains in the editor (ignoring the browser’s default behavior of moving focus to the next focusable element in the page).~~ 

However, Draft does not prevent the default behavior of <kbd>Tab</kbd> + <kbd>Shift</kbd>. The keypresses are received and responded to by Draft (nice!), but the editor blurs and focus moves to the previous focusable element on the page.

I _can_ handle this using a custom key binding, but I’m wondering if this is a bug or designed purposefully.

I am happy to open a PR and make this change, but I want to understand the thinking behind this before I move ahead.

**Comment by gscottolson** [comment]
> I can handle this using a custom key binding…

Within the custom key binding, `event.key === 'Tab'`is false but `event.key === 'Shift'` is true for <kbd>Tab</kbd> + <kbd>Shift</kbd>. **Can the custom key binding handle a <kbd>Tab</kbd> keypress?**

Within my `onTab` handler, I can detect <kbd>Shift</kbd> and call `event.preventDefault()`. My workaround looks like:

```javascript
handleTabKey = (event) => {
  const {editorState} = this.state

  let blockType = null
  if (event.shiftKey) {
    event.preventDefault()
    blockType = promoteBlockType(RichUtils.getCurrentBlockType(editorState))
  } else {
    blockType = demoteBlockType(RichUtils.getCurrentBlockType(editorState))
  }

  if (blockType) {
    this.handleChange(RichUtils.toggleBlockType(editorState, blockType))
  }

  return true
}
```

**Comment by hellendag** [comment]
> Currently, Draft calls preventDefault() when I Tab so the focus remains in the editor

Hmm, I don't think Draft should be preventing default on <kbd>tab</kbd>. Where do you see that? (The `onTab` prop function is called here: https://github.com/facebook/draft-js/blob/06891490069d3ccfb89caf53f33a7545d39fc3ec/src/component/handlers/edit/editOnKeyDown.js#L96)

**Comment by gscottolson** [comment]
> Where do you see that?

You’re right, I don’t. After trying a [`contentEditable` example](http://html5demos.com/contenteditable) elsewhere, I believe that the browser is handling <kbd>Tab</kbd> natively.

**Comment by hellendag** [comment]
I don't *think* the browser should be doing that. Can you demonstrate with a jsfiddle?

**Comment by gscottolson** [comment]
I made too many assumptions. :disappointed:

<kbd>Tab</kbd> blurs the `contentEditable` in [this jsfiddle](https://jsfiddle.net/gscottolson/r6k3x7pw/).

**Comment by gscottolson** [comment]
Let me investigate further and see if I can isolate what appears to a bug specific to my Draft implementation.

**Comment by hellendag** [comment]
Any luck isolating the issue? :)

**Comment by gscottolson** [comment]
Thanks for following up.
No luck yet. I am going to close this to reduce noise. I will add new details if I uncover anything useful.

**Comment by icd2k3** [comment]
I'm having an issue with the `tab` key where draft-js keeps focus and I see an error in the console

`DOMException: Failed to execute 'extend' on 'Selection': This Selection object doesn't have any Ranges.`

Has anyone ran into this before? I have multiple draftJS editors on my page and I want to be able to tab between them. I tried using key binding as described in the docs, but the tab event never gets to the keyBindingFn before the error is triggered...

**Comment by voidstarfire** [comment]
Can you give examples for``` demoteBlockType``` & ```promoteBlockType```?

**Comment by camsjams** [comment]
This issue is occuring for me as well. In the same browser with just Draft JS examples, tab and shift+tab indent ul and ol blocks as expected.

Within my project however, and within a stripped down React storybook, I see the focus lost upon tabbing, much like the link @gscottolson posted on jsfiddle.

**Comment by camsjams** [comment]
For anyone still interested one solution that I found for properly capturing tabs inside Draft-JS in the event that yours wasn't working like mine was:

Add a wrapper div around your DraftJS `Editor` (if following examples, you likely already have one).

Then add the `onKeyDown` prop:
```
<div className={className} onKeyDown={this.onKeyPressed}>
   <Editor .... />
</div>
```

then add this listener to handle the tab event:
```javascript
       onKeyPressed(event) {
		if (event.key === 'Tab') {
			const newEditorState = RichUtils.onTab(
				event,
				this.props.editorState,
				4 /* maxDepth */
			);
			if (newEditorState !== this.props.editorState) {
				this.onChange(newEditorState);
			}
			event.preventDefault();
		}
	}
```

**Comment by JanakiramMaddanala** [comment]
> > I can handle this using a custom key binding…
> 
> Within the custom key binding, `event.key === 'Tab'`is false but `event.key === 'Shift'` is true for Tab + Shift. **Can the custom key binding handle a Tab keypress?**
> 
> Within my `onTab` handler, I can detect Shift and call `event.preventDefault()`. My workaround looks like:
> 
> ```js
> handleTabKey = (event) => {
>   const {editorState} = this.state
> 
>   let blockType = null
>   if (event.shiftKey) {
>     event.preventDefault()
>     blockType = promoteBlockType(RichUtils.getCurrentBlockType(editorState))
>   } else {
>     blockType = demoteBlockType(RichUtils.getCurrentBlockType(editorState))
>   }
> 
>   if (blockType) {
>     this.handleChange(RichUtils.toggleBlockType(editorState, blockType))
>   }
> 
>   return true
> }
> ```

what is demoteBlockType and promoteBlockType doing
