### ISSUE TITLE
Error: Cannot find module 'semver'  :    i get this error while installation 

### ISSUE THREAD

**Issue by jpca999** [facebook/draft-js#1551]
![image](https://user-images.githubusercontent.com/1026325/33636285-5bc4d486-d9d0-11e7-98c5-b2fa376dd70f.png)

![image](https://user-images.githubusercontent.com/1026325/33636270-4e73300c-d9d0-11e7-9afd-fc9c24648a76.png)

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

**What is the expected behavior?**

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

**Comment by juliankrispel** [comment]
Hey @jpca999 thank you for reaching out :)

This is an error thrown by npm and it looks like it has nothing to do with draft.js.

You can see this in the stacktrace depicted in the screenshot that you posted (line 5)

Here's a related issue https://github.com/npm/npm/issues/16807

Also btw - please join the draft js community on slack for more immediate help: https://draftjs.herokuapp.com
