### ISSUE TITLE
Typing issue.

### ISSUE THREAD

**Issue by AnuragShivale** [facebook/draft-js#1553]
Hi...
When we typing in draft.js editor and pressed "**Enter**" key it gives text in **paragraph** tag and when we pressed  "**Shift**"+"**Enter**" it gives **break line** after text line.

How we will change this - means if I only simply pressed "**Enter**" key  only then editor will give **break line**  instead of  **paragraph**  tag ?

Thanks.

**Comment by juliankrispel** [comment]
@AnuragShivale you can change this behaviour by combining the [`handleReturn`](https://draftjs.org/docs/api-reference-editor.html#handlereturn) event handler with the [`RichUtils.insertSoftNewline`](https://draftjs.org/docs/api-reference-rich-utils.html#insertsoftnewline)

Also btw - please join the draft js community on slack for more immediate help: https://draftjs.herokuapp.com
