### ISSUE TITLE
How to add onFocus and onBlur event in Draft-js Editor ?

### ISSUE THREAD

**Issue by mvnnn** [facebook/draft-js#1557]
Can you give me an example for How to use onFocus and onBlue functional events with draft-js.

**Comment by TheTekton** [comment]
https://draftjs.org/docs/api-reference-editor.html#mouse-events

**Comment by juliankrispel** [comment]
@mvnn just add event handlers as props:

```<Editor 
  onBlur={...}
  onFocus={...}
/>
```

More info in the docs: https://draftjs.org/docs/api-reference-editor.html#mouse-events

Also btw - please join the draft js community on slack for more immediate help: https://draftjs.herokuapp.com

**Comment by mateja176** [comment]
The mentioned link https://draftjs.org/docs/api-reference-editor.html#mouse-events is not to be found anymore. On the other hand, as of version `0.11.6` the callbacks passed to onFocus and onBlur are never invoked even though the draft state updates seamlessly. Consider:

```ts
import {
  ContentState,
  Editor as DraftEditor,
  EditorState,
  EditorProps,
} from 'draft-js';
import React from 'react';

export const Editor: React.FC<
  { text: string } & Omit<EditorProps, 'editorState' | 'onChange'>
> = ({ text, ...props }) => {
  const [editorState, setEditorState] = React.useState(
    EditorState.createWithContent(ContentState.createFromText(text)),
  );

  const editor = React.useRef<DraftEditor>(null);

  function focusEditor() {
    editor.current?.focus();
  }

  return (
    <Box onClick={focusEditor}>
      <DraftEditor
        ref={editor}
        editorState={editorState}
        onChange={(editorState) => setEditorState(editorState)}
        {...props}
        onFocus={console.log} // * never invoked
        onBlur={console.log} // * never invoked
      />
    </Box>
  );
};

```
