### ISSUE TITLE
Use decorator with `findWithRegex` strategy along with `entityMap`

### ISSUE THREAD

**Issue by roundrobin** [facebook/draft-js#1561]
**Do you want to request a *feature* or report a *bug*?**
question

I'm struggling to understand the right way to use decorators in my use case. 

I want to decorate/annotate a list of words that match a set of rules/regexs and allow the user to ignore certain words, so that they are not being highlighted anymore.

The idea of the ignore feature goes like this: I want to allow the user to ignore certain matches. For this I added a tooltip above the highlighted word. The issue is, if I just add a filter to ignore this specific regex, all the matches are ignored and I don't want this. I want to ignore only this specific occurrence.

My idea was to get the entities from the `entityMap` and store the key in a `ignore` data structure. Now since I use the `findWithRegex` approach my entities and not really distinguishable since they are not listed in the `entityMap`.

Can you guys help me with it?

Any help would be highly appreciated.
I've looked at the example ([https://github.com/facebook/draft-js/blob/master/examples/draft-0-10-0/entity/entity.html](Here)) and read the docs (https://draftjs.org/docs/advanced-topics-decorators.html#content) and still don't know what's the best way of going about it.

**Comment by richardson-trevor** [comment]
Can you instead just mark the entity as `ignored` in the entity's metadata. That way when you scan back through the entities with your regex, you can check the entity at the location where the regex matched using [`getEntityAt`](https://draftjs.org/docs/api-reference-content-block.html#getentityat) and check whether it has the `ignored` metadata prop set. Hope this helps, but I may be missing something.

**Comment by roundrobin** [comment]
@richardson-trevor Here is an example of what I have in mind. You can click on the red annotations, it adds a console message:

https://jsfiddle.net/roundrobin/eLk20zzx/28/

Check the `ignoreEntity` method. I passed over the `props` of this entity, but it has no `entityKey` right?

**Comment by richardson-trevor** [comment]
I think I would stay away from attempting to access/store an id. That seems like it could lead to some interesting bugs. 

I'm not sure what you mean by none of the entities being listed in the map? Are you talking specifically in your event handler?

**Comment by roundrobin** [comment]
@richardson-trevor what I mean is when I try to convert the current document back into it's raw form, the entityMap is empty, even though it contains decorations.

```
const contentState = newEditorState.getCurrentContent();
var raw = convertToRaw(contentState); // entityMap is empty
```

**Comment by richardson-trevor** [comment]
That's interesting. You have verified that they are there in the data structure at runtime, though (before you `convertToRaw`)? If so, I have not had that specific issue. We are writing out to raw for backend storage, and have not seen our entities disappear. Maybe some others can chime in with a solution to that specific problem.

**Comment by roundrobin** [comment]
@richardson-trevor I think I'm not doing a good job of explaining myself :) So I'm also writing out to raw for backend storage. In my case though I have this extra layer of ignored entities I want to handle and store somehow. This feature let to the question of how entities that are being found through the `findWithRegex` approach can be added to the `entityMap`.

If you look at the logs when clicking on the decorated word I logged the current content state in it's raw form. (Can be seen in this version: https://jsfiddle.net/roundrobin/eLk20zzx/30/)

As you can see the raw object doesn't contain any entities, even though we have 3 highlighted words.

Does this makes sense?

**Comment by richardson-trevor** [comment]
Ah, okay. My apologies for the confusion 😄 ! I think rather than try to keep the data stored separately, I'd recommend using the metadata system so you can [inline the data](https://draftjs.org/docs/advanced-topics-entities.html#introduction) with the entity itself. This has worked pretty well for us, though our use-case is admittedly not the same thing you're shooting for.

**Comment by roundrobin** [comment]
There you go. Now I only need to know in which place to create the entities on runtime (ex: while typing).

I'm looking for the place to do this.

```
const content = editorState.getCurrentContent();
const contentWithEntity = content.createEntity('MY_CUSTOM_ENTITY', 'MUTABLE', { ignored: true});
```

 Can I do it in the `findWithRegex` method of my example? Any pointers?

**Comment by richardson-trevor** [comment]
I believe you can/could, but it might lead to an awkward interaction. You might look more at something like what Twitter and Facebook do when they popout a dropdown or similar to suggest you are about to 'create' an entity. 

I think if your original question was answered it might be best to carry on further questions in the [Slack channel](draftjs.slack.com). I think you'll get faster feedback that way. Best of luck!

**Comment by roundrobin** [comment]
Let me know if you have any questions.

**Comment by richardson-trevor** [comment]
Nice. Glad to hear you were able to figure it out 👍

**Comment by badazzdev** [comment]
> Let me know if you have any questions.

Hi, 

would be very nice if you could share your code(snippet)! I struggle since days to to create regex decorators with entities!

Thanks =)
