### ISSUE TITLE
Use yarn and commit yarn lockfile

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#1568]
**What:**
Commit a `yarn.lock` file and update our CI scripts to use `yarn` instead of `npm`.

**Why?:**

In the past we have had problems where a change in a dependency breaks CI. A recent example - see https://github.com/facebook/draft-js/issues/1562

If we can see the versions of each dependency that were used for each release and commit, then it will give us more info to debug these situations.

There are other reasons to standardize on yarn - see https://code.facebook.com/posts/1840075619545360

**Action items for this issue:**

- [ ] get yarn set up for yourself
- [ ] `cd draft-js && rm -rf node_modules && yarn install`
- [ ] verify that builds, lint, tests, etc. are passing
- [ ] commit the resulting `yarn.lock` file that gets added to the root of the repo
- [ ] update `.travis.yml` to use `yarn` instead of `npm` for all commands. Note that the `yarn` commands may vary a bit from the npm CLI commands.
- [ ] Do any things that @flarnie forgot about to make `yarn` the standard for developing and testing Draft.js

Thank-you-very-much~! 🌸

**Comment by Tonours** [comment]
Hi @flarnie !

A pull request has been made #1570 which add yarn.lock file and an update of travis.yml file.

**Comment by claudiopro** [comment]
This can be closed since #1570 landed 🚀
