### ISSUE TITLE
Events on remove\create entity

### ISSUE THREAD

**Issue by optimatex** [facebook/draft-js#1569]
**Do you want to request a *feature* or report a *bug*?**
Request feature
**What is the current behaviour?**
There is no event on entity remove/create
Are there any events for the creating\removing entities? The common case is to send some server requests when some entity has been removed. If that was done via self-created functions - it's quite easy. But it may be unattainable in the case of undo/redo or selecting the whole editor content and removing it.

**Comment by juliankrispel** [comment]
Hi @optimatex thanks for reaching out :)

The [onChange](https://draftjs.org/docs/api-reference-editor.html#onchange) event handler will also be called when entities are removed/updated.

I'm confident that events for creating or removing entities will not be added as a feature I'm afraid. But you also shouldn't need it. 

Also btw - please join the draft js community on slack for more immediate help: https://draftjs.herokuapp.com

**Comment by optimatex** [comment]
@juliankrispel Thank you for the answer. 
May I ask you, how to define which entity was removed when user select some piece of content and press delete key?
I have joined the slack channel, but I can't find the answer there.

**Comment by juliankrispel** [comment]
Hey there. Just ask peeps on slack they'll help - this isn't the best place
for questions like this

**Comment by optimatex** [comment]
Thank u
