### ISSUE TITLE
Editor does not reflect content change after atomic block deletion

### ISSUE THREAD

**Issue by llyou** [facebook/draft-js#1583]
I want to report a bug.

I have a customized atomic block in draft js editor. To add and delete the customized block, I build the following two functions(addAtomicBlock and deleteAtomicBlock). addAtomicBlock works fine. The newly-added block appears after addAtomicBlock is called.
However, when deleteAtomicBlock is called, Draft editor does not re-render to make the deleted block disappear. I have to refresh the page, essential read the updated content from backend by calling createWithContent to make the deleted block disappear. 

The editorState is kept locally in the component. No Redux or other caching mechanism is used. Can anyone help take a look? Thanks a lot.

	onChange = (editorState) => {
		const currentContent = this.state.editorState.getCurrentContent()
		const newContent = editorState.getCurrentContent()
		if (!equal(currentContent, newContent)) {
			this.saveContent(newContent)
		}
		this.setState({editorState: editorState})
	}

	addAtomicBlock = (entityType, data) => {
		const editorState = this.state.editorState
		const contentState = editorState.getCurrentContent();
		const contentStateWithEntity = contentState.createEntity(
			entityType,
			'IMMUTABLE',
			data
		);
		const entityKey = contentStateWithEntity.getLastCreatedEntityKey();
		const newEditorState = AtomicBlockUtils.insertAtomicBlock(
			editorState,
			entityKey,
			' '
		);
		this.onChange(newEditorState)
		return newEditorState
	}

	deleteAtomicBlock = (blockKey) => {
		const editorState = this.state.editorState
		const contentState = editorState.getCurrentContent()
		const blockKeyBefore = contentState.getKeyBefore(blockKey)
		const blockKeyAfter = contentState.getKeyAfter(blockKey)
		const selectionState = editorState.getSelection()

		// Start Updating Content State
		const selectAtomic = selectionState.merge(
			{anchorKey: blockKeyBefore, anchorOffset: contentState.getBlockForKey(blockKeyBefore).getLength(), focusKey: blockKey, focusOffset: contentState.getBlockForKey(blockKey).getLength()}
		)
		const contentStateAfterRemoval = Modifier.removeRange(
			contentState,
			selectAtomic,
			'forward'
		)
		const selectAfter = selectAtomic.merge(
			{anchorKey: blockKeyAfter, anchorOffset: 0, focusKey: blockKeyAfter, focusOffset: 0}
		)
		const contentWithSeletAfter = contentStateAfterRemoval.merge(
			{selectionAfter: selectAfter}
		)
		const newState = EditorState.push(
			this.state.editorState,
			contentWithSeletAfter,
			'remove-range'
		)

		this.onChange(newState)
	}

I am using Draft js 0.10.4, React 16.2.0 Chrome Version 63.0.3239.108.

**Comment by Cooper97MA** [comment]
have you solved this ?

**Comment by yury-sannikov** [comment]
Looks like this issue still here. There are 2 issues with `Modifier.removeRange` function.

1. With forward selection, it fail to merge block type into the cleared block. So, If you have atomic block right below selection to delete, it will not preseve atomic type
2. Same happening with block data. It just discard it
