### ISSUE TITLE
How to limit the length of the content in the Editor？

### ISSUE THREAD

**Issue by TonyGGC** [facebook/draft-js#1588]
I do like this, but it still work normally:

 onChange(editorState) {
        //     this.setState({
        //         editorState:editorState
        //     });
 };

    render() {
        return (
            <div style={{width:500, height:300, backgroundColor:'red'}}>
                <div onClick={this.focus}>
                    <Editor
                        editorState={this.state.editorState}
                        onChange={this.onChange}
                        plugins={plugins}
                        ref={(element) => { this.editor = element; }}
                    />
                </div>
                <EmojiSelect />
            </div>
        )
    }

**Comment by TheTekton** [comment]
Does [this](https://github.com/facebook/draft-js/issues/119#issuecomment-190277461) work for you?

**Comment by TonyGGC** [comment]
@TheTekton 

# I do like this, but as before:
onChange(editorState) {
        const contentState = editorState.getCurrentContent();
        const oldContent = this.state.editorState.getCurrentContent();
        //const {maxLength} = this.props;
        if (contentState === oldContent || contentState.getPlainText().length <= 25) {
            this.setState({editorState});
        }
}

# I don't add this code:
handleBeforeInput(chars) {
  const totalLength = this.state.editorState.getCurrentContent().getPlainText().length + chars.length;
  return totalLength > this.props.maxLength;
}

**Comment by niveditc** [comment]
The fix/workaround recommended above should work.
