### ISSUE TITLE
How to insert a inline Image? 

### ISSUE THREAD

**Issue by LowkeyY** [facebook/draft-js#1614]
insertText() is only for text how to insert an image

 _insertEmoji(url) { insert emoji
      const decorator = new CompositeDecorator([
        {
          strategy: findImageEntities,
          component: Image,
        }
      ]);
        const emoji = '<img src="' + url + '"/>';
        const {editorState} = this.state;
        var contentState = editorState.getCurrentContent();
        const contentStateWithEntity = contentState
            .createEntity('emoji', 'IMMUTABLE', {
                src: url
            });
        const entityKey = contentStateWithEntity.getLastCreatedEntityKey();
        const currentSelectionState = this.state.editorState.getSelection();
        let emojiAddedContent;
        const afterRemovalContentState = Modifier.removeRange(
            contentState,
            currentSelectionState,
        );
        const targetSelection = afterRemovalContentState.getSelectionAfter();
        emojiAddedContent = Modifier.applyEntity(
            afterRemovalContentState,
            targetSelection,
            emoji,
            null,
            entityKey,
        );
        const blocksFromHTML = convertFromHTML(emoji);
        const state = ContentState.createFromBlockArray(
            blocksFromHTML.contentBlocks,
            blocksFromHTML.entityMap,
        );
      this.state = {
        editorState: EditorState.createWithContent(
          state,
          decorator,
        ),
      };

      const newEditorState = EditorState.push(
            editorState,
        emojiAddedContent
        );

        this.onChange(newEditorState)

    }

**Comment by niveditc** [comment]
Please see my comment on #1818
