### ISSUE TITLE
Making draft handle rich text

### ISSUE THREAD

**Issue by adcoolguy** [facebook/draft-js#162]
We are new with Reactjs. Thus after readinghttps://github.com/facebook/draft-js/blob/master/examples/rich/rich.html, we could not figure out how to make draft.js component handle rich text. Which are the related lines that turn off the default plain text nature of the editor?

Thanks!

**Comment by martijnbac** [comment]
The easiest way is probably to start with the [rich text example](https://github.com/facebook/draft-js/blob/master/examples/rich/rich.html). I'm currently in the process of finding it out myself, but pasting this in React app gave me a working editor immediately :-)

**Comment by hellendag** [comment]
Right, `rich.html` is the place to start with this.

The default behavior of a plain `EditorState` and `Editor` component is a plaintext editor, and you will need to add controls and behavior (for instance, using `RichUtils`) to build on top of it. `rich.html` provides an example of these steps.

**Comment by adcoolguy** [comment]
Guys, LOL the link I sent is the same like martijnbac et. al. are suggesting. I said I do not know which lines are relevant? My editor is currently in plain text, it is like 2 lines of div and input! XD

Which lines do I need to copy, say to turn on the rich text support? There are over 200 lines in that sample.

Thanks!

**Comment by hellendag** [comment]
I suggest following the code to understand how it all connects. :) The objective of this framework is not to provide a widget that can be plugged directly into a React app, but to provide the building blocks to enable developers to build text editors to suit their needs. The `rich.html` example is intended as an instructive example only, to illustrate how rich text *can* be implemented in a Draft editor.

**Comment by adcoolguy** [comment]
The following is the field that we would like to make it to support Rich text with Draft.js. Could you suggest what is the minimal codes to make it support rich text? Currently, whatever we type, it just appear as plain text :)

                                <div className="control-group">
                                    <label htmlFor="desc" className="col-sm-2 control-label">Description:</label>
                                    <div className="col-sm-10">
                                        <input type="text" className="form-control" ref="descriptionRaw" onKeyUp={this.save} value={this.state.descriptionRaw} onChange={function(e){this.setState({descriptionRaw: e.target.value})}.bind(this)} />
                                        <input id="x" ref="desc" type="hidden" name="content" />
                                        <trix-editor style={editorStyle} input="x"></trix-editor>
                                    </div>
                                </div>

The above shown the usage of Trix-React component, we are hoping (yes, hoping) to replace it with Draft.js easily. Does that makes sense to see our intention clearer?

**Comment by hellendag** [comment]
Does the `trix-editor` component support rich text automatically, with no added configuration?

**Comment by adcoolguy** [comment]
Yes, out of the box. With toolbar and everything. One just need one liner script to get the plain text out of it.

**Comment by hellendag** [comment]
Ok. As I noted above, the objective of the Draft framework is not to provide an out-of-the-box widget. Draft does not make any assumptions about the features, controls, or chrome to be applied to the editor, it simply aims to provide the tools and APIs to build them.

The ideal situation here would be for a developer to build and open-source a complete rich text solution on top of the framework, and you would be able to use that as a swap-in for `trix-editor`. (You should feel free to build that solution if you'd like!)

**Comment by adcoolguy** [comment]
So which lines are needed say just to make it support bold?

**Comment by adcoolguy** [comment]
There are 220 lines there LOL

**Comment by hellendag** [comment]
Again, I suggest reading through the example to understand how the pieces fit together. :)

This introduction document may also help get you acquainted with the API: http://facebook.github.io/draft-js/docs/quickstart-rich-styling.html#content

**Comment by adcoolguy** [comment]
Ah, that is better (than a 220 lines of codes that we don't understand). Maybe:

<button onClick={this._onBoldClick.bind(this)}>Bold</button>

should work. Thanks!

**Comment by hellendag** [comment]
Ok. I'm not sure whether that will actually provide what you want, but I'm also not sure I can be any more thorough in my explanation. :) Good luck!

**Comment by adcoolguy** [comment]
The editor cut off the tags that was pasted, but it was the line at button onClick={this._onBoldClick.bind(this)}>Bold</button :)

**Comment by adcoolguy** [comment]
I am not sure what I miss, but when I click Ctrl + B for bold, it gave error:

Uncaught TypeError: editorState.getSelection is not a function

Any insight into what I might miss?

**Comment by hellendag** [comment]
It sounds like you have a bug in your code, in which `editorState` is not being set to what it should be.

You might try our Slack channel for support so that we don't need to keep using this issue thread. The link for an invite is on the repo `README`.
