### ISSUE TITLE
ContentBlock. Cannot implement

### ISSUE THREAD

**Issue by steida** [facebook/draft-js#1621]
v0.10.5

Monitor logs will go to /private/tmp/flow/zSUserszSsteidazSdevzSeste.monitor_log
Error: node_modules/draft-js/lib/ContentBlock.js.flow:54
 54: class ContentBlock extends ContentBlockRecord implements BlockNode {
           ^^^^^^^^^^^^ ContentBlock. Cannot implement
 54: class ContentBlock extends ContentBlockRecord implements BlockNode {
                                                              ^^^^^^^^^ BlockNode
  Property `findEntityRanges` is incompatible:
     54: class ContentBlock extends ContentBlockRecord implements BlockNode {
               ^^^^^^^^^^^^ ContentBlock. Covariant property `findEntityRanges` incompatible with invariant use in
     54: class ContentBlock extends ContentBlockRecord implements BlockNode {
                                                                  ^^^^^^^^^ BlockNode

Error: node_modules/draft-js/lib/ContentBlock.js.flow:54
 54: class ContentBlock extends ContentBlockRecord implements BlockNode {
           ^^^^^^^^^^^^ ContentBlock. Cannot implement
 54: class ContentBlock extends ContentBlockRecord implements BlockNode {
                                                              ^^^^^^^^^ BlockNode
  Property `findStyleRanges` is incompatible:
     54: class ContentBlock extends ContentBlockRecord implements BlockNode {
               ^^^^^^^^^^^^ ContentBlock. Covariant property `findStyleRanges` incompatible with invariant use in
     54: class ContentBlock extends ContentBlockRecord implements BlockNode {
                                                                  ^^^^^^^^^ BlockNode

Error: node_modules/draft-js/lib/ContentBlock.js.flow:54
 54: class ContentBlock extends ContentBlockRecord implements BlockNode {
           ^^^^^^^^^^^^ ContentBlock. Cannot implement
 54: class ContentBlock extends ContentBlockRecord implements BlockNode {
                                                              ^^^^^^^^^ BlockNode
  Property `getCharacterList` is incompatible:
     54: class ContentBlock extends ContentBlockRecord implements BlockNode {
               ^^^^^^^^^^^^ ContentBlock. Covariant property `getCharacterList` incompatible with invariant use in
     54: class ContentBlock extends ContentBlockRecord implements BlockNode {
                                                                  ^^^^^^^^^ BlockNode

Error: node_modules/draft-js/lib/ContentBlock.js.flow:54
 54: class ContentBlock extends ContentBlockRecord implements BlockNode {
           ^^^^^^^^^^^^ ContentBlock. Cannot implement

**Comment by steida** [comment]
Temp fix (it contains another temp fix)

```
[untyped]
; https://github.com/facebook/draft-js/issues/1496#issuecomment-353895318
.*/node_modules/draft-js/lib/DraftEditor.react.js.flow
; https://github.com/facebook/draft-js/issues/1621
.*/node_modules/draft-js/lib/ContentBlock.js.flow
.*/node_modules/draft-js/lib/ContentBlockNode.js.flow
```

**Comment by ericbiewener** [comment]
Getting the same thing, using flow 0.64.0.

**Comment by mitermayer** [comment]
Will look into this. cc @flarnie

**Comment by etrepum** [comment]
The tricky part about this one is that the error isn't present in the draft-js source tree, it only manifests in the distribution version due to the babel transform used by the gulp flow task.

The interface declaration for BlockNode.js looks like this:

```javascript
export interface BlockNode {
  findEntityRanges(
    filterFn: (value: CharacterMetadata) => boolean,
    callback: (start: number, end: number) => void,
  ): void,

  /* ...rest of implementation elided */
}
```

The flow transform will output this:

```javascript
export interface BlockNode {
  findEntityRanges: (
    filterFn: (value: CharacterMetadata) => boolean,
    callback: (start: number, end: number) => void,
  ) => void,

  /* ...rest of implementation elided */
}
```

There are basically three options to fix this:

1. Don't transform interface methods in this way in the first place
2. Transform interface methods as covariant function properties
3. Change the source definition to use covariant function properties instead of methods (assuming that the transform would leave this as-is, have not confirmed)

For 2 or 3 the output would look like this:

```javascript
export interface BlockNode {
  +findEntityRanges: (
    filterFn: (value: CharacterMetadata) => boolean,
    callback: (start: number, end: number) => void,
  ) => void,

  /* ...rest of implementation elided */
}
```

```diff
diff --git a/src/model/immutable/BlockNode.js b/src/model/immutable/BlockNode.js
index 15afe09..8359041 100644
--- a/src/model/immutable/BlockNode.js
+++ b/src/model/immutable/BlockNode.js
@@ -32,31 +32,31 @@ export type BlockNodeConfig = {
 // https://github.com/facebook/draft-js/issues/1492
 // prettier-ignore
 export interface BlockNode {
-  findEntityRanges(
+  +findEntityRanges: (
     filterFn: (value: CharacterMetadata) => boolean,
     callback: (start: number, end: number) => void,
-  ): void,
+  ) => void,

-  findStyleRanges(
+  +findStyleRanges: (
     filterFn: (value: CharacterMetadata) => boolean,
     callback: (start: number, end: number) => void,
-  ): void,
+  ) => void,

-  getCharacterList(): List<CharacterMetadata>,
+  +getCharacterList: () => List<CharacterMetadata>,

-  getData(): Map<any, any>,
+  +getData: () => Map<any, any>,

-  getDepth(): number,
+  +getDepth: () => number,

-  getEntityAt(offset: number): ?string,
+  +getEntityAt: (offset: number) => ?string,

-  getInlineStyleAt(offset: number): DraftInlineStyle,
+  +getInlineStyleAt: (offset: number) => DraftInlineStyle,

-  getKey(): BlockNodeKey,
+  +getKey: () => BlockNodeKey,

-  getLength(): number,
+  +getLength: () => number,

-  getText(): string,
+  +getText: () => string,

-  getType(): DraftBlockType,
+  +getType: () => DraftBlockType,
 }
```
