### ISSUE TITLE
Bug: pasting text does not overwrite selection

### ISSUE THREAD

**Issue by newsiberian** [facebook/draft-js#1622]
Can be reproduced with https://draftjs.org/
1. insert text to editor
2. copy new text
3. select some text within inserted text
4. paste new text.

new text will be pasted not in the selection place, but at the end of the text
![draft-js-past-overwrite-bug](https://user-images.githubusercontent.com/11130487/35212729-b1cce160-ff8d-11e7-824f-9a270ccab89b.gif)

**Comment by thibaudcolas** [comment]
@newsiberian I can't reproduce this in Chrome 63 or Firefox 57 on macOS 10.13 (GIF below from Chrome). Could you let us know what browser you're using?

The issue template specifically asks for **Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

![draftjs-paste-inserted-text](https://user-images.githubusercontent.com/877585/35213253-a8a278de-ff65-11e7-9d43-c04b62d5501d.gif)

**Comment by newsiberian** [comment]
I've been able to reproduce this in debian (kde4 Firefox Nightly (latest), and Chromium 0.57) and windows 7 (in Chrome and Yandex Browser)

**Comment by newsiberian** [comment]
I figured out why this is happening. This is because I am holding the mouse button while pasting. Draft-js state has not yet received the latest selection state
