### ISSUE TITLE
HTML encoding can be bypassed by copy-and-paste

### ISSUE THREAD

**Issue by chengzhenping** [facebook/draft-js#1624]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
HTML encoding can be bypassed by copy-and-paste
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
![image](https://user-images.githubusercontent.com/6301471/35313378-f720018e-00fa-11e8-8e63-32958aba0624.png)
use  http://www.json.cn/# this web site to transfer html-string to html
and then copied right part to draft editor, will copy html structure to draft
**What is the expected behavior?**
all content HTML encoding
**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
chrome

**Comment by niveditc** [comment]
Hi @chengzhenping - I'm having trouble loading http://www.json.cn/#  and thus cannot repro this issue. Could you give some more details & perhaps a repro in a different editor?

**Comment by niveditc** [comment]
I'm closing this issue due to no response. Please reopen & provide more context if this continues to repro.
