### ISSUE TITLE
tweet example broken in chrome

### ISSUE THREAD

**Issue by nsfmc** [facebook/draft-js#1626]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

When using the tweet example from the repo in chrome (63.0.3239.132, 64.0.3282.119), after the decorator successfully matches a string, the selection is set to a position right _before_ the decorated text.

![tweet selection](https://user-images.githubusercontent.com/216572/35356568-a992c252-0105-11e8-98dc-5defe6a811d0.gif)

this works as expected in safari, firefox, brave

the following jsfiddle has an example of this
https://jsfiddle.net/td8xs3xt/

**What is the expected behavior?**

when the decorator matches, the selection should be preserved at the end of the matched string (safari does this).

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

seen in draft >= 0.10.3

although this is specifically a bug in the example, i think this may actually be a bug with how draft and chrome interact.

**Comment by nsfmc** [comment]
This is not a draft issue, it's a bug in the word replacer extension 🤦‍♂️

**Comment by richardson-trevor** [comment]
I would be in favor of keeping this one open. Even though it's not a draft issue, given that it's an example for people to build on, it's misleading to have something that doesn't work properly. If an external dep is breaking, this will drive the draft community members to try to fix that issue and/or come up with a different example to demonstrate the functionality.

**Comment by nsfmc** [comment]
yeah, i guess i am of two minds: 

- one is that we should keep this specific issue closed (the example works just fine), but that i agree that it's useful to keep useful keywords in this issue anyway since i think people usually go scavenging through closed issues for debugging.
- the other is that that specific browser extension has a bunch of issues in its chrome web store along the lines of "i had to uninstall this because it was messing up input in google sheets and other inputs". And the extension itself seems unmaintained. 

i'd be happy to retitle the issue and change the description to reflect the reality of the situation, something like "word replacing extension in chrome can reset selectionstate when decorators are applied" and leave the issue mostly like it is. i dunno, thoughts?

**Comment by richardson-trevor** [comment]
Ah, I think my issue was I didn't understand the verbiage you were using properly. For some reason I read 'dependency' rather than extension. Knowing that it's an extension, I think I'm in favor of leaving as is and closed.

**Comment by GaddMaster** [comment]
Can we embed tweets easily using this Draft ?
