### ISSUE TITLE
Link to Isaac's React Conf talk on the site

### ISSUE THREAD

**Issue by Daniel15** [facebook/draft-js#163]
@hellendag's [React Conf talk](https://www.youtube.com/watch?v=feUYwoLhE_4) is great, and provides a lot of background info. It's probably worth embedding it on the website, in the same way that [the Flow site](http://flowtype.org/) has its release announcement embedded on the homepage.

Embed code:
```
<iframe width="560" height="315" src="https://www.youtube.com/embed/feUYwoLhE_4" frameborder="0" allowfullscreen></iframe>
```

**Comment by hellendag** [comment]
Submit a PR? :)

**Comment by Daniel15** [comment]
I can do that! Would you prefer the video on the home page or in the docs somewhere?

**Comment by hellendag** [comment]
Probably in the docs, perhaps within the Overview article.

**Comment by hellendag** [comment]
@Daniel15 Still want to add this? :)

**Comment by Daniel15** [comment]
Yeah, sorry I haven't gotten around to it yet.

--
Regards,
Daniel Lo Nigro
http://dan.cx/ | Twitter <http://twitter.com/Daniel15> | Facebook
<http://www.facebook.com/daaniel>
