### ISSUE TITLE
convertToRaw generated HTML always appears a camera icon.

### ISSUE THREAD

**Issue by antiantian** [facebook/draft-js#1633]
If there are pictures in the copywriting, and when they are edited again, the convertToRaw generated HTML always appears a camera icon.
![image](https://user-images.githubusercontent.com/23133017/35478624-1cb63a9c-041d-11e8-99f9-0afef4d3227d.png)
![image](https://user-images.githubusercontent.com/23133017/35478625-2532c8d4-041d-11e8-97c5-938b1f605b08.png)

**Comment by flarnie** [comment]
Hi - that is expected, and was introduced in https://github.com/facebook/draft-js/pull/1378

That PR gives context on why we made this the default behavior - using the image 'src' attribute can sometimes crash the editor, and isn't what all users want.

I would suggest writing a filter that removes the image icon if you don't want that in your data.

**Comment by trevordmiller** [comment]
@flarnie "I would suggest writing a filter that removes the image icon if you don't want that in your data."

Could an example of this type of filtering be added to the docs? I'm not seeing how to do this.
