### ISSUE TITLE
Spellcheck doesn't work with CAPS

### ISSUE THREAD

**Issue by xzab** [facebook/draft-js#1638]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When you misspell a word, the browser spellcheck goes into effect ONLY if the test is lowercase.  all caps somehow isn't seen by the browser's spellcheck.  Replicated in Chrome and Safari but not FF.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

**What is the expected behavior?**
The text should be underlined by the browser indicating a misspelling even when using all caps.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
chrome, safari, latest, and mac 10.12.6 (16G1212)

**Comment by flarnie** [comment]
Thanks for reporting this! You are right that this is inconsistent - the inconsistency is the browser's implementation, not Draft.js. Spellcheck is implemented by the browser, and Draft.js just allows it to happen.

To verify - you can test the way native spellcheck would work with this fiddle: https://jsfiddle.net/042eLL4w/

I just did and it looks like, in Chrome, all-caps words don't trigger spellcheck.
![screen shot 2018-02-07 at 8 13 51 am](https://user-images.githubusercontent.com/1114467/35927236-10cada20-0bdf-11e8-9674-1bcc48210b7e.png)
