### ISSUE TITLE
Inline styling - Add class to selection

### ISSUE THREAD

**Issue by lucien-perouze** [facebook/draft-js#1639]
Hello,

I've been trying to understand this for too much time now so I'll ask it here. Excuse me if it's too obvious but it is not for me.

I'm building a side menu that toggle inline styles such as bold, italic, etc .. And I would like to add on top of that custom inline styles (Like a highlight). I have already seen and used the custom styling map but it doesn't fit for my project since I will need the styles of my editor to switch depending on external themes and so not saved in the content of the editor.

That's why I would just need to add a custom class to my selection like this : `<span class='example'>blabla</span>`  so the style of this is not fixed but depend on a higher css class.

I have also took a look at the decorators but I don't see how to use them based on the selection of the text and not a regex strategy.

Is there any way to do so with draft js ? If not why ?

Thank you.

**Comment by thibaudcolas** [comment]
Hey @lucien-perouze,

The styles coming from `customStyleMap` aren't saved in the content of the editor, they are only used when rendering the content in the editor. Only the style "type" is saved, eg `BOLD` or `HIGHLIGHT`.

For the custom classes, this is already covered by #957 and #1368.
