### ISSUE TITLE
Selecting custom block throws

### ISSUE THREAD

**Issue by joelburget** [facebook/draft-js#164]
Simple repro [codepen](http://codepen.io/joelburget/pen/NNGJmq)

Draft.js looks for a `data-offset-key`, but fails to find one since it's not created in the `CustomComponent` case of `DraftEditorContents.react.js`. We can stop Draft.js from throwing by adding a `data-offset-key` to our custom render. This is a hack. I'm not sure what invariant is being broken -- whether Draft should add an offset key or not look for one.

Probably related to #154

**Comment by hellendag** [comment]
Setting `data-offset-key` yourself, as you describe, is currently the way to do this. It's certainly not ideal, and I'm open to solutions. Sorry for the current awkwardness and the lack of documentation on it. :)

The main problem at this point is that the `data-offset-key` has to be applied to a DOM element, the root `div`, `figure`, etc. Without external knowledge of the custom component root, it's not clear how to apply it automatically.

A couple possibilities:

- We could define some standard root component (probably a `div`) that always applies `data-offset-key` and renders the custom component internally, but that also takes some control away from how the client renders the component root.

```javascript
// in DraftEditorContents...
return (
  <DraftCustomBlock ...>
    <CustomComponent ... />
  </DraftCustomBlock>
);

// then...
class DraftCustomBlock extends React.Component {
  render() {
    return <div data-offset-key={...} ...>{this.props.children}</div>;
  }
}
```

- There could be a standard `wrapCustomBlock` function that must be used on the returned root, perhaps with a warning if it is not used.

```javascript
render() {
  return wrapCustomBlock(
    <div>
     /* interesting things */
    </div>,
    this.props
  );
}
```

What do you think? Happy to discuss other alternatives as well.

**Comment by joelburget** [comment]
Is it just `data-offset-key`? Is `data-block` also important here?

I have a slight preference for `wrapCustomBlock`, since it gives full freedom re which component is returned.

**Comment by hellendag** [comment]
`data-block` is useful for finding the position of a block root element in the DOM, i.e. for positioning a menu relative to the selected block. I'll include it within the wrapper solution.

**Comment by remko** [comment]
@hellendag It would also be awesome to get some documentation/tips on how to use `data-block` to get positioning information.

**Comment by johanneslumpe** [comment]
@remko Did you figure out how to get the DOM node from a selection? I ran into this issue today while trying to position a context menu next to a selection.

**Comment by remko** [comment]
@johanneslumpe `getVisibleSelectionRect` helps, but I still had to do something for collapsed selections. The code I currently have is

    let rect = getVisibleSelectionRect(window);
    if (!rect) {
      const selection = window.getSelection();
      if (selection.anchorNode) {
        rect = selection.anchorNode.getBoundingClientRect();
      }

Not entirely confident if this is how it's supposed to be done, but it seems to work for me.

**Comment by johanneslumpe** [comment]
@remko how so? What was the specific issue you ran into with a collapsed selection? When I detect a collapsed selection I just hide the menu, which seems to work fine. I noticed another issue though that when calling `focus` on the editor, the selection changes and my menu re-renders at the top left corner of the editor, until I change the selection did you notice something like this too?

**Comment by lacker** [comment]
It seems like there's a workaround here so I am going to close this issue. Thanks folks for helping out!
