### ISSUE TITLE
MIT license status?

### ISSUE THREAD

**Issue by jeffhoel** [facebook/draft-js#1646]
Hi,
Are you still considering releasing draft.js under the MIT license?
The topic was brought up last October, (Issue 1417), and I'm wondering if there have been any new developments since then.
Thanks!

**Comment by flarnie** [comment]
Hi @jeffhoel - I don't know of any updates but will check with others and see what the status is.

**Comment by flarnie** [comment]
Just checked in with the folks working on this, and the process is ongoing but still nothing to report. I can't give any timeline, except that I don't expect any further updates for a while.
Sorry I don't have much encouragement, hopefully this honest picture of the situation is still valuable.
