### ISSUE TITLE
Too much warning message in browser console.

### ISSUE THREAD

**Issue by LeonDWong** [facebook/draft-js#1647]
Latest draft.js(0.10.5) requires immutable.js which's version is defined between 3.7.0 to 3.7.x as dependency,  it prints too much warning message when it runs in browser. See below.
![image](https://user-images.githubusercontent.com/17465046/36086656-8f8773be-1008-11e8-82e0-75eb53344a48.png)
AFAIK, immutable.js won't print this message once it is updated to 3.8.x, [similar issue](https://github.com/ianstormtaylor/slate/issues/1149)
Could it be fixed? Thx.

**Comment by thibaudcolas** [comment]
@LeonDWong as far as I can see, the Immutable dependency hasn't changed in 0.10.5 – it's still [`~3.7.4`](https://github.com/facebook/draft-js/blob/0a1f981a42ba665471bf35e3955560988de24c78/package.json#L37)

I don't see any of those warning messages in my editor, are you sure you're not using another version of Immutable? You can check this with `npm ls immutable` from within your project.

**Comment by LeonDWong** [comment]
@thibaudcolas 
Yes, immutable.js used in draft.js is 3.7.x, and latest immutable.js version matching 3.7.x is 3.7.6, which installed by draft. And it could be updated to 3.8.x, i think it should make those warning disappear.
![image](https://user-images.githubusercontent.com/17465046/36099441-a4ecf1a4-103d-11e8-83d3-f11f1d52fb58.png)

**Comment by thibaudcolas** [comment]
I haven't seen those warnings in my Draft.js projects using Immutable 3.7.x, so most likely they are produced because some other (not Draft.js?) part of the code which depends on Immutable is using the wrong version, or using those deprecated APIs.

There is already another issue about updating it in Draft.js, over at #950.

**Comment by hxgdzyuyi** [comment]
This warning can be disabled with `Immutable.Iterable.noLengthWarning = true;` in immutable.js@3.7.6

**Comment by LeonDWong** [comment]
It seems like that other updating issue already exist. Closed.

**Comment by maiah** [comment]
@hxgdzyuyi where should we put the `Immutable.Iterable.noLengthWarning = true;` ?

**Comment by hxgdzyuyi** [comment]
@maiah 

you can put it into your entry file（before use `immutable.js`）.

such as:

```

import React from 'react'
import ReactDOM from 'react-dom'
import MainSection from './MainSection'
....
import Immutable from 'immutable'

// See more: https://github.com/facebook/draft-js/issues/950
Immutable.Iterable.noLengthWarning = true

....

ReactDOM.render(
  <Provider store={store}>
    <MainSection />
  </Provider>,
  document.getElementById('react-app-root')
)

```
