### ISSUE TITLE
How to set main editor readOnly=true when clicking on it, back from block component editing?

### ISSUE THREAD

**Issue by againksy** [facebook/draft-js#1651]
I have table with many drafts inside each cell.
indie this.focus i have added - if like :
```
			if(props.tableCellDraft){
				this.props.setMainEditorReadOnly()
			}
```
the setMainEditorReadOnly sets readOnly in state inside main(parent) editor to true.
But when i click back to main draft editor( which have inside the table), how can i set the readOnly back to false. 
The problem is, that if i click on table block , both focuses of main editor and the this.focuse of cell editor are fired.

**Comment by ddelrio1986** [comment]
@againksy I'm not sure if this bit will help but I had many issues with nested editors. I overcame them by finding all events that could propagate up and affect the main editor and then either stopping them or toggling the main editor to read-only. Here is a snippet as an example:

![Example-Snippet](https://user-images.githubusercontent.com/58251/36322694-514911d6-131c-11e8-90e6-7fdff527b48e.jpg)

**Comment by againksy** [comment]
@ddelrio1986  but what is that div? is it div of block component? 
 for now i am setting outer editor to readOnly=true  when mouse over my table block component. On mouseLeave table block component i set state in outer-main editor- like `tableLeaved`, and when i click inside outer> inside this.focus i do check ( if tableLeaved then set readOnly=false) everything seems ok- but when i again press on cell i have just been i got error :

> ` Uncaught TypeError: Cannot read property 'getIn' of undefined ` 

. But if from this focused outer-main editor i press on any other cell everything is ok. What can be wrong?

**Comment by againksy** [comment]
@ddelrio1986 if i set onSelect to Editor component , it does not fires at all=(

**Comment by ddelrio1986** [comment]
@againksy that div is the root container element for my custom block component which has some interactivity that could bubble events up causing errors in the main editor's state. I had to do a lot of trial and error to figure out exactly which events were bubbling up by adding listeners to all events and trying to stop them then testing the behavior.

**Comment by cupcoder** [comment]
@ddelrio1986 Could you please share your code for onEnableReadonly and on DisableReadonly? Thanks!

**Comment by ddelrio1986** [comment]
@cupcoder,

I store a readOnly value of true or false in my component where my editor lives (this.state.readOnly). The onEnableReadOnly and onDisableReadOnly just use this.setState to toggle that value.

![read-only-togglers](https://user-images.githubusercontent.com/58251/36682992-7219c150-1aea-11e8-8680-5e7824261a79.jpg)

Then in my blockRendererFn I pass those down to my custom block components.

![blockrendererfn](https://user-images.githubusercontent.com/58251/36683059-9c8a45d6-1aea-11e8-8353-0f31fc69b89d.jpg)

Then my custom block components can use them to toggle readOnly on the editor whenever needed like I showed @againksy before.

**Comment by niveditc** [comment]
Looks like this was solved.
