### ISSUE TITLE
How to get editor innerText and manipulate?

### ISSUE THREAD

**Issue by Maijied** [facebook/draft-js#1658]
I need those code to get innerText and manipulate them for make it better.. if anyone know about this please help me.....

**Comment by flarnie** [comment]
Hi @Maijied  - can you give an example of what you want to do? I need more info to help you.

**Comment by flarnie** [comment]
Some helpful methods:
`ContentState.getPlainText()` -> https://draftjs.org/docs/api-reference-content-state.html#getplaintext

`ContentState.createFromText()` -> https://draftjs.org/docs/api-reference-content-state.html#createfromtext

You could read the "innerText" of the editor using `getPlainText`, change the text, and then create a new updated `contentState` using `createFromText` and then pass the updated contentState to your Draft.js editor.

**Comment by Maijied** [comment]
From which div..! i'll get my plain text ? Or anyone can suggest or give me simple code about how i'll get innerText by a button.

**Comment by Maijied** [comment]
@flarnie how i'll copy editor innerText by a button. Like Copy To Clipboard method. Thanks in advance.

**Comment by Maijied** [comment]
And basically i work in draft.js for making a editor where  editor automatically check #Bangla spell and suggest 2 gram data(Text).

**Comment by flarnie** [comment]
I think this should demonstrate how you can do it:

https://jsfiddle.net/m6z0xn4r/452/

This demonstrates - 
- how to copy the current selection to the clipboard
- how to set the selection in the Draft editor
- how to get the text of the editor

I hope you can use the example to do what you need, let me know if there is more to your question.

**Comment by Maijied** [comment]
After press the enter button ,text line get a new div .That's why i cant implement my spell checker api for underline the false words . How i get all text or by which div?
and push those words back to the same div?
