### ISSUE TITLE
Bug index of ordered list

### ISSUE THREAD

**Issue by gpietro** [facebook/draft-js#1662]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
While decreasing the indent the following indexes follow a wrong sequence.
When refreshing the editor state the sequence seems to get fixed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
*Decrease indentation  WRONG!*
<img width="489" alt="decrease of indentation" src="https://user-images.githubusercontent.com/7089910/36593644-e70e2958-189a-11e8-8019-c77f9e678506.png">
*After refreshing the editor state*
<img width="498" alt="after editor state update" src="https://user-images.githubusercontent.com/7089910/36593678-0381f204-189b-11e8-8a19-50fa8f5d81d8.png">

**What is the expected behavior?**
<img width="498" alt="after editor state update" src="https://user-images.githubusercontent.com/7089910/36593678-0381f204-189b-11e8-8a19-50fa8f5d81d8.png">

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Latest, with Chrome on different OS

**Comment by niveditc** [comment]
Closing since it's a browser issue & not a Draft.js issue.
