### ISSUE TITLE
Rendering multilevel ordered nested list

### ISSUE THREAD

**Issue by gpietro** [facebook/draft-js#1667]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
The index of a nested numeric list has only the current index.

**What is the desired behavior?**
I did an override of the css to have the nested item index composed with the parent item.
It would be nice to have a property to switch with this type of list rendering.
Here is what I have done to make it work this way (4 levels deep):

```
.public-DraftStyleDefault-orderedListItem.public-DraftStyleDefault-depth1:before {
  counter-increment: ol1;
  content: counter(ol0)"."counter(ol1)". ";
}
.public-DraftStyleDefault-orderedListItem.public-DraftStyleDefault-depth2:before {
  counter-increment: ol2;
  content: counter(ol0)"."counter(ol1)"."counter(ol2)". ";
}
.public-DraftStyleDefault-orderedListItem.public-DraftStyleDefault-depth3:before {
  counter-increment: ol3;
  content: counter(ol0)"."counter(ol1)"."counter(ol2)"."counter(ol3)". ";
}
.public-DraftStyleDefault-orderedListItem.public-DraftStyleDefault-depth4:before {
  counter-increment: ol4;
  content: counter(ol0)"."counter(ol1)"."counter(ol2)"."counter(ol3)"."counter(ol4)". ";
}

.public-DraftStyleDefault-orderedListItem.public-DraftStyleDefault-listLTR:before {
  width: 76px;
  left: -80px;
}
```

<img width="915" alt="screen shot 2018-02-26 at 10 00 09" src="https://user-images.githubusercontent.com/7089910/36674171-9c229fce-1b05-11e8-9e16-3c1aa76e9f23.png">

**Comment by thibaudcolas** [comment]
@gpietro I think it is by design that the default list styles of Draft.js are quite simple. It's easy to override them for a specific need like you did here, and for most use cases the default styles (which mimick what eg. Google Docs or Word do) are probably enough.

**Comment by snapshahab** [comment]
how do i override these to get custom counter styling?
