### ISSUE TITLE
Proper way to replace entity content when typing

### ISSUE THREAD

**Issue by Ahineya** [facebook/draft-js#167]
Hello!

I have an issue with Entity.replaceData (mostly in a way I'm trying to work with it).
I want to change entity data, when I'm typing some text, but, of course, I can't, because custom blockRendererFn is not invoking in that case. 
How can I fire rerender of a block?

Code:
I am saving a block key in a property, after that I'm trying to change it's entity content like this:

        const {editorState, blockKey} = addHintBlock({text: "Search", autocomplete: this.autocomplete}, EditorState.moveFocusToEnd(newState));
        this.blockKey = blockKey;

And after that in handleEditorChange:

        const entity = editorState.getCurrentContent().getBlockMap().get(this.blockKey).getEntityAt(0);

        const hint = searchQuery
            ? "‒ Press Enter to search this"
            : "Search";

        Entity.replaceData(entity, {content: {hint, autocomplete: this.autocomplete}});

        this.setState({editorState});

Thank you!

**Comment by remko** [comment]
You can use `EditorState.forceSelection` to force a rerender. See #148.

**Comment by Ahineya** [comment]
forceSelection works, but after that it duplicates character like in  #92 
Looks like it duplicates symbol, because I'm mutating editorState in onChange:

        this.setState({editorState: EditorState.forceSelection(editorState, editorState.getCurrentContent().getSelectionAfter())});

**Comment by remko** [comment]
Mutating editorState in onChange is indeed known to be unsafe. See #161

**Comment by hellendag** [comment]
One option might be to use state within your block component. That way, it can re-render independent of the editor. That might not work well with your use case, but it's a possible solution.

If the change should only apply while typing, can you perform your change in `handleBeforeInput`? Using this and returning `true` will prevent the native character insertion described in the other issues.

And I'm still trying to determine a good solution for the double character problem. :) Hopefully soon.

**Comment by Ahineya** [comment]
Looks like using state within my block component is the right option in my case, thank you very much!

**Comment by christophercliff** [comment]
Might be opening a can of worms, but something like this might work too:

```js
    handleChangeEditorState: function (editorState) {
        this.setState({
            editorState: editorState,
        }, function () {
            process.nextTick(editorDidChangeState)
        })
    },
```

**Comment by andpor** [comment]
I need to do something similar and cooked up the following code which seems to work. It is a generalisation since I am blindly going after entityAt(0).

```
updateEntityValue(){
        const contentState = editorState.getCurrentContent();
        contentState.getBlockMap().map((block,key) => {
          let entityKey = block.getEntityAt(0);
          if (entityKey !== null){
              contentState.replaceEntityData(entityKey, {title: title, headline: headline});
          }
        });
        const newEditorState = EditorState.createWithContent(contentState);
        this.setState({editorState: newEditorState});
}
```
