### ISSUE TITLE
Decorated text captures arrow/home/end keys badly

### ISSUE THREAD

**Issue by pklavins** [facebook/draft-js#1676]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
With an editor containing decorated text, arrow key behaviour is modified. For example, consider the following text:
```
The following {#text} is decorated.
New line!
```
If I put the cursor at the start of the first line and hit <kbd>&darr;</kbd>, instead of going to the start of 'New line!', it goes to the start of {#text}. It also internally captures <kbd>Home</kbd>/<kbd>End</kbd> keys, so if my cursor is in {#te|xt}, hitting <kbd>Home</kbd> sends it to |{#text} instead of the start of the line (ditto with <kbd>End</kbd> key).

I'm using a simple decorator that returns as its component a <span> with text inside.

**What is the expected behavior?**
When hitting <kbd>&darr;</kbd> at the start of a line, it moves down to the lower line. When hitting <kbd>Home</kbd>/<kbd>End</kbd> keys inside decorated text, it should go to start/end of the line, not the text.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
0.10.3, Win10, Chrome 64.0.3282.186

**Comment by pklavins** [comment]
I resolved this by removing `display: inline-block` from the span's styles (specifically the span that was used as the decorator's component); works fine now.

**Comment by niveditc** [comment]
Looks like this was resolved :)
