### ISSUE TITLE
Content block should have method for getting list of all entity keys

### ISSUE THREAD

**Issue by tarjei** [facebook/draft-js#1681]
**Do you want to request a *feature* or report a *bug*?**
Feature.
**What is the current behavior?**
There is no way to get a list of all entity keys in a contentblock.

**What is the expected behavior?**
If I got a contentblock with two entities then all examples versions of blockRenderFn will just fetch and render the first entity.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
All versions are affected.

What is needed is a way to get all entity keys within the block.

**Comment by thibaudcolas** [comment]
Hey @tarjei, what you're describing sounds a lot like [`ContentBlock.findEntityRanges()`](https://draftjs.org/docs/api-reference-content-block.html#findentityranges).

The first filter callback gets called with a CharacterMetadata instance on which you can call `getEntity()` to access the entity key. If that callback returns true, the second callback gets called with the character ranges' `start` and `end`.

Here's an example from my code if that helps: https://github.com/thibaudcolas/draftjs-filters/blob/28f82b478fc130b2e1f12211e952cbeea7dfcff9/src/lib/filters/entities.js#L62

**Comment by tarjei** [comment]
Hi @thibaudcolas - thanks for a quick reply!

Yes, that works, but I was thinking that it was non ideal as it felt like a convoluted way of handling the issue.

As a followup, if you don't mind, I'm wondering about how I end up in the following state.

1. I got two atomic blocks, each with an entity ref ( in my case an image). 
2. I do some editing with the keyboard, deleting the space between the blocks. 
3. I now got one block of type "unstyled" that contains refs to both entities. 

Is there a way for me to deny merging of the two blocks? 

Kind regards, 
Tarjei

**Comment by tarjei** [comment]
Again, thanks for a quick followup. 

The manipulation that happens is just a few backspace and then a delete. Somehow this merges two atomic blocks into one. That is what I would like to avoid - or should I expect that two blocks of the same type can and will be merged?

PS: Are you on the Draft-js slack channels?

**Comment by thibaudcolas** [comment]
I'm not sure this is the same issue but I can reproduce a similar problem on my test editor by doing, which seems to be the same issue as #915, or similar:

1. Insert image
2. Insert image
3. Place cursor on the `unstyled` block between the images
4. Press backspace – **removes the empty `unstyled` block, cursor disappears** <-- this is bad, it looks like the selection is within the atomic block even though it's set to `editable: false` in the `blockRendererFn`
5. Press delete  – the image entity disappears, but the atomic block is still there. Cursor is still invisible.

It's not even necessary to be between the two images – doing those operations after a single image will produce the same result.

![draft-js-block-delete](https://user-images.githubusercontent.com/877585/37094697-5de182c0-221c-11e8-877f-39ea0cedaf64.gif)

(the pink "404" is what my component displays when there is an atomic block without an entity)

<details>
<summary>Here are the blocks after those operations</summary>

```json
{
  "blocks": [
    {
      "key": "67jqc",
      "text": "",
      "type": "unstyled",
      "depth": 0,
      "inlineStyleRanges": [],
      "entityRanges": [],
      "data": {}
    },
    {
      "key": "3vo10",
      "text": "",
      "type": "atomic",
      "depth": 0,
      "inlineStyleRanges": [],
      "entityRanges": [],
      "data": {}
    },
    {
      "key": "5i7ae",
      "text": " ",
      "type": "atomic",
      "depth": 0,
      "inlineStyleRanges": [],
      "entityRanges": [
        {
          "offset": 0,
          "length": 1,
          "key": 0
        }
      ],
      "data": {}
    },
    {
      "key": "75e0s",
      "text": "",
      "type": "unstyled",
      "depth": 0,
      "inlineStyleRanges": [],
      "entityRanges": [],
      "data": {}
    }
  ],
  "entityMap": {
    "0": {
      "type": "IMAGE",
      "mutability": "IMMUTABLE",
      "data": {
        "src": "./word-toolbars-overload.jpg"
      }
    }
  }
}
```

</details>

---

I couldn't reproduce this behavior on my [production editor](https://github.com/springload/draftail) so I got to compare the two, and the difference is in using `RichUtils.handleKeyCommand` in the `handleKeyCommand` handler.

Looking at how this is implemented, `RichUtils.handleKeyCommand` does extra work in the "backspace before an atomic block" case that will delete the block:

https://github.com/facebook/draft-js/blob/73e5a9c3b57116a5a01d26016964ad3ba8fe0e66/src/model/modifier/RichTextEditorUtil.js#L55-L80

https://github.com/facebook/draft-js/blob/73e5a9c3b57116a5a01d26016964ad3ba8fe0e66/src/model/modifier/RichTextEditorUtil.js#L107-L122

This might be what's missing from your code as well. Could you try adding it? If you're not using `handleKeyCommand` already, it could look like this:

```jsx
<Editor
            editorState={editorState}
            onChange={this.onChange}
            handleKeyCommand={(command) => {
              const { editorState } = this.state

              let newState = RichUtils.handleKeyCommand(editorState, command)

              if (newState) {
                this.onChange(newState)
                return "handled"
              }

              return "not-handled"
            }}
/>
```


Thinking through this, I don't get why `RichUtils.handleKeyCommand` isn't bound to the editor's `handleKeyCommand` by default (https://github.com/facebook/draft-js/issues/915#issuecomment-272602852). I don't see how any `atomic` block implementation could work without this.

**Comment by tarjei** [comment]
@thibaudcolas thanks a big bundle! 

You give very good feedback and comments. I've added the RichUtils.handleKeyCommand now. 
Regards,
Tarjei
