### ISSUE TITLE
editorState is not stored as a Record object in Redux store

### ISSUE THREAD

**Issue by acmoune** [facebook/draft-js#1682]
I am creating an empty editor state in my Redux reducer with this:

```javascript
import { EditorState } from 'draft-js'

const defaultState = {
  editorState: EditorState.createEmpty()
}

const editor = (state = defaultState, action) => {
  switch (action.type) {
    case 'UPDATE_EDITOR_STATE':
      return Object.assign({}, state, {
        editorState: action.payload.editorState
      })

    default: 
      return state
  }
}
```

But the editorState that is injected in the props is a plain Object:

```javascript
EditorState { _immutable: {} }
```
So I am having errors like `getCurrentInlineStyle is not a function`

When I create the editorState from the constructor instead, everything is fine, I have a Record Object:

```javascript
EditorState { _immutable: Record }
```

Am I doing something wrong with my Redux reducer ?

Thanks.

**Comment by qruzz** [comment]
Did you manage to solve this issue? - I have run into the same thing right now, and can't seem to find any solution?

**Comment by acmoune** [comment]
@qruzz  Yes, you must use `convertToRaw` when creating your default state:

```javascript
import { EditorState, convertToRaw } from 'draft-js'

const defaults = {
  editorContent: convertToRaw(EditorState.createEmpty().getCurrentContent())
}
```
