### ISSUE TITLE
can not type chinese in EditorBlock  (when use EditorBlock in custom block component )

### ISSUE THREAD

**Issue by wanlerong** [facebook/draft-js#1684]
**Do you want to request a *feature* or report a *bug*?**
# use EditorBlock in custom block component  

**What is the current behavior?**
# can not type chinese in EditorBlock. 
when i type chinese , it Triggered unmount  and  After that, the cursor cannot move.

by the way, when i type English, it works well.

```js

import React,{Component} from 'react';
import { message,Icon,Checkbox } from 'antd';
import { EditorState, Editor, convertToRaw, convertFromRaw, RichUtils, EditorBlock  } from 'draft-js';
class MyTodoItem extends Component {
  constructor(props) {
    super(props);
    const { block, contentState } = this.props;

    let hasFinished = block.getData().get('hasFinished');
    hasFinished = hasFinished ? true : false;

    this.state = {hasFinished};
  }
  render() {
    const { block, contentState, offsetKey } = this.props;
    let hasFinished = this.state.hasFinished;

    return (
      <div data-offset-key={offsetKey} >
         <span>
            <Checkbox checked={hasFinished}  />
         </span>
        <EditorBlock {...this.props} />
      </div>
    );
  }
}
export default MyTodoItem;



```

![wx20180309-151302](https://user-images.githubusercontent.com/13759820/37195104-67b9a3f4-23ac-11e8-83eb-adcac16927ba.png)

**Comment by flarnie** [comment]
Hi - what browser/OS are you using?
Please try to reproduce in this fiddle: https://jsfiddle.net/stopachka/m6z0xn4r/
I was not able to reproduce, using Pinyin - Simplified, on Mac OSX in Firefox.

![draft_pinyin_simplified_manual_test](https://user-images.githubusercontent.com/1114467/37217187-b89bd5fc-2371-11e8-803a-39d7f5c2ec1f.gif)

**Comment by niveditc** [comment]
I'm closing this support issue due to no response. Please reopen & provide more context if you still need help with this.

**Comment by zz373609** [comment]
what he said is in EditorBlock, not in Editor, Actually I met same problem
