### ISSUE TITLE
A way to remove all entities from a contentState

### ISSUE THREAD

**Issue by roundrobin** [facebook/draft-js#1686]
**Do you want to request a *feature* or report a *bug*?**
question

Is there a way to remove all entities at once from the contentState and not only a specific one? 

I'm implementing a grammar check and I want to wipe out all entities ever time I receive a new batch of grammar mistakes from the backend.

**Comment by dracudakid** [comment]
Same question for me.

**Comment by thibaudcolas** [comment]
There isn't (at least that I know of).

You need to use something like [`ContentBlock.findEntityRanges()`](https://draftjs.org/docs/api-reference-content-block.html#findentityranges) to iterate through all of the entity ranges, and remove them.

The simplest method I found was to use the "low-level" APIs to map through all blocks, and through all characters in each block, replacing chars with `CharacterMetadata.applyEntity(char, null)` when they have a defined entity. See for example this [filterEntityRanges](https://github.com/thibaudcolas/draftjs-filters/blob/ad9ebbd35c71319d7889da3334e23a37ee973f0f/src/lib/filters/entities.js#L72-L119) function.

**Comment by roundrobin** [comment]
@thibaudcolas thanks that helps!
