### ISSUE TITLE
Triggering mentions suggestion [Question]

### ISSUE THREAD

**Issue by hingermayank** [facebook/draft-js#169]
Hi,
I was trying to add mentions support in my editor and my approach to trigger the suggestions list was using a decorator which strategy to match regex like @[\w]+ but for the strategy to work I also need to check if the current cursor position it is currently on should not be an entity and for the same I need selection state in my strategy and for that I need to pass my editor context which I guess is hacky.

So I was wondering how did you implement it on FB because I might be taking a wrong approach of going through decorator to render Suggestions. Any help would be appreciated.

Thanks

**Comment by hellendag** [comment]
At FB, we do not use a decorator for text that triggers mentions. Our process is:

1. Observe the text before the cursor, check it against a regex (like yours).
1. If there is a match, perform an asynchronous `search` to find matching results.
1. Using the DOM selection API, identify the target bounding Rect for the target text.
1. Use absolute positioning to render the results accordingly.

You may be able to use `getVisibleSelectionRect` for step 3 -- it will be released in 0.2.

It does seem like it could be useful to have the active `SelectionState` available to the decorator strategy, though. Or potentially even the entire `EditorState`, in case one wanted to look at surrounding blocks.

**Comment by nikgraf** [comment]
@hingermayank We went the same route as you did with mentions in our plugin system. Works fine as well. see https://github.com/nikgraf/draft-js-plugin-editor/blob/master/src/mentionPlugin/index.js

**Comment by hingermayank** [comment]
@nikgraf My concern is with passing the editor context instead of having selection state or as @hellendag suggested having entire editorState in strategy.

**Comment by nikgraf** [comment]
@hingermayank Yeah, we probably change it. I wonder what you concerns are with passing down the whole context?

**Comment by hingermayank** [comment]
@nikgraf Nothing wrong with that but it is just that I did not want to pass the whole context to a utility function.

**Comment by hingermayank** [comment]
@hellendag  I have upgraded draft-js to 0.2.0 but is getVisibleSelectionRect not exported in this version?

**Comment by hellendag** [comment]
Ah, it's not exported. I'll include it in the next release.

**Comment by hellendag** [comment]
@hingermayank If you'd like to submit a PR to expose it, we can go ahead and get it into master.

**Comment by hingermayank** [comment]
@hellendag I have submitted the PR #199.

**Comment by hellendag** [comment]
Was thinking I shouldn't close this since there was a broader question around mentions, but I'll go ahead and close it after all since the relevant PR is now merged.

**Comment by hingermayank** [comment]
> Was thinking I shouldn't close this since there was a broader question around mentions

@hellendag what is that you are talking about?

**Comment by jvaill** [comment]
I started writing a higher-order component that tracks typeahead state based on the way FB mentions work using the method outlined by @hellendag above. It's not completely finished (straight up missing a README), but I'm not sure when I'll have more time to continue hacking on it..

[Example linked here if anyone is interested in dissecting another approach!](https://github.com/dooly-ai/draft-js-typeahead/blob/master/examples/mentions/mentions.html)
