### ISSUE TITLE
Wrong block found if custom block renderer introduces nested Editor

### ISSUE THREAD

**Issue by slava-osipov-qs** [facebook/draft-js#1693]
**Do you want to request a *feature* or report a *bug*?**
I'm not sure. I think it is a bug, but fix might require new feature.

**What is the current behavior?**
In custom block renderer of **outer** Editor I add _component_ that renders two elements: 1) some div and 2) **inner** Editor in _readOnly_ mode. **Inner** Editor is initialized with some content. When user clicks to the first div in this _component_ then exception occur within `getDraftEditorSelectionWithNodes` of outer Editor. It seems that `findAncestorOffsetKey` returns wrong block key.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
https://github.com/slava-osipov-qs/draft-js-1693-repro

**What is the expected behavior?**
Correct block key must be found and no exception occured.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
I don't know.

**Note:**
Exception is same as in #1671, but reason is different.

**Comment by niveditc** [comment]
Please see my comment on #1671 about nested editors.
