### ISSUE TITLE
Feature: Add a Optional Param for ConvertFromHtml to keep empty blocks.

### ISSUE THREAD

**Issue by GeorgeWL** [facebook/draft-js#1699]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
```
var html = '<p>Text</p><p></p><p>Previous could be an empty Div or a br when converted</p>'
```
when parsed by `ConvertFromHtml(html)`
returns
```
<p>Text</p><p>Previous could be an empty div or a br when converted</p>
```

I believe there are enough use-cases where one wants to send some html string to it, say from an API, use the draft editor to edit the html in EditorState, then send the edited data back as a html string, that it would make sense to make it an optional param.

> This was on purpose to keep pastes of long text from having a lot of extra spaces between paragraphs. The content coming in can be pretty messy sometimes and this is one of the things we try to do to clean it up.
> 
> Going to close this for now, but we may revisit it in the future.

Whilst I agree, in most cases it makes sense to have it do that,

I feel that it should be an optional param for those many cases where it's not the behaviour which is wanted. **Choice is always better than no choice and having to hack your way around it.**

**Comment by niveditc** [comment]
I think we'll probably pass on this again with the same justification as last time. For now, it's probably better to just work around this in your editor/use case.
