### ISSUE TITLE
Pasting into a code block does not seem to work

### ISSUE THREAD

**Issue by bolinfest** [facebook/draft-js#170]
I tried the demo on https://facebook.github.io/draft-js/. I hit "Code Block," got a grey rectangle, focused the cursor there, and then hit cmd-v to try to paste the contents of a source file I had on my clipboard (contents were an entire Java file copied from Eclipse using cmd-a, cmd-c).

All of the contents got pasted below the code block instead of inside of it.

**Comment by hellendag** [comment]
This doesn't repro for me. Is there perhaps a newline at the top of your paste?

**Comment by x2764tech** [comment]
I can confirm this behaviour on Chrome 49 and FireFox 45 on Ubuntu 14.04:

Test: 

- Click "Code Block"
- Paste multiple lines from clipboard (ctrl+v or paste from context menu)

Result:

First line is in code block, second line is not
![image](https://cloud.githubusercontent.com/assets/2870080/13671704/56429a6c-e6c9-11e5-9d63-99d94bf651c8.png)

**Comment by hellendag** [comment]
Oh, I understand the issue now.

When the paste is parsed into `ContentBlock` objects, each line is treated independently if the paste is just arbitrary HTML. If these values are divs, for instance, then they will be treated as `unstyled` blocks. An exception, IIRC, is that if pasted contents are within a `pre`, they will be turned into a single code block. cc @CLowbrow 

If the pasted contents aren't in a `pre`, then I think the contents are split and treated as any other blocks.

If the paste is coming in as plain text, then the paste processor won't do anything to determine that it is code, and every input block will not be given the same block type as the target block -- they will just be unstyled blocks.

**Comment by dburrows** [comment]
We should be able to handle this in the proposed handlePastedText from https://github.com/facebook/draft-js/issues/195

**Comment by CLowbrow** [comment]
Is this hitting the html parsing code path or is it going through plaintext? We do some weird detection in the html path that tries to use DIVs as blocks that we may want to just take out.

**Comment by hellendag** [comment]
I think our HTML handling case here is not necessarily wrong. Pasting into a code block doesn't mean that the pasted contents should all be of block type `code-block`.

I think @dburrows has the right idea here.

**Comment by ianstormtaylor** [comment]
I'm running into this as well, but for raw text, not HTML. In the case of pasting raw text, I think all of the text should be contained within the code block. Right now only the first line is contained.

**Comment by hellendag** [comment]
I suggest using `handlePastedText` to override the default behavior for known code pastes. We can revisit whether the default paste processor should be modified.

**Comment by mass3ff3ct** [comment]
Hello, sorry for my english
how can i use handlePastedText in this problem ?
I do not have enough examples to understand the draftjs. 
I found it difficult to write the code, and I did not get the result. What am I doing wrong?
```typescript
  private handlePastedText = (text: string) => {
        const {editorState} = this.state
        const currentBlockType = (RichUtils.getCurrentBlockType(editorState))
        if (currentBlockType === "unstyled") {
            return true
        }
        const rawContentState = ContentState.createFromText(text)
        const typedContentState = Modifier.setBlockType(
            rawContentState,
            new SelectionState({
                anchorKey: rawContentState.getFirstBlock().getKey(),
                anchorOffset: 0,
                focusKey: rawContentState.getLastBlock().getKey(),
                focusOffset: text.length,
                isBackward: false,
            }),
            currentBlockType
        )
        const newState = Modifier.replaceWithFragment(
            editorState.getCurrentContent(),
            editorState.getSelection(),
            typedContentState.getBlockMap()
        )
        this.changeHandler(EditorState.push(editorState, newState, "insert-fragment"))
        return false
    }
```
