### ISSUE TITLE
Editor types in reverse, bold and italics does not work

### ISSUE THREAD

**Issue by sugandhgoyal** [facebook/draft-js#1704]
**Do you want to request a *feature* or report a *bug*?**
a bug
**What is the current behavior?**
I have implemented two jpuri editors in my react web app. One of them works perfectly but the other one is typing in reverse and most of its functions are not working like bold, italics, cannot select text etc.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
       

     componentWillReceiveProps = (nextProps) => {
       const contentBlock = htmlToDraft(nextProps.parentEditorData);
       const contentState = ContentState.createFromBlockArray(contentBlock.contentBlocks);
        const editorState = EditorState.createWithContent(contentState);
          this.setState({editorState})
        }

    onEditorStateChange = (editorState) => {
        this.setState({editorState});
        this.props.handleStateOfOuterEditor(draftToHtml(convertToRaw(editorState.getCurrentContent())));        
    };

    render() {
        const {editorState} = this.state;
        return (<Editor
            editorState={editorState}
            wrapperClassName="demo-wrapper"
            editorClassName="demo-editor"
            onEditorStateChange={this.onEditorStateChange}
            toolbar={{
                options: ['inline', 'blockType', 'fontSize', 'fontFamily', 'list', 'textAlign', 'colorPicker', 'link', 'embedded', 'emoji', 'image', 'history'],
                inline: {options: ['bold', 'italic', 'underline', 'strikethrough', 'monospace', 'superscript', 'subscript']},
            }}/>)
    }
**What is the expected behavior?**
All the functions should work.
**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
"react-draft-wysiwyg": "^1.12.10",
 "draft-js": "^0.10.5",
  Windows - 10 / 64-bit OS
  Browser - chrome

**Comment by thibaudcolas** [comment]
Hey @sugandhgoyal, if you're using react-draft-wysiwyg you should probably file a bug on its repository (https://github.com/jpuri/react-draft-wysiwyg) rather than Draft.js. Your code looks very simple Draft.js-wise so the issue most likely is there.

**Comment by mitermayer** [comment]
Hi @sugandhgoyal hanks for raising this issue, Please follow @thibaudcolas  advice and post this question on `react-draft-wysiwyg` repo.

Feel free to open other issues and or comment on this one if there is something that is related to draft core itself
