### ISSUE TITLE
How can we add new html block inside the editor?

### ISSUE THREAD

**Issue by hkkr123git** [facebook/draft-js#1707]
How can we add a new custom html block inside editor?
For example i want to add a <video> tag with some specified url inside the editor.
How will do that?
Please help

**Comment by mitermayer** [comment]
Hi @hkkr123git thanks for raising this question, please refer to https://draftjs.org/docs/advanced-topics-block-components.html#content

Another great resource is our slack channel (https://draftjs.slack.com).
