### ISSUE TITLE
Example's code of draft-js is different from npm's version. It may cause confusion.

### ISSUE THREAD

**Issue by WeiAnAn** [facebook/draft-js#1708]
In rich example, it allow indentation beyond one level deeper than block above.(https://github.com/facebook/draft-js/commit/73e5a9c3b57116a5a01d26016964ad3ba8fe0e66)
But the draft installed from npm does not allow this action.

The version is both v0.10.5.

It may cause confusion.
I suggest to release new version to synchronize code.

**Comment by mitermayer** [comment]
Hi @WeiAnAn, 

Thanks for raising this issue, I agree that having a versioned example is a source of confusion. 

@flarnie, @sophiebits  do we have a strong reason to keep the examples versioned ? should we instead just keep latest ? One argument I can think of is to allow users to see examples of older versions, but they can already do that but checking out an older github tag.

**Comment by niveditc** [comment]
I think #1304 will fix this by removing the old examples.
