### ISSUE TITLE
How to apply custom entity to current selection only?

### ISSUE THREAD

**Issue by ming-soon** [facebook/draft-js#1709]
I'm using a sample code found [here](https://github.com/facebook/draft-js/blob/master/examples/draft-0-10-0/link/link.html) to implement a custom entity for links.

**What is the current behavior?**
Select a portion of text, and create a link. Then keep typing after the link is created, and the editor will mark all characters you type in as a part of the link.

**What is the expected behavior?**
The link should be created for the current selection only. When you type more characters after creating a link, they should be plain text, not a link.

**Comment by richardson-trevor** [comment]
@ming-soon it seems like you're wanting an `IMMUTABLE` entity. Take a look at: https://draftjs.org/docs/advanced-topics-entities.html#mutability

**Comment by ming-soon** [comment]
@richardson-trevor Thanks.
