### ISSUE TITLE
Solved: Problem with Babel/Polyfill

### ISSUE THREAD

**Issue by Merovex** [facebook/draft-js#1716]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

I am trying to run `yarn start` on the 0.10 TeX example. After following the instructions I'm getting the following error: `ERROR in ./js/app.js
Module not found: Error: Cannot resolve module 'babel/polyfill' in /Users/.../Projects/draft-js/examples/draft-0-10-0/tex/js
 @ ./js/app.js 17:0-25`

I changed the following in app.js line 17:

```
import 'babel/polyfill';
``` 
to 
```
import 'babel-polyfill';
```

Problem Solved

**Comment by niveditc** [comment]
Looks like we should probably fix this in the examples too. Thanks for flagging!

**Comment by dougmacknz** [comment]
Had a look at fixing this but it was done already in https://github.com/facebook/draft-js/pull/1981, so this can close now :)
