### ISSUE TITLE
Webpack Dev Server

### ISSUE THREAD

**Issue by ThariqS** [facebook/draft-js#1721]
*This is a feature request*

**What is the current behavior?** It looks like there is no clear dev environment that creates a local dev server. The examples are simple HTML files that access the javascript files. This prevents using smart reloading and also in my case, does not allow port forwarding for trying to test local changes on mobile devices.  Trying to npm link draft-js is a possible alternative, but I've run into many problems with npm link.

Most modern react libraries have some sort of local dev server for testing. How does testing and dev happen at Facebook? Do you only use tests for development with no visual interface?

**Comment by thibaudcolas** [comment]
@ThariqS maybe the new playground (#1572) that was added recently is what you are after? It is based on `create-react-app`, and links the local Draft.js version.

**Comment by niveditc** [comment]
Closing since the playground should be sufficient. Happy to accept PRs to improve upon the playground.
