### ISSUE TITLE
Text align

### ISSUE THREAD

**Issue by rodolfobarretoweb** [facebook/draft-js#1728]
Hello guys, I have a question about the style.

I try to put text-align on my richText component and I use the customStyleMap property to map this styles. 

Here is my code:

```
<Editor {...input}
   customStyleMap = { this._setCustomMapStyle() }
   className      = {cn({ [styles.readOnly]: !!readOnly || disabled })}
   readOnly       = {!!readOnly || disabled}
  editorState    = {this.state.contentState}
  onChange       = {this._onChange}
/>

_setCustomMapStyle = () => {
    const display = 'block';

    return {
      'text-align-left'    : { textAlign : 'left', display },
      'text-align-right'   : { textAlign : 'right', display },
      'text-align-center'  : { textAlign : 'center', display },
      'text-align-justify' : { textAlign : 'justify', display }
    };
  }
```
But this style is apply on span element with display block property. So when I try to style a word the behavior is jump the line (this is happening because the display block property). 

Video show the actual behavior: https://youtu.be/LnN2k1ZA7Q0

My question is: There is a way to avoid to apply this style on span element and set on div that wrap the span element ?

**Comment by mzedeler** [comment]
You need to do this on block level. Take a look at `blockStyleFn`: https://github.com/facebook/draft-js/blob/master/docs/Advanced-Topics-Block-Styling.md
