### ISSUE TITLE
How to manipulate a span strategy to apply multiple styles?

### ISSUE THREAD

**Issue by Shudrum** [facebook/draft-js#1729]
Hello there!

Not even a feature request or a bug. I have a **simple** question.

Do you know Bear (the markdown note tool)? I would like to create an effect like this tool.

I'll try to be clear:I would like to test a strategy for making a bold effect. If the user write \*boldtext\*, I would like the editor to display **\*boldtext\***, but I want the stars to be gray.

So I've added a simple test to the tweet example:

```javascript
// After added the strategy to the CompositeDecorator:

const BOLD_REGEX = /\*([\w]+)\*/g;

function boldStrategy(contentBlock, callback, contentState) {
  findWithRegex(BOLD_REGEX, contentBlock, callback);
}

const BoldSpan = (props, test) => {
  const result = BOLD_REGEX.exec(props.decoratedText);
  return (
    <span
      style={styles.bold}
      data-offset-key={props.offsetKey}
    >
      <span style={styles.light}>*</span>
      {result[1]}
      <span style={styles.light}>*</span>
    </span>
  );
};

// Then added the styles
```

Stupid test that does not work because the result is a simple string instead of the complex processed children from the props.

Is there a way to do this?

Thank you!

**Comment by mzedeler** [comment]
Draft.js supports styling of ranges of characters, so you *could* apply bold style to anything contained in a pair of asterisks. Take a look at `RichUtils.toggleInlineStyle`: https://draftjs.org/docs/quickstart-rich-styling.html

But note that you'll be doing double bookkeeping - the asterisks and the actual styling may get out of sync.

**Comment by niveditc** [comment]
Looks like this question is answered. Please reopen if you have further queries :)
