### ISSUE TITLE
feature: idempotent copy-paste?

### ISSUE THREAD

**Issue by Pomax** [facebook/draft-js#1731]
We've using Wagtail the at the Mozilla Foundation, which is a CMS that uses draft.js as basis for its rich text editor, and noticed that copy/paste from one rich text field to another loses a lot of the markup. That feels like a bug, but maybe it's not, so if it's not please consider this a feature request to make copy-paste idempotent.

Right it's possible to have content that can be copied, but cannot be pasted, with links, horizontal rules, and even empty paragraphs losing their markup on paste, which is quite problematic =)

There is an issue for this over on the the draftail (wagtail's code on top of draft.js) repo, https://github.com/springload/draftail/issues/147#issuecomment-382031838, but it would be super great if this was something that could be addressed in draftjs itself.

**Comment by richardson-trevor** [comment]
@Pomax there's been some discussion around this. There's quite a few of us that would like to see this. See https://github.com/facebook/draft-js/issues/787.

**Comment by Pomax** [comment]
this is close enough to a duplicate of that to warrant closing. Looking forward to movement on 787!
