### ISSUE TITLE
Bring back support for aria-owns

### ISSUE THREAD

**Issue by afercia** [facebook/draft-js#1736]
I've read https://github.com/facebook/draft-js/commit/7f0cab28386ec4bde8ec6289377bff9e53cd019b

I think there's probably a misunderstanding in what a "parent-child relationship between the owner and ownee" means in ARIA terms as opposed to DOM terms. ARIA doesn't do anything in the browser, nor changes the DOM of course. It changes the way browsers expose information to assistive technologies through the Accessibility APIs and the accessibility tree.

The combobox ARIA widget is a bit complicated. There are now two different valid patterns, the "traditional" one from ARIA 1.0 and the new one from ARIA 1.1. The differences between the two patterns are very well described in the [ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/#combobox).

Regardless, based on the specifications, `aria-owns` is a required property for the combobox ARIA widgets.

References:
ARIA 1.0
https://www.w3.org/TR/wai-aria-1.0/states_and_properties#aria-owns
> The reason for adding aria-owns is to expose a parent/child **contextual** relationship to assistive technologies that is otherwise impossible to infer from the DOM.

ARIA 1.1
https://www.w3.org/TR/wai-aria-1.1/#aria-owns
> Identifies an element (or elements) in order to define a **visual, functional, or contextual parent/child relationship** between DOM elements where the DOM hierarchy cannot be used to represent the relationship.

Regardless of the specs, the ARIA authoring practices describe very well the implementation details. See under the combobox "WAI-ARIA Roles, States, and Properties"
https://www.w3.org/TR/wai-aria-practices-1.1/#wai-aria-roles-states-and-properties-5 they describe both patterms (1.0 and 1.1)

1.1:
> The element with role combobox contains **or owns** a textbox element that has either role textbox or role searchbox.

Please notice the 1.1 pattern is made of a container with role=combobox and aria-owns, while the textbox element is a child and uses aria-controls, so this pattern is very different from the current implementation, for example, in the Mentions plugin.

1.0
- When the combobox popup is visible, the element with role combobox has aria-owns set to a value that refers to an element with role listbox.

Please also refer to the 5 W3C examples linked there: https://www.w3.org/TR/wai-aria-practices-1.1/#examples-1 they all use `aria-owns`.

The practical consequence of the missing aria-owns attribute is that some browser / screen reader combinations don't read out the suggestions at all. For example, Safari and VoiceOver are not able to announce the options. See also https://github.com/draft-js-plugins/draft-js-plugins/issues/1073

**Comment by afercia** [comment]
See also ARIA 1.1 when it describes how `aria-activedescendant` works:
https://www.w3.org/TR/wai-aria-1.1/#aria-activedescendant

> The value of `aria-activedescendant` refers to an element that is either a descendant of the element with DOM focus or is a logical descendant as indicated by the `aria-owns` attribute.

**Comment by afercia** [comment]
Worth noting a few contributed PR landed in the `draft-js-plugins`, specifically for the mentions and emojis plugins to improve how the ARIA combobox with suggestions gets announced by screen readers. See:
https://github.com/draft-js-plugins/draft-js-plugins/pull/1075
https://github.com/draft-js-plugins/draft-js-plugins/pull/1077
https://github.com/draft-js-plugins/draft-js-plugins/pull/1087

However, Safari + VoiceOver still don't announce anything, because they need `aria-owns` on the editor.

**Comment by niveditc** [comment]
Seeking input from @jessebeach who worked on 7f0cab2.

**Comment by jessebeach** [comment]
@afercia Another great write-up :) I agree that the ARIA 1.1 pattern requires `aria-owns` on the combobox if the listbox isn't a child of the combobox in the DOM (or even if it is, since it's a no-op at that point).

Put up the PR and I'm happy to review!
