### ISSUE TITLE
Update jsfiddle in issue template to use draft-js version?

### ISSUE THREAD

**Issue by ericls** [facebook/draft-js#1737]
The current jsfiddle template is based on draft 0.7.0 and react 15.3

https://jsfiddle.net/stopachka/m6z0xn4r/

It might be helpful to update that to include draft 0.10

**Comment by niveditc** [comment]
@ericls - thanks for flagging! Should be an easy fix - PRs welcome for this :)

**Comment by gmertk** [comment]
I'm just going over jsfiddle PRs. This is now fixed in #2145

For more context; there was an issue on FB side about syncing files on .github folder. This is why these fiddle PRs couldn't get merged. It is fixed now :)
