### ISSUE TITLE
Raw output, default properties, a lot of overhead

### ISSUE THREAD

**Issue by adjourn** [facebook/draft-js#1746]
Draft.js raw output often has a lot of overhead. Most of my output ends up with properties shown in codeblock below. It's not uncommon that "default" state is 50% overall size or even more.

```
"type": "unstyled",
"depth": 0,
"inlineStyleRanges": [],
"entityRanges": [],
"data": {}
```

I don't know about you guys but I pay for bandwidth and storage, so does my customer. Therefore I started to think that maybe I should remove these properties before sending to backend for further processing.

E.g the following object is a valid input for `convertFromRaw()`, just tried it:

```js
{
  entityMap: {},
  blocks: [{text: 'Just hanging out over here, alone, without any fancy state..'}]
}
```
Obviously this is the most basic example but it proves my point.

**So here's my question to maintainers and users:** should Draft.js even output these defaults or do you actually have usecases for these default properties? Other pitfalls I didn't stumble on?

It's not something very hard to implement ourselves but I was wondering if this is a common concern.

```js
// just a wild "pre stage-0" suggestion
convertToRaw(contentState: ContentState, removeDefaults?: bool): RawDraftContentState
```

**Comment by mzedeler** [comment]
You can always remove all default values before transmitting them to the backend and insert them again if the key is missing. That's pretty straight forward and won't ever affect Draft.js, since it gets the data it will get is unchanged.

**Comment by niveditc** [comment]
Agree with what @mzedeler said. Feel free to reopen if you'd like to discuss further.
