### ISSUE TITLE
Strage editor behaviour

### ISSUE THREAD

**Issue by thevoidf** [facebook/draft-js#1752]
**Do you want to request a *feature* or report a *bug*?**
yes bug
**What is the current behavior?**
when i press enter to insert newline, instead editor moves cursor at beginning of the line.
if i press enter twice it insets newline but after start typing cursor jumps back to first line.
also if i press keys too fast it crashes with exception:
The above error occurred in the <DraftEditorLeaf> component:
    in DraftEditorLeaf (created by DraftEditorBlock)
    in div (created by DraftEditorBlock)
    in DraftEditorBlock (created by DraftEditorContents)
    in div (created by DraftEditorContents)
    in div (created by DraftEditorContents)
    in DraftEditorContents (created by DraftEditor)
    in div (created by DraftEditor)
    in div (created by DraftEditor)
    in div (created by DraftEditor)
    in DraftEditor (at RichEditor.js:62)
    in div (at RichEditor.js:61)
    in div (at RichEditor.js:41)
    in RichEditor (at EventForm.js:177)
    in form (at EventForm.js:171)
    in EventForm (created by Route)
    in Route (at App.js:34)
    in div (at App.js:32)
    in div (at App.js:18)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:17)
    in App (at index.js:7)
IndexSizeError: Index or size is negative or greater than the allowed amount

strange thing i noticed is that it works fine on its own but after adding another component Flatpickr(datetime picker) next to it it messes up completely
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
here: https://jsfiddle.net/m6z0xn4r/942/
sorry could not import Flatpickr, please try locally

**What is the expected behavior?**
just to insert newline properly

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Draft.js: 0.10.5
Bbrowser: Firefox and chrome
System: Debian 9

**Comment by githubflub** [comment]
Is the Flatpickr nested inside the editor? If so, when you click on it, the click is probably doing something like changing the focus/selection of the DOM and causing it to go out of sync with draft-js, which leads to these kind of bugs. 

Possible solutions are to set the editor to read-only while Flatpickr is open or to not have it nested inside of the editor. 

Not sure if this is your problem, but hope it helps.

**Comment by thevoidf** [comment]
no its sibling, next to it, just like in fiddle i provided

**Comment by sconnor07** [comment]
I had a similar issue when using Flatpickr (4.4.4) on the same page as the editor. Upgrading Flatpickr to 4.5.0 fixed my issue.

**Comment by thevoidf** [comment]
@sconnor07 yeah after update it seems fine, closing
