### ISSUE TITLE
Docusaurus migration issues

### ISSUE THREAD

**Issue by yangshun** [facebook/draft-js#1765]
**Do you want to request a *feature* or report a *bug*?**

Bug (sorta)

**What is the current behavior?**

Some issues I just discovered with the migration of Draft.js to Docusaurus. Perhaps we can use this issue as a master issue to keep track of the smaller issues.

- [ ] Footer not bottom-sticky on home page (This is something that has to be fixed in Docusaurus core)
- [ ] On mobile widths, the editor exceeds the width and the page is horizontally scrollable
  - ![screen shot 2018-05-16 at 2 13 56 pm](https://user-images.githubusercontent.com/1315101/40144438-7642f302-5913-11e8-98c0-8d19c0e7870d.png)
- [ ] The development version of React is being used
  - <img width="731" alt="screen shot 2018-05-16 at 2 14 20 pm" src="https://user-images.githubusercontent.com/1315101/40144441-7f1ad44a-5913-11e8-8147-8beb5df45ecf.png">

cc @NoamELB

**Comment by NoamELB** [comment]
Regarding mobile, I think we should not show the editor at all (it's not supported in mobile). @flarnie do you agree?
@yangshun want me to create a PR for the sticky footer? I'd be glad to help out 😄

**Comment by yangshun** [comment]
@NoamELB Docusaurus would be so glad to receive your PR 😄
