### ISSUE TITLE
blockRenderMap breaks formatting for the pasted code 

### ISSUE THREAD

**Issue by andrewfan** [facebook/draft-js#1769]
Hey,

When using `blockRenderMap` for` code-block`, pasting code has incorrect formating 

https://codepen.io/anon/pen/erbOpK?editors=1111 (try to paste code) 
Removing `blockRenderMap` in example fixes the issue

**Comment by githubflub** [comment]
Add a handlePastedText function to your editor so you can grab and print (and check) what html your editor is receiving. 

Once you see what html elements the copied code html is in, you can add those elements to your blockRenderMap, like so: 

```
"code-block": {
    element: "code",
    wrapper: <pre spellCheck="false" />,
    aliasedElements: ['pre'], // maybe ['pre', 'code']
  },
```
