### ISSUE TITLE
DocSearch ready for your documentation website

### ISSUE THREAD

**Issue by s-pace** [facebook/draft-js#1775]
👋 team:

Congratulations, your search is now ready! You [can try a showcase here](https://draftjs-docsearch.surge.sh/):
![Preview here](https://cl.ly/2X413T2r2O0X/download/Screen%20Recording%202018-05-29%20at%2011.46%20AM.gif)

I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:

- Copy the following CSS/JS snippets and add them to your page

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: 'ae94c9e3ee00ea8edddd484adafc37cd',
  indexName: 'draft-js',
  inputSelector: '### REPLACE ME ####',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```
- Add a search input in your page if you don't have any yet. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field.
- Optionally customize the look and feel by following [the DocSearch documentation](https://community.algolia.com/docsearch/documentation/)
- You can also check your configuration [in our GitHub repo](https://github.com/algolia/docsearch-configs/blob/master/configs/draft-js.json).

The integration within Docusaurus is [even faster](https://docusaurus.io/docs/en/search.html#docsNav). We do provide analytics on the search. Feel free to ping if you want me to grant you access.

Please open a pull request if want to leverage your configuration!

Feel free to get back to us if you have any issues or questions regarding the integration.

We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it.

Have a nice day :)

**Comment by niveditc** [comment]
Seeking input from some folks who have helped with setting up Docusaurus for Draft.js - @yangshun, @NoamELB, @aadsm. What do you think about adding this and is it being used in other FB open-source projects?

**Comment by yangshun** [comment]
@niveditc Yes! Algolia docSearch is frequently being used for Docusaurus projects. It's the de facto way we integrate search into a Docusaurus site now.

**Comment by niveditc** [comment]
@yangshun - awesome! Seems exciting :D

**Comment by yangshun** [comment]
@niveditc I could help to integrate it into draftjs.org if you like 😄

**Comment by niveditc** [comment]
@yangshun - that would be amazing! Thank you 😄

**Comment by yangshun** [comment]
@niveditc We need an Algolia API Key before we can even start on this. I'm not sure of the process for FB OSS projects to create one. cc @JoelMarcey do you know of the typical process?

**Comment by JoelMarcey** [comment]
@yangshun the API key is embedded in the comment from @s-pace above, right? Or am I misunderstanding your question?

**Comment by yangshun** [comment]
@JoelMarcey Oh I thought that API key above is their demo API key which is
not managed by Facebook/Draftjs. Is it ok to use that key?

**Comment by s-pace** [comment]
Hi all.

Indeed @JoelMarcey, this key is the one to integrate within your website:
```
apiKey: 'ae94c9e3ee00ea8edddd484adafc37cd',
indexName: 'draft-js',
```
I have updated your configuration in order to acknowledge and integrate the changes from your website. Effects are live and deployed.

Let us know if you need anything else. Thank you @yangshun

**Comment by yangshun** [comment]
I have no permissions to close this issue but we can close this now. We have search on draftjs.org now! 🎉

**Comment by s-pace** [comment]
Awesome news. Thank you. Feel free to ping for further help

**Comment by niveditc** [comment]
@yangshun - awesome! Thanks for implementing this 👍
