### ISSUE TITLE
Docs don't have link styling

### ISSUE THREAD

**Issue by Prinzhorn** [facebook/draft-js#1778]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Links on the docs looks 100% like text. For example the word "why" in the screenshot is a link.

![selection_276](https://user-images.githubusercontent.com/679144/40773116-334df1cc-64c2-11e8-87d8-1e386d384543.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

Visit https://draftjs.org/docs/getting-started.html and try to find any of the links

**What is the expected behavior?**

Links should at least have an underline or a distinct color. I wanted to create a PR but the problematic CSS is not part of this project.

```
a {
  color: #3B3738;
  text-decoration: none;
}

.mainContainer .wrapper a,
.inner .projectIntro a {
  text-decoration: none;
}
```

The react docs use both underline and a light background color. I recommend to do the same.

![selection_277](https://user-images.githubusercontent.com/679144/40773295-c79ade30-64c2-11e8-8ecb-d11cc0cc6e62.png)

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

n/a

**Comment by niveditc** [comment]
Looks like this is fixed now, possibly due to the recent Docusaurus update.
<img width="706" alt="screenshot 2018-09-08 11 50 57" src="https://user-images.githubusercontent.com/2357761/45257588-77521a80-b35d-11e8-8c9b-558e8249321f.png">
