### ISSUE TITLE
Why editor missing the focus (hasFocus issue)

### ISSUE THREAD

**Issue by dChunikhin** [facebook/draft-js#1792]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
I am using Draft JS in role a field for message input in my messenger. And when i press ENTER (to send message).
When I dispatch 'SENDMESSAGE' action (Redux) and return 'handled' - my editor again shows placeholder and blinking cursor, but EditorState.getSelection().hasFocus return false now, however before sending message (in first time typing) it returned true;
Help, how can i hold the focus on my input field despite the message sending?
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
no, i can't provide the steps cause it's happen in too big code (project)
**What is the expected behavior?**
typing text => send message (by press the Enter) => cleared the field => typing text else
**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
draft-js: "0.10.5"
windows 10

**Comment by niveditc** [comment]
@dChunikhin - not sure how much help can be provided here (there isn't much detail). Any chance you've found your answer already?

**Comment by niveditc** [comment]
Closing this issue due to no response.
