### ISSUE TITLE
How to use mergeData in v0.10 ?

### ISSUE THREAD

**Issue by againksy** [facebook/draft-js#1795]
for example now i use something like
`          change: (key, size) => {
            Entity.mergeData(key, size);
`
but how should i write mergeData without Entity -> Entity is deprecated?

**Comment by juliankrispel** [comment]
Instead of using `Entity.mergeData` the docs recommend you use `ContentState.mergeEntityData`, [see here for the docs](https://draftjs.org/docs/api-reference-content-state.html#mergeentitydata)
