### ISSUE TITLE
this.state.contentState.createEntity is not a function

### ISSUE THREAD

**Issue by againksy** [facebook/draft-js#1796]
i am migratin from 0.9 to 0.10, got this error, what is the problem?

**Comment by niveditc** [comment]
@againksy  - we'll need more info to be able to help here. `createEntity` works fine for me in a code snippet like this one in my code base:
```
this.state.editorState
  .getCurrentContent()
  .createEntity('IMAGE', 'IMMUTABLE', {src: url});
```

**Comment by niveditc** [comment]
I'm closing this support issue due to no response. Please reopen & provide more context if you still need help with this.
