### ISSUE TITLE
MUTABLE entity no longer work when adding character

### ISSUE THREAD

**Issue by phuczeero** [facebook/draft-js#1798]
**Do you want to request a *feature* or report a *bug*?**
\> Bug

**What is the current behavior?**
\> Edit a word (MUTABLE entity) by adding a character, the character no longer annotated by the entity.

**What is the expected behavior?**
\> The added character annotated by the entity.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

- Version: 0.10.5, 0.10.4
- Browser: Chrome on Windows.

**Comment by phucvinhng** [comment]
@thibaudcolas So we have to implement manually, or there is an optional configuration to do this?

**Comment by thibaudcolas** [comment]
There is no configuration, you need to add some code to re-establish that behavior for your project. I believe the issue I linked has some examples in the comments, via `handleBeforeInput`.

**Comment by phuczeero** [comment]
@thibaudcolas Thanks
