### ISSUE TITLE
editor is not working correctly in non-english language

### ISSUE THREAD

**Issue by ktjd123** [facebook/draft-js#1808]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

when you try to type "안녕하세요" (It's korean)
Its not detected until non-korean char is detected ( ex: space, or alphabet)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

**What is the expected behavior?**

It should be detected after one char is written

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

"draft-js": "^0.10.5", macOS Mojave(10.14)(k)

**Comment by bologer** [comment]
@ktjd123 there is some [note](https://draftjs.org/docs/advanced-topics-issues-and-pitfalls.html#ime-and-internet-explorer) about Korean language in official docs. It is probably now fully supported at the moment

**Comment by niveditc** [comment]
There is more detail & discussion in #1102 so I'm closing this issue to keep that one the source of truth.

**Comment by ks11singh** [comment]
I am facing the same issue.
when you try to type "안녕하세요" (It's korean)
Its not detected until non-korean char is detected ( ex: space, or alphabet).
I am using Draft JS 0.11.3

**Comment by MMRahman28** [comment]
চা
