### ISSUE TITLE
convertFromRaw not working as expected

### ISSUE THREAD

**Issue by ktjd123** [facebook/draft-js#1809]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

convertFromRaw is giving error (Cannot convert undefined or null to object) even though it's not

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

**What is the expected behavior?**

should be able to make content with rawcontent

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

![2018-07-05 4 00 23](https://user-images.githubusercontent.com/15044488/42307255-c34cdbce-806c-11e8-9ec0-f488c19c68af.png)
this is the code I used
![2018-07-05 4 00 25](https://user-images.githubusercontent.com/15044488/42307270-cba76c3a-806c-11e8-9219-3e9146fe5420.png)
this is error I got

**Comment by ktjd123** [comment]
Please close this. this problem was caused when saving to mongodb as object.

stringify it and parsing it solved it

**Comment by bologer** [comment]
@ktjd123 you may close it yourself as you are the one who opened it.
