### ISSUE TITLE
Why my original draft-js and my forked draft-js, have a different structure when installed?

### ISSUE THREAD

**Issue by RobbyWH** [facebook/draft-js#1816]
**Do you want to request a feature or report a bug?**
bug

**What is the current behavior?**
My original draft-js and my forked draft-js, have a different structure when installed

The screenshot below is the structure of my forked draft-js 
<img width="508" alt="screen shot 2018-07-20 at 11 01 24" src="https://user-images.githubusercontent.com/11469477/42982783-2466507e-8c0d-11e8-9ea1-840c292f6c6b.png">

The screenshot below is the structure of original draft-js 
<img width="526" alt="screen shot 2018-07-20 at 11 03 17" src="https://user-images.githubusercontent.com/11469477/42982787-26c0a6da-8c0d-11e8-9ed9-697125b7e4d5.png">

**What is the expected behavior?**
It should have a same structure

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
draft-js: "0.10.5"
MacOS High Sierra

**Comment by niveditc** [comment]
My guess is that we just changed the structure of files here for some reason. The current fork (your first screenshot) seems like the correct/latest version.
<img width="1110" alt="screenshot 2018-09-08 11 33 42" src="https://user-images.githubusercontent.com/2357761/45257440-2e00cb80-b35b-11e8-922c-3d43743ab81f.png">

Please reopen the issue if you have a further question on this.
