### ISSUE TITLE
How to edit the 'MUTABLE' entity if not render it's decoratedText

### ISSUE THREAD

**Issue by Feelin** [facebook/draft-js#1817]
I mean when I set the type of entity as 'MUTABLE',only by render `props.children` can I edit it's content.
Does it possible to edit a MUTABLE entity when I render other text?

**Comment by niveditc** [comment]
@Feelin - I'm not sure I correctly understand this question. Could you provide some more details and a code snippet, so that the community may be able to help you?

**Comment by niveditc** [comment]
Closing this issue due to no response.
