### ISSUE TITLE
how insert inline img

### ISSUE THREAD

**Issue by www5826** [facebook/draft-js#1818]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
do not support insert inline img

**What is the expected behavior?**
i can insert inline img
**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
0.10.5

**Comment by niveditc** [comment]
@www5826 - the only way to do this at the moment is by implementing your own custom blocks. We won't be supporting this natively in Draft.js at this time.

**Comment by hengkx** [comment]
@niveditc custom block implement,Do you have demo reference? Thanks

**Comment by UXDart** [comment]
with custom blocks is it possible to work with "inline" blocks? I tried and it always creates a new line
