### ISSUE TITLE
License hasn't been updated to be on par with React.js license

### ISSUE THREAD

**Issue by juliankrispel** [facebook/draft-js#1819]
I noticed this the other day and was wondering if it's intentional? Will this be changed? Would be a shame if not :/

**Comment by wishfoundry** [comment]
I have the same, we're considering using this but cannot unless the license is chagned

**Comment by thibaudcolas** [comment]
See #1417 and #1646 which cover this already.

**Comment by juliankrispel** [comment]
Closing this in favor of above ^
