### ISSUE TITLE
convertFromHTML breaks after converting \n string

### ISSUE THREAD

**Issue by yury-sannikov** [facebook/draft-js#1822]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug

**What is the current behavior?**
After a call to the `convertFromHTML('\n')` another call to the `convertFromHTML`, for instance `convertFromHTML('<h1>H</h1>')` return unstyled block type.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
https://jsfiddle.net/m6z0xn4r/1190/

**What is the expected behavior?**
Call to the `convertFromHTML` should be idempotent.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
0.10.5 (latest)

**Comment by yury-sannikov** [comment]
The core issue is here:
https://github.com/facebook/draft-js/blob/master/src/model/encoding/convertFromHTMLToContentBlocks.js#L376

A call to the `let chunk = {...EMPTY_CHUNK};` create a shallow copy of the `EMPTY_CHUNK` object. It means that `chunk.blocks` array (and others) share the same reference to the `EMPTY_CHUNK.blocks`.

If code hit this line https://github.com/facebook/draft-js/blob/master/src/model/encoding/convertFromHTMLToContentBlocks.js#L633 `EMPTY_CHUNK` object will end up having `block` array with one element of `{type: 'unstyled', depth: 0}` which caused the aforementioned issue.

**Comment by yury-sannikov** [comment]
PR has been created: https://github.com/facebook/draft-js/pull/1823

**Comment by MikeKoval** [comment]
I also faced the same issue, thank you @yury-sannikov

**Comment by claudiopro** [comment]
Issue already fixed with switch to the new HTML converter, test case was added with #1823
