### ISSUE TITLE
Formatting changes when pasting from Word	

### ISSUE THREAD

**Issue by mwd-vinhnguyen** [facebook/draft-js#1824]
**Do you want to request a *feature* or report a *bug*?**
- I want to report a **bug**

**What is the current behavior?**
- If copying text from MS Word the spaces between paragraphs disappears. This does not happen when the text is copied from Notepad. Refer the attachment file.
![issuecopypaste](https://user-images.githubusercontent.com/38930847/43306514-a84e2982-91a5-11e8-82bd-7698e7e30dce.gif)

**Comment by thibaudcolas** [comment]
Hey @mwd-vinhnguyen, this is the same issue as #523. It's not just Word, this happens whenever the paste is handled as "rich text" instead of plain text (even if it doesn't contain any formatting).

**Comment by niveditc** [comment]
Going to close this in favor of #523 where the discussion is ongoing :)
