### ISSUE TITLE
How can I get a custom anchor attribute in toString('html') ?

### ISSUE THREAD

**Issue by EmmanuelHidalgo** [facebook/draft-js#1826]
Hello guys,

First I have to say thanks for this amazing project!!!
Recently I am working a project and I have to send the html 'representation' of the value that I have on the rte to the server. The problem is that I have to send an anchor tag with some information (url, title and a custom attribute link-id), but when I get the html value my custom attribute does not come. Any possible solution for this?

Also I am using a decorator in oder to get customize the link
`const Link = (props) => { console.log(props.contentState.getEntity(props.entityKey).getData()) const {url, linkId, title} = props.contentState.getEntity(props.entityKey).getData(); return ( <a href={url} link-id={linkId} title={title}> {props.children} </a> ); };`

and this to get the value:

`rteText.toString('html'),`

and finally what I get is
`<blockquote>short <a href="www.facebook.com" title="test link 2">title<em>en</em></a><em>-US</em></blockquote>`

**Comment by niveditc** [comment]
Closing the issue since @cojennin's response seems sufficient. Please reopen if there are still issues.
