### ISSUE TITLE
How to turn off "BOlD" and other styles when input a new text?

### ISSUE THREAD

**Issue by RenqiangZone** [facebook/draft-js#1829]
How to turn off "BOlD" and other styles when input a new text?

eg:
In the editor,I inputed the text "I am **happy**",the **happy** already set the BOLD style, if I input a new text after **happy**,the new text's style also is BOLD. 

So there any way is turn off "BOlD" and other styles when input a new text?

Thanks!

**Comment by denyskotsur** [comment]
You have to use [decorators](https://draftjs.org/docs/advanced-topics-decorators.html). 

This question has been already discussed here: [#133](https://github.com/facebook/draft-js/issues/133).

**Comment by RenqiangZone** [comment]
@denyskotsur Thank you very much
