### ISSUE TITLE
Bug! Text alignment issue when we hit enter.

### ISSUE THREAD

**Issue by jatinderbahl** [facebook/draft-js#1831]
Steps To replicate

1) I have apply the center alignment to text and then hit enter, the cursor went to the left. 

Didn't maintain alignment.

So Is there any way to maintain the text alignment when we hit enter ?

Any help regarding this really appreciated! 

Thanks!

**Comment by niveditc** [comment]
Hi @jatinderbahl - Draft.js doesn't expose a way to do text alignment. Can you share details on how you implemented text alignment? That's the only way the community may be able to help here.

**Comment by niveditc** [comment]
I'm closing this support issue due to no response. Please reopen & provide more context if you still need help with this.
