### ISSUE TITLE
Backspace not working after pressing enter.

### ISSUE THREAD

**Issue by Ishtmeet-Singh** [facebook/draft-js#1834]
After we press "Enter" to go to a new line, it doesn't goes back to the previous line if the line has no text. So, basically it clears the current line if we use the backspace, but once if there's no text left, it doesn't goes back to the previous line. 

What could be a possible issue?

**Comment by niveditc** [comment]
@Ishtmeet-Singh - really hard for the community to help with this without any insight into your codebase or a repro in some way. Could you share more details?

**Comment by niveditc** [comment]
I'm closing this support issue due to no response. Please reopen & provide more context if you still need help with this.
