### ISSUE TITLE
focus() method renamed to focusEditor() ???

### ISSUE THREAD

**Issue by mattdamon108** [facebook/draft-js#1844]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
this.domEditor.focus method is not a function

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
https://draftjs.org/docs/advanced-topics-managing-focus.html

**What is the expected behavior?**

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

Hi There~!

I tried to implement the translating container clicks to focus into my project. but it keeps saying that below error in console.

    this.domEditor.focus is not a function

Hence, I've looked into it with command console.log(this.domEditor), I found that it seems focus method renamed to focusEditor.

Please update the documentation for future users.

**Comment by Daniel15** [comment]
Would you like to submit a pull request to update the documentation? The page is here: https://github.com/facebook/draft-js/blob/master/docs/Advanced-Topics-Managing-Focus.md. You can edit it and submit the pull request directly through Github :)

**Comment by mattdamon108** [comment]
@Daniel15 Well noted. I've directly edited the page you've linked and also edited sample code 'plaintext.html' in same page, then i've submitted the pull requests.

https://github.com/facebook/draft-js/tree/master/examples/draft-0-10-0/plaintext

**Comment by niveditc** [comment]
@mattdamon108 - thanks for putting up https://github.com/facebook/draft-js/pull/1846/ for fixing this issue.

I noticed that you closed the PR. If you reopen it, I'd be happy to merge this in for you :)

**Comment by mattdamon108** [comment]
@niveditc Sorry for making confusion with my PR. Actually, I realized that focus() method still there and works fine. I mis-read codes in my project with different packages.

**Comment by niveditc** [comment]
@mattdamon108 - ah awesome, I'm glad it works as expected! Closing this issue in that case :)
