### ISSUE TITLE
does not support voice to text input

### ISSUE THREAD

**Issue by runningmaverick** [facebook/draft-js#1856]
**Do you want to request a *feature* or report a *bug*?**
I think it's a bug.

**What is the current behavior?**
when I input with voice to text,  the words show and quickly disappear

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

**What is the expected behavior?**
show inputted text in editor

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
draftjs-0.10.5

**Comment by niveditc** [comment]
Hey @runningmaverick - thanks for reporting. Could you give more details on how someone would go about trying to repro this? How do we set up voice to text, etc?

**Comment by runningmaverick** [comment]
seems duplicate of #1077

**Comment by niveditc** [comment]
Got it, thanks! Let's keep the discussion on that issue then.
