### ISSUE TITLE
Entity length, offset bug if we use emojis, which content more than 1 symbol

### ISSUE THREAD

**Issue by wamujlb** [facebook/draft-js#1861]
Bug

Some emojis contains more than 1 symbol, so if you use emoji as entity (link for example) plugin doesn't count right the length of the string. 

Example - [📧parcel.com](url):
Expected: 2 symbol(emoji) + 10 symbols(text) = 12
We get: entity.length as 11 (what is wrong)

If we use entity (with emoji) after some content offset isn't correct also.

Example for - 😂[📧parcel.com](url):  
Expected: {offset: 2, length: 12, key: 0}
We get: {offset: 1, length: 11, key: 0} 

We can use [https://github.com/mathiasbynens/emoji-regex](url) to properly get and count emojis length

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
v0.10.4

**Comment by SureshSc** [comment]
Any solution for this ?

**Comment by johnsenpeder** [comment]
@wamujlb did you find a fix for this seeing as you closed it? If so please share your solution for others with same issue :)

**Comment by wamujlb** [comment]
> @wamujlb did you find a fix for this seeing as you closed it? If so please share your solution for others with same issue :)

Yep. You can use this prop:

`linkCallback` 

```
toolbar={{
		link: {
           	inDropdown: true,
            defaultTargetOption: "_blank",
            linkCallback: (linkProps: Object): Object => linkProps,
            trailingWhitespace: false,
        }
}}
```
