### ISSUE TITLE
How can I get the current block on hover outside of the editable area?

### ISSUE THREAD

**Issue by purezen** [facebook/draft-js#1863]
I intend to implement a functionality where I can highlight the content block on hover but outside of the editable area. Something like 10 pixels to the left of it.. akin to the functionality in Workflowy and similar editors.

**Comment by juliankrispel** [comment]
Hi @purezen. Thanks for opening an issue.

This seems like a question very specific to the product you're bulding. I'd advise not to use github issues for these sort of questions, you'd probably be better of asking around in the [draft js community slack](https://draftjs.herokuapp.com/).

Generally all your blocks are contained in your `editorState`, you could use `editorState.getCurrentContent().getBlockMap()` to get your blocks and loop over that to render relevant ui outside your editor. That should be enough to get you started
