### ISSUE TITLE
Expose adjustBlockDepthForContentState

### ISSUE THREAD

**Issue by thesunny** [facebook/draft-js#187]
Could we expose adjustBlockDepthForContentState somewhere?

My use case is to have list unindenting work like a typical word processor.

For example, let's say I have a list like this
- Item 1
  - Subitem 1
  - |

The | represents the caret.

In a typical word processor, if I hit enter on a blank list item, the list item unindents.
- Item 1
  - Subitem 1
- |

If I hit enter again, the bullet is removed.
- Item 1
  - Subitem 1

This last part I already have working. I can do the first part by manually writing all the same code as adjustBlockDepthForContentState, but it seems like it would be cleaner if I'm not replicating the code.

**Comment by hellendag** [comment]
Yeah, I've been thinking that the full list of transaction functions should probably all be exposed in the top-level module.

I hadn't done it yet since I wasn't sure if it would be necessary, but they're useful building blocks so I figured it would probably make sense at some point.

**Comment by hellendag** [comment]
Want to submit a PR to expose this?

**Comment by lacker** [comment]
There's a followup PR here so let's continue the discussion there - I'll close this issue.
