### ISSUE TITLE
Proposal to replace immutable.js by immer

### ISSUE THREAD

**Issue by JLarky** [facebook/draft-js#1870]
I think size of this project is a common concern (for example #1852) and I wonder if replacing immutable.js with smaller library like immer would also help with the size

**Comment by juliankrispel** [comment]
Hi @JLarky, thanks for opening an issue. Tbh I don't think that's an option. It would require a hefty rewrite and there's more pressing items on the roadmap.

Appreciate the idea though! Cheers!
