### ISSUE TITLE
How to do a custom text block. I want to add additional action buttons to the custom components. Thank you.

### ISSUE THREAD

**Issue by janjon** [facebook/draft-js#1874]
How to do a custom text block. I want to add additional action buttons to the custom components. Thank you.

**Comment by janjon** [comment]
```javascript
myBlockRenderer = (contentBlock) => {
    const type = contentBlock.getType();
    if (type === 'unstyled') {
      return {
        component: CustomText,
        editable: true,
        props: {
          foo: 'bar',
        },
      };
    }
  }
```
```javascript
class CustomText extends Component {
  render() {
    const {block, offsetKey} = this.props;
    console.log(this.props);
    return (
      <span data-offset-key={offsetKey}>
        <span data-text={true}>
          {block.text}
        </span>
      </span>
    );
  }
}
```
But the text input box clicks the Enter key without the wrap wrap effect of the original component's enter key.

**Comment by juliankrispel** [comment]
I'm not sure I follow entirely. The wrap wrap effect?

In order for a custom block component to work you need to use `DraftEditorBlock`, please refer to the docs for a more detailed explanation -> https://draftjs.org/docs/advanced-topics-block-components.html

Btw, you might find it helpful to join the [draft js community on slack](https://draftjs.herokuapp.com/), lots of helpful people there!
