### ISSUE TITLE
how to listen onSelect text

### ISSUE THREAD

**Issue by chengzhenping** [facebook/draft-js#1881]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

**What is the expected behavior?**

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

**Comment by cojennin** [comment]
It seems like you should be able to use the `onChange` handler to determine if text is being selected. There's an example of listening to a content change vs a selection [in this comment](https://github.com/facebook/draft-js/issues/830#issuecomment-264185874). And another example [in this thread](https://github.com/facebook/draft-js/issues/1060#issuecomment-284907998).

**Comment by niveditc** [comment]
Looks like this is resolved - please reopen if you have further questions.
