### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'isInCompositionMode' of undefined

### ISSUE THREAD

**Issue by ramisalem** [facebook/draft-js#1919]
**What is the current behavior?**
I am getting Uncaught TypeError: Cannot read property 'isInCompositionMode' of undefined when I try to get draft.js work with redux in my React project

https://codesandbox.io/s/y23mw8v199

**Comment by qruzz** [comment]
Did you manage to solve this issue? - I have run into the same thing right now, and can't seem to find any solution?
