### ISSUE TITLE
blockRenderMap type error

### ISSUE THREAD

**Issue by nonameolsson** [facebook/draft-js#1946]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Can't compile code with TypeScript when trying to use `blockRenderMap` prop.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started:
// https://jsfiddle.net/stopachka/m6z0xn4r/.**
// Not using JSfiddle since I use TypeScript.

```typescript
...
// The example below deliberately only allows
// 'heading-two' as the only valid block type and
// updates the unstyled element to also become a h2.
const blockRenderMap = Immutable.Map({
  'header-two': {
    element: 'h2'
  },
  'unstyled': {
    element: 'h2'
  }
});

...

<Editor
  editorState={editorState}
  blockRenderMap={blockRenderMap} // This line throws an error, see attached image.
  onChange={this.onChange}
/>
```

![image](https://user-images.githubusercontent.com/1493018/49319932-2752a200-f4cd-11e8-8753-b2c95875a027.png)
![image](https://user-images.githubusercontent.com/1493018/49320068-cf686b00-f4cd-11e8-8927-b2a1861f742c.png)

I have tried the instructions from ImmutableJS when using TypeScript: https://facebook.github.io/immutable-js/#using-typescript-with-immutable-js-v4

> Immutable.js type definitions embrace ES2015. While Immutable.js itself supports legacy browsers and environments, its type definitions require TypeScript's 2015 lib. Include either "target": "es2015" or "lib": "es2015" in your tsconfig.json, or provide --target es2015 or --lib es2015 to the tsc command.

**What is the expected behavior?**
blockRenderMap should work without type errors.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
It is not a browser problem. The problem is with type definitions.

```
"draft-js": "0.10.5",
"immutable": "4.0.0-rc.12",
```

**Comment by claudiopro** [comment]
Hi @nonameolsson, can you share details of your development environment (OS, editor, typescript version etc.) and a copy of your `package.json` and `package-lock.json` or `yarn.lock`?

**Comment by claudiopro** [comment]
Okay, I was able to reproduce with this config:

TypeScript version: 3.2.2

```
  "dependencies": {
    "@types/draft-js": "0.10.26",
    "@types/immutable": "^3.8.7",
    "@types/react": "16.7.18",
    "@types/react-dom": "16.0.11",
    "draft-js": "0.10.5",
    "immutable": "4.0.0-rc.12",
    "react": "16.5.2",
    "react-dom": "16.5.2",
    "react-scripts": "2.0.3"
  }
```

I receive your same error:

```
→ tsc --jsx react --lib 'es2016,dom' src/index.tsx
src/index.tsx:36:11 - error TS2322: Type 'Map<string, { element: string; }>' is not assignable to type 'Map<"blockquote" | "unstyled" | "paragraph" | "header-one" | "header-two" | "header-three" | "header-four" | "header-five" | "header-six" | "unordered-list-item" | "ordered-list-item" | "code-block" | "atomic", DraftBlockRenderConfig>'.
  Types of property 'update' are incompatible.
    Type '{ (key: string, notSetValue: { element: string; }, updater: (value: { element: string; }) => { element: string; }): Map<string, { element: string; }>; (key: string, updater: (value: { element: string; }) => { ...; }): Map<...>; <R>(updater: (value: Map<...>) => R): R; }' is not assignable to type '{ (updater: (value: Map<"blockquote" | "unstyled" | "paragraph" | "header-one" | "header-two" | "header-three" | "header-four" | "header-five" | "header-six" | "unordered-list-item" | "ordered-list-item" | "code-block" | "atomic", DraftBlockRenderConfig>) => Map<...>): Map<...>; (key: "blockquote" | ... 11 more ... ...'.

36           blockRenderMap={blockRenderMap}
             ~~~~~~~~~~~~~~

  node_modules/@types/draft-js/index.d.ts:170:17
    170                 blockRenderMap?: DraftBlockRenderMap
                        ~~~~~~~~~~~~~~
    The expected type comes from property 'blockRenderMap' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<DraftEditor> & Readonly<{ children?: ReactNode; }> & Readonly<DraftEditorProps>'


Found 1 error.
```

I'll take a look at the TS type definitions for Draft.js now

**Comment by claudiopro** [comment]
Please downgrade `immutable` to version **3.7.6** (this is the maximum supported by Draft.js at the moment, check the dependencies in [package.json](https://github.com/facebook/draft-js/blob/master/package.json): `"immutable": "~3.7.4"`.

Also, declare `blockRenderMap` as follows:

```
import { Editor, EditorState, DraftBlockType, DraftBlockRenderConfig } from "draft-js";
// ...
const blockRenderMap = Immutable.Map<DraftBlockType, DraftBlockRenderConfig>({
  "header-two": {
    element: "h2"
  },
  unstyled: {
    element: "h2"
  }
});
```

with these changes, the code compiles fine for me. Hope this helps!

**Comment by nonameolsson** [comment]
Thank you very much for the help!

**Comment by adityashubham1997** [comment]
I am facing similar problems in using blockRenderMap.
![image](https://user-images.githubusercontent.com/12209522/76209219-640c5d80-6227-11ea-96ec-7f1aff2ad59c.png)

**Comment by nonameolsson** [comment]
> Hi @nonameolsson, can you share details of your development environment (OS, editor, typescript version etc.) and a copy of your `package.json` and `package-lock.json` or `yarn.lock`?

Sorry that I haven't answered. Sadly, I stopped developing the project. I hope the issue will be solved.
