### ISSUE TITLE
Handle pasted text to create entities

### ISSUE THREAD

**Issue by hingermayank** [facebook/draft-js#195]
Hello

While pasting the content, we can get the pasted content in onPasteRawText but then again editOnPaste handles the pasted data. My usecase is something like this:

I have a input where when a user types a comma separated values, I convert them into entities(immutable) and decorate them to look like this which I have done.

<img width="522" alt="screen shot 2016-03-11 at 7 17 08 pm" src="https://cloud.githubusercontent.com/assets/6342096/13703715/ebee3824-e7bd-11e5-8dbf-4ea9b3c0a9de.png">

But the same steps need to be done to the pasted data. I might be missing something on how to handle the pasted data.

Any help would be appreciated.

Thanks

**Comment by hellendag** [comment]
Hmm. `onPasteRawText` could possibly be a canceling handler, i.e. `handlePastedText`. Then you would be able to `return true` if you handle the paste yourself.

**Comment by hingermayank** [comment]
Yes. Something like handleBeforeInput is a cancelling event.

**Comment by hellendag** [comment]
I would be fine with this. Would you like to submit a PR to replace `onPasteRawText` with `handlePastedText`?

**Comment by hingermayank** [comment]
Sure. I will do the changes and submit the PR.

**Comment by avk** [comment]
@hingermayank thanks for adding `handlePastedText`. Are there are any examples of how to use it? [The docs](https://facebook.github.io/draft-js/docs/api-reference-editor.html#handlepastedtext) are a little sparse...

**Comment by avk** [comment]
Found an example of `handlePastedText` for anyone searching in the future: https://github.com/facebook/draft-js/issues/416#issuecomment-221639163
