### ISSUE TITLE
need onMoseHover in the editor component 

### ISSUE THREAD

**Issue by ramisalem** [facebook/draft-js#1953]
**Do you want to request a *feature* or report a *bug*?**
feature 
**What is the current behavior?**

**What is the expected behavior?**
 adding onMoseOver will be very awesome to manipulate  a range of text in the editor component 
**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
0.10.5

**Comment by niveditc** [comment]
This seems like something that you could add to your fork and use, since it isn't a common feature request :) We're happy to take a look at a PR if you have a use case and it doesn't add too much customization.

I'm closing the issue but feel free to submit a PR if you'd like.
