### ISSUE TITLE
How can I update the editoerState by a custom text 

### ISSUE THREAD

**Issue by ramisalem** [facebook/draft-js#1954]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
feature

**What is the expected behavior?**
I would like to add the feature of uploading files to my draft editor and, I did implement uploaded the file and read it is content and save it in redux reducer as a text but I am wondering what is the easy way to update the editor state by that text?

I did try to pass the text in editorState property as shown below
`
                 <Editor
                 editorState={
                 this.props.fileContent !== "" ? this.props.fileContent :
                 this.state.editorState }
                 onChange={this.handleChange}

              readOnly={false}  
 /> `
but it ends up with the following error

> TypeError: nextEditorState.getDirectionMap is not a function

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

**Comment by claudiopro** [comment]
Hi @ramisalem, assuming your file contains plain text, the API you're looking for is `ContentState.createFromText()` (see [the docs](https://draftjs.org/docs/api-reference-content-state#createfromtext)).

Here's a quick example I set up for you: https://codesandbox.io/s/z686zk99jm

If your file contains HTML, a handy third party utility that comes to help is [html-to-draftjs](https://www.npmjs.com/package/html-to-draftjs). Here's another example: https://codesandbox.io/s/q347qpr9p9

For other utilities and resources, I recommend checking out the [awesome-draft-js](https://github.com/nikgraf/awesome-draft-js) list.

Hope this helps! Please reopen if this wasn't what you were looking for.
