### ISSUE TITLE
Bold not working for numbers in ordered list

### ISSUE THREAD

**Issue by frankietaylor** [facebook/draft-js#196]
Tried this in the sample https://facebook.github.io/draft-js/

Steps to reproduce:-

1. Select bold option. 
2. Type some text (ex:- abcdef)
3. Press Enter
4. Click on OL.
5. Start typing some text (ex:- xyz)

Observation:-
abcdef and xyz are in bold, but number '1' is not bold.

**Comment by hellendag** [comment]
The OL number is not expected to share the inline style of the text in the list item.

If you'd like to make the numbers bold, you can use CSS to do this, overriding `DraftStyleDefault` classes for ordered list items.

**Comment by denich** [comment]
@hellendag what would you suggest in case this styling should be added dynamically?
