### ISSUE TITLE
Content is duplicated when typing slightly fast

### ISSUE THREAD

**Issue by ShaneZhengRF** [facebook/draft-js#1965]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Different content paragraphs are duplicated when typing slightly faster between paragraphs 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
To replicate the issue:
- Just go to the draftjs office home page and use the editor
- Type 3 paragraphs (or more if you wish). Start each paragraph with very different contents so you can observe the issue more easily.
- Try to change the paragraph contents faster, inserting texts to different paragraphs

Just keep changing, at some point, one of the paragraphs will be replaced by the other paragraph.

**What is the expected behavior?**

The text replacement / duplication should NOT happen.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
all environments (that I have tested, current version of Draft.js, Firefox, Chrome on MacOS and Windows)

**Comment by ShaneZhengRF** [comment]
![2018-12-31 10 56 42](https://user-images.githubusercontent.com/2180397/50551810-3efb9100-0cec-11e9-913a-a1c52d24ce2a.gif)

**Comment by thibaudcolas** [comment]
@ShaneZhengRF this is already reported at #989, along with #424, #910, #1906, #1928. Yup, that many duplicates.

**Comment by ShaneZhengRF** [comment]
@thibaudcolas thank you
