### ISSUE TITLE
List item for empty line

### ISSUE THREAD

**Issue by frankietaylor** [facebook/draft-js#197]
Tried this here (https://facebook.github.io/draft-js/)

Steps to reproduce:-

- Type/Paste something like the following 
```
abcdef

xyz
```
- Select everything
- Click on OL

Observation:-
xyz will be assigned number 3, whereas it should be number 2.
(Tested the same in Microsoft Word 2013)

**Comment by hellendag** [comment]
With an empty line in between, I disagree that `xyz` should be assigned number 2.
