### ISSUE TITLE
_onMouseDown not used

### ISSUE THREAD

**Issue by brenmcnamara** [facebook/draft-js#1972]
Hi,

I was looking through the code and saw that the `DraftEditor.react.js` file defined a `_onMouseDown` function [here](https://github.com/facebook/draft-js/blob/master/src/component/base/DraftEditor.react.js#L224), though that function is not actually being registered with the component. This seemed strange to me since every other handler was registered except this one. It's not being used anywhere. I'm sure this is not causing any bugs at the moment, but it seems like an oversight, so I wanted to create an issue so it's on the radar.

I'd be happy to submit a quick pull request if this is a bug.

**Comment by niveditc** [comment]
It does look like a bug AFAICT. PRs are appreciated :)

**Comment by adad20** [comment]
Is this to be removed? I would like to create a PR if this is still open

**Comment by jhalak27** [comment]
@niveditc I am new here, is this PR still open? If yes, I could create a PR for this.
