### ISSUE TITLE
Add hooks to API docs

### ISSUE THREAD

**Issue by rg4real** [facebook/draft-js#1987]

**Comment by claudiopro** [comment]
Hi @rogovdm, can you provide some context for this issue? I am not sure what hooks you'd like to be added to docs.

**Comment by rogovdm** [comment]
Sorry for not being clear enough.

I am talking about converting this:
`
class MyInput extends React.Component {
  constructor(props) {
    super(props);
    this.state = {value: ''};
    this.onChange = (evt) => this.setState({value: evt.target.value});
  }
  render() {
    return <input value={this.state.value} onChange={this.onChange} />;
  }
}
`

To use react hooks. `useState` etc.

**Comment by claudiopro** [comment]
Aha, okay - it makes a lot of sense. I'd wait till hooks are released officially before updating the docs. After all, Draft is not even using them yet 😓

**Comment by rogovdm** [comment]
@claudiopro , this is a date. They are officially released!

**Comment by claudiopro** [comment]
@rogovdm go ahead and propose a PR if you feel like doing it yourself! 👍🏼

**Comment by rogovdm** [comment]
@claudiopro , I fall into using slate so can't promise anything. Anyway good luck with hooks - they are great!

**Comment by gmertk** [comment]
Closing this one as the PR was merged! 🎉
