### ISSUE TITLE
if can use es6?not commonjs

### ISSUE THREAD

**Issue by ckmilse** [facebook/draft-js#2000]
I use rollup to build one project whitch use the draft-js
but it's hard
always have this below error
```
Error: 'BlockMapBuilder' is not exported by node_modules/draft-js/lib/Draft.js
```

**Comment by claudiopro** [comment]
Hi @ckmilse, thanks for reporting this issue. I'm not familiar with Rollup, can you share your dev environment setup (stripped from the non-essential parts)?

**Comment by butchmarshall** [comment]
I attempted to use rollup to build DraftJS as well - it doesn't work well.

I believe internally Facebook uses some @providesMethod magic - paths aren't relative.
It's also using modules.export syntax rather than export default.  Rollup doesn't seem to like this either.

**Comment by TrySound** [comment]
@butchmarshall @ckmilse Use [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs)

**Comment by claudiopro** [comment]
Thanks for chiming in @TrySound, I'll familiarize myself with this setup. I hope that unblocks you @ckmilse ? Feel free to reopen the issue if still blocked.
