### ISSUE TITLE
In Chrome (version 49.0.2623.112) copy docx format word text to draft, there will be dirty data

### ISSUE THREAD

**Issue by coldice945** [facebook/draft-js#2006]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

 copy docx format word text to draft, there will be dirty data. In Chrome the version is 49.0.2623.112.

**What is the expected behavior?**

no dirty data

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

lastest version Draft.js,  Chrome version 49.0.2623.112

**Comment by jf97** [comment]
What is dirty data? What is no dirty data? What is latest version draft.js?

You do realize from the [docs ](https://draftjs.org/docs/api-reference-editor#handlepastedtext)that you can modify the pasted fragment before sending it to the editor?

**Comment by coldice945** [comment]
@jf97 
Like this.
![draft-js-old-chrome-dirty-data](https://user-images.githubusercontent.com/18394852/61930813-82cc2580-afb1-11e9-8e29-2a4b36cc4a3e.jpg)

**Comment by robbertbrak** [comment]
@coldice945: according to [this page](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767917(v=vs.85)), when you copy HTML from Word, it ends up in the clipboard with some surrounding "stuff". The copied fragment is surrounded by markers, like this:

```
<!--StartFragment -->
<P>The Fragment</P>
<!--EndFragment -->
```

DraftJS does not take this into account when you copy-paste HTML, so you'll have to write your own handling for this, as suggested by @jf97.

**Comment by thibaudcolas** [comment]
It’s interesting that this is only happening in Chrome v49 and not the latest, although from what I can see online Chrome 49 is 3 years old – so that’s unlikely to get fixed.
