### ISSUE TITLE
FlowTypes are totally broken in 0.11.0-beta

### ISSUE THREAD

**Issue by abettadapur** [facebook/draft-js#2027]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When installing `draft-js@0.11.0-beta` from NPM, the flow types are completely broken.

Flow Version: 0.92.0

As an example, in DraftEditor.flow.js:
![image](https://user-images.githubusercontent.com/2415669/53922507-7eff2d00-4029-11e9-8da3-27f56579823c.png)

`Unexpected token ':'` 

This looks syntactically wrong. Am I missing something here?

**What is the expected behavior?**
The flow types should work

**Comment by claudiopro** [comment]
Whoa, thanks for bringing this up. I'll take a look now. Something must be broken in the build step that strips types.

**Comment by claudiopro** [comment]
This is broken in master too. It seems related to the way types for class properties are declared:
https://github.com/facebook/draft-js/blob/7b9a7e116ab6dd639ebba28736629dfc04cbc7b0/src/component/base/DraftEditor.react.js#L522

**Comment by claudiopro** [comment]
Boarding a plane now, will take a look once landed 😅

**Comment by claudiopro** [comment]
Okay I confirmed it's [babel-plugin-syntax-flow](https://www.npmjs.com/package/babel-plugin-syntax-flow) that barfs when encountering types associated with [class properties](https://tc39.github.io/proposal-class-fields/). I'll take a closer look.

**Comment by claudiopro** [comment]
I have a fix @abettadapur, would you like to review?

**Comment by claudiopro** [comment]
Hold on, there's still an issue with the `'check-dependencies'` build step

**Comment by claudiopro** [comment]
Fixed with #2028
