### ISSUE TITLE
Unknown DraftEntity key: 1.

### ISSUE THREAD

**Issue by Fi1osof** [facebook/draft-js#2040]
Bug. Related to #2035

**What is the current behavior?**
After upgrade to draft-js-android-fix Insert links did broken (decorator). 

Here unminified demo: http://142.93.239.100:3124/link Reproduce: http://joxi.ru/VrwYWeLS7VQ5z2

[Here](https://github.com/prisma-cms/editor/blob/2632d91219b912aef9a29d49076a8d14b154797d/src/components/decorator/index.js#L130) i got corrent entityKey and [here](https://github.com/prisma-cms/editor/blob/2632d91219b912aef9a29d49076a8d14b154797d/src/components/decorator/index.js#L135) i got entity from current contentState. But [here](https://github.com/prisma-cms/editor/blob/2632d91219b912aef9a29d49076a8d14b154797d/src/components/decorator/index.js#L148) i got error on newContentState.mergeEntityData(entityKey, data);
On pure draft-js all works correct.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
draft-js-android-fix commit 21753fa3316acf03d5e0568d465503944cb9bf18

**Comment by fabiomcosta** [comment]
@Fi1osof do you have a link with the version of draft-js on master?
It's being hard to understand what the issue is, and I'm getting the issue even on Chrome, it's not even Android related, so this is surprising and I want to make sure we don't introduce any bugs.

**Comment by fabiomcosta** [comment]
@Fi1osof do you understand why `entityKey` is `1` on your example?
It sounds like you have entity `0`, even though `getLastCreatedEntityKey` returns `1`, which is weird.
I really don't see how my changes are related to those things.

What could be happening is that you are not only applying the changes on that PR but also all the changes that are in master which are not in 0.10.5, which is probably the version that you mean whe you say "pure draft-js".

**Comment by Fi1osof** [comment]
@fabiomcosta sorry! 
My mistake. Was included both packages draft-js and draft-js-android-fix in different files. Now wokrs fine (inline styles too).
