### ISSUE TITLE
Cannot 'npm install' Draft.js

### ISSUE THREAD

**Issue by marton-levay** [facebook/draft-js#2046]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/40199821/55161705-6dabcb00-5166-11e9-955c-ccae5d0c8709.png)

![image](https://user-images.githubusercontent.com/40199821/55161663-58cf3780-5166-11e9-85d8-d8372ee0ff5f.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Clone the repository and try to install it
```git clone git@github.com:facebook/draft-js.git```
```cd draft-js```
```npm install```

**What is the expected behavior?**
Not getting a truckload of errors right off the bat would be a nice start :)

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Draft.js 0.10.5 / no browser yet / nope my Windows is not affected by this issue (i'm not sure what that supposed to mean) / I wouldn't know, trying it for the first time.

**Comment by claudiopro** [comment]
Taking a look

**Comment by claudiopro** [comment]
It may be an issue with the npm registry. I'm receiving timeouts:

```
# procidac at mbp.local in ~/dev/gh/facebook/draft-js on git:master ● [19:24:09]
→ npm install
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ETIMEDOUT: request to https://registry.npmjs.org/del failed, reason: connect ETIMEDOUT 104.16.22.35:443
```

**Comment by claudiopro** [comment]
@marton-levay are you on a VPN? I had issues connecting to the registry with IPv4 while on an IPv6 VPN myself.

**Comment by marton-levay** [comment]
Thanks for the help!
I'm not using a VPN (as in ExpressVPN or NordVpn or some such). However I'm behind the usual - internet provider (UPC) given - router so from that point of view I'm sitting in my own private network. Didn't have any problem with it so far.

**Comment by claudiopro** [comment]
Just out of curiosity, do you have yarn installed on your system? We may have uncovered an implicit dependency of yarn via `fbjs-scripts`.

**Comment by claudiopro** [comment]
I believe this is an issue of `fbjs`, it assumes you have yarn installed on your system. Please install `yarn` [following these instructions](https://yarnpkg.com/lang/en/docs/install/) to unblock yourself.

I opened https://github.com/facebook/fbjs/issues/344 to track it. Feel free to reopen if you still have issues.

**Comment by mohitkumarCLS** [comment]
![image](https://user-images.githubusercontent.com/45752084/57176031-95cad000-6e70-11e9-9be4-f8bbd4e4ce3b.png)
I am getting this issue using npm install. Need help thanks

**Comment by dflanagan** [comment]
@claudiopro informing of dependency upon yarn solved this issue for me upon my yarn install. Thanks!!!

**Comment by morganfeeney** [comment]
Thanks for raising this issue, without it I would have had no idea how to get a demo up and running.

**Comment by Fnatic-twist** [comment]
> Thanks for raising this issue, without it I would have had no idea how to get a demo up and running.

Did you solve the problem,can you help me?

**Comment by Fnatic-twist** [comment]
I also get the error,do you have solution?Can you help me

**Comment by morganfeeney** [comment]
@Fnatic-twist I think the solution was to install Yarn globally.

**Comment by jerryfishzz** [comment]
Install Yarn and `yarn install`

**Comment by fml077** [comment]
Did you solve the problem? I also get the error. I also tried install Yarn and run yarn install ,but it doesn't work.
