### ISSUE TITLE
SelectionState.merge does not return type SelectionState.

### ISSUE THREAD

**Issue by tzerchyuan** [facebook/draft-js#2050]
I am using Immutable.merge to set new properties in a new SelectionState, but the returned type is Immutable.Map<string, any> instead of a SelectionState. Is there a workaround for this?

![image](https://user-images.githubusercontent.com/9909149/55298137-c6869800-53e0-11e9-83c8-e0ce27c8bf22.png)

and this is the error I get:
![image](https://user-images.githubusercontent.com/9909149/55298149-dd2cef00-53e0-11e9-9c29-7dc81daa51d8.png)

**Comment by tzerchyuan** [comment]
I just initialized all the fields when creating the new SelectionState. 
![image](https://user-images.githubusercontent.com/9909149/55496642-6b2cf380-55f4-11e9-854f-b9796d93871b.png)

**Comment by Krknv** [comment]
```
const selectionState = currentSelection.merge({
  anchorKey,
  anchorOffset,
  focusKey,
  focusOffset,
}) as SelectionState;
```
