### ISSUE TITLE
Configuration to allow character insertion in beginning or end of entity string to be part of entity

### ISSUE THREAD

**Issue by mdzeng** [facebook/draft-js#2056]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
After creating a content block, marking a middle string to be an entity, the entity changes correctly when adjusting the middle of the string. 

ie. for the string 
"hello how are you" 
- if a mutable entity is set for "how" (entity range offset: 6, length: 3), and I add an extra "o" so it's "ho[o]w", the entity range is as expected.

If adding at the beginning of the string, ie "[h]how" or "how[n]", the "h" and "n" are not reflected as part of the entity.

**What is the expected behavior?**
Allow a way to configure character insertions before the entity offset beginning or after the end to count as part of the entity.

(Haven't tried but imagine can do a manual override by hooking into the Editor onChange and detecting how the new content block is different and reconstructing a new entity state with changed entity ranges, unsure if there might be another alternative) 

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
0.10.5 on MacOS, never tried with older version of Draft.js

**Comment by thibaudcolas** [comment]
You could implement this with `handleBeforeInput`, similarly to what’s described in https://github.com/facebook/draft-js/issues/430#issuecomment-420521597.

**Comment by mdzeng** [comment]
Thanks for sharing! That looks like a good approach
