### ISSUE TITLE
Grammarly Does Not Work on DraftJS Example Site

### ISSUE THREAD

**Issue by Sutarodo** [facebook/draft-js#2058]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
When on the DraftJS website, the grammarly icon does not appear in the corner.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
Go to https://draftjs.org/ with the Grammarly plugin in Chrome, type something.

**What is the expected behavior?**
The grammarly icon should appear in the bottom right-hand side of the Draft editor with an error count, or at the least the Grammarly logo.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Chrome: 73.0.3683.103 (Official Build) (64-bit) (cohort: Stable) on Windows

**Comment by thibaudcolas** [comment]
@Sutarodo this is intentional by Grammarly, not a bug in Draft.js. See https://github.com/facebook/draft-js/issues/616#issuecomment-265349356.

**Comment by Sutarodo** [comment]
The comment after it suggests that Grammarly works now, however it does not give any suggestions. I'm presuming I can use the enable that `data-gram` attribute and this should be all good?

**Comment by thibaudcolas** [comment]
The comment after just says that Grammarly doesn't break Draft.js editors anymore from what I can see, because of the fact they've disabled it? I'd suggest contacting their support / checking out their docs instead of opening an issue for Draft.js, as (as far as I understand) this isn't a bug with Draft.js itself.

**Comment by Sutarodo** [comment]
Email from Grammarly:

`Our technical team is already aware of the problem you reported, but unfortunately, we don’t currently have a quick fix. I can’t provide you with an estimated timeframe right now because the developers need some time to analyze the cause of the issue, but please rest assured that we won’t forget about it.

At this time, our extension can work in a non-readonly textarea, a non-readonly contenteditable, and an iframe with a contenteditable body. There are exceptions and conditions to this rule, for example, Draft.js fields are ignored.

I’m going to close this case, but if you have more information regarding this issue, please reply to this email and the case will be re-opened for further investigation. We apologize for any inconvenience.
`
