### ISSUE TITLE
Modifier.replaceWithFragment() throws an error `TypeError: block.set is not a function`

### ISSUE THREAD

**Issue by jf97** [facebook/draft-js#2059]
**Do you want to request a *feature* or report a *bug*?**
Bug 

**What is the current behavior?**
```
var newTable = new ContentBlock({
	key: genKey(),
	text: "",
	type: "unstyled",
	editable: true,
	data: Map({ })
})
var newBlockMap = Map({})
newBlockMap = newBlockMap.set(newTable.getKey, newTable)
var selection = this.state.editorState.getSelection();
var content = this.state.editorState.getCurrentContent();
var newContent = Modifier.replaceWithFragment(
	content, 
	selection,
	newBlockMap 
)
```
throws an error `block.set is not a function` inside Modifier.replaceWithFragment() in the `randomizeContentBlockKeys()` function. 

Error is here: 

![image](https://user-images.githubusercontent.com/32752904/56231000-3a0be480-6032-11e9-92bf-622cd09c5f93.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

**What is the expected behavior?**

It's supposed to insert the new blockMap at the current selectionstate. 

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

Using latest version of firefox, and Draft v0.11.0-beta

**Comment by dkartacs** [comment]
@jf97 What was the solution ? :)
I have the same issue with this piece of code

```
const bugTemplate = {..here is raw contentState as a JSON..};`
const contentState = Modifier.replaceWithFragment(
             editorState.getCurrentContent(),
             editorState.getSelection(),
             convertFromRaw(bugTemplate),
        );
onChange(EditorState.push(editorState, contentState, 'insert-fragment'));
```

**Comment by jf97** [comment]
Thanks, but I don't think that was the issue-- I wasn't passing in a `ContentState` as my third parameter, I was passing in an Immutable Map, which was what a `BlockMap` is.  Instead of manually creating a block map, I used the `BlockMapBuilder.createFromArray()` static method  (in the Draft library) which I then inserted into `Modifier.replaceWithFragment()`
