### ISSUE TITLE
Remove mention by click

### ISSUE THREAD

**Issue by Darex1991** [facebook/draft-js#2068]
Hey guys, I have problems with my feature.. I'm trying to modify `draft-js-mention-plugin` mention component. 

<img width="852" alt="Screenshot 2019-04-30 at 19 45 08" src="https://user-images.githubusercontent.com/5881611/56984936-83f2df80-6b87-11e9-888b-e26f7bea06a2.png">

So the user will able to click "X" and remove added mention. It sounds easy.. But I spend a few hours with zero results..

I tried to use: 
- `removeRangeFromContentState` - `import removeRangeFromContentState from 'draft-js/lib/removeRangeFromContentState';`
- `Modifier.applyEntity`
- `Modifier.removeRange`
- `getEntitySelectionState` from https://github.com/facebook/draft-js/issues/182#issuecomment-223608572

I have no idea what I'm doing wrong. 
First question. If I use these functions should I update state with changes or it will be changed out of the box? I tried both ways..

Second, if any of code below is close to my flow..?

```
mentionComponent: (mentionProps) => {
<span onClick={() => this.delete(mentionProps)}>
     {mentionProps.children}
</span>
})

onChange = editorState => {
    this.setState({
      editorState,
    });
  };

  delete = mentionProps => {
    // 1
    // const contentState = editorState.getCurrentContent();
    // const entitySelectionState = getEntitySelectionState(editorState, mentionProps.entityKey);
    // this.onChange(RichUtils.toggleLink(editorState, entitySelectionState, null))
    
    // 2
    const { editorState } = this.state;
    const contentState = editorState.getCurrentContent();
    const selectionState = editorState.getSelection();
    const selectionKey = selectionState.getAnchorKey();
    const block = contentState.getBlockForKey(selectionKey);
    const blockKey = block.getKey();
    const getBlock = getRangesForDraftEntity(block, mentionProps.entityKey);
    const entitySelection = new SelectionState({
      anchorOffset: getBlock.start,
      anchorKey: blockKey,
      focusOffset: getBlock.end,
      focusKey: blockKey,
      isBackward: false,
      hasFocus: selectionState.getHasFocus(),
    });
    // 3
    const aaa = selectionState.merge({
      anchorOffset: getBlock[0].start,
      focusOffset: getBlock[0].end,
    });
    
    // const a = removeRangeFromContentState(contentState, aaa);
    // 4
    // const z = Modifier.applyEntity(contentState, entitySelection, null);
    // 5
    const z = Modifier.removeRange(contentState, entitySelection, 'forward');
    this.onChange(EditorState.push(this.state.editorState, z));
  };
```

I found few similar issues and I really tried used code and help from there but like U see, with no achievements, ie.:

https://github.com/facebook/draft-js/issues/182
https://github.com/facebook/draft-js/issues/1979

I will be really appreciated for any help

**Comment by Nolence** [comment]
Hi, I have a similar use case and was wondering if you found the solution and would mind sharing it?

**Comment by Darex1991** [comment]
Yeah cool, tomorrow I will try to create something for U :)

**Comment by Darex1991** [comment]
@Nolence https://github.com/Darex1991/draft-js-with-an-option-for-delete-mentions

**Comment by Nolence** [comment]
Very cool! Thanks @Darex1991 for your help!

**Comment by sergeyromanovsky** [comment]
@Darex1991 You are my life-saver
