### ISSUE TITLE
Section tag is so commonly used. It will be very convenient to add them to the default block render map.

### ISSUE THREAD

**Issue by lisun0459** [facebook/draft-js#2074]
`<section>` tag is so commonly used. It will be very convenient to add them to the default block render map.expect so！

**Comment by claudiopro** [comment]
Thanks for pointing this out @lisun0459, semantic tags like `<section>` and `<article>` are way more common nowadays than when the project was started. I'd be curious to see what is the distribution of tags supported by custom block render maps out in the wild.

This looks like a very good first issue for a community member who would like to contribute a code change to Draft.js! I'm more than happy to assist being the point of contact and doing a code review.

**Comment by ab-pm** [comment]
These appear to be missing from the documentation at https://draftjs.org/docs/advanced-topics-custom-block-render-map?
