### ISSUE TITLE
DraftJS getBlocksAsArray() returns an array of an array in production but just an array in dev (and works)

### ISSUE THREAD

**Issue by meds** [facebook/draft-js#2077]
I found a bug in the production environment I have set up that is very similar to my dev environment but is showing some very odd behaviour.

Following code:

```
    const sampleMarkup = "<div>Insert Text Here</div>";
    
    const blocksFromHTML = convertFromHTML(sampleMarkup);
    
    let builtContentState = ContentState.createFromBlockArray(blocksFromHTML.contentBlocks);
    console.log("builtContentState", builtContentState.getBlocksAsArray());
    
    return <div>{JSON.stringify(builtContentState)}</div>
```

In the dev environment the shape looks the same as production but the console.logs are different:

https://i.stack.imgur.com/0ADTk.png

https://i.stack.imgur.com/ClMze.png

And when I try to run draftjs editor in production I get an error about 'getKey' is not a function (probably because the array above is misshapen).

This happens using the latest version of DraftJS in all browsers

**Comment by claudiopro** [comment]
It's very difficult to answer without knowing how your production and dev environments differ.

**Comment by j2mvc** [comment]
I'm the same question.
TypeError: k.getKey is not a function
    at o.c.render (DraftEditorContents-core.react.js:164)
    at ga (react-dom.production.min.js:3880)
    at va (react-dom.production.min.js:3871)
    at qu (react-dom.production.min.js:6116)
    at zu (react-dom.production.min.js:5101)
    at Lu (react-dom.production.min.js:4958)
    at Au (react-dom.production.min.js:4817)
    at react-dom.production.min.js:2543
    at t.unstable_runWithPriority (scheduler.production.min.js:338)
    at so (react-dom.production.min.js:2513)
Aa @ react-dom.production.min.js:4260
Ha.n.callback @ react-dom.production.min.js:4659
Lo @ react-dom.production.min.js:2808
Io @ react-dom.production.min.js:2796
(anonymous) @ react-dom.production.min.js:5821
t.unstable_runWithPriority @ scheduler.production.min.js:338
so @ react-dom.production.min.js:2513
Uu @ react-dom.production.min.js:5547
Au @ react-dom.production.min.js:4817
(anonymous) @ react-dom.production.min.js:2543
t.unstable_runWithPriority @ scheduler.production.min.js:338
so @ react-dom.production.min.js:2513
ho @ react-dom.production.min.js:2538
po @ react-dom.production.min.js:2528
Tu @ react-dom.production.min.js:4773
Gi @ react-dom.production.min.js:3589
t @ create.ts:131
g @ redux.js:220
(anonymous) @ bundle.js:376
(anonymous) @ ConfigProvide.ts:29
s @ runtime.js:45
(anonymous) @ runtime.js:264
e.<computed> @ runtime.js:98
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ ConfigProvide.ts:22
(anonymous) @ App.tsx:21
Da @ react-dom.production.min.js:4299
(anonymous) @ react-dom.production.min.js:5921
t.unstable_runWithPriority @ scheduler.production.min.js:338
so @ react-dom.production.min.js:2513
Hu @ react-dom.production.min.js:5906
Lu @ react-dom.production.min.js:4935
Au @ react-dom.production.min.js:4817
(anonymous) @ react-dom.production.min.js:2543
t.unstable_runWithPriority @ scheduler.production.min.js:338
so @ react-dom.production.min.js:2513
ho @ react-dom.production.min.js:2538
po @ react-dom.production.min.js:2528
Nu @ react-dom.production.min.js:4877
hc @ react-dom.production.min.js:6748
render @ react-dom.production.min.js:6784
(anonymous) @ index.tsx:8
s @ edit?id=8b06cdd8-e6d8-4f3d-b9db-66a34c7b9ec5:1
(anonymous) @ main.97e5d9d1.chunk.js:1
s @ edit?id=8b06cdd8-e6d8-4f3d-b9db-66a34c7b9ec5:1
l @ edit?id=8b06cdd8-e6d8-4f3d-b9db-66a34c7b9ec5:1
e @ edit?id=8b06cdd8-e6d8-4f3d-b9db-66a34c7b9ec5:1
(anonymous) @ main.97e5d9d1.chunk.js:1

**Comment by felipellrocha** [comment]
I'm also running into this issue. How did you guys get around it?
