### ISSUE TITLE
Why inline styles are uppercase and other operations are lowercase

### ISSUE THREAD

**Issue by mitermayer** [facebook/draft-js#208]
Was wondering why the inline commands are on the format UNDERLINE BOLD ITALIC and the blockmode operations are header-one, header-two. 

Would be great if we could use them either on a consistent way or case insensitive.

**Comment by hellendag** [comment]
Great question. This is due to refactoring over time, and is not intentional. Personally, I prefer the lowercase values.

**Comment by mitermayer** [comment]
@hellendag How about we refactor the codebase to put everything lowercase, but still allow case insensitive to avoid breaking changes ?

**Comment by mitermayer** [comment]
we could also somehow mark as deprecated the usage of upper-case commands

**Comment by hellendag** [comment]
@mitermayer That sounds good to me.

**Comment by mitermayer** [comment]
having a look on this issue now, the problem that we have is that in order to have backwards support we would need to do a bunch of toLowerCase() in many different places since we don't yet have a centralized reference for inlineStyles matching. I wonder if we want to still proceed with backwards compatibility in this regards or we can just lower case everything else internally. @hellendag

**Comment by mitermayer** [comment]
Closing this for now
