### ISSUE TITLE
Cannot type Chinese in Edge

### ISSUE THREAD

**Issue by robbertbrak** [facebook/draft-js#2082]
To reproduce:

* Use the latest version of Draft (i.e., one that includes https://github.com/facebook/draft-js/commit/634bd297f1646934087051b1149164b01a09a136)
* In Microsoft Edge, open the rich text example
* Switch to Chinese, with the standard Microsoft IME.
* Type `nihao1`

Result: the text disappears. See the below screencast:

![screencast 2019-05-22 17-24-08](https://user-images.githubusercontent.com/734581/58189581-11bf7780-7cbb-11e9-8cc4-903849469194.gif)

Note that it does work correctly when the block already contains some text.

**Comment by robbertbrak** [comment]
When I change https://github.com/facebook/draft-js/blob/master/src/component/handlers/composition/DOMObserver.js#L120 from

```
if (removedNodes && removedNodes.length) {
  return '';
}
```

to

```
if (removedNodes && removedNodes.length) {
  return '';
} else if (target.textContent !== '') {
  return target.textContent;
}
```

This appears to be working correctly. Some preliminary testing seems to indicate that it also works on Android, and on browsers other than Edge, but I might be missing something.

@fabiomcosta: I'd be very interested in hearing your thoughts on this. Do you think this fix is in the right direction?

**Comment by fabiomcosta** [comment]
Hi @robbertbrak thank you so much for looking further and finding a fix!
The fix looks fine to me, this path is supposed to handle cases when you are removing blocks, ex:
```
draft-js
r[carret]
```
Now removing "r" and going back to the previous like by pressing Backspace 2 times should create the proper draft-js EditorState.

I'm just providing this as a test case so you can make sure no bugs are introduced in this case. By looking at your code, I don't there will be though, the fix looks pretty safe to me.

Do you want to go ahead and create a PR?

cc @claudiopro
