### ISSUE TITLE
Critical error when using React from version 16.0.0 on Android

### ISSUE THREAD

**Issue by browserkit** [facebook/draft-js#2086]
# What you need to do to get an error?

**I use the React version higher or equal to 16**

```
 "dependencies": {
    "draft-js": "^0.10.5",
    "react": "^16.0.0",
    "react-dom": "^16.0.0"
  },
```

Сreate a simple component

```javascript
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {editorState: EditorState.createEmpty()};
    this.onChange = (editorState) => this.setState({editorState});
  }
  render() {
    return (
        <Editor editorState={this.state.editorState} onChange={this.onChange} />
    );
  }
}
```

Open the result on the phone or tablet

I use: **Android 5.1.1; Nexus 7 Build/LMY47V; Google Chrome 74.0.3729.157;**
But the error is reproduced on newer versions of Android.

## Error life cycle

1. I write any text
2. At the end of the paragraph I press Enter
3. I click Backspace and again Enter

**After which the page falls**

![ezgif-4-63b0f5d97187](https://user-images.githubusercontent.com/7061988/58325165-9df3ab00-7e31-11e9-8fc2-403926dce2e7.gif)

## Console errors

`DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
`

`Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
`

![Screenshot_108](https://user-images.githubusercontent.com/7061988/58325456-7cdf8a00-7e32-11e9-9733-33745d58cba1.png)

**If you use the React version below 16, then there is no such error.**

**Comment by claudiopro** [comment]
Hi @browserkit thanks for reporting this bug! Have you tried to reproduce this with master after #2035 was merged?

**Comment by dimicuss** [comment]
Similar situation! On React 15.6.2 works almost fine.

**Comment by browserkit** [comment]
I updated the libraries to the newest version to date and this bug has disappeared.

```
 "react": "^16.10.2",
 "react-dom": "^16.10.2",
 "draft-js": "^0.11.1",
```

**Comment by StGeass** [comment]
For me still reproduced.

```
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "draft-js": "^0.11.7",
```

**Comment by jocrat** [comment]
same here

`    "draft-js": "^0.11.7",
     "react": "17.0.1",
     "react-dom": "17.0.1",`
