### ISSUE TITLE
keyBindingFn SyntheticKeyboardEvent keyCode not case sensitive 

### ISSUE THREAD

**Issue by Terminux** [facebook/draft-js#210]
SyntheticKeyboardEvent.keyCode (or which) isn't case sensitive on the keyBindingFn function.
When I press the `A` key I get the code `65` (it's good) but when I press the `a` key I get the same code `65` instead of `97`.

Thanks in advance

**Comment by hellendag** [comment]
Key bindings are triggered by keydown events, for which `keyCode` corresponds to the actual key being pressed, not the character that would be printed by the key.

https://www.w3.org/2002/09/tests/keys.html

The way to distinguish between the two in your key binding function would be to check whether the shift key is also being pressed.
