### ISSUE TITLE
Expose interface DraftDecorator in @types/draft-js

### ISSUE THREAD

**Issue by MunifTanjim** [facebook/draft-js#2101]
**Do you want to request a *feature* or report a *bug*?**
:thinking: Feature...  !

**What is the current behavior?**
`@types/draft-js` package doesn't expose the `interface DraftDecorator`.

**What is the expected behavior?**
`@types/draft-js` package to export the `interface DraftDecorator`.

**Why?**
Here's an usecase on my mind at the moment: writing a function that takes an array of `DraftDecorator` and returns a `CompositeDraftDecorator`

---

Should I create a PR?

**Comment by claudiopro** [comment]
Closing as the type definitions [@types/draft-js@0.10.33 were published to npm](https://www.npmjs.com/package/@types/draft-js) 🎉
