### ISSUE TITLE
Trouble implementing custom block

### ISSUE THREAD

**Issue by joesonw** [facebook/draft-js#211]
function use to insert custom block into draft
```js
	insertMedia(type, src, cb) {
		let editorState = this.state.editorState
		let contentState = editorState.getCurrentContent();
		let selectionState = editorState.getSelection();

		let afterRemoval = Modifier.removeRange(contentState, selectionState, 'backward');
		let targetSelection = afterRemoval.getSelectionAfter();
		let afterSplit = Modifier.splitBlock(afterRemoval, targetSelection);
		let insertionTarget = afterSplit.getSelectionAfter();

		let asMedia = Modifier.setBlockType(afterSplit, insertionTarget, `media-${type}`);
		let entityKey = Entity.create('TOKEN', 'IMMUTABLE', {
			src: src
		});

		let charData = CharacterMetadata.create({entity: entityKey});

		let fragmentArray = [
			new ContentBlock({
				key: genKey(),
				type: `media-${type}`,
				text: '',
				characterList: List(Repeat(charData, 1))
			}),
			new ContentBlock({
				key: genKey(),
				type: 'unstyled',
				text: '',
				characterList: List()
			})
		];
		let fragment = BlockMapBuilder.createFromArray(fragmentArray);
		let withMedia = Modifier.replaceWithFragment(asMedia, insertionTarget, fragment);

		let newContent = withMedia.merge({
			selectionBefore: selectionState,
			selectionAfter: withMedia.getSelectionAfter().set('hasFocus', true)
		});

		this.onChange(EditorState.push(editorState, newContent, 'insert-fragment'), cb);
	}
```

Custom block component 

```js
export default class extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			src: Entity.get(props.block.getEntityAt(0)).getData()['src']
		}
	}
	render() {
		return (
		<div contentEditable={false}>
			<img src={this.state.src}/>
		</div>
		);
	}
}
```

But somehow, i kept getting `Uncaught Error: Got unexpected null or undefined` and `Uncaught Invariant Violation: Unknown node in selection range` out of no where. 

I ran the tex example, it went perfectly fine. But mine directly copied from tex example with just a bit tune, went south.

**Comment by hellendag** [comment]
I'm fairly sure #200 will help here. Can you try adding those props to your `div` and see if that helps?

**Comment by thesunny** [comment]
I didn't look in detail but a quick glance of your code shows me one issue immediately. The first contentBlock has text of '' but should be ' '. That is, a space (or probably any character is okay).

You have a `characterList` that contains one character but it doesn't match with any text character. From my understanding, there should be a one to one relationship between `text` and `characterList`.

**Comment by joesonw** [comment]
this part was directly from tex example, other than the block type(which i
dont think is the issue here)

**Comment by hellendag** [comment]
@thesunny is correct, you need a character in your media block.

https://github.com/facebook/draft-js/blob/master/examples/tex/js/modifiers/insertTeXBlock.js#L73

**Comment by joesonw** [comment]
wow, I didnt even noticed it, thanks a lot.

btw, love this project, the true editor framework.

**Comment by nickhsine** [comment]
@joesonw @hellendag @thesunny 
I am encountering the same problem.
Even if I add a space in the text field, like  ``` text: ' '```,
and I am getting the same error ```Uncaught Error: Got unexpected null or undefined``` and ```Uncaught Invariant Violation: Unknown node in selection range```.

**Comment by thesunny** [comment]
@nickhsine 
Hi Nick, it's unlikely this solution is going to work within a text block (e.g. 'paragraph', 'unstyled', 'header-one' etc). At least not without a bit of work of which I'm not sure what that would be.

The reason is that I believe the text fields expect to have edit access to all the characters within a block and behave that way. This single character thing works with the media blocks because you are using a custom renderer that does not expect text editing.

I believe the solution you are looking for can be solved with this PR:

https://github.com/facebook/draft-js/pull/216

**Comment by Calyhre** [comment]
For those who come here from `0.7.0`, I **highly** recommend you to check #367.
I was missing the new `blockRenderMap` feature.
