### ISSUE TITLE
Update editorState via redux

### ISSUE THREAD

**Issue by jqhercules** [facebook/draft-js#2136]
**Do you want to request a *feature* or report a *bug*?**
Feature?

**What is the current behavior?**
Unable to update editor state within redux. While attempting to update editor state through a dispatch with redux the following message shows 
`_nextEditorState.getDirectionMap is not a function_ `

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: 

Here's a demo which shows multiple failed attempts. 
https://codesandbox.io/s/react-redux-with-draftjs-final-7t59n?fontsize=14.**

**What is the expected behavior?**
The editorState should update

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
0.11.0

**Comment by jf97** [comment]
This isn't a problem with Draft, but your own code + data structure.  

If you look in `./components/TextEditor.js`, when you `mapStateToProps()` your editorState isn't in `state.editorState`. 

It's in `state.editorState.editorState`. See image below:
![image](https://user-images.githubusercontent.com/32752904/61744211-924a3500-ad4b-11e9-837f-6822c8041859.png)

To prove it, change `mapStateToProps()` @ `./components/TextEditor.js` to this: 

```
const mapStateToProps = state => {
  console.log(state)  //The console is the best debugger there is. 
  return ({
  sample: state.sample,
  editorState: state.editorState.editorState  //This is the fix. works like a charm.
})}
```

**Comment by jqhercules** [comment]
humm that's strange when I set up the demo my error was "_nextEditorState.getDirectionMap is not a function_" NOT "'editorState' of null".

I did what you suggested but the error changes to  below 
<img width="408" alt="Screenshot 2019-07-29 at 15 38 02" src="https://user-images.githubusercontent.com/3270850/62057186-0e92bb80-b217-11e9-99eb-e9930fc2590a.png">

In the console, this shows
<img width="694" alt="Screenshot 2019-07-29 at 15 37 42" src="https://user-images.githubusercontent.com/3270850/62057205-1ce0d780-b217-11e9-8eda-6964f5a8b73e.png">

I'm very new to redux / state management so getting a grip of it has been somewhat frustrating.

**Comment by jqhercules** [comment]
The error was due to me not understand redux well enough

**Comment by jqhercules** [comment]
I'm back to square one, If anyone has a working example, you would be helping me outimmensely.
