### ISSUE TITLE
jsfiddle for issue reports is out of date and does not work

### ISSUE THREAD

**Issue by dobesv** [facebook/draft-js#2144]
The issue template suggests using this fiddle to get started reproducing an issue:

https://jsfiddle.net/stopachka/m6z0xn4r/

However, if you just open that fiddle unmodified, you may notice some issues:

* It uses a pretty old versions of react and draft-js
* The rendered component has major issues in Chrome (Firefox seems OK).  For example, if you enter some text, then move the cursor to the middle and edit the text in the middle, weird things happen

I tried creating one on codesandbox here:

https://codesandbox.io/embed/draft-js-0110-hk0g8

However, even running the latest version of draft-js within codesandbox I get the same weird editing behavior on the draft-js component in Chrome as in jsfiddle.

I think it would be helpful for the project to sort out why these sandboxes aren't working, and to make a fresh one with the latest version(s) of the packages.

I ran into this because I was having some weird issues with draft-js I was hoping to reproduce and report, but I wasn't able to even get a simple draft-js example working in jsfiddle or codesandbox in Chrome.

**Comment by claudiopro** [comment]
Thanks for reporting this @dobesv, we'll add this to the chores for when a new version is released 👍 

I see @gmertk is proposing a PR, we'll land it shortly.
