### ISSUE TITLE
Implement Track Change and inline comment in Draft js 

### ISSUE THREAD

**Issue by JitPatil12** [facebook/draft-js#2148]
I want to implement Track Change and inline comment in Draft js.
How I can do it?

Please share.

**Comment by jf97** [comment]
You can implement track changes using another `this.state` variable (i.e. `this.state.trackChanges: bool`).

There is a function prop you can feed to the `<Editor />` called `handleBeforeInput(key, editorState)` that gives you the opportunity to manually set the changes you want.  If your this.state.trackChanges is on, you can insert the text with an inline style that marks the additions.  You can then style the custom inline style ("track-changes") using the `<Editor />` `customStyleMap` prop (https://draftjs.org/docs/advanced-topics-inline-styles)

I'm not sure there's a clean way to track deletions, though.  

```
 handleKeyInput(key: string, editorState: EditorState) {
    if (this.state.trackChanges) { //If your track change state is on
        const content = editorState.getCurrentContent();
        const newContent = Modifier.insertText( //Just insert the character that got inputted, 
            //with an inline style of 'track-changes'
            content, 
            editorState.getSelection(), 
            key, 
            OrderedSet(["track-changes"]))
        const finalEditorState = EditorState.push(editorState, newContent, "insert-characters")
        this.onChange(finalEditorState)
        return 'handled' //Don't forget this.  Tells Editor that you've done all the 
            //edits that need to be.
    }
}
```

Inline comments can be accomplished by entities, much like links.  If you can create an entity of type "INLINE-COMMENT", and use the decorator to style that with a React component.  Depending on if you want to have a hover for your comments (more comment text is shown when you hover), you can style the component any way you want.  

Although "inline comments" seems to suggest that you want the entire comment's text visible.  Same concept-- insert the whole comment string and apply an entity to it.

**Comment by claudiopro** [comment]
Hi @JitPatil12, I assume you were okay with the answer by @jf97? Please reopen in case this wasn't sufficient.

**Comment by iamramizansari** [comment]
Goog article to read about having google docs like inline commenting in draftjs.
[Google Docs like Inline Commenting with Draftjs Rich Text Editor](https://medium.com/@ramizulhaqansari/google-docs-like-inline-commenting-with-draftjs-rich-text-editor-part-1-8fbf922929f7)

**Comment by enaluz** [comment]
@iamramizansari The suspense is killing me. Learning how to do this would be incredibly helpful for something I'm building right now-- is there any way I could take a peek at the code, or will I need to stay tuned for the continued blog post? 👀

Would really love to chat! Please DM me on Twitter @ethannaluz if you'd be kind enough to share some knowledge 😄

**Comment by tylerjbainbridge** [comment]
Hi @iamramizansari! Any plans to add a part 2?

**Comment by punithbm** [comment]
@enaluz were you able to figure out how to add the inline comments. We also looking for a similar feature in one of our products. If there is any resource it will be very helpful @iamramizansari

**Comment by SimonKlausLudwig** [comment]
Its helpful for us as well

**Comment by CoenWarmer** [comment]
Also interested!

**Comment by vinothknr1** [comment]
Also Interested
