### ISSUE TITLE
Store custom inline styles in inlineStyleRanges while converting to raw?

### ISSUE THREAD

**Issue by joesonw** [facebook/draft-js#215]
I noticed that the output of `convertToRaw` does not include custom inline styles.

for example, I tried to coloring my text. I did work in the editor. However, when I export(`convertToRaw`) them, it only includes those built-in inline styles (e.g, `BOLD`, `ITALIC`). Is there anyway around it?

**Comment by pdillon** [comment]
There's a PR with failing tests that addresses it - #158 . If it's not updated, I may submit my own this weekend to support it.

**Comment by hellendag** [comment]
@pdillon Please do, that one has gotten a bit stale. :)

**Comment by pdillon** [comment]
Submitted #217. Let me know if that's different from what you had in mind. Thanks!
