### ISSUE TITLE
spellCheck doesn't work at all.

### ISSUE THREAD

**Issue by sultanassi95** [facebook/draft-js#2150]
**What:**
_Reporting a bug._

**The Current Behavior:**
_Spell Checking is not working._

**Reproduced with a very basic example:**
https://codesandbox.io/s/spellcheck-draft-js-krb4b

**The Expected Behavior?**
_Spell Checking Activated and Working after adding prop `spellCheck` to the `Editor` Component_

**Tools:**
- Browser: Chrome Version 75.0.3770.142 (Official Build) (64-bit).
- OS: Linux Ubuntu 18.04.2 LTS.
- `draft-js@0.10.4`.
- I haven't checked this againest other versions of `draft-js`.

**What I did:**
- **Looked through:**
--- The Opened/Closed issues for this repositery, found non having `spellCheck` deactivated natuarly after passing the `true` value for the prop.
--- I have read through [this part of the documentation](https://draftjs.org/docs/api-reference-editor.html#spellcheck) and found that there are no other properties that may break this one.
- **Tried:** passing a new `key` prop for the `Editor` component on each `onChange` callback invoked to make the component possibly mount-remount again for what I think it should do to show marks that indicates for a wrong spelling where text has been added to the editor.

**Comment by gmertk** [comment]
Hi @sultanassi95, 
I've just taken a look at your sample, and I see the wavy red underline. Maybe I'm missing something. Could you clarify what you mean by "not working"? 

Also note that the latest version is 0.11.0 :) 

<img width="691" alt="Screen Shot 2019-08-02 at 10 50 10 AM" src="https://user-images.githubusercontent.com/907281/62361658-5a917900-b513-11e9-9861-80d78231d3f0.png">

**Comment by sultanassi95** [comment]
@gmertk My fault!

Found that spellcheck option was turned of in the browser where I have that problem.
Sorry for such a mistake and Thanks for the reply.
