### ISSUE TITLE
\n doesn't add bullet points for new line

### ISSUE THREAD

**Issue by Pachicito** [facebook/draft-js#2151]
I think this is more of a feature request than a bug. I am pre-populating a draftjs editor with content from Contentful. I am able to get the comma separated values onto new lines programmatically using \n but only the first line has a bullet point in front of it. I tried \r but this didn't even create a new line. Here's my code: 

```
componentDidMount() {
        const editorState = this.state.editorState;
        let newText = this.props.serverText;
        newText = newText.slice(0, newText.length);
        let combinedText = '';
        for(let i in newText) {
            combinedText += newText[i]+"\n";
        }
        const selection = editorState.getSelection();
        const contentState = editorState.getCurrentContent();
        const ncs = Modifier.insertText(contentState, selection, combinedText);
        const es = EditorState.push(editorState, ncs, 'insert-fragments');

        this.setState({
            editorState: RichUtils.toggleBlockType(
                es,
                'unordered-list-item'
            ),
        });
    }
```
Any help is much appreciated.

**Comment by jf97** [comment]
`Modifier.insertText()` is specifically meant to insert text _only in the current block._  The problem with that is that when you have a list in Draft, each bullet point is its own block.  

For what you're trying to accomplish, I would suggest the following steps:

1) create an array of content blocks. `let var blockArray = [];`
2) For each iteration in your `for(let i in newText)` loop, create a ContentBlock.  You can use the constructor. https://draftjs.org/docs/api-reference-content-block.  Then add the block to the array.
3) `import { BlockMapBuilder } from 'draft'`,  then call `BlockMapBuilder.createFromArray(blockArray)`.  You get a block map out of that.  
4) Use `Modifier.replaceWithFragment()` to insert the block map you just built.  

I've done a rough mockup. 

```
componentDidMount() {
    const editorState = this.state.editorState;
    let newText = this.props.serverText;
    newText = newText.slice(0, newText.length);

    let blockArray = [];

    
    for(let i in newText) {
        const newContentBlock = new ContentBlock({
            key: genKey(), // import {genKey } from 'draft-js'
            type: "unordered-list-item",
            text: newText[i], //Assign text here
            data: Map({ })
        })
        blockArray.push(newContentBlock)
    }

    const blockMap = BlockMapBuilder.createFromArray(blockArray)
    const newContent = Modifier.replaceWithFragment(
        editorState.getCurrentContent(),
        editorState.getSelection(),
        blockMap
    )

    //You know the rest. 
}

```

I haven't tested the code yet.

**Comment by Pachicito** [comment]
Thank you @jf97 ! I didn't realize each new line was a new block. Your code worked great. I just had to remove the 'data: Map({ })' in the constructor.
