### ISSUE TITLE
figure tag is not supported?

### ISSUE THREAD

**Issue by popmanhe** [facebook/draft-js#2166]
I have a segment of HTML that has figure tag in it. After I use convertFromHTML, draft editor will error out with message: invariant.js:40 Uncaught Invariant Violation: Unknown DraftEntity key: null

If I remove figure tag from html, there is no problem. figure tag is one of HTML5 tag, it should be added in the support tag list.

**Comment by claudiopro** [comment]
I can import a `<figure>` element like the [MDN example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure) no problem ([fiddle](https://jsfiddle.net/L27sjogd/)). If you still have issues, please reopen this.
