### ISSUE TITLE
Some options are not converted to html string

### ISSUE THREAD

**Issue by Kashio** [facebook/draft-js#2170]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when I insert an image or add color to my text and then uses `const content = convertToHTML(editorState.getCurrentContent());`
all I get is:
`"<p>test</p><figure> </figure><p></p><p></p>"`
for the following content:
![React App - Google Chrome](https://user-images.githubusercontent.com/16501683/63925559-f64ed000-ca52-11e9-9d08-848486d2e74d.jpg)

No font size, color, or image data was deserialized. (I guess other features won't work as-well)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: 
```
import React from 'react';
import "./StatusAndComments.scss";
import Status from './Status/Status';
import {convertFromHTML, EditorState, ContentState} from 'draft-js';
import {convertToHTML} from 'draft-convert';
import {Editor} from 'react-draft-wysiwyg';
import 'react-draft-wysiwyg/dist/react-draft-wysiwyg.css';

class StatusAndComments extends React.Component {
    constructor(props) {
        super(props);

        const {customer} = this.props;

        let editorState;

        if (customer.comments) {
            const blocksFromHTML = convertFromHTML(customer.comments);
            const contentState = ContentState.createFromBlockArray(blocksFromHTML);
            editorState = EditorState.createWithContent(contentState);
        }
        else {
            editorState = EditorState.createEmpty();
        }

        this.state = {
            editorState
        };
    }

    shouldComponentUpdate(nextProps, nextState) {
        return nextProps.customer.comments !== this.props.customer.comments ||
            nextState.editorState !== this.state.editorState;
    }

    onEditorStateChange = editorState => {
        const {updateCustomer} = this.props;
        const content = convertToHTML(editorState.getCurrentContent());
        this.setState({
            editorState
        });
        updateCustomer("comments", content);
    };

    render() {
        const {customer, updateCustomer} = this.props;
        const {editorState} = this.state;
        return <div className="status-and-comments">
            <Status customer={customer} updateCustomer={updateCustomer}/>
            <Editor
                editorState={editorState}
                wrapperStyle={{
                    direction: 'ltr'
                }}
                onEditorStateChange={this.onEditorStateChange}
            />
        </div>;
    }
}

export default StatusAndComments;
```

**What is the expected behavior?**
`const content = convertToHTML(editorState.getCurrentContent());`
should convert to html string with all relevant data like images inserted and color formatting.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Windows 10 
```
    "draft-convert": "^2.1.8",
    "draft-js": "^0.11.0",
    "react-draft-wysiwyg": "^1.13.2",
```

**Comment by thibaudcolas** [comment]
@Kashio you should be using the both `convertFromHTML` and `convertToHTML` from `draft-convert` instead of `draft-js`, and configure them to be compatible with the editor you’re using.

Have a look at the draft-convert docs: https://github.com/HubSpot/draft-convert.

**Comment by claudiopro** [comment]
Hi @Kashio, please report this issue to https://github.com/HubSpot/draft-convert or https://github.com/jpuri/react-draft-wysiwyg, as the problematic behavior is not built-in in Draft.js. Feel free to follow up here if the issue lies in the core editor framework /cc @jpuri or @maxwellskala

**Comment by maxwellskala** [comment]
@Kashio you need to wrap `convertFromHTML` in some `draft-extend` plugins in order for it to recognize content like links and images. For example, [here](https://github.com/HubSpot/draft-extend/blob/master/example/link.html#L113-L119) is an implementation of a link plugin. And [here](https://github.com/HubSpot/draft-extend/blob/master/example/link.html#L123) is where `convertFromHTML` is wrapped with the plugin, allowing it to recognize links.
