### ISSUE TITLE
How can I communicate from decorator to Editorparent Component?

### ISSUE THREAD

**Issue by PetrykowskiM** [facebook/draft-js#2179]
**Do you want to request a *feature*?**
Hey there, I was wondering whether there are any best practices for communicating changes from within a decorator component?

**What is the current behavior?**
Currently the decorator is purely descriptive and cannot get any additional props to communicate changes back up.

**What is the expected behavior?**
Maybe it would be great to be able to pass props to the decorator, or have any other way to allow to pass back changes.

Would be great to know if someone already had some experience with that.

**Comment by jf97** [comment]
You can write a function that generates the `Decorator` object like the following: 

```


export const generateDecorator = (callback) => {
	return new CompositeDecorator([
		{
			strategy: getEntityStrategyByType("trigger"),
			component: Marker
		},
		{
			strategy: getEntityStrategyByType("mention"),
			component: MentionTag
		},
		{
			strategy: getEntityStrategyByType("LINK"),
			component: Link
		}
	])
}

```

Then in the `<EditorParent />` constructor, generate the decorator by feeding in the callback you want.

```
constructor(props: any) {
		super(props);
		
		this.decorator = generateDecorator(this.myCallbackFunction)
	}
```

Then, use the decorator like this: 

```
		const initialEditorState = EditorState.createWithContent(content, this.decorator)


```

**Comment by PetrykowskiM** [comment]
Great, thanks for the idea. Initially i used React.Context but for some reason it did not work out and the text-cursor didn't want to change anymore. 😂

However, using the HOC approach and passing in the context "by hand" works. :)
