### ISSUE TITLE
Typing ctrl-m in the editor causes an invariant violation 

### ISSUE THREAD

**Issue by Paul-Wray** [facebook/draft-js#218]
To reproduce, focus on an empty editor and type (eg) x, ctrl-m, x.

Upon typing ctrl-m, the cursor returns to the beginning of the line, and a new block is created, but the second x is also within the first block, and the second block is empty. Both blocks have the same data-reactid. The first block seems to take up 2 lines (with the second line empty), and the second block is on the third line of the editor.

The exception is raised when the user focuses the cursor on the second block.
(OSX/Chrome)

**Comment by hellendag** [comment]
Nice catch. The browser should not be allowed to mutate the DOM this way, so the command should be added to https://github.com/facebook/draft-js/blob/master/src/component/utils/getDefaultKeyBinding.js.

**Comment by hellendag** [comment]
If anyone is looking for an easy PR to dip a toe into the codebase, this would be a good one. :)

**Comment by diki** [comment]
I would like to work on that this weekend

**Comment by diki** [comment]
@hellendag i am working on understanding the code generally. What i realized so far is `gulp watch` does not create `dist` files because it runs only `modules`. So instead of running `gulp build` on change i needed to add `dist` to `watch`, then i could see changes on refresh. Do you consider a PR for this?

**Comment by brookslyrette** [comment]
TIL: Ctrl + M is a carriage return: https://en.wikipedia.org/wiki/Carriage_return 

Should `cmd + M` new block or be ignored?

**Comment by mitermayer** [comment]
@diki this PR is already here https://github.com/facebook/draft-js/pull/242

**Comment by diki** [comment]
@mitermayer thanks, i was wondering if i was missing something.
