### ISSUE TITLE
Inserting decorated emojis while using an IME crashes editor

### ISSUE THREAD

**Issue by jdecked** [facebook/draft-js#2187]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Typing in a language which uses an IME, inserting an emoji directly after it (i.e. no spaces), then typing in the IME-using language again gives the following error if you've applied a decorator to the emojis:
<img width="407" alt="Screen Shot 2019-09-19 at 7 34 40 PM" src="https://user-images.githubusercontent.com/9261276/65294913-8e048300-db14-11e9-8972-450d260ca8f9.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/gmertk/e61z7nfa/.**

_Fiddle: https://jsfiddle.net/36tvhmce/_

For example, in Chinese on Mac:
![js-fiddle-draft-js-chinese-bug](https://user-images.githubusercontent.com/9261276/65295170-5b0ebf00-db15-11e9-9d6a-8d548e7fcadc.gif)
1. Switch your input method to "Pinyin - Traditional".
2. Type in the Draft.js field "yldx" (Yale University) and hit spacebar to insert the Chinese characters.
3. Type "hhh" (for laughing face emoji) and hit spacebar to select the laughing face emoji.
4. Type "yldx" and hit spacebar again to insert more Chinese characters.
5. Notice the above error in the console. Also notice that you can't backspace anything you've typed.

There's similar behavior inserting Japanese:
![js-fiddle-draft-js-japanese-bug](https://user-images.githubusercontent.com/9261276/65295550-9fe72580-db16-11e9-82da-243fd949f725.gif)
1. Switch your input method to Hiragana.
2. Type in the Draft.js field "watashi" (I) then hit Enter to select 私.
3. Type "emoji" and scroll down by hitting spacebar until you land on any emoji, then hit Enter to select it.
4. Type "watashi" and select 私 with Enter again.
5. Notice the above error in the console. Also notice that you can't backspace anything you've typed.

**What is the expected behavior?**
No error when inserting characters via an IME, an emoji, and then more characters, and you can backspace everything. [Here](https://jsfiddle.net/nueyL3o8/) is a fiddle where I use Draft.js v0.10.5 instead and this issue is no longer present. This is what it looks like:
![js-fiddle-draft-js-chinese-v10-5](https://user-images.githubusercontent.com/9261276/65296069-3536e980-db18-11e9-806b-fd7114b3fad0.gif)

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Draft.js version 0.11.0
Chrome v76.0.3809.132, Firefox v69.0.1, and Safari v12.1.2 on Mac OS 10.14.6
This previously worked in Draft.js v0.10.5. The PR that changed this is #2035. Reverting the [changes](https://github.com/facebook/draft-js/pull/2035/files#diff-4af33fa146be1b5864c8c7ee8b15ced5L131) made to resolveComposition in DraftEditorCompositionHandler.js in that patch fixes this issue.

**Comment by robbertbrak** [comment]
Hi @jdecked, I tried your scenarios in [my fork of Draft](https://github.com/robbertbrak/draft-js/commits/0.11.0-beta-4me), and they both work correctly. I suspect that [this commit](https://github.com/robbertbrak/draft-js/commit/1e4286b642919c4d3c9f46b30c9622c1fb77cd85) is the one that fixes it. Would you have time to give it a try and see if it solves your issue? If so, feel free to "borrow" the commit to open a pull request.

**Comment by claudiopro** [comment]
Thanks for reporting this issue @jdecked, the repro steps are very well written and helped me understand the problem!

Thanks for chiming in @robbertbrak, I was able to verify that the suggested check does indeed prevent the error reported by Justine. While I'm not fond of silently ignoring errors, recovering from the error returning the previous selection seems safe enough to unbreak the scenario of this issue.

I'll prepare a PR shortly
