### ISSUE TITLE
Can I do some extra work on my own to make it compatible with ie9?

### ISSUE THREAD

**Issue by gyh9457** [facebook/draft-js#2190]
**Do you want to request a *feature* or report a *bug*?**
it just a question

**What is the current behavior?**
I learned from the official website that it is compatible with ie11，But now, I need to support IE9

So i want to know can I do some extra work on my own to make it compatible with ie9?  may be i can fork it and do some polyfills and add some extra code?

**Comment by claudiopro** [comment]
Hi @gyh9457, you're more than welcome to fork Draft.js and adapt it to your project requirements! If you want to contribute back your enhancements to the project, feel free to open PRs against this repo and we'll evaluate them.
