### ISSUE TITLE
Cannot input Japanese letters with Microsoft Edge

### ISSUE THREAD

**Issue by atsuoishimoto** [facebook/draft-js#2192]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

With Microsoft Edge, I cannot input Japanese letters with IME.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/gmertk/e61z7nfa/.**

With Microsoft Edge, turn IME on and enter Japanese letters such as "あいうえお". No letters are stored to the draft editor.

I can repoduce this issue with sample at https://draftjs.org.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

* draft.js 0.11.1
* windows 10/Microsoft Microsoft Edge 44.17763.1.0

**Comment by robbertbrak** [comment]
I believe that this is the same as https://github.com/facebook/draft-js/issues/2082, which already has an open pull request: https://github.com/facebook/draft-js/pull/2088.

@atsuoishimoto: perhaps you could try if my pull request fixes your issue? Alternatively, you could try [my fork](https://github.com/robbertbrak/draft-js/commits/0.11.0-beta-4me), which also contains the fix.

**Comment by claudiopro** [comment]
Thank you for reporting this issue @atsuoishimoto, it is pretty bad 😞 

Thanks again for chiming in with another handy fix @robbertbrak ! I'll look into merging your PR today.

**Comment by atsuoishimoto** [comment]
This is a duplicate of #2082.
