### ISSUE TITLE
Decorators are not working as expected

### ISSUE THREAD

**Issue by backyardcoder** [facebook/draft-js#2198]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Decorators are not working as expected in the latest version of the draft-js.

The Decorator Component for the matched text gets replaced by a `span` _after typing a new character after the first regular expression match_. It then messes the editor state and cursor jumps unexpectedly upon deleting the decorated characters.

**Codepen that shows the problem**
Codepen for reproducing the issue: https://codepen.io/BackyardCoder/pen/jONzEEp

* Type `@cool` or `#cool` in the draft editor to reproduce. It will render the expected link for the first match then it will render a `span`.
* Press `backspace` to see the problems with state and cursor.

Here is gif for quick reference:

![decorators-bug](https://user-images.githubusercontent.com/7418297/65993428-156fc180-e446-11e9-814c-a376206e017e.gif)

**What is the expected behavior?**
It should render the replacement decorated component and should not cause state corruption. Removing the decorated text should work as expected.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
From an analysis, it looks like the problem got introduced in `0.11.0`. The prior version of the library works as expected. 
The problem is reproducible in all browsers and OS.

**Comment by fabiomcosta** [comment]
Here is a slightly simplified version that focus little more on the issue: https://codepen.io/fabiomcosta/pen/LYPwpde?editors=0010

**Comment by gland2015** [comment]
add the button's JSX attribute contenteditable = false

**Comment by backyardcoder** [comment]
@gland2015 : thank you, seems to work. Could you point me where is this documented?

**Comment by gland2015** [comment]
remove href is normal......

**Comment by gland2015** [comment]
@backyardcoder  Try to add a href only when presenting
