### ISSUE TITLE
Table editor

### ISSUE THREAD

**Issue by abeq** [facebook/draft-js#220]
Is there plan for table editor to make HTML table instance with GUI like as Google Doc?
And Is it built-in or plug-in in current plan?

**Comment by hellendag** [comment]
My current suggestion is to use the block component approach demonstrated in the TeX example. You can render the table statically, then use a control to expose some way to edit it, perhaps as HTML or markdown.

There are no ongoing plans to incorporate table support directly within the Draft core.

**Comment by gbbr** [comment]
This is related... https://github.com/facebook/draft-js/issues/143

**Comment by againksy** [comment]
@hellendag Please, can u share the link to TeX example with such table?
