### ISSUE TITLE
Custom styles raw encoding/decoding

### ISSUE THREAD

**Issue by Paul-Wray** [facebook/draft-js#221]
Custom styles don't seem to reach the raw-encoded output, although I find there is a test case which suggests that they should. I feel sure you would be aware of this, but I cannot find an issue or discussion for it. There is also an unanswered question on StackOverflow re this.
* Add (eg) SUP and SUB styles
* Apply custom styles to a block in the editor
* Export using convertToRaw
* Examine inlineStyleRanges for the block
* No style ranges appear for custom styled text

**Comment by hellendag** [comment]
This was merged as #217, and will be in the upcoming release. :)

**Comment by Paul-Wray** [comment]
Doh, thanks.
