### ISSUE TITLE
Playground Example is broken

### ISSUE THREAD

**Issue by drdgvhbh** [facebook/draft-js#2219]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Playground example doesn't compile

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/gmertk/e61z7nfa/.**
Just run it

**What is the expected behavior?**
It should work.

The error seems to be coming from `App.js` because the import refers to a non-existent file.

```ts
import convertFromHTMLModern from 'draft-js/lib/convertFromHTMLToContentBlocks2';
```

it should be

```ts
import convertFromHTMLModern from 'draft-js/lib/convertFromHTMLToContentBlocks';
```

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
https://github.com/facebook/draft-js/commit/42a9d8b04315cbe7bd7a2fa01e29387c6fae09e1

**Comment by claudiopro** [comment]
Good catch @drdgvhbh, I was able to reproduce

```
Failed to compile.

./src/App.js
Module not found: Can't resolve 'draft-js/lib/convertFromHTMLToContentBlocks2' in '/Users/procidac/Development/gh/claudiopro/draft-js/examples/draft-0-10-0/playground/src'
```
