### ISSUE TITLE
Question: Why wrap RichUtils calls in this.onChange calls?

### ISSUE THREAD

**Issue by cogell** [facebook/draft-js#223]
I've noticed in the examples that style changes are made with calls to `RichUtils` nested in `this.onChange` calls (where `this` is the editor component).  Example:
```
toggleInlineStyle = (style) => {
    this.onChange(
      RichUtils.toggleInlineStyle(
        this.state.editorState,
        style
      )
    );
  };
```

It seems that the call to `RichUtils.toggleInlineStyle` alone will trigger a `onChange` call via `EditorState.push`.  So the above code calls onChange twice.

Is my understanding of that correct?

**Comment by spicyj** [comment]
EditorState.push returns a new state with an updated undo stack – by design, it doesn't actually mutate anything. If you want to actually use that new state you need to store it yourself in state and cause a rerender.
