### ISSUE TITLE
Using the Chinese input method will result in the loss of the selected inline style. such as bold, italic

### ISSUE THREAD

**Issue by lemon-lc** [facebook/draft-js#2244]
**Do you want to request a *feature* or report a *bug*?**

**bug**

**What is the current behavior?**

Entering Chinese will cause the selected inline style to be lost.

but Draft.js v0.10.5 is ok.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

version: 0.11.0

browser: chrome 77

![issue](https://s33.aconvert.com/convert/p3r68-cdx67/h4vsn-s831i.gif)

**Comment by day-scene** [comment]
same here...

**Comment by mrkev** [comment]
@day-scene are you on  0.11.0 too?

**Comment by day-scene** [comment]
@mrkev yes, 0.11.3

**Comment by zengyuangai** [comment]
0.11.4   is ok

**Comment by mrkev** [comment]
Sweet! 0.11.4 had a few bugfixes. This bugfix also just came in, and will be included in 0.11.5

https://github.com/facebook/draft-js/commit/ad8374d278507ae73dceffd9bbbcede398f849e3

**Comment by Topgt** [comment]
Setting the style (such as bold, italics) first in the blank line, and then entering the Chinese style will be lost, but English is normal

**Comment by misakisaysyes** [comment]
I've tried 0.11.3~0.11.7 ,but none of them works

**Comment by misakisaysyes** [comment]
refer to [issues2745](https://github.com/facebook/draft-js/issues/2745), v0.10.5 really works !!!
