### ISSUE TITLE
SpaceBar pressing calling a function but space  not applying in the editor 

### ISSUE THREAD

**Issue by vigneshBlockDev** [facebook/draft-js#2253]
I made a function to call whenever a space bar is pressed a function is calling perfectly but after that, space is not applying in editor...  any help/ideas? anyone else having the same problem?

myKeyBindingFn = (e) => {
    console.log(e.keyCode);
    if (e.keyCode === 32 /* `S` key */ && !hasCommandModifier(e)) {
      console.log(32);
      return 'on-Space';
    }
    return getDefaultKeyBinding(e);
  }

handleKeyCommand = (command, editorState) => {
      console.log("handleKeyCommand",command);
      if (command === 'on-Space') {
             this.onSpaceBarPressed();
       }
}

 onSpaceBarPressed = () => {
      const { editorState } = this.state;
      let text = convertToRaw(editorState.getCurrentContent()).blocks;
      let value = text[0].text
        ? text
            .map(block => (!block.text.trim() && "\n") || block.text)
            .join("\n")
        : "";
        console.log(value);
      value = value.split(" ");
      console.log(value[value.length-1]);
    }

   if there is a reference/solution  to this problem..please provide me the issue id.

**Comment by vigneshBlockDev** [comment]
I think I found the solution to the problem.
This works for me


if (command === 'on-Space') {
        const {editorState} = this.state;
        let selection = editorState.getSelection();
        let cs = Modifier.insertText(
          editorState.getCurrentContent(),
          selection,
          ' '
        );

        const newEditorState = EditorState.push(
          editorState,
          cs,
          'insert-text'
        );
      this.setState({ editorState: newEditorState }, this.focus);
      return "handled";
      }

**Comment by geobde** [comment]
👍
