### ISSUE TITLE
Is it possible to support sup tags within from incoming content.

### ISSUE THREAD

**Issue by Abdulsametileri** [facebook/draft-js#2293]
**Do you want to request a *feature* or report a *bug*?** 
FEATURE

**What is the current behavior?**
In my database some rows has contents that include <sup>(12)</sup> like that.  But draft js content discard sup tag. They like a normal text. There is no superscript behavior.

**What is the expected behavior?**
I want, draft js render sup tags and displays superscript behavior as shown below.
[w3 sup example](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_sup)

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
"draft-js": "^0.11.2",
 "draft-js-export-html": "^1.4.1",
Google Chrome version. 
Version 79.0.3945.88 (Official Build) (64-bit)

This is my code to get content and send editor
`componentDidMount() {
        const { content } = this.props;

        const blocksFromHTML = convertFromHTML(content);
        const state = ContentState.createFromBlockArray(
            blocksFromHTML.contentBlocks,
            blocksFromHTML.entityMap
        );
        this.setState({
            editorState: EditorState.createWithContent(state)
        })
    }`

**Comment by jf97** [comment]
Unfortunately the `convertFromHTML` is pretty limited.  You'll need to either write your own parser, or apply a custom inline style using `Modifier.setInlineStyle` after `convertFromHTML`.
