### ISSUE TITLE
The version tags are not updated

### ISSUE THREAD

**Issue by fabiomcosta** [facebook/draft-js#2296]
The latest version on npm is 0.11.3 https://www.npmjs.com/package/draft-js, but the latest tag here on gitub is 0.11.0: https://github.com/facebook/draft-js/releases

Can someone push the tags used to publish the npm package?

**Comment by mrkev** [comment]
cc @claudiopro

**Comment by claudiopro** [comment]
Duh, I did that after pushing `v0.11.4` without realizing @fabiomcosta noticed and opened this 😅 anyhows it's done. Thanks for spotting this!
