### ISSUE TITLE
Rendering .docx files

### ISSUE THREAD

**Issue by sudh-0** [facebook/draft-js#2307]
**Do you want to request a *feature* or report a *bug*?**
*Feature Request*

**What is the current behavior?**
I don't know if it's possible to render .docx files somehow in draft-js

**What is the expected behavior?**
Is there any way so that I can use docx files for rendering? Or anything that can be used to convert the docx files to draft-js state, which can then be used for rendering?

**Comment by colinjeanne** [comment]
You can use [mammoth](https://www.npmjs.com/package/mammoth) to convert the docx file to HTML and then use Draft's own HTML conversion to go from HTML to Draft's own state.

**Comment by mrkev** [comment]
I don't think direct support for `.docx` is something we'll consider in the short or even medium term. This is a good idea, but `docx` is also very complex, plus like @colinjeanne mentioned, there's already tools to convert it to formats draft understands. (:
