### ISSUE TITLE
Homepage demo broken

### ISSUE THREAD

**Issue by andrei-cacio** [facebook/draft-js#2315]
Nothing works expect writting.

Tested on Chrome (MacOS), Firefox
![image](https://user-images.githubusercontent.com/5195546/73469263-bfc50a80-438e-11ea-8d9b-1eba942af780.png)

**Comment by mrkev** [comment]
This happened during our migration to Docusaurus 2. @yangshun was investigating (iirc filed under another issue, but then the holidays fell in the way).

**Comment by mrkev** [comment]
Found the other issue, closing as duplicate.

https://github.com/facebook/draft-js/issues/2280
