### ISSUE TITLE
when input Chinese characters after a link, link convert to text.

### ISSUE THREAD

**Issue by 55utah** [facebook/draft-js#2319]
**Do you want to request a *feature* or report a *bug*?**
I report a bug.
**What is the current behavior?**
when input Chinese characters after a link, link convert to text. 
if I input number or English characters, it does not happen.

![insert link](https://user-images.githubusercontent.com/17704150/73817604-5fb6e400-4826-11ea-8890-35f439cf14b6.png)
![input after link](https://user-images.githubusercontent.com/17704150/73817631-6e9d9680-4826-11ea-81a2-45f889a212ec.png)

**What is the expected behavior?**
It should not change when input  Chinese characters.
**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
"draft-js": "version": "0.10.38",

```insertLink = (type, data, text) => {
    const editorState = this.state.editorState;
    const contentState = editorState.getCurrentContent();
    const selection = editorState.getSelection();
    const textWithSpace = text.concat(' ');
    // create new content with text
    const newContent = Modifier.insertText(
      contentState,
      selection,
      textWithSpace,
    );
    // create new link entity
    const newContentWithEntity = newContent.createEntity(
      type,
      'MUTABLE',
      data,
      false,
    );
    const entityKey = newContentWithEntity.getLastCreatedEntityKey();
    // create new selection with the inserted text
    const anchorOffset = selection.getAnchorOffset();
    const newSelection = new SelectionState({
      anchorKey: selection.getAnchorKey(),
      anchorOffset,
      focusKey: selection.getAnchorKey(),
      focusOffset: anchorOffset + text.length,
    });
    // and aply link entity to the inserted text
    const newContentWithLink = Modifier.applyEntity(
      newContentWithEntity,
      newSelection,
      entityKey,
    );
    // create new state with link text
    const withLinkText = EditorState.push(
      editorState,
      newContentWithLink,
      'insert-characters',
    );
    // now lets add cursor right after the inserted link
    const withProperCursor = EditorState.forceSelection(
      withLinkText,
      newContent.getSelectionAfter(),
    );
    // update the editor with all changes
    this.setState({editorState: withProperCursor });
  };
```

**Comment by zhaoyao91** [comment]
this happens not only to link, but also to all entities. typing chinese next to an entity will break the it.

**Comment by zhaoyao91** [comment]
BTW, I trid the draft v0.10.5, it doesn't have this problem

**Comment by 55utah** [comment]
> this happens not only to link, but also to all entities. typing chinese next to an entity will break the it.
> 
> you can try the `mention` feature of other draft-based editors, none works for inputing chinese just next to the mention without space between.
> 
> https://jpuri.github.io/react-draft-wysiwyg/#/demo
> https://www.draft-js-plugins.com/plugin/mention

I found that

**Comment by zhaoyao91** [comment]
@55utah why this issue got closed? is it resolved in some related issue or PR?

**Comment by ahauzq** [comment]
不知道为什么要关闭掉这个issue，我目前只能在前后插入一个空格 但是解析很麻烦
