### ISSUE TITLE
Entity should terminate when typing

### ISSUE THREAD

**Issue by christophercliff** [facebook/draft-js#232]
##### 1. Select text

![screen shot 2016-03-25 at 3 03 28 pm](https://cloud.githubusercontent.com/assets/317601/14052808/f0220c62-f29a-11e5-86c6-8ffe6f72691f.png)

##### 2. Create link entity

![screen shot 2016-03-25 at 3 03 39 pm](https://cloud.githubusercontent.com/assets/317601/14052812/f028269c-f29a-11e5-81d2-907841b76824.png)

##### 3. Move cursor to end of entity

![screen shot 2016-03-25 at 3 03 46 pm](https://cloud.githubusercontent.com/assets/317601/14052811/f027555a-f29a-11e5-9971-bfc8b54e6148.png)

##### 4. Type `"4"`. `"4"` is included in entity

![screen shot 2016-03-25 at 3 04 12 pm](https://cloud.githubusercontent.com/assets/317601/14052809/f025f5ac-f29a-11e5-9f43-7fe9600c3f71.png)

##### 5. Type `" "` . `" "` is included in entity

![screen shot 2016-03-25 at 3 04 18 pm](https://cloud.githubusercontent.com/assets/317601/14052810/f026cf22-f29a-11e5-9e97-6f88c149e235.png)

In this case, I think `"4"` should be included but not `" "`. Is this intentional? Is is possible to alter this in implementation?

**Comment by hellendag** [comment]
The behavior here is entirely up to you. :)

If you'd like to break the entity on whitespace, you can use `handleBeforeInput` and disallow the entity from being preserved on the inserted character if it's a whitespace character.

http://facebook.github.io/draft-js/docs/api-reference-editor.html#handlebeforeinput

**Comment by jo-asakura** [comment]
@hellendag, do you have any examples/techniques on how to break the entity?

**Comment by jo-asakura** [comment]
OK, figured it out.. you can use `Modified.insertText` and the last parameter `entityKey` is responsible for whether to continue the entity (`entityKey: key`) or break it (`entityKey: null`).

**Comment by egorovli** [comment]
@jo-asakura thanks, you just saved me 30-40 minutes of figuring out the same thing 😄
