### ISSUE TITLE
Typescript: Issue when <Editor /> is set to readOnly, is onChange really required?

### ISSUE THREAD

**Issue by jsnwng** [facebook/draft-js#2324]
**Do you want to request a *feature* or report a *bug*?**
Bug/Improvement/Question(?)

**What is the current behavior?**
If the `DraftEditorProps.readOnly` prop is set to true, does it make sense to make the `onChange` prop required?

<img width="578" alt="Screen Shot 2020-02-06 at 1 57 50 PM" src="https://user-images.githubusercontent.com/757609/73982247-bd136980-48e8-11ea-8389-34a7e6225212.png">
<img width="466" alt="Screen Shot 2020-02-06 at 1 57 33 PM" src="https://user-images.githubusercontent.com/757609/73982257-c13f8700-48e8-11ea-8f42-464b5f206585.png">

**What is the expected behavior?**
`onChange` is an optional prop

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

	"draft-js": "^0.11.4",

**Comment by ABL1860** [comment]
Well, i think draft assumes that `readOnly` is a temporary thing.  You could always use `editorState => null` as your `onChange` function, which is what I do for my dedicated readonly editor. 

If you're using typescript, that's exactly what you want VSCode to show.
