### ISSUE TITLE
[Bug] Mac OS X - Redo short key is not working cmd + shift + Z in draftjs.org

### ISSUE THREAD

**Issue by joonhocho** [facebook/draft-js#2328]
bug

cmd + shift + Z shortkey for redo is not working for mac os x

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/gmertk/e61z7nfa/.**
https://draftjs.org/

**What is the expected behavior?**
cmd + Z should undo and cmd + shift + Z should redo, but redo is not registering.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Latest Draft.js v0.11.4. Chrome / Mac OS X.

**Comment by nik72619c** [comment]
would love to look into this!

**Comment by guillaume-duchemin** [comment]
I can see the redo action in the field (with your jsFiddle, on Chrome MacOS Mojave), what do you mean by `not registering` ?

**Comment by mrkev** [comment]
Redo works for me in the provided fiddle.
