### ISSUE TITLE
onChangeContent and onChangeSelection

### ISSUE THREAD

**Issue by ianstormtaylor** [facebook/draft-js#233]
In working with the current `Editor`, I was wondering if you'd considered adding these two conveniences. `onChangeContent` would only fire when the content itself changes, so that developers don't have to worry about diff'ing it themselves, which would be what you want to listen for to save the content somewhere.

`onChangeSelection` would be the same, but only for the selection.

Just a thought!

**Comment by hellendag** [comment]
You shouldn't need to diff anything. Since the objects are immutable, it's just a matter of equals-checking.

```javascript
onChange(editorState) {
  if (editorState.getCurrentContent() !== this.state.editorState.getCurrentContent()) {
    // content has changed
  }
  if (editorState.getSelection() !== this.state.editorState.getSelection()) {
    // selection has changed
  }
}
```

**Comment by hellendag** [comment]
The idea throughout is that you can use `onChange` for everything that occurs, then just do a quick comparison. :)
