### ISSUE TITLE
Is this project still being maintained？

### ISSUE THREAD

**Issue by gland2015** [facebook/draft-js#2340]
**Do you want to request a *feature* or report a *bug*?**
I maintain a typescript version of draftjs，Is there anyone interested in participating

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/gmertk/e61z7nfa/.**

**What is the expected behavior?**

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

**Comment by gland2015** [comment]
https://github.com/gland2015/gland/tree/master/packages/draft-ts

**Comment by Daniel15** [comment]
It's still very heavily used at Facebook, so definitely still being maintained. I'm not sure who is in charge of the open-source release at the moment though.

**Comment by jkhaui** [comment]
@gland2015 I definitely would be interested in being part of a community-driven fork of Draft.js that's under frequent development. But your repo is not going to get much attention unfortunately due to it being in Chinese. GitHub is still overwhelmingly English-based projects

**Comment by gland2015** [comment]
@jkhaui  thanks，It's easy to change to English，The problem is that I may not have enough time and ability right now。。。

**Comment by mrkev** [comment]
It's still being maintained in the sense it's what facebook uses, so fixes / features we implement keep being released (look at the commit history). There's no dedicated team working on OSS triage full-time, and Facebook web in general is hard at work on the new [beta site](https://www.reddit.com/r/facebook/comments/ev5oy9/facebook_will_be_beta_testing_their_new_look/), so that's why the repo in general is quiet.

**Comment by Johnson444** [comment]
Thanks @mrkev, @Daniel15  for your insight . I was wondering if Facebook still plans to look at mobile support?

**Comment by mrkev** [comment]
AFAIK mobile has never been quite fully supported. See: https://github.com/facebook/draft-js#browser-support
