### ISSUE TITLE
Tiny problem running examples 

### ISSUE THREAD

**Issue by HYJ29** [facebook/draft-js#2343]
**Do you want to request a *feature* or report a *bug*?**
bug 

**What is the current behavior?**

> The suggestion to run examples not working straightly (neither with npm or yarn) 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/gmertk/e61z7nfa/.**

> There comes errors with npm install. 
> So I just tried yarn and succeeded building.
> But there is naming problem on 'dist/Draf.min.js'. it should be 'dist/Draft.js'. Because most examples use that path. 
> I think it is tiny problem

**Comment by mrkev** [comment]
Yup! An earlier update means we weren't generating `dist/Draf.min.js`, only `dist/Draf.min.js`. Fix is in #2359 

Thanks for the heads up (:
