### ISSUE TITLE
convertFromHTML not documented

### ISSUE THREAD

**Issue by aaronshaf** [facebook/draft-js#236]

**Comment by hellendag** [comment]
cc @CLowbrow @mitermayer

We could probably have a little information on this in the http://facebook.github.io/draft-js/docs/api-reference-data-conversion.html#content section.

**Comment by CLowbrow** [comment]
I can write something this week if you want to give this to me.

**Comment by mitermayer** [comment]
Happy to help on it too, @CLowbrow let me know if there is anything I can do on it. :)

**Comment by CLowbrow** [comment]
@mitermayer thanks! I'm going throw something together and send a PR. Would be great to get your feedback/edits once I have something.

**Comment by smtheard** [comment]
@CLowbrow any progress ever made on this? I'd love to see even a partial writeup in this issue so I can have something to go off of. The doc up currently provides no information as to what all the parameters are or what they do. So I really don't know how to use the function at all. 

I'm going to take a look at the source and if I get a good understanding of it I'll come back and write what I find.

**Comment by tylercraft** [comment]
@smtheard There is now an example using convertFromHTML in the examples folder in master.
