### ISSUE TITLE
convertFromHTML doesn't include anchor tags

### ISSUE THREAD

**Issue by aaronshaf** [facebook/draft-js#237]
```
const blockArray = convertFromHTML('<div><a href="/foo">Bar</a></div>')
const editorState = EditorState.createWithContent(ContentState.createFromBlockArray(blockArray))
```

This seems to strip the anchor tag.

**Comment by hellendag** [comment]
Yeah, looks like the link is stripped. @CLowbrow, intentional?

**Comment by marcboeren** [comment]
It seems only http: and https: protocols are allowed (hasValidLinkText), so no relative urls or mailto: links? 
My workaround was to remove the hasValidLinkText check and now any href is allowed.
(/src/model/encoding/convertFromHTMLToContentBlocks.js)

**Comment by CLowbrow** [comment]
Yep, this is pretty aggressive. I assume we did this to not let stuff like `<a href="javascript:getPwned();"></a>` through. We can accept more stuff, but someone has to think through the security implications.

**Comment by alexeygolev** [comment]
@marcboeren @CLowbrow it strips all the a's even If I comment out `hasValidLinkText`. Any workarounds? I only need it once to transform the existing html strings to draft raw format

**Comment by aaronshaf** [comment]
This is still sad-trombone. Any ideas for a workaround?

**Comment by CLowbrow** [comment]
You could try to mutate your html to have the href attributes start with "http://www.yourdomain.com" and then pass it through? Is it failing for every possible link or just certain forms?

**Comment by xarg** [comment]
Even with the protocol set the "a" tag gets stripped: 

`convertFromHTML('<a href="http://google.com">goog</a>')` renders a text node: `goog`
Same for `<img>` tags - removed completely. 

Version is 0.7.0.

**Comment by jbrozena22** [comment]
Any update on this? It appears anchor tags don't work at all with convertToHtml.

**Comment by cgreening** [comment]
Are you passing in the list of decorators when you create the EditorState?

```js
const blocksFromHTML = convertFromHTML('<a href="http://news.bbc.co.uk">A link</a>');
const editorState = ContentState.createFromBlockArray(
  blocksFromHTML.contentBlocks,
  blocksFromHTML.entityMap
);

this.state = { editorState: EditorState.createWithContent(editorState, new CompositeDecorator(decorators)) };
```

**Comment by marcguidancenl** [comment]
Just an update, but removing the hasValidLinkText still works for me in the latest version.

If I look at https://github.com/facebook/draft-js/blob/master/src/model/encoding/convertFromHTMLToContentBlocks.js, lines 460-465, they now say:

```
while (child) {
	    if (
	      child instanceof HTMLAnchorElement &&
	      child.href &&
	      hasValidLinkText(child)
	    ) {
```

changing this helped me:

```
while (child) {
	    if (
	      child instanceof HTMLAnchorElement &&
	      child.href
	    ) {
```

All hrefs, such as /foo, https://foo.bar/, #anchor, relative-foo, they are all accepted. Yes, javascript: too probably, so use with caution.

**Comment by afhole** [comment]
Any fix for this?

**Comment by aliceriot** [comment]
I solved this issue by adding a client-side validation that uses a regular expression to check for anchor tags with non `http|https` urls in them. The user has to clear the validation error (by fixing the URL) before the request to save the HTML to the server will be issued. This works out well for the product requirements for us, maybe you can implement something similar.

**Comment by afhole** [comment]
Thanks for such a quick reply :)
I'll probably just switch back to https://github.com/sstur/draft-js-import-html to be honest.
`convertFromHTML` is also adding spaces after new lines for me (https://github.com/facebook/draft-js/issues/1217).

**Comment by mitermayer** [comment]
Closing this thread for now, but if there is still interest in this discussion please feel free to reopen/comment or create a new issue around it.

**Comment by temberature** [comment]
> Thanks for such a quick reply :) I'll probably just switch back to https://github.com/sstur/draft-js-import-html to be honest. `convertFromHTML` is also adding spaces after new lines for me (#1217).

still not working

**Comment by temberature** [comment]
```tsx
import "draft-js/dist/Draft.css";

import * as React from "react";

import {
	CompositeDecorator,
	ContentState,
	Editor,
	EditorState,
	RichUtils,
	convertFromHTML,
} from "draft-js";
import { useEffect, useState } from "react";

import metaMarked from "meta-marked";
import { stateFromHTML } from "draft-js-import-html";
import { useApp } from "./hooks";

export class Card extends React.Component {
	card: string;
	constructor(props) {
		super(props);
		const sampleMarkup =
			"<b>Bold text</b>, <i>Italic text</i><br/ ><br />" +
			'<a href="http://www.facebook.com">Example link</a>';

		const blocksFromHTML = convertFromHTML(sampleMarkup);
		const state = ContentState.createFromBlockArray(
			blocksFromHTML.contentBlocks,
			blocksFromHTML.entityMap
		);
		// const state = ContentState.createFromText(this.props.card.html);
		this.state = {
			editorState: EditorState.createWithContent(
				state,
				new CompositeDecorator([
					{
						strategy: this.findLinkEntities,
						component: this.Link,
					},
				])
			),
		};
		this.onChange = (editorState: any) => this.setState({ editorState });
	}
	findLinkEntities(contentBlock, callback, contentState) {
		contentBlock.findEntityRanges((character) => {
			const entityKey = character.getEntity();
			return (
				entityKey !== null &&
				contentState.getEntity(entityKey).getType() === "LINK"
			);
		}, callback);
	}
	Link(props) {
		const { url } = props.contentState.getEntity(props.entityKey).getData();
		return <a href={url}>{props.children}</a>;
	}
	render() {
		return (
			<Editor
				editorState={this.state.editorState}
				onChange={this.onChange}
				placeholder="Write something!"
			/>
		);
	}
}
```

**Comment by danherre** [comment]
@temberature were you able to resolve this?

**Comment by temberature** [comment]
> @temberature were you able to resolve this?

yes
