### ISSUE TITLE
[Q] Allow a custom block to retrieve data to render via an injected getter function

### ISSUE THREAD

**Issue by johanneslumpe** [facebook/draft-js#238]
This is a general question regarding plugin architecture and the dos/don'ts. Should the content block rendered by a plugin only ever user entity meta data to render its content? It seems logical to do so, but what if we have a list of items from which a user can select and that list of items can be modified. If an entity would store that information, it would become stale. In such a case I feel that using a getter injected via props to retrieve the up-to-date data for a certain id is legit, but I'd like to hear what others think about this.

**Comment by hellendag** [comment]
You should feel free to pass through any props you need to your custom block component -- it does not have to be restricted purely to entity data.

One point worth noting: if your custom block should re-render independently of other content changes, you may want to use internal state or a subscription on your custom block to trigger this independent re-rendering.
