### ISSUE TITLE
Invariant Violation: "invalid RawDraftContentState"

### ISSUE THREAD

**Issue by lalineanegra** [facebook/draft-js#2394]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
As I try to retrieve the Editor state from the database, previously saved with convertToRaw, I got the error message `Invariant Violation: "invalid RawDraftContentState"`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/gmertk/e61z7nfa/.**

Here's the code

```
import React, { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import {Editor, EditorState, RichUtils, getDefaultKeyBinding, convertToRaw,
  convertFromRaw} from 'draft-js';
import { BaseUrl } from './baseUrl'

const OC_API = BaseUrl;

function SaveGuide(props) {
```

	const [content, setContent] = useState(props.raw)

	useEffect(() => {
		if(props.raw != content) {
			setContent(props.raw)
		}
	}, [props.raw])

	function handleSubmit(e) {
		e.preventDefault();
		if (content) {
			console.log('contenido: ',content)
			fetch(`${OC_API}/guide`, {
				method: 'POST',
				body: JSON.stringify(content),
				headers: {
					'Content-Type': 'application/json'
				},
				credentials: 'same-origin'
			})
			.then(res => {
				if (res.ok){
					alert('Cambios guardados exitosamente')
				} else {
				let err = new Error(`Error, ${res.status}, ${res.statusText}`);
				alert(err);
				}
			console.log(res)
			},
			error => {
				let errmess = new Error(error.message);
				throw errmess;
			})
			.catch(e=> {
				console.log(`hubo un error ${e}`);
			})
		}   
	}  

    return (
        <button 
            className="btn btn-primary text-right" 
            name="submit" 
            type="submit"
            onClick={ (e) => handleSubmit(e) }
            style={{'backgroundColor':'#1a1a1a',
             'color':'#ffffff',
              'border': 'none',
              'fontFamily': 'Lato',
              'fontSize':'13px'
            }}
        >
            CONFIRMAR CAMBIOS
        </button>
```
    )
}

export default class Guide extends React.Component {

```
    constructor(props) {
        super(props);
        this.state = {
            editorState: EditorState.createEmpty(),
			raw: '',
			current: ''
        };

        this.focus = () => this.refs.editor.focus();

        this.onChange = (editorState) => {
            const contentState = editorState.getCurrentContent();
            const raw = convertToRaw(contentState)
            this.setState({
            editorState,
            raw: raw
            });
        }

        this.handleKeyCommand = this._handleKeyCommand.bind(this);
        this.mapKeyToEditorCommand = this._mapKeyToEditorCommand.bind(this);
        this.toggleBlockType = this._toggleBlockType.bind(this);
        this.toggleInlineStyle = this._toggleInlineStyle.bind(this);
  	}

	componentDidMount() {
		fetch(`${BaseUrl}/guide`)
		.then(res => {
			if (res.ok){
				return res
			} else {
				alert('Error de conexión. Intente más tarde')
				console.log(`Error ${res}`)
			}
		}, err => console.log(`Error ${err}`))
		.then(res => res.json())
		.then( res => {
				const content = convertFromRaw(res);
				this.setState({
					editorState: EditorState.createWithContent(content)
				})
		})
		.catch( error => {
			alert('Hubo un error')
			console.log(error)
		})
	}

	_handleKeyCommand(command, editorState) {
		const newState = RichUtils.handleKeyCommand(editorState, command);
		if (newState) {
		this.onChange(newState);
		return true;
		}
		return false;
	}

	_mapKeyToEditorCommand(e) {
		if (e.keyCode === 9 /* TAB */) {
			const newEditorState = RichUtils.onTab(
				e,
				this.state.editorState,
				4, /* maxDepth */
			);
			if (newEditorState !== this.state.editorState) {
				this.onChange(newEditorState);
			}
			return;
		}
		return getDefaultKeyBinding(e);
	}

	_toggleBlockType(blockType) {
		this.onChange(
			RichUtils.toggleBlockType(
				this.state.editorState,
				blockType
			)
		);
	}

	_toggleInlineStyle(inlineStyle) {
		this.onChange(
			RichUtils.toggleInlineStyle(
				this.state.editorState,
				inlineStyle
			)
		);
	}

    render() {
        const {editorState} = this.state;

        // If the user changes block type before entering any text, we can
        // either style the placeholder or hide it. Let's just hide it now.
        let className = 'RichEditor-editor';
        var contentState = editorState.getCurrentContent();
        if (!contentState.hasText()) {
            if (contentState.getBlockMap().first().getType() !== 'unstyled') {
                className += ' RichEditor-hidePlaceholder';
            }
        }

        return (
            <motion.div className="container" 
                initial={{ opacity: 0 }} 
                animate={{ opacity: 1}} 
                transition={{ duration: 1}}
                style={{'paddingTop':'3em'}}
            >
                <div className="card" >
					<div className="card-header text-left">
						Administrar Contenido en Inicio
					</div>
					<div className="card-body">
						<div className="row">
							<div className="col col-12">
								<div className="RichEditor-root">
									<BlockStyleControls
										editorState={editorState}
										onToggle={this.toggleBlockType}
									/>
									<InlineStyleControls
										editorState={editorState}
										onToggle={this.toggleInlineStyle}
									/>
									<div className={className} onClick={this.focus}>
										<Editor
											blockStyleFn={getBlockStyle}
											customStyleMap={styleMap}
											editorState={editorState}
											handleKeyCommand={this.handleKeyCommand}
											keyBindingFn={this.mapKeyToEditorCommand}
											onChange={this.onChange}
											placeholder="Comienza aquí..."
											ref="editor"
											spellCheck={true}
										/>
									</div>
								</div>
                        	</div>
                      	</div>
                      	<div className="row" style={{'padding': '1em 0em 0em 0em'}}>
                        	<div className="col col-12 text-right">
                            	<SaveGuide raw={this.state.raw}/>
                        	</div>
                      	</div>
                  	</div>
                </div>
            </motion.div>
```
        );
    }
}

// Custom overrides for "code" style.
const styleMap = {
  CODE: {
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    fontFamily: '"Inconsolata", "Menlo", "Consolas", monospace',
    fontSize: 16,
    padding: 2,
  },
};

function getBlockStyle(block) {
  switch (block.getType()) {
    case 'blockquote': return 'RichEditor-blockquote';
    default: return null;
  }
}

class StyleButton extends React.Component {
  constructor() {
    super();
    this.onToggle = (e) => {
      e.preventDefault();
      this.props.onToggle(this.props.style);
    };
  }

  render() {
    let className = 'RichEditor-styleButton';
    if (this.props.active) {
      className += ' RichEditor-activeButton';
    }

    return (
      <span className={className} onMouseDown={this.onToggle}>
        {this.props.label}
      </span>
    );
  }
}

const BLOCK_TYPES = [
  {label: 'Titulo 1', style: 'header-three'},
  {label: 'Titulo 2', style: 'header-four'},
  {label: 'Parrafo', style: 'header-six'},
  {label: 'Cita', style: 'blockquote'},
  {label: 'Lista', style: 'unordered-list-item'},
  {label: 'Lista ordenada', style: 'ordered-list-item'},
];

const BlockStyleControls = (props) => {
  const {editorState} = props;
  const selection = editorState.getSelection();
  const blockType = editorState
    .getCurrentContent()
    .getBlockForKey(selection.getStartKey())
    .getType();

  return (
    <div className="RichEditor-controls">
      {BLOCK_TYPES.map((type) =>
        <StyleButton
          key={type.label}
          active={type.style === blockType}
          label={type.label}
          onToggle={props.onToggle}
          style={type.style}
        />
      )}
    </div>
  );
};

var INLINE_STYLES = [
  {label: 'N', style: 'BOLD'},
  {label: 'I', style: 'ITALIC'},
  {label: 'S', style: 'UNDERLINE'},
  {label: 'Monospace', style: 'CODE'},
];

const InlineStyleControls = (props) => {
  const currentStyle = props.editorState.getCurrentInlineStyle();
  
  return (
    <div className="RichEditor-controls">
      {INLINE_STYLES.map((type) =>
        <StyleButton
          key={type.label}
          active={currentStyle.has(type.style)}
          label={type.label}
          onToggle={props.onToggle}
          style={type.style}
        />
      )}
    </div>
  );
};
`

**What is the expected behavior?**
To get an editable saved state

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
```

```I'm Using Ubuntu, Firefox and draft-js: ^0.11.5

**Comment by lalineanegra** [comment]
SOLVED. Turns out I saved more than one editor content in the database when I was testing the `convertToRaw` method. Later on I added the `converFromRaw` method, which found an array of contents for the editor, and this thrown this error

**Comment by manushishethsonos** [comment]
Did you find the solution? I am getting the same error.

**Comment by anubhav-gig** [comment]
Take care that while saving you are using ` covertToRaw() ` function. This fixed for me.
