### ISSUE TITLE
I did something wrong?

### ISSUE THREAD

**Issue by alexalannunes** [facebook/draft-js#2416]
### Code
![image](https://user-images.githubusercontent.com/16847836/81357781-f48ddf80-90aa-11ea-92b5-582e461bb8f7.png)

### Result
![image](https://user-images.githubusercontent.com/16847836/81357698-b7c1e880-90aa-11ea-952f-3eb97091d3bf.png)

**Comment by mohammadgarmroodi** [comment]
me too!

**Comment by NaviMarella** [comment]
@alexalannunes Can you provide more details on the issue.

Please try to use default issue template so we can capture more information for troubleshooting issue.

**Comment by alexalannunes** [comment]
I just followed the steps about it but the Editor not appers :sob:

**Comment by mrkev** [comment]
My guess if you forgot to import `Draft.css`. There's a PR adding it to the docs: https://github.com/facebook/draft-js/pull/2434

**Comment by alexalannunes** [comment]
> Meu palpite se você se esqueceu de importar `Draft.css`. Há um PR que o adiciona aos documentos: [# 2434](https://github.com/facebook/draft-js/pull/2434) .
> 
> Fechando, já que esse tipo de pergunta é mais adequado para o StackOverflow - mantemos os problemas do Github para relatórios de bugs e solicitações de recursos. Sinta-se livre para continuar a discussão aqui embaixo.

Thanks!
