### ISSUE TITLE
remove "current" from getCurrentContent and getCurrentInlineStyle

### ISSUE THREAD

**Issue by ianstormtaylor** [facebook/draft-js#243]
Right now `getSelection`, `getCurrentContent` and `getCurrentInlineStyle` aren't quite parallel, even though they all return the "current" representation. I'd propose removing `Current` from the latter two, since it's pretty clear still without needing to say "current", and it saves verbosity.

**Comment by hellendag** [comment]
I had actually been thinking I'd prefer to call them `getSelectionState` and `getContentState`, to make it clearer what is actually being returned.

For `getCurrentInlineStyle`, I guess my goal was to try to clarify that the value being returned is either the inline style override or the style determined via the contents and selection. Like, this is the inline style you will have right this second if you begin typing. So, current. I suppose `getInlineStyle` could also achieve this.

**Comment by ianstormtaylor** [comment]
Ah nice, `get*State` makes sense for clarity. (Although, might argue dropping the "state" everywhere, since it can be implied after a first read through an introduction to the data model in the docs, since after that people know what Draft works with.)

For inline, I didn't realize that actually! (Poor reading comprehension :) Might be clearer as `getSelectionInlineStyle`? Something to tie it to the idea that this is the style for the current selection in the editor? Since that's where the "current" is derived from?

**Comment by ianstormtaylor** [comment]
(Side thought about naming for `state`.)

I wonder if it makes sense to remove the `State` suffix everywhere, since it can be implied after learning how Draft stores data, which is already required to start using Draft. This would save a lot of typing, for not that much loss, I _think_.

`ContentState` and `contentState` become `Content` and `content`. `SelectionState` and `selectionState` become `Selection` and `selection`. And then `EditorState` and `editorState` can become the only reference to `State` and `state`. Such that:

- `State` represents the entire state of the editor, consisting of `Content` and `Selection`.
- `Content` represents all of the content of the editor.
- `Selection` represents the current selection state in the editor.
- `Block` represents and individual content block.

(Right now we don't call it `ContentBlockState`, since it's implied, so why keep calling it `ContentState` at one level higher? :smile: And we already refer to the `SelectionState` as `"selection"` in most methods, and in most prose in the docs for simplicity.)

Just a thought to throw out there!

**Comment by hellendag** [comment]
I actually really like the idea of tidying up the class names, and I have thought a lot about it.

I didn't do this prior to open sourcing because within the FB codebase we would have ended up with module naming conflicts, as all of our module names occupy the same namespace. I might have caused some grief among other engineers by naming my own modules things like `State`. :)

Going a step further, I didn't want open source users to have to talk about something as generic as "State" or "Content" while discussing very specific Draft concepts and objects.

Unfortunately, I think these issues could still be problematic. What do you think?

**Comment by ianstormtaylor** [comment]
Ah, didn't realize that for FB modules. On that one I obviously can't help :stuck_out_tongue: but hopefully that limitation wouldn't impact the open-source version? (Although now I think I know why Relay also has verbose naming :smile:, since it's still being relied on internally and ported over.)

I personally think `State`, `Content` and `Selection` as terms inside of Draft.js aren't too generic, since you need to understand the data model to use Draft at all. Similar to how Express generically calls them `Middleware`, React calls it a `Component`, etc.

The one exception might be the top-level `State`, which could more easily be argued to be ambiguous. I'd be of the opinion that once the `*State` prefixes are dropped from elsewhere, it will sort itself out to be clear enough, but could go the other way on that one specifically.

**Comment by lacker** [comment]
It seems like this discussion has converged into this renaming being a "nice to have" but not a critical bug. I am going to close this issue but if someone is interested in taking this specific proposal it might help to open a new issue with explicit suggestions of what to rename what. Thanks for bringing this up!
