### ISSUE TITLE
When I use insertAtomicBlock, I got an error: Unknown DraftEntity key: null

### ISSUE THREAD

**Issue by love-fay** [facebook/draft-js#2453]
When I encountered this error, I compared the media code in the example.
> this.setState({
>             // The third parameter here is a space string, not an empty string
>             // If you set an empty string, you will get an error: Unknown DraftEntity key: null
>             editorState: AtomicBlockUtils.insertAtomicBlock(
>               newEditorState,
>               entityKey,
>               '  '
>             ),
>             showURLInput: false,
>             urlValue: '',
>           }, () => {
>             setTimeout(() => this.focus(), 0);
>           });
[https://github.com/love-fay/draft-js/commit/a4c877846bd206af6f75d2ea6fe2ec5c064c57fd?diff=unified](https://github.com/love-fay/draft-js/commit/a4c877846bd206af6f75d2ea6fe2ec5c064c57fd?diff=unified)
I'm just adding two lines of comments, because I made this hard to see difference mistake, and I'm worried that others are the same as me

**Comment by pohsiu** [comment]
I have same issue, how do you solve? @love-fay

**Comment by love-fay** [comment]
@pohsiu I annotated AtomicBlockUtils.insertAtomicBlock. I thought the third parameter was an empty string, but it was actually a space string
