### ISSUE TITLE
cursor jumps by touching decorated element

### ISSUE THREAD

**Issue by liesislukas** [facebook/draft-js#2467]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
cursor jumps by touching decorated element

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: 

tried to make demo but fiddle is crashing with some other error https://jsfiddle.net/am86fs4j/

**What is the expected behavior?**

cursors would just go pass the decorated element just like through any other symbol

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

Chrome Version 83.0.4103.97 (Official Build) (64-bit)
Mac OS 10.14.6
draft: 0.11.6

added this question on stackoverflow as well: https://stackoverflow.com/questions/62306329/draftjs-cursor-jumps-when-touching-entity

Cursor jumps to beginning on touching the decorated element:
![jump-on-touch](https://user-images.githubusercontent.com/2733862/84284224-968a6700-ab44-11ea-8cb5-8c48121802d8.gif)

Cursor jumps just after the insert of emoji (probably same issue as 1st while it's "touching" the decorated element):
![jumps-from-both-sides](https://user-images.githubusercontent.com/2733862/84284261-a144fc00-ab44-11ea-91ef-3b1b57e110bf.gif)

![jumps-after-insert](https://user-images.githubusercontent.com/2733862/84284240-9ab68480-ab44-11ea-86ff-8d567380a8fe.gif)

Remove kind of works. Would love to just remove full decorated element w/o removing part of the text, yet i guess that's doable with handleKeyCommand and that's a different question.

![remove kind of works](https://user-images.githubusercontent.com/2733862/84284275-a5711980-ab44-11ea-8fe7-8d35fe4ccb73.gif)

Why cursor jumps to start on touching the decorator? I expect it to pass by to the right.

**Comment by liesislukas** [comment]
i think my issue is that inside decorator i had to use children and i was replacing that children with new thing and to do any kind of text replace i needed to use Modifier.replaceText() https://draftjs.org/docs/api-reference-modifier#replacetext

**Comment by digitalgopnik** [comment]
@liesislukas can you explain a bit more detailed how you solved your issue? :)

**Comment by digitalgopnik** [comment]
maybe the same problem as #1198
