### ISSUE TITLE
Upgrade to corejs-3

### ISSUE THREAD

**Issue by rosczja** [facebook/draft-js#2479]
Also the latest version of draft-js does not depend on corejs, one of its dependencies does: fbjs.

Looking into the fbjs repository it seems as it has already been upgraded to use corejs-3, but no new release has happened. 

Therefore I am creating an issue in this project, because we depend on draft-js and cannot upgrade our codebase to corejs-3.

**Comment by mrkev** [comment]
I'll try to figure out what's the deal with fbjs

**Comment by JoshRobertson** [comment]
I opened an issue to request a new version because no one is responding to the open thread about outdated dependencies there:
https://github.com/facebook/fbjs/issues/395

**Comment by mrkev** [comment]
Yup, saw it! I haven't had time to update the dependencies— but will do so soon. 👍

**Comment by mrkev** [comment]
Fixed in https://github.com/facebook/draft-js/pull/2541 (:

**Comment by JoshRobertson** [comment]
@mrkev thanks! Any chance we could get a new publish to NPM?

**Comment by mrkev** [comment]
True true, one is overdue. This one might not be immediate but I'll get 0.11.7 in in the next couple of weeks.

**Comment by mrkev** [comment]
@JoshRobertson just published 0.11.7 👍
