### ISSUE TITLE
Text Alignment

### ISSUE THREAD

**Issue by Philin-Anton** [facebook/draft-js#248]
I really like this feature, but it is not able to align text, tell me how to do it?
PS with example code please, thanks!

**Comment by hellendag** [comment]
Not sure what you are referring to. If you use the `textAlignment` prop on `Editor`, it will align your text for the entire editor.

**Comment by SumeetR** [comment]
I think that @Philin-Anton is referring to aligning certain blocks of text and not the entire editor. Any ideas on how one would go about doing that?

Thanks,
S,

**Comment by mitermayer** [comment]
You would have to do the following, create a getBlockStyle handler:

```
const getBlockStyle = (block) => {
    switch (block.getType()) {
        case 'left':
            return 'align-left';
        case 'center':
            return 'align-center';
        case 'right':
            return 'align-right';
        default:
            return null;
    }   
}
```

pass it to your editor

```
                   <Editor
                        blockStyleFn={getBlockStyle}
                       ...
                    />
```

When clicking on a button that triggers this this will than add a class 'align-right' or 'align-center' or 'align-left' to your block container. WIth that you can use CSS to:

```
.align-right {
    text-align: right;
}
.align-center {
    text-align: center;
}
.align-left {
    text-align: left;
}
```

In order to hook buttons to commands you can have a look into the rich.html example from draftjs.

**Comment by hellendag** [comment]
I generally wouldn't advise using block types that are outside the [EditorBlockType enum](https://github.com/facebook/draft-js/blob/master/src/model/constants/DraftBlockType.js).

@Philin-Anton I'd say there aren't really supported ways to do this right now on a per-block level. Is it possible that you only need certain block types to be aligned differently? If so, you can certainly use `blockStyleFn` for that.

**Comment by johanneslumpe** [comment]
@hellendag Wouldn't it be possible to do this now that https://github.com/facebook/draft-js/pull/216 has landed? When aligning a block, custom meta data could be assigned to that block, which can then be used in the `blockStyleFn` to derive which classes should be added.

**Comment by hellendag** [comment]
@johanneslumpe I think that would enable it, yeah. I've imported that one but haven't merged it yet, though.

**Comment by joshdover** [comment]
Yep we're hoping to use block level metadata for this too.

**Comment by Zulfia73** [comment]
I did all as say @mitermayer, but i'm have error.
my code:
`onCenter(self){
    self.onChange(RichUtils.toggleBlockType(self.state.editorState, 'centerAlign'));
  }
`

and that error:
`nullthrows.js?2b54:18 Uncaught Error: Got unexpected null or undefined`

what i'm do wrong?

**Comment by mitermayer** [comment]
@Zulfia73 I think we will need https://github.com/facebook/draft-js/pull/372/files to be merged

**Comment by ruffle1986** [comment]
@hellendag I think it's a common issue to set text alignment on a per-block basis.

**Comment by johanneslumpe** [comment]
@ruffle1986 The PR for block level meta data has already been imported so it is just a matter of time now until you can do alignment with meta data.

**Comment by ruffle1986** [comment]
@johanneslumpe great news! thank you guys, you're awesome! 👍

**Comment by deanmcpherson** [comment]
For reference I found a hackish way around text alignment with the current version. I used custom inline styles and checked for their existence within a block in my blockStyler function to add alignment classes to the whole block. To do so I wrote a modifier which applies a style to all of the blocks within the selection range and removes an arbitrary array of styles, so that a block can only have one alignment at a time.

It's obviously a bit dirty, but works quite well so far.

**Comment by lmgonzalves** [comment]
@deanmcpherson Can you share the code? I'm interested in your workaround :)

**Comment by deanmcpherson** [comment]
@lmgonzalves Just threw the pieces roughly together at https://gist.github.com/deanmcpherson/69f9962b744b273ffb64fe294ab71bc4

**Comment by N1kto** [comment]
Is there any 'api' solution so far? Block alignment seems to be a pretty common use case, so we really lack it in `Draft`. Thnx

**Comment by cinder92** [comment]
any update about this? i'm getting this error following the steps of @mitermayer  DraftEditorContents.react.js:151 Uncaught TypeError: Cannot read property 'wrapper' of undefined

**Comment by johanneslumpe** [comment]
@cinder92 block-level meta data has been included in version 0.8. So you do not need @mitermayer's hack from above - you can now use the meta data to tell your block which kind of text alignment you want. You can then retrieve the alignment in a custom block component and apply it in any way you want to the wrapper.

**Comment by cinder92** [comment]
@johanneslumpe thanks for your quick reply! do you have any example about this? i'm searching since 2 hours ago and there is nothing! 👍

**Comment by johanneslumpe** [comment]
@cinder92 I'm sorry, but I do not have an actual working example of this right now. I might throw one together soon though. The basic gist is to get the current selection's content block instance and then set custom alignment metadata on it. How that metadata is then interpreted is up to the wrapper component. (Could be `float` or just `text-align`)

**Comment by joshdover** [comment]
This is an example of how we did it. It's largely based on RichUtils, and gives us two new utilities:
- `toggleAlignment(editorState, alignment)` - assigns a text alignment to the current block
- `splitBlock(editorState)` - override default "return" key behavior to handle keeping the same text alignment from the previous block to the newly created block.

https://gist.github.com/joshdover/7c5e61ed68cc5552dc8a25463e357960

**Comment by anztrax** [comment]
thanks @deanmcpherson for your gist, it works for me :+1: :octocat:

**Comment by creativenode** [comment]
I've implemented the gist from @joshdover without errors, but no formatting is being added to the editor. What am I missing? Do I need to add a styles/CSS for this to work?

**Comment by mmachnicki-mdsol** [comment]
@creativenode you need probably parse this by styling method: https://facebook.github.io/draft-js/docs/advanced-topics-block-styling.html#blockstylefn

**Comment by machnicki** [comment]
@creativenode you need probably parse this by styling method: https://facebook.github.io/draft-js/docs/advanced-topics-block-styling.html#blockstylefn

**Comment by dreamcog** [comment]
i have the same question.@cinder92 @Philin-Anton
with @mitermayer 's code ,we have a error like @cinder92 said : "DraftEditorContents.react.js:151 Uncaught TypeError: Cannot read property 'wrapper' of undefined"

I fixed it like this:

`                    <Editor
                        blockRenderMap={this.extendedBlockRenderMap}
                        ...
                    />
`

and this.extendedBlockRenderMap is defined in construct:

`
    constructor(props) {
        super(props)

        const blockRenderMap = Immutable.Map({
            'text-align-left': {
                element: 'div'
            },
            'text-align-center': {
                element: 'div'
            },
            'text-align-right': {
                element: 'div'
            }
        });
        this.extendedBlockRenderMap = DefaultDraftBlockRenderMap.merge(blockRenderMap);
        ...
    }
`
so,when the draft.js meet a block have a type ==  'text-align-left' will use div element to render it.

**Comment by lcc19941214** [comment]
I find four ways to customize contentBlock, but only `blockStyleFn` works well for me.

- [ ] **`blockRenderFn`**: well, if you want to write characters normally, it is not good choice because this function doesn't provide `props.children`;

- [ ] **`blockRenderMap`**: it's not good as well as `blockRenderFn`. This Map needs to includes every block you need, unless you decide to create some new block types outside of provided `EditorBlockType`, and I don't suggest to do that.

- [x] **`blockStyleFn`**: with `Modifier.setBlockData` and `contentBlock.getData`, you can easily use `blockData` to store your contentBlock text-align style when press text-align button and set a proper classname to your block. Here is what I deal with this issue.

```javascript
// blockStyleFn
export default contentBlock => {
  const type = contentBlock.getType();
  const blockStyle = contentBlock.getData().get('style');
  let cls = '';
  switch (type) {
    case BlockType.UNSTYLED:
      cls = 'RichEditor-style__initial-unstyled';
      break;
    case BlockType.ATOMIC:
      cls = 'RichEditor-style__initial-atomic';
      break;
    default:
  }

// BASIC_BLOCKS includes unstyled, header-one, header-two,
// header-three, header-four, header-five, header-six
  if (Object.keys(BlockType.BASIC_BLOCKS).some(key => BlockType.BASIC_BLOCKS[key] === type)) {
    cls += ` RichEditor-style__text-align-${blockStyle.textAlign}`;
  }

  return cls;
};
```

I use this function because I really don't want to produce 'extra' blocks.

- [x] **`decorators`**: use `composedDecorators` it's also very easy to set text-align. But it does not work well with other strategy inside the same block, like HashTag or hyperAtTag. I found decorator component only serves one strategy at once.

```javascript
// BASIC_BLOCKS includes unstyled, header-one, header-two,
// header-three, header-four, header-five, header-six

// decorators
function matchTextAlignWrapper(contentBlock, callback, contentState) {
  if (Object.keys(BlockType.BASIC_BLOCKS).some(key => BlockType.BASIC_BLOCKS[key] === type)) {
    callback(0, contentBlock.getLength());
  }
}


export const decorator = [
  {
    strategy: matchTextAlignWrapper,
    component: TextAlignBlock
  }
];

// TextAlignBlock
export default class TextAlignBlock extends Component {
  render() {
    const { children, className } = this.props;
    const child = children[0];
    const blockStyle = child.props.block.getData().get('style');
    return (
      <div
        className={classnames(
          className,
          `RichEditor-style__text-align-${blockStyle.textAlign}`
        )}
      >
        {this.props.children}
      </div>
    );
  }
}
```

**Comment by flarnie** [comment]
Wow - I see several answers here.
Closing this issue for now. ✨ Great work everyone!

**Comment by Karpfador** [comment]
I feel like draft-js should have this functionality by default instead of requiring these kinds of workarounds

**Comment by qinggy** [comment]
[32652](url)

**Comment by juliankrispel** [comment]
Hey folks. We're about to implement text alignment in draft-js-plugins. Shouldn't be much work to implement. If anyone fancies giving it a go before I do or is simply interested in following the progress, please check here: https://github.com/draft-js-plugins/draft-js-plugins/issues/1104

**Comment by byr-gdp** [comment]
It seems only **blockStyle** worked.

**Comment by JMA12** [comment]
There's still no suggestive answer or way to address this issue. Text align is a common feature needed in an editor.

**Comment by JMA12** [comment]
@mitermayer Youre solution works well in the editor. I just want to know on how can i render it, for instance using draft-js-export-html?

**Comment by JMA12** [comment]
Already found how to render it.

**Comment by ecureuill** [comment]
> Already found how to render it.

@JMA12  could share a code pen?

**Comment by morgangreenwalt** [comment]
@ ahungrynoob could you share a code pen ?

**Comment by ahungrynoob** [comment]
@morgangreenwalt Sorry. I have left this project for too long time to pick it up. But I recommend you to use slatejs. It’s more elegant and have a stronger community.

**Comment by volkandkaya** [comment]
@juliankrispel this would be huge

**Comment by tsfahmad** [comment]
Any update on the above?
@JMA12 Can you share your solution?

**Comment by sayjeyhi** [comment]
Dear @facebook team! did you have a solution for this?!

**Comment by JMA12** [comment]
@ecureuill 
@mitermayer's answer worked for me just tweaked it a little bit. Can't find my file where I used it. If ever I found it will post it here

**Comment by AminRafaey** [comment]
Created an example with draft-js in react using hooks and features like align text is included. That was a pretty intense task so I want to share it with everyone. Anyone can access the code using this link:
https://codesandbox.io/s/draft-js-text-editor-0xg24?file=/src/NoteTile/index.js

![Screenshot from 2021-09-15 17-55-35](https://user-images.githubusercontent.com/62640101/133437279-cb1748df-2af4-4269-ae4d-480051066977.png)

**Comment by bearsworth** [comment]
So for anyone looking back, AminRafaey's solution works. If anyone is looking back its because you have to use 
function getBlockStyle(block) {
    switch (block.getType()) {
      case 'left-align':
        return 'customEditorAlignLeft';
      case 'center-align':
        return 'customEditorAlignCenter';
      case 'right-align':
        return 'customEditorAlignRight';
      case 'justify-align':
        return 'customEditorJustifyAlign';
      default: return null;
    }
  };

You can name whatever you like for the css i just called it customEditorJustify... etc. In your draft.css, you then have to make sure to add 'div' after the name itself. For some reason it won't work without it. So for instance:

.customEditorJustifyAlign div {
  text-align: justify;
}

I tried to go about using custom blocks, but it wouldn't work. I suspect it has to do with the way the editor defines the newly created block.

**Comment by PinoFlores** [comment]
A text editor without text alignment? O.o '
Who did this?

Thanks to God I realized of this before start to use it, becuase as I can see the big discussion Meta engineers got, adding this 3 lines of code can take a couple years more. 🙊

**Comment by gakin95** [comment]
I noticed the following functionalities are not working on nextjs: underline, quote, strikethrough, and text alignment. Can someone help out?

**Comment by avibz1987** [comment]
Any news regarding this bug?

**Comment by ilija-trbogazov** [comment]
Abandon ship now !
Its a pity that such core functionality is not implemented yet.
@PinoFlores thank you for the encouragement.
