### ISSUE TITLE
How to prevent editor from getting focus(or adding selection)?

### ISSUE THREAD

**Issue by xinghul** [facebook/draft-js#2482]
**Do you want to request a *feature* or report a *bug*?**
More of a question.
**Description**
I'm trying to implement a Link popover, which allows user to change the link URL(entity data) with a popover input:
![Screen Shot 2020-06-27 at 1 53 14 PM](https://user-images.githubusercontent.com/6555861/85932090-fb043080-b87d-11ea-997c-fd4a1e86db37.png)

However, whenever I start typing in the popover input, the Editor always tries to invoke `addFocusToSelection`, which makes the popover input lose focus, is there any way to prevent the Editor from doing that?

I might be doing it wrong, here's the code I'm using to update the entity data:
```javascript
<Input
          ref={inputRef}
          onChange={(event) => {
            const newSrc = event.target.value;
            const newContentState = contentState.mergeEntityData(
              entityKey,
              { src: newSrc },
            );

            const newEditorState = EditorState.push(editorState, newContentState, 'apply-entity');

            setEditorState(newEditorState);
          }}
/>
```

**Comment by NaviMarella** [comment]
@xinghul Can you provide a sandbox example, i can take a look.

We implemented similar functionality and don't see any issues with focus.

**Comment by xinghul** [comment]
So I ended up disabling the editor whenever the popover shows, so it wont fight for focus.
