### ISSUE TITLE
How to achieve this effect

### ISSUE THREAD

**Issue by usecodelee** [facebook/draft-js#2484]
How to achieve this effect？
Press the right cursor to jump directly from position 1 to position 2：
example
![image](https://user-images.githubusercontent.com/32923083/86225130-66226f80-bbbc-11ea-8811-dde29ab0d57d.png)

Thanks for anyone who helped me

**Comment by claudiopro** [comment]
Hi @usecodelee, this behavior can be achieved with immutable (or segmented) custom entities. See [this documentation topic](https://draftjs.org/docs/advanced-topics-entities#mutability) for more details.
