### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Zmeu213** [facebook/draft-js#2488]
Bug

Link to CompositeDecorator in documentation doesnt lead anywhere https://github.com/facebook/draft-js/blob/master/docs/APIReference-CompositeDecorator.md

**Comment by AlokTakshak** [comment]
@Zmeu213 

I think Links are supposed to work on draft.js not inside the github repo, you can check below it is working
https://draftjs.org/docs/api-reference-composite-decorator

**Comment by claudiopro** [comment]
@AlokTakshak is correct, the links embedded in markdown of files of documentation topics are currently authored to work with the routes of the draftjs.org Docusaurus website.
