### ISSUE TITLE
Editor renders incorrectly when state is reset inside handleReturn

### ISSUE THREAD

**Issue by akprasad** [facebook/draft-js#249]
(Context: I want to use draft-js as a richer `<input type="text">`. To do so, I'd like to get the editor's text value and clear it when the user presses enter.)

If you try to reset the editor state within `handleReturn`, the editor renders later text incorrectly, i.e. on multiple lines and with broken cursor/delete behavior.

Here's a minimal jsbin. See the comments to reproduce:
http://jsbin.com/wiwiwekohu/edit?html,js,output

**Comment by tasti** [comment]
This came up before, see https://github.com/facebook/draft-js/issues/73#issuecomment-191394559 :)

**Comment by akprasad** [comment]
Thanks, this seems to work.

IIRC, the issue is that `editorState` doesn't model blur, so its behavior is undefined when we reset the state while the editor is focused. Is that about right?

**Comment by hellendag** [comment]
Yeah, if the `EditorState` doesn't have awareness of what the DOM focus state is, you can get into a bad state. It's always good to establish the proper focus state on your `EditorState` if you are clearing it.

**Comment by shashiranjansingh** [comment]
rewwwwwwwwwwwwwwwwwwwwwwwwwwwwwww

**Comment by shashiranjansingh** [comment]
hello how are you

**Comment by shashiranjansingh** [comment]
hello how are you
