### ISSUE TITLE
Documentation website is unnecessarily difficult to read

### ISSUE THREAD

**Issue by stefan-krajnik** [facebook/draft-js#2501]
**Do you want to request a *feature* or report a *bug*?**
bug (original issue https://github.com/facebook/draft-js/issues/2494 was closed but not resolved as some of the comments were left ignored)

**What is the current behavior?**
The whole website is basically black and white
<img width="1632" alt="Screenshot 2020-07-17 at 17 06 16" src="https://user-images.githubusercontent.com/16229997/87801342-e51bd700-c84f-11ea-9038-ac23b397422b.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open https://draftjs.org/docs/getting-started

**What is the expected behavior?**
<img width="1636" alt="Screenshot 2020-07-17 at 17 06 29" src="https://user-images.githubusercontent.com/16229997/87801368-ee0ca880-c84f-11ea-8ccf-0eb7b3a1e539.png">

**Comment by ivansivaklepsi** [comment]
I like syntax highlighting with colors as well. Such a good feature!
