### ISSUE TITLE
allow for commands to take arguments?

### ISSUE THREAD

**Issue by ianstormtaylor** [facebook/draft-js#252]
Right now it looks like commands can only be simple strings, things like `undo`, `redo`, `delete-word`, etc. Which works for all of the natively-defined commands, but isn't extensible for "userland" things. For example, I'd like to be able to handle commands in a single spot for inserting images. It seems like it would be nice if I could:

```
handleCommand(command) {
  // insert image logic
}
```

Where command is:

```js
{
  type: 'insert-image',
  src: 'https://...',
  alt: '...',
}
```

I think this would make it easier to decouple and reuse logic (in a plugin-like ecosystem).

---

Along those lines, it seems like the built-in commands for `bold`, `italic`, `underline`, `code` should probably actually be something like `toggle-style` with `data` about what specifically to style. Right now it just so happens to work for them, since all of the necessary data can just be serialized into the command string itself.

**Comment by ianstormtaylor** [comment]
I think I'm still fighting against the fact that Draft isn't architected (yet/almost) as a system that takes transformations (eg. commands) and applies them, resulting in a content state. It seems like it's so close, and that making that change would simplify the way to think about a lot of the logic around `Modifier`s. 

But I feel like I'm still not grokking something about the current architecture, that forces it to be the way it currently is.

**Comment by hellendag** [comment]
In `handleCommand`, I assume you are operating on your `EditorState` with some parameters about what the inserted image should be, and that `handleCommand` lives in your top-level component with access to other areas of your application state.

If so, can't you just obtain the relevant parameters within `handleCommand`? What is the benefit of passing them through from the key binding as a payload?

**Comment by ianstormtaylor** [comment]
Yeah, that's definitely true. Not exactly sure where I was going with this anymore. I think I was thinking along the lines of a plugin ecosystem, since the same "handle in inline in `handleCommand` could be given for the internal library I'd think. But I'll reopen if I figure out a more concrete use case again.
