### ISSUE TITLE
Replace window.prompt in media example

### ISSUE THREAD

**Issue by tasti** [facebook/draft-js#253]
I didn't see https://github.com/facebook/draft-js/issues/91 until now, so I think it's worth switching away `window.prompt` for a regular input like https://github.com/facebook/draft-js/pull/110.

**Comment by hellendag** [comment]
Yeah `window.prompt` is terrible. :)

**Comment by mitermayer** [comment]
This has been fixed on https://github.com/facebook/draft-js/commit/8099c0d34823de81d88b03304e0794ef2a855ced
