### ISSUE TITLE
don't apply `CODE` styles to `code-block` blocks

### ISSUE THREAD

**Issue by ianstormtaylor** [facebook/draft-js#254]
It looks like right now `CODE` style ranges are being applied to everything inside of the `code-block` blocks, but I think these two things should be separated. 

The `CODE` inline range could have things like borders, paddings, etc. applied to them, and if they do then they break `code-blocks` styles (which have to be removed with `!important`). Instead, I think people should just apply the same `font-family` (and whatever else they want) to the `code-block` block in addition to the `CODE` range.

**Comment by hellendag** [comment]
Where are you seeing this? The inline range should not be automatically applied to `code-block` elements at all.

**Comment by hellendag** [comment]
I'm not able to repro on the draftjs.org example editor.

- Create a block of text, make it a code block
- Select some text, make it monospace.

Behavior appears correct to me.

**Comment by ianstormtaylor** [comment]
Ah shoot, sorry you're totally right, I forgot to check this one against the demo. Was serializing both `code` and `pre > code` but in the wrong order, all `pre > code` were also getting the styles always.
