### ISSUE TITLE
Decorator docs - "these aren't very good regexes, don't use them!" - Why?

### ISSUE THREAD

**Issue by vlopp** [facebook/draft-js#2549]
[The decorator docs](https://draftjs.org/docs/advanced-topics-decorators) include an example of decorator usage to highlight handles and hashtags. In a block of code, it's written:
```
// Note: these aren't very good regexes, don't use them!
const HANDLE_REGEX = /\@[\w]+/g;
const HASHTAG_REGEX = /\#[\w\u0590-\u05ff]+/g;
```

Why are these not very good regexes? Is it something performance-related?

I know this is not a DraftJS question, just providing links for any further regex-related reading for me would be highly appreciated.

**Comment by waynegerard** [comment]
Hey @vlopp!

Mostly they're just not very accurate.

For example:

`const HANDLE_REGEX = /\@[\w]+/g;` will also match email domains (e.g. it'll match `bar` in `foo@bar.com`)
`const HASHTAG_REGEX = /\#[\w\u0590-\u05ff]+/g` will match anything with a `#` symbol in it (for example, `"I'm #1!"`)

Neither of which is probably great for user-entered data.

**Comment by waynegerard** [comment]
Closing, let me know if you have additional questions :).
