### ISSUE TITLE
Cmd+A does not work in Firefox

### ISSUE THREAD

**Issue by johanneslumpe** [facebook/draft-js#257]
When selecting the whole editor contents using `Cmd+A` in Firefox, both the anchor and focus node will be the the wrapping div for the editor content, not text nodes. Firefox will then fail with a `Error: Got unexpected null or undefined`.

The result of this is that the browser will show the selection across all blocks, but when actually pressing a key, the content will be added/removed at the previous cursor position.

**Comment by hellendag** [comment]
Damn. This used to work properly. https://github.com/facebook/draft-js/blob/master/src/component/selection/__tests__/getDraftEditorSelection-test.js#L1158

Exactly which wrapper element is selected when this happens?

**Comment by johanneslumpe** [comment]
The one with the `public-DraftEditor-content` class.

**Comment by johanneslumpe** [comment]
@hellendag The release of `0.4.0` got rid of this bug. I think it only happened with custom blocks and that was probably related to them not having an editor key set.
