### ISSUE TITLE
How should `convertFromHTMLToContentBlocks` process media tags ?

### ISSUE THREAD

**Issue by filod** [facebook/draft-js#260]
`convertFromHTMLToContentBlocks` simply ignore media contents for now.  this is obviously not what i want.

to my knowledge, draft.js suggest to provide media through `Block` type, but img/video/etc..  are often inline tags in DOM .

of course i can return a chunk in `convertFromHTMLToContentBlocks ==> genFragment`:
```javascript
function genFragment(...) {
...
  if (nodeName === 'img') {
    return {
      text: '\r \r',
      inlines: [],
      entities: [],
      blocks: [{
        type: 'media',
        src: node.src,
        depth: depth
      },{
        type: 'unstyled',
        depth: depth
      }]
    }
  }
...
}
```
but this code makes me feel tricky, don't know if it is right, should `convertFromHTMLToContentBlocks` provide some hooks to allow customization of `html => ContentBlocks`?

Any thoughts on this?

**Comment by hellendag** [comment]
You may wish to create your own HTML conversion utility. Feature support that may be obvious to some is unnecessary for others. In this case, the limit of this conversion utility is the feature set that we have required at Facebook, as I would not have wanted to open source anything we aren't using in production.

`convertFromHTML` is just an exposed version of our paste processor, and is not currently expected to handle all possible use cases.

That said, #205 will provide more flexible support for mapping HTML tags to block types.

**Comment by filod** [comment]
thanks for reply.

for those who want know how to handle media content in `convertFromHTML`, see this [naive implementation](https://github.com/shengupiao/draft-js/commit/064a16e145e669a41870669e1b4e1ed3785b4bcc)
