### ISSUE TITLE
Trigger onChange only when content or style changed?

### ISSUE THREAD

**Issue by adsee42** [facebook/draft-js#2624]
#### Do you want to request a *feature* or report a *bug*?

feature

#### What is the current behavior?

`onChange` is triggered when content or styles change, but also triggered when select or cursor change.

#### What is the expected behavior?

I would like to the `onChange` to only triggered for content or style changes.
Is there any workaround?

**Comment by laxminarayana-endugapally** [comment]
https://stackoverflow.com/questions/40911570/draftjs-triggers-content-change-on-focus

**Comment by laxminarayana-endugapally** [comment]
> #### Do you want to request a _feature_ or report a _bug_?
> feature
> 
> #### What is the current behavior?
> `onChange` is triggered when content or styles change, but also triggered when select or cursor change.
> 
> #### What is the expected behavior?
> I would like to the `onChange` to only triggered for content or style changes.
> Is there any workaround?

https://stackoverflow.com/questions/40911570/draftjs-triggers-content-change-on-focus

**Comment by mrkev** [comment]
In the Draft.js model, editor state refers to the whole state of the editor, though we do separate the data structure between content, selection, etc. The post @laxminarayana-endugapally is spot on with their example, you can achieve this with an if-statement on your `onChange` event (: Overall, erring on the side of keeping the model simple is what we're shooting for here so I'm afraid we won't add a separate callback.
