### ISSUE TITLE
`focus` missing from Editor component API documentation

### ISSUE THREAD

**Issue by remko** [facebook/draft-js#263]
The 'Managing focus' guide mentions `Editor` having a `focus` method, but it's not in the API docs.

**Comment by hellendag** [comment]
Cool, thanks -- I'll take a PR for it. :)

**Comment by remko** [comment]
>  I'll take a PR for it

Your kindness knows no bounds.

I hope I made up for my drive-by-shooting-issue-report (I was in the middle of debugging, and didn't want to forget about it) by doing a little extra in the PR. 🐶
