### ISSUE TITLE
Editor duplicates typed text and retains caret at 0 position in Firefox 

### ISSUE THREAD

**Issue by izkrivera** [facebook/draft-js#2658]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What is the current behavior?

Editor duplicates typed text and retains caret at 0 position in Firefox only. In Chrome and Safari it behaves as expected.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

https://codesandbox.io/s/quirky-antonelli-u7sy9?file=/src/index.js

1) Open sandbox in Safari or Chrome and type in the outlined editor: "Hello World!". The editor displays: "Hello World!".
2) Open sandbox in Firefox and type in the outlined editor: "Hello World!". The editor retains caret at 0 and displays:
"!dlroW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHoW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHroW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHoW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHlroW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHoW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHroW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHoW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHdlroW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHoW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHroW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHoW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHlroW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHoW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHroW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHoW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH!dlroW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHoW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHroW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHoW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHlroW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHoW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHroW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHoW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHdlroW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHoW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHroW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHoW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHlroW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHoW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHroW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHoW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHHW olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH olleHHeHHleHHeHHlleHHeHHleHHeHHolleHHeHHleHHeHHlleHHeHHleHHeHH!".

#### What is the expected behavior?

Draft editor should display "Hello World!" as in other browsers.

#### Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?

 "draft-js": "^0.11.7",
 "preact": "^10.4.8",
 "@babel/core": "^7.11.6",
 "webpack": "^4.44.1",

**Comment by jamespantalones** [comment]
I'm having a similar issue with Firefox. Was going to say, your sandbox does not include the required `Draft.css`, so was wondering if that was it, but the issue appears to linger despite adding the CSS.

**Comment by izkrivera** [comment]
> I'm having a similar issue with Firefox. Was going to say, your sandbox does not include the required `Draft.css`, so was wondering if that was it, but the issue appears to linger despite adding the CSS.

If you look at the Draft CSS is just default styling for the editor content. It is not functional and unnecessary. Again, it works on Chrome and Safari and even mobile, just not Firefox.

I have  seen similar reports but on not English implementations.

**Comment by mrkev** [comment]
The issue here is Preact— unfortunately React and Preact share the same developer API, but don't work in the same way under the hood. I don't know exactly the source of the issue is, but the way React schedules events/rendering/etc matters more in Draft.js than for other components since we're dealing with `contenteditable` modifying the DOM directly a lot here.

Maybe on the Draft.js there's things we could do differently (and perhaps better). Maybe a side-effect of this is that Draft might work with Preact in Firefox. Unfortunately, for the time being, explicitly supporting Preact is not planned.
