### ISSUE TITLE
SideToolbarEditor

### ISSUE THREAD

**Issue by aliplutus** [facebook/draft-js#2659]
#### verstions
```
"draft-js": "^0.11.7",
 "draft-js-buttons": "^2.0.2",
"draft-js-plugins-editor": "^3.0.0",
    "draft-js-side-toolbar-plugin": "^3.0.2",
    "draft-js-static-toolbar-plugin": "^3.0.1",
````

**Comment by thibaudcolas** [comment]
@aliplutus you should report this to https://github.com/draft-js-plugins/draft-js-plugins, where the side toolbar package is maintained, not here.

**Comment by aliplutus** [comment]
> @aliplutus you should report this to https://github.com/draft-js-plugins/draft-js-plugins, where the side toolbar package is maintained, not here.

I can't click the submit button there!

**Comment by waynegerard** [comment]
Hi there, as @thibaudcolas noted please report this to the plugins repo instead.
