### ISSUE TITLE
Error in Documentation Regarding Advanced Topics - Entities

### ISSUE THREAD

**Issue by wdfinch** [facebook/draft-js#2669]
In the documentation, the example line is presented.

`
const newEditorState = EditorState.push(editorState, {
  currentContent: contentStateWithLink,
});
`

However, this is incorrect. The method called by EditorState should be set rather than push. The push method has a different method signature.

**Comment by dwjohnston** [comment]
Yeah I saw that. Submit a PR?

**Comment by waynegerard** [comment]
Hey there @wdfinch, this should be fixed now!

**Comment by waynegerard** [comment]
Closing, this should be fixed. Thanks for reporting :).
