### ISSUE TITLE
hey I think this might be a solution to me as well but any chance u could try explaining ur code to me?

### ISSUE THREAD

**Issue by Hello-Reed** [facebook/draft-js#2679]
@aslamanver  Good to see that I'm not the only one in 2020 ;) 
here's my workaround for that problem 
my dependencies 
```
import MUIRichTextEditor from 'mui-rte';
import { convertFromHTML, ContentState, convertToRaw } from 'draft-js';
import draftToHtml from 'draftjs-to-html';
```
and converting html to editors state (mui-rte requires stringfied object) part:
```
let editorDefaultValue = null;
if (initialData?.text) {
    const contentHTML = convertFromHTML(initialData.text);
    const state = ContentState.createFromBlockArray(contentHTML.contentBlocks, contentHTML.entityMap)
    const raw = convertToRaw(state);
    const { blocks, entityMap } = raw;

    const fixedBlocks = blocks.map((block) => {

      return {
        ...block,
        type: block.text === '📷' ? 'atomic' : block.type
      }
    })

   const fixedEntityMap = {}
    for (const [key, value] of Object.entries(entityMap)) {
      if (value.type === 'IMAGE') {
        value.data.url = value.data.src
      }

      fixedEntityMap[key] = value;
    }

    editorDefaultValue = JSON.stringify({
      blocks: fixedBlocks,
      entityMap:fixedEntityMap
    });
  }
```

I know that might be discussable to rely on emoji comparison, but at least it works for now ;)  
And fixing entities is because somehow editor displays images src from 'url' property.

_Originally posted by @KubaZachacz in https://github.com/facebook/draft-js/issues/818#issuecomment-695799397_

**Comment by waynegerard** [comment]
Hey there! I'm guessing you meant to comment in the other thread, so I'm going to close out this issue for now :). If I made a mistake, please let me know!
