### ISSUE TITLE
Aggressive Warning

### ISSUE THREAD

**Issue by yepnamesjames** [facebook/draft-js#27]
> Warning: A component is `contentEditable` and contains `children` managed by React. It is now your responsibility to guarantee that none of those nodes are unexpectedly modified or duplicated. This is probably not intentional.

Is this needed for every onChange? Seems to do justice just on the component mounting.

Ps. This project made my day.

**Comment by hellendag** [comment]
Yeah, this is tracking on the React repo: https://github.com/facebook/react/issues/5837

> Ps. This project made my day.

:D
