### ISSUE TITLE
`&#13` (Carriage Return from xml entity) will break `convertFromHTML`

### ISSUE THREAD

**Issue by filod** [facebook/draft-js#274]
when i use jsdom to process html => dom, 
some weird html page will have this issue (which claim they are html doc but return with some XML entities).

perform these changes solved my issue with `convertFromHTML`:
```javascript
html = html.trim().replace(REGEX_CR, '').replace(REGEX_NBSP, SPACE);
```
to
```javascript
var XML_RETURN = new RegExp('(&#13;|&#13)', 'g');
...
html = html.trim().replace(REGEX_CR, '').replace(REGEX_NBSP, SPACE).replace(XML_RETURN, '');
```

for time reason, i have not dive into this too much (other cases like ZERO WIDTH SPACE may break this too?). Just create this issue as a reminder for people who encounter same problem.

further reading: 
https://github.com/facebook/draft-js/blob/master/src/model/encoding/convertFromHTMLToContentBlocks.js#L374
http://stackoverflow.com/questions/1459170/what-is-13

**Comment by hellendag** [comment]
Seems like this fix might be worth adding. cc @CLowbrow
