### ISSUE TITLE
[HELP] How do I retain focus on the selected content after a style is applied?

### ISSUE THREAD

**Issue by swaathi** [facebook/draft-js#275]
I'm trying out the basic implementation of DraftJS with Rich styles. When I select a word and apply a style to it (like bold/italics), it applies it. But it loses the selected text (the word is not selected anymore). If I click on the editor region, it selects it again. 

I don't see a similar workflow when I try the examples. So I'm pretty sure I'm missing something, but I don't know what. Is there something I should do to retain the selected content?

**Comment by guitardave24** [comment]
Are you applying a style with a mouse click that's changing focus
after? You could try prevent default in the click handler where you apply
the style.

**Comment by swaathi** [comment]
Nope. I'm using a `onMouseDown` on a span element to apply the style.

**Comment by hellendag** [comment]
I suggest using `preventDefault` on the mousedown event.

**Comment by swaathi** [comment]
Thanks so much! This cleared it up right away. :+1: :smile:

**Comment by thaoms** [comment]
The preventdefault fix doesn't work anymore in 0.11
