### ISSUE TITLE
Spellchecking related changes remove entities

### ISSUE THREAD

**Issue by johanneslumpe** [facebook/draft-js#277]
I just noticed that when I have an entity applied to a range and then use the browser's spellchecking functionality to change a word, the entity is removed. PR to fix this issue: https://github.com/facebook/draft-js/pull/276

**Comment by hellendag** [comment]
Let's be sure this works as expected for all mutability types, as discussed in Slack. :)

**Comment by johanneslumpe** [comment]
@hellendag It works for `MUTABLE` and `SEGMENTED` but it fails for `IMMUTABLE`. For `IMMUTABLE` I assume we'd want to remove the entity when a change occurs - right now it keeps it even though the text changes.

**Comment by hellendag** [comment]
@johanneslumpe I think that's correct, yeah. If it's an `IMMUTABLE` entity, setting `null` is probably more appropriate.

**Comment by johanneslumpe** [comment]
@hellendag With the latest commit the entity gets removed correctly if it is `IMMUTABLE`, but when using `ctrl+z` to undo it, the block content is copied from the beginning of the entity to the end of the block and applied to the end of it. A gif might explain it better:

![immutable_broken](https://cloud.githubusercontent.com/assets/3470207/14439737/5884def4-0035-11e6-9ebf-cc8bc4c672d8.gif)

**Comment by hellendag** [comment]
Does your current PR commit resolve the issue above?

**Comment by johanneslumpe** [comment]
Unfortunately it does not. I haven't yet been able to figure out what the issue is with immutable entities and undo.

**Comment by johanneslumpe** [comment]
@hellendag Thinking about this more: I just fun for re-read the explanatory text in the gif above. And in that case we shouldn't remove the whole entity but only from a sub-range?

**Comment by hellendag** [comment]
If a character is added within an entity:

- `IMMUTABLE` entity: remove the entity, insert the character
- `SEGMENTED` entity: same as above

If a character is deleted within an entity:

- `IMMUTABLE`: remove entire entity string
- `SEGMENTED`: remove segment of string, delimited by whitespace

To see this in action, use a Facebook input and mention two things: 1) a Page and 2) a friend. Pages are `IMMUTABLE`, and friends are `SEGMENTED`.

**Comment by johanneslumpe** [comment]
@hellendag The culprit for the weird insertion at the end of the content is this:

https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/commands/keyCommandUndo.js#L28

If we let the browser handle the undo, then it will insert the content at the end of the block due to the changed DOM structure I believe because it cannot figure out where to put it. When I removed that part, the undo feature worked fine, which would mean that I only need to fix segmented entities as they currently do get partially removed when a character within them is removed.

Let me know what your thoughts on this one are. I personally think that correct handling of entities is more important than trying to have the browser not suggest a change again.

**Comment by hellendag** [comment]
Ah, that makes sense. Nice sleuthing.

I think you can get around this by using `apply-entity` as the `EditorChangeType` (instead of `spellcheck-change`) in editOnInput.js, for the `SEGMENTED` and `IMMUTABLE` cases. This way, when undo occurs, it will not fall through to the browser.

**Comment by johanneslumpe** [comment]
@hellendag Check out the latest version of https://github.com/facebook/draft-js/pull/276 - I think I fixed all possible cases for entities!
