### ISSUE TITLE
Remove all inline styles from current block

### ISSUE THREAD

**Issue by heymath** [facebook/draft-js#278]
Hi there!

I did not find a Util function that allows to remove all inline styles from a block. **Did I miss it?**

Anyway I tried to do it myself, and I went to something like below ; but this seems to work only if there is a non-collapsed selection in the current block :disappointed: 

```javascript
const { Editor, EditorState, Modifier, RichUtils } = Draft;

// ...

function removeInlineStyles (editorState, inlineStyles) {
  const selection = editorState.getSelection();
  const nextContentState = Object.keys(inlineStyles)
  .reduce((contentState, style) => {
    return Modifier.removeInlineStyle(
      contentState,
      selection,
      style
    );
  }, editorState.getCurrentContent());

  return EditorState.push(
    editorState,
    nextContentState,
     'change-inline-style'
  );
}

class TestEditor extends React.Component {
  // ...
  _changeBlockType (type) {
    const nextEditorState = RichUtils.toggleBlockType(
      this.state.editorState,
      type
    );
    this.onChange(
      removeInlineStyles(nextEditorState, INLINE_STYLES)
    );
  }
}
```

If someone understand why, I would love to know :smile:  

And could / should this be added to Draft as a Util / Modifier function?
I am needing it because in my case, each block type has its own inline styles basically. So we do not want that some inline styles from a "paragraphe" becomes applied to a "title" if the user change the block type from "paragraphe" to "title". To keep it simple, this implies that if user change it back to "paragraphe", inline styles are lost.
I think this could be usefull for many cases anyway.

PS: thanks for everybody's work on Draft and making this open source :)
BTW I am in holidays for 2 weeks starting tomorrow and probably won't be available (Vietnam) so do not take it bad if I do not reply for some days :)

**Comment by guitardave24** [comment]
Haven't tested this, but maybe try calling `Modifier.replaceText` passing in the string that already exists and `null` for inlineStyle param?

**Comment by johanneslumpe** [comment]
@heymath To be sure that all inline styles for the whole block get reset you could create a new `SelectionState` for the block which is changed, by using the `anchorKey` of the original selection, if it is collapsed. Then you can span from 0 to `block.getLength()` and have `anchorKey` and `focusKey` be the same block. Then you can use this selection to remove inline styles for all characters in the block.

In order to reset everything (inline styles AND entities) you can just set the block's `CharacterList` to new one without styles:

`List(Repeat(CharacterMetadata.create(), textLength))`

If you have entities which you want to keep, then you will have to loop over the character list and just reset the `style` prop of each character:
```js
const characterList = block.getCharacterList();
const updatedCharacterList = characterList.map(c => (
  c.set('style', c.get('style').clear())
));

const updatedBlock = block.set('characterList', characterList);
```

**Comment by heymath** [comment]
Thank you very much guys! I will try this right after my holidays, that should be OK :)

**Comment by hellendag** [comment]
Both suggestions here should work. :)

**Comment by dictions** [comment]
For anyone looking in the future:

```js
const clearInlineStyles = editorState => {
  const styles = [
    'BOLD',
    'ITALIC',
    'UNDERLINE',
    'STRIKETHROUGH',
    'CODE'
  ];
	
  const contentWithoutStyles = _.reduce(styles, (newContentState, style) => (
    Modifier.removeInlineStyle(
      newContentState,
      editorState.getSelection(),
      style
    )
  ), editorState.getCurrentContent());
	
  return EditorState.push(
    editorState,
    contentWithoutStyles,
    'change-inline-style'
  );
};
```

**Comment by andpor** [comment]
@dictions - this should be in draft by default...plain and simple feature and clean code. I would suggest a PR...

**Comment by andpor** [comment]
@hellendag - why did you close the issue? Is this feature (a standard for any editor with text styling feature) already part of DraftJS???

**Comment by Ciantic** [comment]
In my project I don't want any of the inline stylings (and whitelisting the block elements that is allowed), I would presume this is pretty common in simplest use cases for the draft-js.

This leads to the second question, what is performant way to do this? It's probably a difficult thing to answer and having a canonical and documented way to "disable" inline styles would be preferable.

There is now two, but I'm pretty sure there is some other ways too. @dictions approach seems to be relying on listing all the styles (which seems fragile), but is probably more performant. @johanneslumpe approach seems more generic since one does not need to list the different styles, but is looping characterList a slow process?

**Comment by ArteroWeb** [comment]
I've solved it this way (it might be an outdated question, sorry if it's the case) :

`  const handleClearInlineFormatting = () => {
    const newContentState = [
      editorState.getCurrentContent(),
      ...INLINE_STYLES,
    ].reduce(( contentState, style ) => {
      return Modifier.removeInlineStyle(
        contentState,
        editorState.getSelection(),
        style
      );
    });
    setEditorState(EditorState.createWithContent(newContentState));
  };
`

**Comment by fatima-gloqal** [comment]
it doesnt remove styles for span elements

**Comment by geporys** [comment]
I think it is the best approach because it can delete styles from several rows 

`const selectionState = editorState.getSelection();

        const currentContent = editorState.getCurrentContent();

        const start = selectionState.getStartOffset();
        const end = selectionState.getEndOffset();

        let text = "";

        const startKey = selectionState.getStartKey();
        const endKey = selectionState.getEndKey();

        const contentStart = currentContent.getBlockForKey(startKey);

        const contentStartText = contentStart.getText();

        text = contentStartText.slice(
          start,
          startKey === endKey ? end : contentStartText.length
        );

        let nextKey = startKey;

        while (nextKey !== endKey) {
          nextKey = currentContent.getKeyAfter(nextKey);

          const contentEnd = currentContent.getBlockForKey(nextKey);
          const contentText = contentEnd.getText();

          text = `${text} ${
            nextKey === endKey ? contentText.slice(0, end) : contentText
          }`;
        }

        const contentWithoutStyles = Modifier.replaceText(
          editorState.getCurrentContent(),
          selectionState,
          text
        );

        onChange(
          EditorState.push(
            editorState,
            contentWithoutStyles,
            "change-inline-style"
          )
        );`

**Comment by mista3** [comment]
I've done it like that. Removes all styling, inline and block

```
import { EditorState, Modifier, RichUtils } from 'draft-js';

export const clearAllStyles = (editorState: EditorState) => {
  let contentState =
    RichUtils.tryToRemoveBlockStyle(editorState) ??
    editorState.getCurrentContent();
  const selection = editorState.getSelection();
  editorState
    .getCurrentInlineStyle()
    .toArray()
    .forEach((style) => {
      contentState = Modifier.removeInlineStyle(contentState, selection, style);
    });
  return EditorState.push(editorState, contentState, 'change-inline-style');
};
```
