### ISSUE TITLE
convertFromRaw returns an Array of ContentBlocks not a ContentState

### ISSUE THREAD

**Issue by dustin-H** [facebook/draft-js#28]
Hi there,

As documented [here](https://facebook.github.io/draft-js/docs/api-reference-data-conversion.html#content) the function `convertFromRaw` should return a `ContentState` object. 

However it returns an array of `ContentBlock` objects.

**This works:**
```js
var data = '{"entityMap":{},"blocks":[{"key":"4oah6","text":"Dieser Test","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":7,"length":4,"style":"BOLD"},{"offset":0,"length":11,"style":"CODE"},{"offset":0,"length":6,"style":"ITALIC"}],"entityRanges":[]}]}'

var json = JSON.parse(data)

var blockArray = convertFromRaw(json);

var contentState = ContentState.createFromBlockArray(blockArray);

var editorState = EditorState.createWithContent(contentState);
```

**However this throws an error:**
```js
var contentState = convertFromRaw(json);

var editorState = EditorState.createWithContent(contentState);
```

**Error:**
<img alt="screen shot 2016-02-23 at 00 56 54" src="https://cloud.githubusercontent.com/assets/6003519/13236988/6c2ea194-d9c8-11e5-9dc9-35c41d527f25.png">

Is this a mistake in the docs or a bug?

**Comment by hellendag** [comment]
Great catch. It's a mistake in the docs.

**Comment by dustin-H** [comment]
Ok, thanks... PR is in progress ;)

**Comment by maksimsemenov** [comment]
Hi there,

There is still mistake in the docs: https://facebook.github.io/draft-js/docs/api-reference-data-conversion.html#content

convertFromRaw(rawState: RawDraftContentState): ContentState

**Comment by dustin-H** [comment]
Where? Can't find it.

**Comment by maksimsemenov** [comment]
Here is a screenshot of this page: https://facebook.github.io/draft-js/docs/api-reference-data-conversion.html#content

I marked the mistake with the red rectangle
![group](https://cloud.githubusercontent.com/assets/3608139/14906894/d31150ba-0d8e-11e6-8b9f-c057a8a1cd3c.png)

**Comment by dustin-H** [comment]
What do you think should be there?

**Comment by maksimsemenov** [comment]
From conversation above instead of **ContentState** there should be array of **ContentBlocks**

**Comment by dustin-H** [comment]
Ah, now I see. I had fixed this in [PR](https://github.com/dustin-H/draft-js/commit/aa48ab74736d5687c7acb58256c24fd647227c90). 

However, it was changed it back by @hellendag [here](https://github.com/facebook/draft-js/commit/d8823c95eb3488b491fd05b909666db190d32d96)

This was because the return type has changed [here](https://github.com/facebook/draft-js/commit/844b85e6576b0575a716bbfe0381336737482b53).

In PR #333 it was discussed a bit.

So docs are correct.

**Comment by maksimsemenov** [comment]
Oh, thanks. I used a 0.5.0 version and it was returning an array of ContentBlocks, so I thought that there is a mistake in docs. Now, after I've updated to 0.6.0 it works fine.
