### ISSUE TITLE
Apparent issue with focusing the editor when using functional component

### ISSUE THREAD

**Issue by AlonBru** [facebook/draft-js#2803]
#### Do you want to request a *feature* or report a *bug*?
*bug*
#### What is the current behavior?
when using 
#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. 

[*demo*](https://jsfiddle.net/wqora7pc/22/)  
using draft in a functional component, use and outside button to change inline style.  
this works but does not refocus the editor.  
using a ref, I came up with two solutions:
1.  call `ref.current.focus()` onclick after the style change:  
 refocuses but does not change the style.
2. call it in useLayoutEffect /useEffect on editorState change:  
  seems to generally work, with minor bug: if you set the style before writing anything the button won't remove it.  
  however once you start writing this should be ok.  
  also there seem to be other issues sometimes when adding, removing and combining inline styles, block styles seem to be fine, presumably because they are mutually exclusive.
  this also makes it impossible to focus out, if #2804  is correct than it's because onChange is triggered on focus change

#### What is the expected behavior?  
hopefully style change functions should refocus the editor (as I think they do in class components but I may be mistaken) or at least fix what causes the bug in option 2.
#### Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?
I'm working on Windows, Chrome, latest draft-js.

**Comment by hvc02** [comment]
https://dev.to/rose/draft-js-introduction-custom-styles-highlighted-text-and-have-formatting-buttons-show-whether-they-are-on-or-off-4f9p
refer to this blog series it might be helpful.

**Comment by AlonBru** [comment]
thanks for the offer, it seems useful and I'll be sure to dive into it, but on a quick scan the term "focus" is not mentioned.

**Comment by AlonBru** [comment]
https://dev.to/rose/rich-text-editing-on-the-web-getting-started-with-draft-js-2f68

However, the first page did contain the word 'blur', and it solved my problem.
thanks!
