### ISSUE TITLE
Backspace doesn't delete image entity

### ISSUE THREAD

**Issue by gigiskarlett** [facebook/draft-js#2857]
#### Do you want to request a *feature* or report a *bug*?
Bug
#### What is the current behavior?
When I press on backspace it ignores the image and removes everything else
#### What is the expected behavior?
For the image to be deleted 
#### Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?
https://cdnjs.cloudflare.com/ajax/libs/draft-js/0.10.0/Draft.js

**Comment by thibaudcolas** [comment]
Most likely this is the same issue as #1354, #915, #483, (https://github.com/facebook/draft-js/issues/1681#issuecomment-371087387). 

See https://github.com/facebook/draft-js/issues/1510#issuecomment-473718477 for a solution.
