### ISSUE TITLE
[HELP] How do I require MediaUtils?

### ISSUE THREAD

**Issue by swaathi** [facebook/draft-js#289]
I'm trying to play around with image embedding in DraftJS and followed the examples in the repo. MediaUtils seemed to be similar to requiring RichUtils, but when I tried that, I keep running in to `undefined`. I tried searching thought the source and found that there are bindings to RichUtils but nothing for MediaUtils. Like here,

```
  Modifier: DraftModifier,
  RichUtils: RichTextEditorUtil,

  convertFromHTML: convertFromHTMLToContentBlocks,
  convertFromRaw: convertFromRawToDraftState,
```

This is how I require RichUtils, `var RichUtils = Draft.RichUtils;`. But when I try to do the same for MediaUtils it doesn't work. What am I missing?

**Comment by max-mykhailenko** [comment]
MediaUtils (AtomicUtils in master) are not in npm yet. Maybe on the next Tuesday. Now you can get it in master

**Comment by swaathi** [comment]
Oh man! Thank you. :+1: So I need to do something like `var AtomicUtils = Draft. AtomicUtils;` to get MediaUtils, right?

**Comment by max-mykhailenko** [comment]
Look at example https://github.com/facebook/draft-js/blob/master/examples/media/media.html#L31-L38

**Comment by swaathi** [comment]
Thanks!
