### ISSUE TITLE
A read-only editor has problems of focus (caret)

### ISSUE THREAD

**Issue by akkadaska** [facebook/draft-js#2891]
#### Do you want to request a *feature* or report a *bug*?
Feature or question.
#### What is the current behavior?
I'm tring to put 2 editors on the same page.
One is the read-only editor which shows the same content as another editor.
However, it doesn' work as I expected.

1. When a new block is inserted (typing the first letter or or inserting new line) on the editable editor, the focus goes somewhere (maybe it gose to the read-only editor), in Chrme.
2. In Firefox, the focus also often goes somewhere when type a letter.
3. The read-only editor doesn't always update when its editorState updates. It updates only when the focus leaves from editable editor.

This is the code.

    class TwoEditors extends React.Component {
        constructor(props) {
            super(props);
            this.state = {commonEditorState: EditorState.createEmpty()};
            this.handleChange = this.handleChange.bind(this);
        }
        handleChange(content) {
            this.setState({commonEditorState: content});
        }
        render() {
            return (
                <div>
                    {/* Editable Editor */}
                    <Editor editorState={this.state.commonEditorState} onChange={this.handleChange} />
    
                    {/* Read-only Editor */}
                    <Editor editorState={this.state.commonEditorState} onChange={() => {}} readOnly />
                </div>
            );
        }
    }

#### What is the expected behavior?
When the editor is read-only, it should not get focused and should always update when its editState updates.
Is there any way to get it works like this? 

#### Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?
Draft.js 0.11.7
Google Chrome 89.0.4389.114 (Official Build)  (64 bit) and Mozilla Firefox 87.0 (64 bit)
Windows 10

**Comment by vlad-fylymonov** [comment]
please tell me, did you manage to solve this problem?
