### ISSUE TITLE
Incorrect values with getVisibleSelectionRect under certain selection circumstances?

### ISSUE THREAD

**Issue by deep-c** [facebook/draft-js#290]
Hi,

I am attempting to create a floating toolbar which shows on text selection. I read through a similar issue #45 and noted the use of getVisibleSelectionRect(). This works for the most part but as you can see in the video below there are a couple of strange issues I've encountered.

https://www.youtube.com/watch?v=eHTj7F62S7g

The toolbar is included as a seperate component to the `Editor`.
### TextEditor.js

```
      <div styleName="container">
          <Toolbar
            editorState={editorState}
            onChange={this.onEditorChange}
            boundingRect={boundingRect} />
          <Editor
            editorState={editorState}
            onChange={this.onEditorChange}
            customStyleMap={styleMap}
            placeholder="Enter your text.." />
      </div>
```

The condition ive used to hide and show the toolbar is this:
### Toolbar.js

```
const boundingRect = getVisibleSelectionRect(window); (passed from parent component)
const selectionState = editorState.getSelection();

if (boundingRect && !selectionState.isCollapsed() && selectionState.getHasFocus()) {
      var toolbar =
        <div
          styleName="container"
          style={{top: boundingRect.top, left: boundingRect.left + boundingRect.width/2}}>
            ...buttons
        </div>
}

//which is returned in render
    return (
      <span>
        {toolbar}
      </span>
    )
```

```
.container {
  position: fixed;
  transform: translate3d(-50%, calc(-100% - 5px), 0);
  max-width: 300px;
  z-index: 80;
}
```
### Environment

Ive tested on Chrome on both my window and mac machines which show identical issues. I'll test the same on firefox and safari and post my findings here later today.
### Issue 1 (can be seen in the vid from ~30s to end)

Selection of text from the start/end of any line except the first/last (i.e last word) results in the width value returned from the boundingRect being larger than the selection (as you can in the vid the toolbar seems to hover in the middle of the line which seems like the width being returned is that of the entire line instead of the just the selection? 
Ive noticed that this is sometimes intermittent on the last word of a line and might have something to do with a space character being included as part of double clicking a specific word. As for why it happens on the first word of a line (apart from first) I havent noticed anything concrete.
### Issue 2 (can be seen in the vid from 0 - ~ 30s)

Double clicking on any word and then taking focus away from the editor and then clicking into the editor again results in incorrect boundingRect values. This can be seen in the vid where for example I select the word `Female` click once outside the editor and then click within the editor to gain focus again. As you can see the boundingRect values seems to not correlate to the selection.
**Possible solution to this issue?** On editor blur reset cursor to nothing (0) or end of content? I dunno if this would be appropriate.

I havent had much experience yet with the selection API (and just started getting to know draft-js which is awesome btw) so maybe im missing some piece of the puzzle.

Thanks!

**Comment by hellendag** [comment]
Thanks for the details and the video. It would help if you could add time information to the two issues so that I know exactly what to look for at what time.

A couple questions:

- Is this on Windows? I wouldn't assume that would cause issues, but it's worth checking.
- Is Toolbar.js rendered with a decorator, or independent of `Editor`? (The latter is **strongly** preferred for positioning/behavior simplicity.)

**Comment by deep-c** [comment]
Hi Isaac,

Ive amended, and thanks for taking a look. Also of note in @bkniffler awesome work here http://draft-wysiwyg.herokuapp.com/ I can reproduce the second issue but not the first.

Thanks

**Comment by shalanah** [comment]
Working on a prototype I ran into a similar issue. Since `getVisibleSelectionRect` will find any selection (within or outside of the editor) it still might have data from a selection outside of the editor's text editing div. As a fix for now, I'm checking that the coordinates from `getVisibleSelectionRect` are within my text editing div before displaying an inline toolbar.

**Comment by ayal** [comment]
I see a similar behavior (Chrome on Mac) where if selecting the first word (or letter) of a line, the rect returned by getVisibleSelectionRect is a rect containing the previous line. The actual "getClientRects()" returns one rect which would work better for displaying a menu (the second), but it's not the one returned by "getVisibleSelectionRect". Of course, always choosing the last rect would break something else :/

BTW, this happens on the "Notes" editor as well (Chrome on Mac)

**Comment by spicyj** [comment]
In a different function I ignore ranges of width 0 or 1:

https://github.com/facebook/draft-js/blob/60b6538f83d4b3a1d293421759255c3104684a7b/src/component/selection/expandRangeToStartOfLine.js#L64
