### ISSUE TITLE
Get the word count like in MS Word and others?

### ISSUE THREAD

**Issue by itsag** [facebook/draft-js#3008]
#### Do you want to request a *feature* or report a *bug*?

Feature

#### What is the current behavior?

There is no way (known to me) to get the word count of the editor.

#### What is the expected behavior?

A plugin or something which allows to get the word count/number of characters currently typed on the editor.

**Comment by derskeal** [comment]
You can use `editorState.getCurrentContent().getPlainText().length`.

**Comment by derskeal** [comment]
You can use `editorState.getCurrentContent().getPlainText()` to get the text content and then perform string split gymnastics to get the word count.
