### ISSUE TITLE
Dependencies deprecated

### ISSUE THREAD

**Issue by ZeGregg** [facebook/draft-js#303]
FYI
```npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.````

```npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.````

```npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.```

**Comment by zpao** [comment]
Thanks for the heads up. These are all warnings from transitive dependencies, but we have a bunch of outdated direct dependencies we should be able to update. Hopefully these go away if we do that.

**Comment by zpao** [comment]
FYI, I'm working on getting some fbjs stuff in order so that we can update the dependencies here more easily, then these should hopefully go away.
