### ISSUE TITLE
How can i truncate pasted text if limit exceeded? 

### ISSUE THREAD

**Issue by Nurtilekk** [facebook/draft-js#3081]
I have problem with pasting text in Draft.js. If user wants to paste a large text with 5000 characters, but i already set maxLength to 4000, user can not paste because this behaviour handled by handledPastedText. That`s why i want to handle this moment and if pasted text exceeds maxLength, draft.js should truncate pasted text to permitted length. Is there any solution ?

**Comment by bryantbrock** [comment]
You might still use `handlePastedText`: it passes you the `html` as the second argument, which you can then truncate at your desire. When you have cut off what you want, pass the remaining html to `convertFromHtml` and update the `editorState` from your `handlePastedText` callback function.

For Example, your `handlePastedText` callback could look something like this (assuming you care about styling)
```js
const handlePastedText = (text, html) => {
    // Handle this better for a cleaner slice,
    // i.e. not in the middle of an html tag
    const truncatedHtml = html.slice(0, 5);

    const blocksFromHTML = convertFromHTML(truncatedHtml);
    const state = ContentState.createFromBlockArray(
      blocksFromHTML.contentBlocks,
      blocksFromHTML.entityMap
    );

    // Set the new editorState
    setEditorState(EditorState.createWithContent(state));

    // Important! Tell draft-js you already handled the pasted text
    return 'handled';
  };
```

Or if you didn't care about the styling, just do
```js
const handlePastedText = (text, html) => {
    // Set the new editorState
    setEditorState(
      EditorState.createWithContent(
        ContentState.createFromText(text.slice(0, 5001))
      )
    );

    // Important! Tell draft-js you already handled the pasted text
    return 'handled';
  };
```

Hopefully this gives you an idea for how you can achieve what you are going for. Cheers!
