### ISSUE TITLE
Is draft-js stabilized now? 

### ISSUE THREAD

**Issue by WinmezzZ** [facebook/draft-js#3091]
More than a year has passed since the last release,it is stabilized now? Any plan with next version ? 

From a draft-js lover.

**Comment by thegreatercurve** [comment]
Added a more detailed message in https://github.com/facebook/draft-js/pull/3136, but, effectively, it's unmaintained.

Internally at Meta, we're migrating all Draft.js instances to our new framework, [Lexical](https://github.com/facebook/lexical).

The APIs aren't 100% compatible, but we're hoping to write a migration guide soon (https://github.com/facebook/lexical/issues/1641).

**Comment by WinmezzZ** [comment]
Lexical looks nice, very intrested to it.
