### ISSUE TITLE
multiline list items don't work via shift-enter

### ISSUE THREAD

**Issue by aleemb** [facebook/draft-js#312]
Other WYSIWYG editors allow multi-line list items by pressing shift-enter, which allows a new line on the same list item but the rich editor example doesn't.

Example from trix:

![image](https://cloud.githubusercontent.com/assets/46616/14561844/9c791634-0332-11e6-826e-c6b415344a5c.png)

**Comment by hellendag** [comment]
You will need to enable soft newlines to support this. By default, <kbd>shift</kbd>+<kbd>enter</kbd> will have the same behavior as <kbd>enter</kbd>. See `RichUtils.insertSoftNewline`, which you can use within `handleReturn`.

**Comment by williamli** [comment]
Sorry for double posting, just trying to leave some breadcrumbs for others who are looking into ways to handle shift-enter in ordered / unordered lists.

I was researching how to handle insertSoftNewline and after around an hour of research, came to across Medium-Draft's insertSoftNewline implementation. 

Their function is over at https://github.com/brijeshb42/medium-draft/blob/master/src/editor.js#L355 with demo at http://bitwiser.in/medium-draft/http://bitwiser.in/medium-draft/.

@aleemb 
I got multi-line list items working and much more working by following their code.
