### ISSUE TITLE
Is DraftJs still supported?

### ISSUE THREAD

**Issue by RafaelZasas** [facebook/draft-js#3130]
### Support for DraftJs long term

There are 768 issues and 166 open Pull Requests at the time of posing this.

The framework has not yet released a major version and hasn't had an update in over two years.

Will this or the docs be updated in the near future?

**Comment by thegreatercurve** [comment]
Added a more detailed message in #3136, but, effectively, it's unmaintained. 

Internally at Meta, we're migrating all Draft.js instances to our new framework, [Lexical](https://github.com/facebook/lexical).

The APIs aren't 100% compatible, but we're hoping to write a migration guide soon (https://github.com/facebook/lexical/issues/1641).

**Comment by RafaelZasas** [comment]
Lexical look awesome! Thank you very much. Looking forward to this refactor and using some of the new features.
