### ISSUE TITLE
Use draftjs.org domain?

### ISSUE THREAD

**Issue by Daniel15** [facebook/draft-js#317]
`github.io` subdomains look pretty tacky - It'd be like a professional company hosting their website on `geocities.com` :smile: 

It looks like you've got the draftjs.org domain but it just redirects to `facebook.github.io/draft-js/`. IMO it'd look nicer to use draftjs.org as the domain for the site.

**Comment by Secretmapper** [comment]
I kinda agree, but I think keeping consistency between all of facebook's open source projects is better?

i.e.
https://facebook.github.io/react/
https://facebook.github.io/relay/
https://facebook.github.io/react-native/

https://facebook.github.io/draft-js/ feels at home.

**Comment by Daniel15** [comment]
That's not actually consistent though - As far as I know, more projects are using proper domains rather than subdomains :smile: 

Some examples:
http://flowtype.org/
http://hacklang.org/
http://hhvm.com/
http://fbinfer.com/
http://nuclide.io/
http://fbredex.com/
http://rocksdb.org/
http://osquery.io/
http://buckbuild.com/
http://frescolib.org/

Especially for projects that already own a domain name (like draftjs.org in this case), it doesn't really make sense to use the tacky subdomain :smile:

**Comment by Secretmapper** [comment]
Ah proved me wrong :smile: For me draft-js still feels at home at github.io domains - that's probably just me being used to react projects having github.io subdomains though. Anyway that's just my two cents, and I don't really have particularly strong views one way or the other.

**Comment by lacker** [comment]
I think the consensus is that this would be handy but it's non-urgent. I'm going to close this issue but if someone at FB wants to volunteer to set this up then I think that would be great ;-)

**Comment by Daniel15** [comment]
>  if someone at FB wants to volunteer to set this up

I'm happy to help, I just don't know who owns the domain. @hellendag Do you own the draftjs.org domain?

**Comment by flarnie** [comment]
Thanks @Daniel15! It sounds like @hellendag and @spicyj own the relevant domains and are supportive of this change. Leaving this closed since it sounds like it will be solved soon, but we can reopen if questions/concerns remain.

**Comment by Daniel15** [comment]
I've moved the site over to the draftjs.org domain name. It's working!
![](http://ss.dan.cx/2017/02/Draft.js__Rich_Text_Editor_Framework_for_React_-__24-23.57.52.png)

I had to build the site manually as TravisCI is running way behind.

**Comment by hyperpress** [comment]
Looks good across devices and browsers I checked, including:

Android 7.1.1 Pixel Chrome
Android 7.1.1 Nexus 5x Chrome
Android 7.1.1 Pixel C Chrome
Ubuntu 16.04 Chrome, Firefox LRs
