### ISSUE TITLE
How to get the cursor position?

### ISSUE THREAD

**Issue by chenjiashrimp** [facebook/draft-js#3174]
i want to insert something in the middle of the text and i need to get the cursor position, how to get it?

**Comment by bsaptyadeep** [comment]
document.write("Coordinate(X) = " + event.clientX + "<br>Coordinate(Y) = " + event.clientY)
This is the code to write cursor position in javaScript

**Comment by bsaptyadeep** [comment]
@chenjiashrimp  can I be assigned this issue

**Comment by chenjiashrimp** [comment]
@bsaptyadeep thank you very much

**Comment by chenjiashrimp** [comment]
> i want to insert something in the middle of the text and i need to get the cursor position, how to get it?

`editorState.getSelection().getAnchorOffset()`
