### ISSUE TITLE
https://facebook.github.io/draft-js/ Demo warn error

### ISSUE THREAD

**Issue by suhaotian** [facebook/draft-js#323]
see console:
![v9mj56 7xglov ue3cf15 f](https://cloud.githubusercontent.com/assets/6512574/14637886/db4dff3c-0666-11e6-903a-160a2e870b11.png)

**Comment by hellendag** [comment]
https://github.com/facebook/draft-js/blob/master/website/package.json needs a bump to React 15.

**Comment by zpao** [comment]
I think you actually need to bump these: https://github.com/facebook/draft-js/blob/master/website/src/draft-js/index.js#L252-L253

**Comment by suhaotian** [comment]
nice work :+1:
