### ISSUE TITLE
Behavior Of textAlignment="right" with whitespace:pre-wrap

### ISSUE THREAD

**Issue by jclyons** [facebook/draft-js#324]
When textAlignment="right", I would expect pressing 'space' in a no-wrap scenario to introduce another space into the text content. However, because of whitespace:pre-wrap the space is not added until I press another character.  Changing whitespace to 'normal' solves this problem. However, changing it to 'normal' also introduces other irregularities, such as misplaced cursors after deletion. 

The situation I'm using Draft in is a spreadsheet-cell, because I wanted to take advantage of the rich text capabilities of draft for things like autocompletion of cell references (which often contain metadata for my application), functions, etc. In many spreadsheet cells numeric values are right-aligned in the cell, with spaces appending normally and the cell enlarging (usually by multiples of column width) as you type. What's the standard way to disable or override Draft's text-wrapping and resizing behavior?

**Comment by hellendag** [comment]
Yeah, that's annoying.

You'll definitely need to keep `white-space: pre-wrap` to avoid whitespace collapsing, for the reason you mentioned. Draft selection behavior needs the character count in text nodes to match the model.

A couple ideas:

- Does it behave properly if you use `white-space: pre`?
- You could possibly use `handleBeforeInput` to intercept spacebar presses, and insert a non-breaking space [`'\u00a0'`](http://www.fileformat.info/info/unicode/char/00a0/index.htm) instead. I don't know for sure if that would prevent the collapsing, but I have a hunch that it would.

**Comment by lacker** [comment]
It seems like this question has been sufficiently answered so I am going to close this issue. Thanks for bringing it up!
