### ISSUE TITLE
post examples onto gh-pages

### ISSUE THREAD

**Issue by goldensunliu** [facebook/draft-js#33]
on https://facebook.github.io/draft-js/docs/advanced-topics-inline-styles.html#mapping-a-style-string-to-css

we are trying to refer to a non existing live example which I assume should be this

https://github.com/facebook/draft-js/blob/master/examples/color/color.html
but published

**Comment by hellendag** [comment]
Might be nice to have these available live. @zpao is this doable?

**Comment by goldensunliu** [comment]
I can take a stab at it, assuming everything needs here https://github.com/facebook/draft-js/blob/master/examples/color/color.html#L29-L34
is on gh-pages already

**Comment by zpao** [comment]
Those things aren't all there but we could make something work. @goldensunliu if you want to take a stab, go for it. You can run the website locally without having to think about gh-pages from the `website/` directory. We might need to do an additional conversion for these examples but it could be done (for everything but the tex example which had a running server).

**Comment by tylercraft** [comment]
Going to close this out for now, since the examples can all be run locally.
