### ISSUE TITLE
Adding Gutters

### ISSUE THREAD

**Issue by carlesba** [facebook/draft-js#338]
I'm trying to implement an editor that has gutters on the side so the way I tried it is something like:

```jsx
<div className='my-editor'>
  <Gutter blocks={this.state.editorState.getCurrentContent().getBlocksMap()} />
  <Editor … />
</div>
```

So the Gutter can make a new element for each block that we have. The problem is that **there's not an easy way to sync gutters's height with the actual height of the block** unless we start using `ReactDOM.findDOMNode()` what I think is a bad approach.

How should we build this?

Thanks

**Comment by oyeanuj** [comment]
@carlesba You could take a look and see if this gutter implementation helps - https://github.com/yepnamesjames/draft-js-gutter

**Comment by hellendag** [comment]
Unfortunately, there is no way to get the rendered height of a block without querying the DOM.

One possibility -- within your `onChange`, you might try something like this:

```js
onChange(editorState: EditorState): void {
  if (editorState.getCurrentContent() !== this.state.editorState.getCurrentContent()) {
    const changedBlocks = /* find any `ContentBlock` objects that differ */
    requestAnimationFrame(() => {
      // Use `data-offset-key` and `data-block` attributes to find rendered
      // block elements for any changed blocks, measure their heights,
      // and set height values in state to update your gutter.
    });
  }
  this.setState({editorState});
}
```

In this way, you could be sure to measure only the blocks that actually need measuring.

**Comment by hellendag** [comment]
And as you noted in Slack, the `setState` callback can be used for this. Probably the right decision, since it will execute after rendering is complete.

**Comment by carlesba** [comment]
@oyeanuj draft-js-gutter is buggy when the line is too long and then it falls like another line. Gutter's height won't fit then.
