### ISSUE TITLE
How to simulate user input for testing purpose?

### ISSUE THREAD

**Issue by llh1** [facebook/draft-js#347]
Hi all,

First, thanks for providing such a great library.

Actually, this is more a question than an issue. We are trying to write tests including the rich text editor that we built using DraftJS. Our rich text editor is part of a bigger form (written with React) that we need to test. One of the problem that we faced is we don't know how to simulate a text input into our editor. Ideally, we would like to use the React TestUtils.Simulate function. 

Any advice on how to proceed? Which event to we need to simulate on which DOM node?

Thanks!

**Comment by llh1** [comment]
Well, I've finally found the answer to my question debugging Draft. 
So here is the solution if anybody needs it. You need to target the dom node with the class name `public-DraftEditor-content` and trigger a `beforeInput `event.

With React TestUtils:
```
var draftEditorContent = TestUtils.findRenderedDOMComponentWithClass("public-DraftEditor-content");
TestUtils.Simulate.beforeInput(draftEditorContent, {data: "some text"});
```

**Comment by danawoodman** [comment]
For future readers; `beforeInput` no longer exists so this won't work anymore
