### ISSUE TITLE
handle SelectionState for multiple blocks (more than two)

### ISSUE THREAD

**Issue by maerzhase** [facebook/draft-js#348]
i am wondering how to work with the SelectionState if the user has selected more than 2 ContentBlocks. How do I get the Text of all ContentBlocks? Do u i have to traverse through the whole ContentState from startBlock till endBlock, or is there a more direct way to obtain all the selected text?

**Comment by hellendag** [comment]
A `SelectionState` has two endpoints, which may be in different blocks. See http://facebook.github.io/draft-js/docs/api-reference-selection-state.html#content for details.

You can use the `immutable` API to map over the blocks within the selection, using the `OrderedMap<string, ContentBlock>` returned by `ContentState.getBlockMap()`. Namely, `skipUntil` and `takeUntil` are useful methods for extracting the selected blocks for mapping.
