### ISSUE TITLE
Inserting content through an extension causes a duplication issue.

### ISSUE THREAD

**Issue by JohnCoates** [facebook/draft-js#36]
Hi, I'm working on a chrome extension that lets you input text through it. Unfortunately Draft.js breaks when inputting in a standard way.

Steps to reproduce:
1. Load http://facebook.github.io/draft-js/
2. Open Chrome Dev Tools
3. Select the Draft.js input box so that the input caret is present 
4. execute `document.execCommand("insertHTML", false, "X");` in the dev tools console

Result expected:
`X` is added to the input box

Actual result:
`X` is added to the input box twice. You're able to delete one of the instances, but the other one is undeletable but is selectable.

Note: Once at least one character has been typed into the Draft.js input the command works as expected.

Screenshot of the result:
![screen shot 2016-02-22 at 8 09 26 pm](https://cloud.githubusercontent.com/assets/967800/13241572/18c317fa-d9a1-11e5-8073-eeb436875faa.png)

**Comment by hellendag** [comment]
Making changes to the DOM in this way may break React reconciliation, which can put the component into an uncertain state. Note that this can happen with any extension that modifies DOM rendered by a React component, not just the Draft editor.

What is the nature of your extension? Perhaps there is a way to make this work.

**Comment by JohnCoates** [comment]
Thanks for the reply @hellendag!

It's an open emoji extension. We just launched last week: http://emojione.com/chrome/
We'd love to make this work somehow! Is there a sanctioned method for inputting programmatically?

**Comment by hellendag** [comment]
Only if you have access to the `EditorState`, which I think it's safe to say your extension won't. :)

Are you always inserting characters? Or arbitrary HTML?

**Comment by hellendag** [comment]
If you're able to access the clipboard within your extension and are just pasting plaintext emoji characters, then you might be able to use `document.execCommand('paste')`.

**Comment by JohnCoates** [comment]
That's a good solution, but because the code run as a content script, it unfortunately doesn't have access to paste unless it's triggered by a user action. Since the action happens in the panel which is in the extension's sandbox, the user action can't be passed to the content script.

I've found that this code works well:
```
var inputEvent = document.createEvent('TextEvent');
inputEvent.initTextEvent('textInput', true, true, window, text);
````
Still having an issue with the caret not moving forward after the first insertion though.

**Comment by hellendag** [comment]
Oh, that's an interesting approach. Is that text event cancelable?

**Comment by grzeczko** [comment]
Hi @JohnCoates,
I'm having exactly the same issue!  I'm writing a Firefox extension to add Polish characters to any text field using keyboard shortcuts.  It's working for all text fields, except for Facebook. I'm getting the same issue as you are describing.  I've done lots of research and it's hard to find a solution.  Did you find a fix yet for this issue?   I'm still working on it, so if you haven't yet, I'll post a solution as soon as I figure it out.

Thanks,
Gregory

**Comment by grzeczko** [comment]
I figured it out.  Once you execute `document.execCommand("insertHTML", false, "X");`, check to see if the length of `<span data-text="true">X</span>` is 1.  If it is, just run `document.execCommand("undo", false);` and voila!  it works!

**Comment by grzeczko** [comment]
Here's the code:

`if (document.querySelectorAll('span[data-text="true"]').length === 0) {
    document.execCommand("insertHTML", false, "X");
    document.execCommand("undo", false);
} else {
    document.execCommand("insertHTML", false, "X");
}`

It will check to see if you entered the first character.  If you did, it'll do the undo execCommand and remove the extra X.  The `else` will just insertHTML since it won't insert extras once characters are entered.

**Comment by tylercraft** [comment]
Looks like a workaround was found, so I'm going to close this out.
