### ISSUE TITLE
Rename the default bundle

### ISSUE THREAD

**Issue by mitermayer** [facebook/draft-js#363]
For consistency with the published npm package name would be ideal to have the default bundle as 'draft-js.js' so that it matches the published name on npm. Only downside is the double up of 'js' 

The current use case for the above is by being able to `import Draft from 'draft-js'` loaded from an alternate modules path with a local copy that resembles draft-js from github master therefore allowing to test product with the latest branch and being able to remove the local copy at later stage without having to re-factor the code base.

**Comment by spicyj** [comment]
Can you clarify which default bundle you mean? Is there a reason you can't choose the local file name to be whatever you want it to be?

**Comment by zpao** [comment]
Or if you're testing with the latest branch and (presumably) building that bundle - maybe you can use that package as you would from npm (eg `npm pack` it and install that)

**Comment by mitermayer** [comment]
By bundle I mean the default dist filename output. But The above are two valid options to avoid that. I undertstand that having 'draft-js.js' would look weird.
