### ISSUE TITLE
Expose flow.

### ISSUE THREAD

**Issue by marudor** [facebook/draft-js#366]
Hey,
As I can see draft-js uses flow and has flow annotations.
Would it be possible to leave them in in the dist?
This would allow people who use flow to take advantage of them.

**Comment by zpao** [comment]
We have some infra for this in place (it's how fbjs works) so it should be possible. I'm not sure if that method is the best way to do it for something like this or if we'd want a single top-level flow lib. Let's talk with @hellendag when he gets back (per #355)

**Comment by marudor** [comment]
I've talked to jeffmo of flow and he suggested either .js.flow files or a single top level flow lib (like immutable.js)

**Comment by zpao** [comment]
Right, those are the options I'm talking about too :) We can build the .js.flow files easily and that *should* work but it might be cleaner long term to do a single flow lib.

**Comment by jeffmo** [comment]
>  it might be cleaner long term to do a single flow lib.

I agree. Once we get the [flow-typed](https://github.com/flowtype/flow-typed/) CLI shipped, the next thing i would like to explore is some tooling to generate libdefs from flow typed .js files (for contribution). If that works out well, maybe we can build tooling to auto-contribute libdefs on `npm publish` for each version...

**Comment by jeffmo** [comment]
(but in the meantime, .js.flow files might be a good stop-gap if it's easy)

**Comment by alexeygolev** [comment]
Hooray... trying to wrap my head around how to use it:)
