### ISSUE TITLE
Pasting HTML content ignores the first block style

### ISSUE THREAD

**Issue by mitermayer** [facebook/draft-js#369]
If you paste 

```
<h1>foo</h1>
<h2>bar</h2>
```

this currently generate the blocks:

`'unstyled', 'header-two' `

desired outcome would have been

`'header-one', 'header-two' `

the first block is always keeping the same 'block' that was active before the pasting

**Comment by guitardave24** [comment]
Pretty sure this is the same as https://github.com/facebook/draft-js/issues/369

cc @johanneslumpe

**Comment by spicyj** [comment]
This is #369. :)

**Comment by guitardave24** [comment]
Gah. Meant https://github.com/facebook/draft-js/issues/302

**Comment by mitermayer** [comment]
Closing this issue as a duplicate
