### ISSUE TITLE
[IE bug] Underline style unexpectedly removed

### ISSUE THREAD

**Issue by llh1** [facebook/draft-js#377]
Hi all,

New episode regarding my travel in IE land ;) 
I've found an unexpected behaviour regarding the underline style. Only happen in IE so far.
Below is a small gif to reproduce it, it's quite easy: write some text with underline style, then select bold style. Then you expect the following text you input would be bold and underline, but the underline style is lost.

![immensegoodaoudad-size_restricted](https://cloud.githubusercontent.com/assets/2639155/15109593/b2efa632-160e-11e6-9222-75547df555c8.gif)

I've tracked that bug in DraftJS. It happens in the DraftEditorLeaf. At some point, the text decoration style is generated using the following:

`mergedStyles.textDecoration = [map.textDecoration, style.textDecoration].join(' ')`

The problem with this is that it could generate a string like " underline " (with space before AND after underline). I couldn't find the reason why, but this doesn't work in IE. You can easily reproduce this issue rendering a simple React component. Open it in IE, and you'll see the text is not underlined:

`<span style={{textDecoration: " underline "}}>Some underline text</span>`

I'm going to send a PR for this, for now I've just used trim() after join() to remove the extra space, but if you have a better fix, let me know.

Thanks :)

**Comment by niveditc** [comment]
Looks like this was fixed in #378
