### ISSUE TITLE
handle key command doesn't fall through on false

### ISSUE THREAD

**Issue by olup** [facebook/draft-js#382]
My handleKeyCommand on the editor checks for backspace, and, given a condition, operates some actions. If the condition is not met, i'd like to apply normal backspace event.

So, as advise in the doc, i return false in my handleKeyCommand function.

But however i try, I can't get it to work, and the normal event never fires.

Is that an issue or some behavior i didn't master ?

**Comment by niveditc** [comment]
In the current API, the way to fall through is returning `not-handled` in the handleKeyCommand method.
