### ISSUE TITLE
[Question] Best way of grouping blocks

### ISSUE THREAD

**Issue by dphoursa** [facebook/draft-js#386]
Hi, 

Is there a good way of grouping or wrapping different blockTypes?

I have been trying to do this with _customBlockRenderMap_, which is then added to the editor via _blockRenderMap_.
However this doesn't quite work, as all the blocks that have the same wrapper, and are next to each other, get wrapped together. 
What I would like to achieve is certain blocks restart the grouping process and are placed into their own wrapper, i.e:

**Current output:**
```
wrapper
   h1
   h2
   h1
   h2
/wrapper
```
**Desired output:**
```
wrapper
   h1
   h2
/wrapper
wrapper
   h1
   h2
/wrapper
```

**Here is the example of  _customBlockRenderMap_:**
```javascript
const WRAPPER = ( < div classname = ‘one’ / > )

export const customBlockRenderMap = Map({
  h1: {
    element: 'h1',
    wrapper: WRAPPER
  },
  lower_level_block_one: {
    h2: 'h2',
    wrapper: WRAPPER
  }
})
```

(Other way would be implementing metadata and grouping blocks that way, but this would be more complicated)

**Comment by mitermayer** [comment]
Hi @dphoursa, you are right, the blockRenderMap provide a wrapper for a single blockType at a time. Draft has a linear data structure and at the moment does not support block type level nesting, this would require a tree data structure. There is a ticket open for that issue https://github.com/facebook/draft-js/issues/143. 

Also included the missing documentation for blockRenderMap on https://github.com/facebook/draft-js/pull/387

**Comment by dphoursa** [comment]
I am closing this issue, I have resolved this by implementing block metadata

**Comment by jkhaui** [comment]
@dphoursa I realise it's been a while and Draft.js may have changed since then, but would you mind telling me how you solved this? I'm facing the exact same issue and would really appreciate any guidance in the right direction :)
