### ISSUE TITLE
Failed at the draft-js@0.1.0 prebuild script 

### ISSUE THREAD

**Issue by ZeGregg** [facebook/draft-js#39]
Hi

I get an error on npm run build with latest node and npm release

    assert.js:89
    throw new assert.AssertionError({
    ^
    AssertionError: Current node version is not supported for development, expected "5.7.0" to satisfy "4.x".

    npm ERR! Darwin 15.3.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
    npm ERR! node v5.7.0
    npm ERR! npm  v3.7.3

**Comment by RobJTingay** [comment]
In a similar vein I get an assertion exception using NPM 3.7.5 and Node 4.3.0

AssertionError: Current npm version is not supported for development, expected "3.7.5" to satisfy "2.x".
    at /$HOME/draft-js/node_modules/fbjs-scripts/node/check-dev-engines.js:57:5

**Comment by taggon** [comment]
In my case, just running `gulp` seems to build it successfully.

**Comment by ZeGregg** [comment]
@taggon thank you. `gulp`build successfully

**Comment by ryantemple** [comment]
Is there a hard dependency on a particular version of Node?  I notice it failed with node@5.0.0 as well.  If things work fine then perhaps the version check should be relaxed?

**Comment by RobJTingay** [comment]
@taggon, you're completely correct. Running gulp builds the package just fine. Seems peculiar that there's such a strict Node/NPM version check. Works fine on 4.3.0-4.3.1(LTS) and 5.7.0(Stable) using NPM 3.7.5

**Comment by mitermayer** [comment]
Also wondering why does the check for 4.x exists ? What are the current incompatibilities ? Are they listed anywhere that we could submit PR's ?

**Comment by zpao** [comment]
The dependency on node 4 is not a hard dep. But npm 2 is so that we can run our tests. See #37 where we're going to make it so it's possible to build with npm3 but if you try to contribute and run tests you'll get stopped.

**Comment by hellendag** [comment]
I assume we're ok here?
