### ISSUE TITLE
How to create custom inline components without text

### ISSUE THREAD

**Issue by inyono** [facebook/draft-js#390]
I'm currently stuck at creating custom inline components. I want to have a component for inline LaTeX equations. I tried to follow [Creating and Retrieving Entities](https://facebook.github.io/draft-js/docs/advanced-topics-entities.html#creating-and-retrieving-entities) but I'm not sure what to pass `Modifier.applyEntity`. Something like this didn't work as intended:

``` .js
addInlineLatexEquation() {
  const { editorState } = this.state

  const entityKey = Entity.create(
    'INLINE_LATEX_EQUATION',
    'IMMUTABLE',
     { src: '' }
  )

  const contentState = editorState.getCurrentContent()
  const selectionState = editorState.getSelection()

  const newContent = Modifier.applyEntity(
    contentState,
    selectionState,
    entityKey
  )

  const newEditorState = EditorState.push(editorState, newContent, 'apply-entity')

  this.setState({
    editorState: newEditorState
  })
}
```

I now can create an inline LaTeX component by selecting text, but I rather want to have a behavior similar to the block components. I.e., I want to add an inline component at the current cursor position without any text (basically `AtomicBlockUtils.insertAtomicBlock` for inline components).

**Comment by mull** [comment]
Just going to share the snippet I shared on Slack. This

1. Inserts an empty space before the current selection
2. Adds a blank character with an entity (which I then render customly through a decorator)
3. Adds a blank character afterwards

```js
import { Entity, Modifier, EditorState } from 'draft-js';

export function insert(editorState) {
  const currentContent = editorState.getCurrentContent();
  const entity = Entity.create(
    'TEX',
    'IMMUTABLE',
    {content: "$ 1 + 1 $"}
  );

  const selection = editorState.getSelection();

  const firstBlank = Modifier.insertText(
    currentContent,
    selection,
    " ",
    null,
    null
  );

  const withEntity = Modifier.insertText(
    firstBlank,
    selection,
    " ",
    null,
    entity
  );

  const withBlank = Modifier.insertText(
    withEntity,
    selection,
    " ",
    null,
    null,
  );

  return EditorState.push(
    editorState,
    withBlank,
    'insert-text'
  );
}
```

**Comment by jussch** [comment]
@mull Thanks for the example snippet.

If I may ask, what does your TEX entity component look like? I'm having a problem keeping the cursor out of the inline math block, and in turn, letting the user make some weird interactions with the rendered math. I've tried setting contentEditable="false" on the math container, but that has some odd behavior when the math is at the beginning or end of the line.

For reference, this is the super quick and naive component I threw together:
```javascript
class InlineMath extends Component {
  componentDidMount() {
    const { content } = Entity.get(this.props.entityKey).getData();
    katex.render(content, this.refs.math);
  }

  render() {
    return (
      <span ref="math" contentEditable="false">math</span>
    );
  }
}

// ...

const decorator = new CompositeDecorator([
  {
    strategy: findTex, // essentially find entity.getType() === 'TEX'
    component: InlineMath,
  },
]);
```

**Comment by johanneslumpe** [comment]
Heads up: right now adding custom text within decorators is not supported. Decorators are only supposed to render what they receive via `props`. Anything else can result in broken state. There was a discussion about allowing something like atomic decorators, which just render custom content which is not selectable, but then maintaining the selection is tricky.

**Comment by inyono** [comment]
@jussch You can look at my first attempt at https://github.com/ory-am/editor/tree/draftjs with a live demo at https://inyono.github.io/editor. I basically do the same as in the [TeX example](https://github.com/facebook/draft-js/tree/master/examples/tex/) by showing a editor for the LaTeX source after clicking the formula. IIRC, it is the same thing @mull is doing.

**Comment by yujiangshui** [comment]
The 'insert-text' change type had been removed now, and how can I deal with this problem? @hellendag @inyono @mull

**Comment by afraser** [comment]
I'd like to do the same thing here. Inline equations that are treated as atomic with respect to the cursor, but whose Latex can be edited when clicked on. The only way I can think to do this right now is with decorators but it seems like they wont get me the cursor behavior that I want. Is that true or is there a way for me to treat a particular decorated range as atomic?

**Comment by inyono** [comment]
I used decorators for this. The cursor behavior is okay but deleting is weird (see https://inyono.github.io/editor/). Didn't find a solution for this, yet.

**Comment by johanneslumpe** [comment]
@afraser no it hasn't yet.

**Comment by johanneslumpe** [comment]
@inyono The cursor behavior in your example is actually rather broken. Using the left/right cursor keys the cursor is jumping to a completely different spot when trying to step through the equation. That's due to the decorator rendering content which is not present in the text. But it should be pointed out that it definitely has this limitation, as opposed to suggesting that the cursor behavior works fine I think.

**Comment by inyono** [comment]
@johanneslumpe You're right, I mixed up the cursor with the mouse. I guess the weird delete behavior comes from the weird cursor behavior.

**Comment by johanneslumpe** [comment]
@inyono The weird delete behavior and the cursor behavior have the same source, correct: rendering content which is not part of the data model. Draft internally does not know about the content and thus will place the cursor incorrectly and delete different characters.

**Comment by afraser** [comment]
@inyono @johanneslumpe I noticed if I manually set `contenteditable='false'` on the Entity span tag, the cursor behavior seems to be restored. Anyone have a sense of whether this is a bad idea?

/cc @aamontal

**Comment by afraser** [comment]
@jussch Just noticed that you also had some success with setting `contentEditable=false` any luck with those anomalies at the beginning and end of line?

**Comment by jussch** [comment]
@afraser Unfortunately I haven't played around with Draft-JS and `contentEditable="false"` too much, but I have been playing around with `contentEditable="false"` within any `contentEditable="true"`. I've found that the anomalies that were occurring in DraftJS were also sort of happening in non-DraftJS contentEditable divs. In Chrome for example, placing the cursor after a `<div contentEditable="false"/>` at the end of the line renders the cursor off the page.

Outside of those anomalies though, `contentEditable="false"` seemed to be working fine as long as one character represented one custom inline block, but I haven't played around with it too much yet.

**Comment by afraser** [comment]
I'm proposing fixes to copy & paste behavior for these sorts of entities here if anyone is interested: https://github.com/facebook/draft-js/issues/504

**Comment by afraser** [comment]
I added an example with inline equations working here:
https://github.com/facebook/draft-js/pull/525

The only issue I haven't fixed yet is the broken cursor behavior when the equation is at the beginning or end of a block. However, @aamontal has a solution for this working that I'll add to the example sometime next week.

**Comment by mull** [comment]
@afraser would love it if you ping this thread when you've got cursor behavior working well!

**Comment by afraser** [comment]
@mull Can do.

**Comment by afraser** [comment]
@mull Here's a gist with our editor component in it. The important code for fixing the end-of-line entity bug is in the `onChange` handler here https://gist.github.com/afraser/12d97ee842eeb41bb05dc66fc2c6a9d2#file-boundless-editor-L38-L80

As for copy and paste, you'll have to refer to my PR referenced above.

**Comment by mull** [comment]
@afraser much appreciated!

**Comment by kevinguard** [comment]
Hello Folks! First of all, big apology for the silly question here but I kinda found this thread the most relevant to what I am trying to do. Again apology in advance if you think I should have posted this somewhere else.

My problem is that I successfully manage to add a custom block (an iframe for example) to the editor I'm working on and in fact the added block renders itself pretty well and shows up in the editor alongside other equations and images. But when I try to save the content of the editor, the custom block is simply replaced by a whitespace and is never get saved. This is what I'm currently doing:

To create a new entity, for which there a custom decorator with corresponding strategy and component:

`let entityKey = Entity.create('IFRAME', 'MUTABLE', {embeddedContent});`

Then attempting to get the updated content:

`const updatedContent = Modifier.insertText(contentState, selection, ' ', null, entityKey);`

Finally invoking the onChange method passed to the editor:

`onChange(EditorState.push(editorState, updatedContent));`

The value passed in to onChange method contains all equations, images, but the custom block I have just added. Although the item can be seen in the editor (as it has been correctly rendered), but it doesn't appear in the EditorValue and therefore is missed when saving the content. 

I understand why there is a whitespace in the replacement of the block as I am using ' ' inside insertText method of Modifier but I am not even certain if what I'm doing is correct. I have seen folks here use applyEntity as well but that doesn't work either. 

Thanks for your help!

**Comment by bryanph** [comment]
@afraser So how would you go about removing the inline TeX? Since no custom block is created, would I have to search through all blocks for the selection range with the entity key corresponding to the inline tex? Or is there an easier way?

**Comment by bryanph** [comment]
@afraser, fixed a little bug in your gist, where blocks with only plaintext are not copied/pasted.
https://gist.github.com/bryanph/17a805449a0937156965ee55c755ed41

**Comment by bryanph** [comment]
@afraser, I'm now trying to get this to work for pastes between editor (so not internal). No idea how to approach this since the required data is stored in the entity store itself. Do you have any ideas maybe?

**Comment by afraser** [comment]
@bryanph Thanks for sharing your fix. Pasting between editors is definitely a challenge. I think storing it as a data-attribute is a fine idea but a couple of notes/warnings:

1) You'd be storing the entity data in 2 places, which begs the question: Which is the source of truth? And when are they synced so there is a minimal chance of them being accessed while out of sync.
2) You're better off having one code-path for cloning entities, which means you should rewrite `cloneEntitiesInFragment` to handle the more general case of pasting from another draft editor.
3) Is it worth avoiding the use of Entities altogether?

Unfortunately I'm no longer working on this project so I most likely won't have much time to make improvements to the code that I've shared, but @aamontal is working on fixing the edge cases that occur when inserting equations at the end of a block.

**Comment by bryanph** [comment]
Thanks @afraser, I will definitely give it a shot. 

My main problem now is actually converting from and to html from the inline-latex representation. Using DraftPasteProcessor.processHTML I don't get the same representation unfortunately when trying to convert the external clipboard to ContentBlocks. Going to try some other approaches this week, hopefully I can get something working.

**Comment by flarnie** [comment]
From reading the discussion, it looks like there are some work-arounds that can be used for now to deal with this use case. In general, I don't think we can support having lots of complex custom inline components at this time, so I'll close this issue.

**Comment by hengkx** [comment]
I need inline `img`.Is there any solution?

**Comment by crazywilson** [comment]
in my Math.tsx file: 

```typescript
import React, { useRef, useCallback, useMemo } from 'react'
import { EditorState, ContentBlock, ContentState, SelectionState, CompositeDecorator, Modifier, Entity } from 'draft-js'
import createStyles from 'draft-js-custom-styles'
import katex from 'katex'
import ReactDOM from 'react-dom'
import { Input, Popover } from 'antd'

const customStyleMap = {
  STRIKETHROUGH: {
    textDecoration: 'line-through',
  },
}

const { exporter } = createStyles(['font-size', 'color', 'background-color', 'font-family'], 'CUSTOM_', customStyleMap)

export function insertMathEntity(editorState: EditorState, mathString: string) {
  const currentContent = editorState.getCurrentContent()

  const selection = editorState.getSelection()

  const firstBlank = Modifier.insertText(currentContent, selection, ' ')
  const entity = Entity.create('MATH', 'IMMUTABLE', { content: mathString })
  const withEntity = Modifier.insertText(firstBlank, selection, ' ', undefined, entity)
  const withBlank = Modifier.insertText(withEntity, selection, ' ')

  return EditorState.forceSelection(
    EditorState.push(editorState, withBlank, 'insert-characters'),
    selection.merge({
      anchorOffset: selection.getFocusOffset() + 2,
      focusOffset: selection.getFocusOffset() + 2,
    }),
  )
}

export function MathComponent(props: {
  contentState: ContentState
  entityKey: string
  children: React.ReactNode[]
  decoratedText: string
  offsetKey: string
  blockKey: string
  start: number
  end: number
  dir: any
  setEditorState: React.Dispatch<React.SetStateAction<EditorState>>
}) {
  const styles = useMemo(() => {
    const state = EditorState.createWithContent(props.contentState)
    const selectionState = SelectionState.createEmpty(props.blockKey)
    const newSelectionState = selectionState.merge({
      anchorOffset: props.start - 2 < 0 ? props.start : props.start - 2,
      focusOffset: props.end + 1,
    })
    const newState = EditorState.forceSelection(state, newSelectionState)
    const stateAllStyles = exporter(newState)
    const SelectionStyles = newState.getCurrentInlineStyle().toJS()
    console.log(SelectionStyles)
    let stylesUnion = {}
    const stylesTemp = Object.keys(stateAllStyles).filter(key => SelectionStyles.includes(key))
    for (let key of stylesTemp) {
      Object.assign(stylesUnion, stateAllStyles[key].style)
    }
    return stylesUnion
  }, [props.blockKey, props.contentState, props.end, props.start])
  const mathText = props.contentState.getEntity(props.entityKey).getData().content
  const container = useRef<HTMLSpanElement | null>(null)

  const mathRef = useCallback(
    (dom: HTMLSpanElement) => {
      if (dom) {
        katex.render(mathText, dom, {
          throwOnError: false,
          output: 'html',
        })
      }
    },
    [mathText],
  )

  const MathCodeEditor = useMemo(() => {
    return ({ code, style, hide }: { code: string; style?: React.CSSProperties; hide: (val: string) => void }) => {
      return (
        <Popover
          content={
            <Input.Search
              placeholder='input search text'
              enterButton='Done'
              size='large'
              defaultValue={code}
              onPressEnter={e => hide((e.target as HTMLInputElement).value)}
              onBlur={() => hide(code)}
              onSearch={value => {
                hide(value)
              }}
              autoFocus
            />
          }
          visible
          destroyTooltipOnHide>
          <div
            style={{
              position: 'absolute',
              ...style,
            }}></div>
        </Popover>
      )
    }
  }, [])

  const showMathCodeEditor = useCallback(
    (e: React.MouseEvent<HTMLSpanElement>) => {
      const containerRect = (
        container.current?.getElementsByClassName('base')[0] ||
        container.current?.getElementsByClassName('katex-error')[0]
      )?.getBoundingClientRect()
      const root = document.createElement('span')
      ReactDOM.render(
        MathCodeEditor({
          code: mathText,
          style: {
            width: containerRect?.width,
            height: containerRect?.height,
            left: containerRect?.left,
            top: containerRect?.top,
          },
          hide: (val: string) => {
            const newState = props.contentState.replaceEntityData(props.entityKey, { content: val })
            props.setEditorState(pre => {
              return EditorState.createWithContent(newState, pre.getDecorator())
            })
            ReactDOM.unmountComponentAtNode(root)
            document.body.removeChild(root)
          },
        }),
        root,
        () => {
          document.body.appendChild(root)
        },
      )
    },
    [MathCodeEditor, mathText, props],
  )

  return (
    <span
      data-offset-key={props.offsetKey}
      ref={container}
      className='math-content'
      contentEditable={false}
      style={{ cursor: 'pointer' }}
      onDoubleClick={showMathCodeEditor}>
      <span ref={mathRef} style={styles} contentEditable={false}></span>
    </span>
  )
}

export function getEntityStrategy(
  contentBlock: ContentBlock,
  callback: (start: number, end: number) => void,
  contentState: ContentState,
) {
  contentBlock.findEntityRanges(character => {
    const entityKey = character.getEntity()
    if (entityKey === null) {
      return false
    }
    return contentState.getEntity(entityKey).getType() === 'MATH'
  }, callback)
}

export const generatorDecorator = (props?: object) => {
  return new CompositeDecorator([
    {
      strategy: getEntityStrategy,
      component: MathComponent,
      props,
    },
  ])
}
```

in my editor file use:

```typescript
import { getEntityStrategy, MathComponent } from './Math'

// ......
const [editorState, setEditorState] = useState(EditorState.createEmpty())
  const decorator = useMemo(() => {
    return new CompositeDecorator([
      {
        strategy: getEntityStrategy,
        component: MathComponent,
        props: {
          setEditorState,
        },
      },
    ])
  }, [])
  useEffect(() => {
    setEditorState(EditorState.createEmpty(decorator))
  }, [decorator])
//......
```

finaly. my UI looks:

![image](https://user-images.githubusercontent.com/12150488/186887296-dff4cc2c-6d88-47d0-b5e8-a1c33541eaa5.png)
