### ISSUE TITLE
is the `paragraph` block type removed now?

### ISSUE THREAD

**Issue by ianstormtaylor** [facebook/draft-js#395]
I have been using the `paragraph` block type instead of unstyled, but in upgrading to the lastest version from `0.4.0` (aka somewhere in the recent releases) it seems like the `paragraph` concept for blocks was removed? And in it's place `unstyled` is the only one?

Just wanted to double check if this is true. Might be good to add a breakage note to the release notes if they are retroactively editable.

Thanks!

@mitermayer you might be able to answer this one since it looks like you were creating a bunch of PRs around it.

**Comment by mitermayer** [comment]
paragraph support is still present but it needs to be done using the blockRenderMap, apologies for not having the documentation yet on the website.  The documentation for it is open as a pull-request, but you can read it from here https://github.com/facebook/draft-js/pull/387/files

will paste it here so that you can see

```
const blockRenderMap = Immutable.Map({
 	'paragraph': {
 		element: 'p'
 	},
 	'unstyled': {
 		element: 'p'
 	}
 });
 
 // Include 'paragraph' as a valid block and updated the unstyled element but
// keep support for other draft default block types
const extendedBlockRenderMap = Draft.DefaultDraftBlockRenderMap.merge(blockRenderMap);

class RichEditor() {
    ...
    render() {
      return (<Editor ...
                blockRenderMap={extendedBlockRenderMap} />);
    }
}
```

**Comment by ianstormtaylor** [comment]
Why have the paragraph supported internally but then make it not work until adding it to the `blockRenderMap`? Wouldn't it be better if it's considered a "core" type to just support it fully? Or if it's not a core type to remove it fully?

**Comment by gimmixAT** [comment]
Hi, I am currently having a similar problem. Are you sure the overriding paragraph & unstyled with 'p' works? Because the resulting DOM, at least for me, is invalid (note the div in the p):

```
<div data-contents="true" data-reactid=".0.0.0.2.0.$editor0.0.0">
   <p class="" data-block="true" data-editor="1r4ao" data-offset-key="et022-0-0" data-reactid=".0.0.0.2.0.$editor0.0.0.$et022">
      <div data-offset-key="et022-0-0" class="public-DraftStyleDefault-block public-DraftStyleDefault-ltr" data-reactid=".0.0.0.2.0.$editor0.0.0.$et022.$et022">
         <span data-offset-key="et022-0-0" data-reactid=".0.0.0.2.0.$editor0.0.0.$et022.$et022.0:$et022-0-0"><br data-text="true" data-reactid=".0.0.0.2.0.$editor0.0.0.$et022.$et022.0:$et022-0-0.0">
         </span>
      </div>
   </p>
</div>
```

**Comment by brianreavis** [comment]
> ```js
// suggested blockrendermap
const blockRenderMap = Immutable.Map({
    'paragraph': {
        element: 'p'
    },
    'unstyled': {
        element: 'p'
    }
 });
```

@mitermayer This is perhaps a different issue but this suggestion doesn't work with `convertFromHTML` (with `blockRenderMap` as the third argument) – paragraph blocks will be omitted. The important part of the implementation here [here](https://github.com/facebook/draft-js/blob/master/src/model/encoding/convertFromHTMLToContentBlocks.js#L132-L143):

```js
function getBlockMapSupportedTags(
  blockRenderMap: DraftBlockRenderMap
): Array<string> {
  const unstyledElement = blockRenderMap.get('unstyled').element;
  return blockRenderMap
    .map((config) => config.element)
    .valueSeq()
    .toSet()
    .filter((tag) => tag && tag !== unstyledElement)
    .toArray()
    .sort();
}
```

If `paragraph` and `unstyled` share the same element type it'll be dropped. With this in mind and @gimmixAT's point, what is the suggested way to support paragraphs?

**Comment by mitermayer** [comment]
This PR is a temporarly fix https://github.com/facebook/draft-js/pull/488 until a more robust solution like https://github.com/facebook/draft-js/issues/486 is not created

**Comment by kenticomartinh** [comment]
I am having the same problem as @gimmixAT Even though I configure the editor to use P, nested DIV for content block is invalid in DOM and it doesn't work properly. Are there any plans to fix that? 

As far as I can tell, the DIV usage for that block is hard-coded here in render():

https://github.com/facebook/draft-js/blob/69890ed57b5f4256cc93ae8e9ea178296851a23e/src/component/contents/DraftEditorBlock.react.js

**Comment by AugustKarlstedt** [comment]
Having the same issue. The div here https://github.com/facebook/draft-js/blob/5120924e4ed1a04f050ee58fa3a02016e83c373c/src/component/contents/DraftEditorBlock.react.js#L210 should either be configurable or changed to a span?

**Comment by niveditc** [comment]
I'm closing this out since the changes were intentional and it's been a while. The other open issues referenced here may still be relevant for potential improvements.

**Comment by thinkclay** [comment]
Could someone share context as to why divs are used internally instead of spans? I understand and agree with not defaulting to unstyled as paragraph, but the invalid DOM nesting is problematic. Is there a "proper" solution or do I have to default to some other hackery (or just ignore the error and move on)?

**Comment by maulerjan** [comment]
Did anyone find a solution yet? Invalid DOM nesting is indeed problematic .

**Comment by irvingv8** [comment]
Something went wrong in the PR, I can see the text related to the paragraphs, however the codeblock above it points to section, and would be nice if the table at the top made any kind of reference to the paragraph Draft block type, as it's hard to know that it exists :), if you need a PR for this, let me know :)
