### ISSUE TITLE
Selecting a single character then typing it doesn't replace it

### ISSUE THREAD

**Issue by gdehmlow** [facebook/draft-js#398]
I can replicate it on the [DraftJS demo page](https://facebook.github.io/draft-js/) by typing a single character (such as "t"), selecting it, then trying to type "t" again. "t" should get replaced, with the selection collapsing after the "t". Instead, this does not happen until I type "t" again. This does _not_ happen if the character is different.

The `editorState` passed into `onChange` seems to think its selection's `anchorOffset` and `focusOffset` are the same after entering the character, which would be the correct behavior, but this isn't reflected in the selection itself.

**Comment by spicyj** [comment]
Weird bug, thanks for reporting.

**Comment by steviesama** [comment]
If I understand this correctly, I reproduced it. Select the character and have to key it twice before it replaces it and not happening if the character is different. Seems to me this is maybe something in how the editor detects changes in state. I watched the draft.js talk about how it handles intermediary states between transforms while you are typing and it said that it throws them out.

If this is the case, maybe it doesn't realize that the state has actually changed when you key it in the first time. What seems to support that, is if you select 2 of the same character, like `tt` and hit t, it will replace it. I think it's a matter of the selection being in the same state as the state you are trying to transform it to.

**Comment by hellendag** [comment]
Nice catch! I've never noticed this before. I believe @steviesama is correct here, and the editor doesn't think the state has changed within the `beforeInput` handler.

This seems fixable by checking whether the typed character matches the selected character, then simply updating the `SelectionState` instead of changing the `ContentState`.

**Comment by steviesama** [comment]
I'm not familiar with the underlying code, but would allowing the input to be applied if there is a selection applied without comparing state?
