### ISSUE TITLE
More/Clear Documentation

### ISSUE THREAD

**Issue by Umbrellagun** [facebook/draft-js#409]
I would like to preface this with the fact that this feedback is not coming from an expert developer and that Draft.js is a very cool tool that has clearly taken a lot of work and thought, so I absolutely appreciate the open source-ness and work that has been put into it. If I point something out that I believe is an issue that actually has a very good reason behind it that I didn't notice, I am absolutely open to learning and have open ears. 

So I started playing around with Draft.js not too long ago, I have the editor working to the point that I can customize inline styles, I've read all of the docs, looked through all of the examples, and during that process I've been continually frustrated with understanding the documentation. While I can see some of the logic behind the documentation in retrospect, I still have some criticisms of it.

The documentation seems very disconnected from itself (meaning that, sometimes, when the docs are explaining a function, it will loosely reference another part of the documentation that has not been explained yet, or it will loosely reference something that doesn't have any direct documentation itself at all and is only loosely mentioned here and there, or it is just a describer and not an actual function or object but is still presented in a way that makes it look like it is a function or object because camel-case is used). This means that sometimes I have to jump around all over the place until I can put together what a term means and how it is used or I find out that it is just pseudo-code to describe some other function or object therefore not having any documentation for itself at all. Sometimes the documentation is clear enough through context that the pseudo-code/a describer makes enough sense so it is understood to just be pseudo-code/a describer and other times it is not clear enough. Either way, it adds to initial confusion.

One example is: "targetRange"

The term "targetRange" only appears in four places in all of the documentation (once in the Advanced Topics Entities page, and three times in the Modifier API documentation page). All four places it appears in, it is never explained. It only appears in the pseudo-code. It only seems to be a stand-in for SelectionState. If this is correct, and "targetRange" is not actually a real term and is merely a made up describer, why not just use "SelectionState" by itself? What is the point of using a second term to describe the same thing? It seems to only cause confusion.

This same scenario happens multiple times throughout the documentation.

Also, there are dozens of functions that do not have any description in the API docs. Many of them you can guess the function of, but there are some that are not as clear and it adds to the confusion and uncertainty regardless of whether it is clear or not.

One more example is the Data Conversion documentation. Probably one of the most important pieces of documentation beyond the basics. The naming "convertFromRaw" and "convertToRaw" is confusing because "Raw" is never clarified. If you replace the word "Raw" with "Json", it makes much more sense and it's what I have been doing in my own head to keep things clear. The confusion is compounded by the fact that "convertFromRaw" and "convertToRaw" are presented to the reader out of logical order. If you are placing Draft.js data into a database or anywhere else, you must first use "convertToRaw", yet, "convertFromRaw" is presented first. One of the reasons the order is important is because of the nebulous "Raw" part of the function name. Not that everyone reading the documentation may be tripped up by this the way I have, but, for myself, I was thinking that "Raw" meant "Raw React/Draft.js junk". The way this makes sense to me is that, by comparison, Json is refined. So I do not consider Json to be "Raw".

I know that was a lot, and if there is any agreement about what I am saying, I would love to contribute to actual changes, but I can't say I understand what every piece of documentation represents yet. I do think Draft.js is cool and that it's confusing documentation should not get in the way of people using it. Thoughts?

**Comment by gdehmlow** [comment]
Having just spent the last week getting up to speed, I agree. I found getting the basics down to be easy enough, but when I started digging through the API / documentation, I noticed a few inconsistencies and confusing points. I definitely want to chip in and help improve it as well.. some of this work [already seems to be happening](https://github.com/facebook/draft-js/pull/387/files).

**Comment by spicyj** [comment]
Thanks for writing up your detailed thoughts. I think we would definitely be in favor of improving this but it's not always clear the best way to change things to make them clearer. It's also sometimes difficult for people who are familiar with the concepts to keep track of what concepts have and haven't been introduced and describe things in a logical progression, but hopefully we can get to a point where we have that.

Isaac, the primary author, is out until June (#355) so I'll let him respond when he gets back.

**Comment by Umbrellagun** [comment]
Awesome, I'm glad I'm not entirely out in left field. 

As I'm working with it now, I've come across another one. Although it is used in a code example on the SelectionState documentation page under "Properties", there is no direct documentation for the "merge" function that can be called on SelectionState, nor is it mentioned or used anywhere else in the docs. I thought it was very easy to understand it's use just by seeing the example code, but I wouldn't have searched for it where I found it.

**Comment by Umbrellagun** [comment]
Just making another quick note on one more that I found, even for myself, in order to make a pull request later. The Overview for Entity documentation says that .create() returns a DraftEntityInstance, but under the actual method is says it returns a string.

**Comment by gdehmlow** [comment]
`ContentBlock.getEntityAt()` returns an entity key string, not an entity is another one that tripped me up a few times.

**Comment by hellendag** [comment]
Apologies for the struggles with navigating the project and getting up to speed, and thanks for your thoughts on this. I freely admit that the documentation here is lacking, and I'd love for it to be better. :) Unfortunately, what we currently have was a bit of a rush job leading up to React Conf. And as @spicyj notes, it can be hard to have a good sense of what needs better explanation and clarification.

I'm open to any ideas on how to improve or streamline the documentation. If you have found yourself struggling with certain topics and have suggestions for improved tutorials, etc, please do submit PR's. :)

**Comment by tylercraft** [comment]
We are working on trying to improve the documentation. Since this issue is more of a general (and completely understandable complaint), I'm going to close this out for now. Please feel free to reopen.
