### ISSUE TITLE
Caret on right side of DraftEditor after clearing text.

### ISSUE THREAD

**Issue by steviesama** [facebook/draft-js#410]
I'm using the editor, but it remains on the screen after use. I get the text, store it somewhere else, and clear the editor. The result is the caret is shoved to the right side of the text line. If you type it doesn't end up relocating, but not sure what's up with it. I did EditorState.createEmpty() and replaced the current state with it. Don't know if that is how it should be done or if it affects the cursor or not, but there it is.

![caret](http://i.imgur.com/MHJXcnN.png)

**Edit:** Actually, it takes 2 keystrokes before the caret returns to the appropriate place.
I also tried pushing a ContentState.createFromText('') with no luck; same behavior.

![push](http://i.imgur.com/fO5A1in.png)

**Comment by steviesama** [comment]
I made a video showing the problem and describing it. I noticed an addition bug. You input 2 keystrokes, at which point the cursor returns to the appropriate position. However, if you enter a backspace, it delete the second character, but the cursor jumps in front of the first character instead of behind it where it should be.

The video:
https://youtu.be/f9BeAssCLR0

**Comment by steviesama** [comment]
I don't think the editor should behave this way, but I figured out a way for it to work, you want to import Modifier, also SelectionState, and ContentState on top of the standard stuff. Refer to the snippet below.

![Modifier](http://i.imgur.com/frB9EnP.png)

Then, you'll need to set up a selectionState that spans from the beginning of the first block in the editor to the end of the last block; as well as setting hasFocus to true as we are using merge and it will screw up the focus otherwise. I included a console.log that turns the object into JSON for debugging.  You want to use Modifier.removeRange() which will return a new ContentState with the removed text (empty). Then do an EditorState.push() and update the state. Here is a snippet below. If you do this, the caret won't go to the right, and the typing behavior will be consistent.

![fixed](http://i.imgur.com/BkukjvJ.png)

That was long winded as hell, and totally unintuitive. Hacking around in this stuff to figure that out is annoying. Pushing a ContentState created from ContentState.createFromText('') like another issue resolution said would be a lot more succinct, but that isn't working.

**Comment by steviesama** [comment]
I don't know if my solution should be cause to close this issue. I think the push from ContentState.createFromText('') should be addressed.

**Comment by spicyj** [comment]
What about doing…

```
const editorState = EditorState.push(
  this.state.editorState,
  EditorState.moveFocusToEnd(ContentState.createFromText(''))
);
```

Does that work? I haven't tried it but I believe it should. Related to #73.

**Comment by gdehmlow** [comment]
I'm thinking we should update `createEmpty`'s [documentation](http://facebook.github.io/draft-js/docs/api-reference-editor-state.html#createempty) with a warning about this unexpected behavior

**Comment by steviesama** [comment]
@spicyj I've tried something like that before and it didn't. Not sure I tried `moveFocusToEnd `with `createFromText('')`. I'll give it a shot.

**Comment by steviesama** [comment]
@spicyj I tried that out. Not only did it not work, but it didn't actually delete any text from the editor either.

**Comment by steviesama** [comment]
@spicyj The only push related call that is similar to that that removes text at all is the first thing I did a while ago:

![push](http://i.imgur.com/fO5A1in.png)

However, this is the one that causes that caret behavior. Along with just plain `this.state.editorState = EditorState.createEmpty()` both give the same weird caret results. I did the latter first.

**Comment by hellendag** [comment]
A couple notes:

- With `EditorState.push`, you must include a change type.
- `EditorState.push` is only useful for you in the "reset" case if you actually want to preserve undo/redo state. If not, you should just be able to set the new empty `EditorState` as your current state.
- `EditorState.createEmpty` does not entail focus, which is confusing but kind of necessary because we can't make any up-front assumptions about what the developer actually wants from selection behavior here. Using `EditorState.moveFocusToEnd` should work to resolve this.

I think the use of `EditorState.push` may be causing problems here. Can you add `'remove-range'` as the change type argument, and see if that helps?

Or, if you don't need to preserve undo/redo state, can you try the following?

```js
reset() {
  const newState = EditorState.createEmpty();
  this.setState({editorState: EditorState.moveFocusToEnd(newState)});
}
```

**Comment by steviesama** [comment]
@hellendag I actually did try that.

Referring to:
```
reset() {
  const newState = EditorState.createEmpty();
  this.setState({editorState: EditorState.moveFocusToEnd(newState)});
}
```
Currently, the only thing that has worked, is the pretty long `reset()` definition further up in this thread. What you are suggesting here, wiped the display, but the current slammed to the right side of the text line. You did say it isn't supposed to affect the selection state, but something must have been pushing the caret to the right side?

I'll go back and try the `moveFocusToEnd()` again just to make sure, but I recall trying that and another variation a handful of times already.

**Comment by steviesama** [comment]
@hellendag Actually...I was thinking about it a moment...I don't think I did do the exact thing you put. I think I tried setting `editorState` directly to `EditorState.createEmpty()`, not passing it to `EditorState.moveFocusToEnd()` on `setState()`. I did what spicyj suggested with the `EditorState.moveFocusToEnd(ContentState.createFromText(''))`....checking now.

**Comment by steviesama** [comment]
@hellendag Sorry, I got held up doing some other stuff. I just tried your suggestion. That did in fact do the trick. I find it peculiar that doing that with `ContentState.createFromText('')` didn't work per @spicyj 's suggestion. I seems very similar, but I realize the fact that it is a different type will cause a different path of mutation. I would imagine either would ideally work conceptually. But in any case, thanks.

**Comment by paulyoung** [comment]
I'm doing something similar except I _do_ want to preserve undo/redo state. My issue is that everything looks good when I clear the content but when I undo and redo, the caret is over to the far right.

**Comment by paulyoung** [comment]
It looks as if this was related to the way I was previously setting some content without properly specifying the selection state.

**Comment by paulyoung** [comment]
For anyone interested, here's my latest version to address issues with the cursor being positioned on the far right. This maintains the correct cursor position for me with undo/redo, and also accounts for backwards selection:

```javascript
const replaceAllText = (editorState, text) => {
  const contentState = editorState.getCurrentContent();
  const selectionState = editorState.getSelection();

  const isBackward = selectionState.getIsBackward();

  const firstBlock = contentState.getFirstBlock();
  const lastBlock = contentState.getLastBlock();

  const leftmostBlock = !isBackward ? firstBlock : lastBlock;
  const rightmostBlock = !isBackward ? lastBlock : firstBlock;

  const rightmostBlockLength = rightmostBlock.getLength();

  const anchorKey = leftmostBlock.getKey();
  const anchorOffset = !isBackward ? 0 : rightmostBlockLength;

  const focusKey = rightmostBlock.getKey();
  const focusOffset = !isBackward ? rightmostBlockLength : 0;

  const newSelectionState = selectionState.merge({
    anchorKey,
    anchorOffset,
    focusKey,
    focusOffset,
    hasFocus: true,
  });

  return EditorState.push(
    EditorState.moveFocusToEnd(editorState),
    Modifier.replaceText(contentState, newSelectionState, text)
  );
};
```

**Comment by SnowDiamond** [comment]
Hi, I have same issue with caret. I tried:
```
reset() {
  const newState = EditorState.createEmpty();
  this.setState({editorState: EditorState.moveFocusToEnd(newState)});
}
```
It works correct, but plugins (hashtag, emojione, etc.) doesn't works after reset().

and also **paulyoung** way to avoid this behavior, but doesn't work for me at all.

**Comment by SnowDiamond** [comment]
Solved with this code:
```
    const editorState = EditorState.push(this.state.editorState, ContentState.createFromText(''));
    this.setState({editorState: EditorState.moveFocusToEnd(editorState)});
```
It's clear input, caret in correct place, and plugins works.
