### ISSUE TITLE
After removing an inline style at the end of a string and then hitting return, the inline style remains

### ISSUE THREAD

**Issue by huangbong** [facebook/draft-js#412]
Using underline as an example:

![](http://g.recordit.co/OejE1iOcsm.gif)

When you hit return the Underline becomes highlighted again and the corresponding typed text on the next line is underlined.

**Comment by hellendag** [comment]
Thanks for reporting!

I think the appropriate fix here would be to reapply any inline style override within https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/commands/keyCommandInsertNewline.js#L18.
