### ISSUE TITLE
Possibility to override the core class names

### ISSUE THREAD

**Issue by frenzzy** [facebook/draft-js#413]
[src/component/base/DraftEditor.react.js](https://github.com/facebook/draft-js/blob/1ce48f67728681fcb7c24a73ac26fa8b97a6e909/src/component/base/DraftEditor.react.js#L217-L220) uses a special class names, for example:
- `DraftEditor/root`
- `DraftEditor/editorContainer`
- `public/DraftEditor/content`
- etc

But how we can see at [facebook.com](https://www.facebook.com/), it uses minimized 5-digit names of these same classes:
_..looks like [CSS Modules](https://github.com/css-modules/css-modules) usage_
![facebook](https://cloud.githubusercontent.com/assets/640669/15498602/f5dc599a-21a8-11e6-8a53-8d00e80fbf90.png)

How we can redefine Draft.js class names in our own projects the same way?
It seems at the moment the editor does not provide the api to change the core class names..

**Comment by spicyj** [comment]
This ties into our internal CSS build system and it's not going to be practical for us to support this in open source – it's unlikely that it will make a practical difference for anyone so hopefully it isn't a big deal for you. If you're interested, we statically transform calls to `cx()` using a Babel transform that replaces the class names with a minified version. (We never reference classes with a slash without using `cx()`.) If you were motivated you could implement the same thing by building Draft from source but it's unlikely to be worth the time it would take you to set it up.
