### ISSUE TITLE
Toggle inline styles to current block(s), even when it is not fully selected

### ISSUE THREAD

**Issue by lmgonzalves** [facebook/draft-js#417]
First of all, thank you very much for making public this fantastic editor.

I'm trying to do something simple, at least I think so :) I want to toggle inline styles for the entire current block(s), as if fully selected, even when it is not. Even with the clear understanding that I have to play with [`SelectionState`](https://facebook.github.io/draft-js/docs/api-reference-selection-state.html), I can't understand how to do it.

This is what I have so far (the basic functionality), taken from the [RichEditor](https://github.com/facebook/draft-js/blob/master/examples/rich/rich.html) example:

```js
_toggleInlineStyle(inlineStyle) {
  this.onChange(
    RichUtils.toggleInlineStyle(
      this.state.editorState,
      inlineStyle
    )
  );
}
```

Thanks again for this awesome project!

**Comment by pveyes** [comment]
First you have to change your selection into entire block. To do that you can set anchorOffset to 0, and focusOffset to content length, then apply using forceSelection which will return new editorstate. You can then use the new editor state to perform the operation you want, like this

```js
const editorState = this.state.editorState;
const currentKey = editorState.getSelection().getAnchorKey();
const currentBlock = editorState.getCurrentContent().getBlockForKey(currentKey);
const selectionState = SelectionState.createEmpty();
const entireBlockSelectionState = selectionState.merge({
  anchorKey: currentKey,
  anchorOffset: 0,
  focusKey: currentKey,
  focusOffset: currentBlock.getText().length
});

const newEditorState = EditorState.forceSelection(
  editorState,
  entireBlockSelectionState
);

// do what you want using newEditorState here, e.g:
this.onChange(
  RichUtils.toggleInlineStyle(
    newEditorState,
    inlineStyle
  )
);
```

**Comment by lmgonzalves** [comment]
Thanks a lot @pveyes, that works like a charm! Draft documentation lacks examples like this.

Just one more thing: Is there any way to do this for all selected blocks? I mean the styles only apply for a block, even if other selected.

The latter is a plus, thank you very much for this helpful example.

**Comment by pveyes** [comment]
ah sorry, you should use current focus key instead of using anchor key in `selectionState.merge`

```
{
  anchorkey: editorState.getSelection().getAnchorKey()
  focusKey: editorState.getSelection().getFocusKey()
}
```

**Comment by lmgonzalves** [comment]
Sorry, but still not working for multiple selected blocks. Maybe because of: 
```
focusOffset: currentBlock.getText().length
```
is getting only the `lenght` of "currentBlock" instead of all selected?

Thanks for the link, I definitely need to check it.

**Comment by pveyes** [comment]
yes, you should also change the focusOffset, use focusKey to get currentBlock instead of anchorKey

**Comment by lmgonzalves** [comment]
Yeah, it's solved now! Thanks again!

**Comment by anztrax** [comment]
thanks fatih @pveyes
