### ISSUE TITLE
convertFromHTML lost inline style

### ISSUE THREAD

**Issue by Zulfia73** [facebook/draft-js#418]
`const blockArray = convertFromHTML(this.state.body);
const editorState = createWithContent(ContentState.createFromBlockArray(blockArray))`

when i insert `editorState `, all inline style lost, what is problem may be?
thanks

**Comment by Catlite91** [comment]
Why you close the issue?

**Comment by Zulfia73** [comment]
@Catlite91  i begin send editorState to server

**Comment by Uysim** [comment]
@Zulfia73 you closed this because you can't fix it?

**Comment by Uysim** [comment]
@Catlite91 you found the solution?
