### ISSUE TITLE
serialization?

### ISSUE THREAD

**Issue by brigand** [facebook/draft-js#422]
I may be missing something in the docs, but how do you serialize a draft.js editor, send it to the server, and then load it again?

I know there are third party things for creating html, but I don't see how you'd load that back into the editor.

This is half a support question, and half a request for docs. I can write them once I figure it out.

I'm guessing you can't just .toJS/fromJS on the EditorState because there are sub-objects with special methods.

**Comment by spicyj** [comment]
You can use these:

http://facebook.github.io/draft-js/docs/api-reference-data-conversion.html#content

**Comment by brigand** [comment]
Thanks! Sorry I missed that.

**Comment by spicyj** [comment]
Don't apologize! Feel free to send a PR to make this clearer if you looked elsewhere in the docs.

**Comment by brigand** [comment]
I wrote a guide for doing it, but I'm not sure if it should be its own page, or part of getting started. Part of it is copied from the reference page. Also, feedback?

---

# Serialization

Because a text editor doesn't exist in a vacuum and it's important to save 
contents for storage or transmission, you will want to be able to convert 
`ContentState` into a plain JS object, and vice versa.

```js
import {Editor, EditorState, convertToRaw} from 'draft-js';

class MyEditor extends React.Component {
  constructor(props) {
    super(props);
    this.state = {editorState: EditorState.createEmpty()};
    this.onChange = (editorState) => this.setState({editorState});
    this.onSave = () => {
      var content = this.state.editorState.getCurrentContent();
      var raw = convertToRaw(content);
      $.post('/api/comment', {comment: raw}, () => {
        alert('Saved');
      });
    };
  }
  render() {
    return (
      <div>
        <Editor editorState={this.state.editorState} onChange={this.onChange} />
        <button onClick={this.onSave}>Save</button>
      </div>
    );
  }
}
```

You can then load it back into an `EditorState`.

```js
var editorState = EditorState.createWithContent(convertFromRaw(raw));
```

To display this elsewhere in your site, you can create an Editor component with
the `readOnly` prop set to `true`.

```js
<Editor editorState={editorState} readOnly />
```

Note that the Draft library does not currently provide utilities to convert to and from markdown or markup, since different clients may have different requirements for these formats. We instead provide JavaScript objects that can be converted to other formats as needed.

**Comment by barbu110** [comment]
@brigand your guide it explains it pretty well.

However I have some questions regarding saving and reading from a database. So, say I write a blog post and get its content using `convertToRaw`. Should I save and read JSON in/from the database?

**Comment by brigand** [comment]
@barbu110 yeah, and since you don't need to query it, you can just store it as a string instead of using a json data field.

**Comment by Grsmto** [comment]
This should definitely be accessible somewhere in the doc. I feel like as soon as you use a rich text editor you want to input/output datas from it and this is lacking of informations on how/what can/cannot do Draft about this.
I saw loads of issues related to html conversion too, having a line saying that Draft doesn't support HTML export (and the import is very basic) somewhere on the `Data Conversion` page would help.

Also to complete this guide, I would say that would may need to serialise this as JSON like so:
Sending to DB:
`JSON.stringify(convertToRaw(content))`

Reading from DB:
`Draft.convertFromRaw(JSON.parse(content))`

**Comment by kevinguard** [comment]
@brigand, What if we want to get the raw data after reading it from database and render it as HTML? Is there any clean way you might be aware of to accomplish this? I know `stateToHTML` from `draft-js-export-html` but that doesn't, for example, support `iframe`s. It simply removes them! Thoughts?

**Comment by brigand** [comment]
@kevinguard did you try `<Editor editorState={editorState} readOnly />`?

**Comment by kevinguard** [comment]
@brigand Thanks for prompt response. It worked like a charm! 👍

**Comment by tj** [comment]
Definitely a little tricky to find in the docs, "data conversion" -> "import & export" or something maybe.

**Comment by johnlin0207** [comment]
thanks a lot!

> I wrote a guide for doing it, but I'm not sure if it should be its own page, or part of getting started. Part of it is copied from the reference page. Also, feedback?
> 
> # Serialization
> Because a text editor doesn't exist in a vacuum and it's important to save
> contents for storage or transmission, you will want to be able to convert
> `ContentState` into a plain JS object, and vice versa.
> 
> ```js
> import {Editor, EditorState, convertToRaw} from 'draft-js';
> 
> class MyEditor extends React.Component {
>   constructor(props) {
>     super(props);
>     this.state = {editorState: EditorState.createEmpty()};
>     this.onChange = (editorState) => this.setState({editorState});
>     this.onSave = () => {
>       var content = this.state.editorState.getCurrentContent();
>       var raw = convertToRaw(content);
>       $.post('/api/comment', {comment: raw}, () => {
>         alert('Saved');
>       });
>     };
>   }
>   render() {
>     return (
>       <div>
>         <Editor editorState={this.state.editorState} onChange={this.onChange} />
>         <button onClick={this.onSave}>Save</button>
>       </div>
>     );
>   }
> }
> ```
> 
> You can then load it back into an `EditorState`.
> 
> ```js
> var editorState = EditorState.createWithContent(convertFromRaw(raw));
> ```
> 
> To display this elsewhere in your site, you can create an Editor component with
> the `readOnly` prop set to `true`.
> 
> ```js
> <Editor editorState={editorState} readOnly />
> ```

helps me,thanks a lot!

**Comment by hayk-saryan** [comment]
What if I want to query and modify the data in the database?
I need to somehow persist it normalized in a relational database so I can benefit from using foreign keys, do joins.
What is the general approach for that case?
