### ISSUE TITLE
Same component for display and edit mode

### ISSUE THREAD

**Issue by anothermohit** [facebook/draft-js#423]
Can I keep the display and edit modes of Editor in a single react component? The display mode would load the initial editor state from the database (convertFromRaw) and clicking on an edit button (for the writer only) would make the content Editable and display a submit button to update/create the content.

Not sure if I am making sense but I want to use the same React component to 
- display the editor content to readers, and
- load editor mode for the writer (with Edit/Submit buttons) 

Any example implementing this would be great (with standard practices of switching between display/Edit mode)

**Comment by anothermohit** [comment]
Just found out that I can switch on display mode with this - 
``this.setState({
      editorEnabled: !this.state.editorEnabled
    });``

But I am still curious if this approach is recommended or not.

**Comment by spicyj** [comment]
Draft doesn't do anything called `editorEnabled` so I'm not sure where you got that. You can set `readOnly={true}` on the root DraftEditor component though.

**Comment by anothermohit** [comment]
Yeah, sorry about that. It's calling readOnly - [https://github.com/brijeshb42/medium-draft/blob/master/src/editor.js#L284](url)
