### ISSUE TITLE
dataTransfer property being null in the drop event object throws an error

### ISSUE THREAD

**Issue by delijah** [facebook/draft-js#425]
If the dataTransfer property is null in the event object, draft-js code throws an error. For me this happens because i am implementing an own drag and drop mechanism (through mousedown). But i think according to the specs, the dataTransfer property is allowed to be null in the event object. So draft-js should be able to handle this, or ignore this...

**Comment by hellendag** [comment]
Can you provide more details? Where is the error thrown?

**Comment by delijah** [comment]
Sorry for the late response. I've been digging into this again and realised, that the actual problem is another. I will close this issue and open another one with a more precise title and description.
