### ISSUE TITLE
Performing EditorState changes in a reducer

### ISSUE THREAD

**Issue by carlesba** [facebook/draft-js#426]
I'm trying to build a **Rich Editor** that handles my own markup language. The app is based on **Redux** architecture so every change on the state has to be handled by a reducer.

The simplest way for me to handle all the rules on the editor has been dispatching a single action every time the `<Editor/>` calls **`onChange`** (instead of calling `this.setState`). Then, on the reducer, I can analyze each particular case and apply the changes I need. After this, my component will be updated with the new State and same for the `<Editor/>`.

The problem I'm facing right now is that I'm modifying the state several times on every action called. For example, if some line has this `\n#` I need to remove `\n` and move the # and everything after to a new block. This is done by using `Modifier` several times. When a new state is eventually passed down, for some unexpected reason, `onChange` is being executed twice when it shouldn't and it seams like **this is corrupting my state**.

When I debugged the app, I found `getLastChangeType` was pointing to `apply-entity` on this ghost `onChange` calls, what is weird as I wasn't playing with entities at all.

Finally, I found this issue on the repo: https://github.com/facebook/draft-js/issues/161 where you suggest to not to make changes on the `onChange` callback.

So, is there a better way of structuring my redux app so I can handle complex rules like the one above with the reducers?

**Comment by oyeanuj** [comment]
Very interested in this answer as well. I was hoping to integrate this with Redux-form that rest of my application (and that page needs to use). Redux-form, it seems, also depends on onChange event.

http://redux-form.com/5.2.5/#/faq/custom-component?_k=q20jdm

**Comment by kube** [comment]
Any news on this?

**Comment by diegolaciar** [comment]
Any help on how to integrate with redux-form v7 ?
