### ISSUE TITLE
convertFromRaw returns Array and not ContentState

### ISSUE THREAD

**Issue by davisml** [facebook/draft-js#43]
From the documentation

> convertFromRaw(rawState: RawDraftContentState): ContentState
> Given a raw state, convert it to ContentState object. This is useful when restoring contents to use within a Draft editor.

From my testing, convertFromRaw actually returns an Array of ContentBlock objects. To convert this back to a ContentState you must do the following:

> ContentState.createFromBlockArray(convertFromRaw(rawData))

**Comment by hellendag** [comment]
#30 resolved this. Thanks!
