### ISSUE TITLE
Miss style:color in html

### ISSUE THREAD

**Issue by Catlite91** [facebook/draft-js#431]
While I use 
`let html = "<div style=\"color:#A52A2A\">HELLO</div>"
 EditorState.createWithContent(ContentState.createFromBlockArray(convertFromHTML(html)))`
the color is disappeared.
Is there something wrong with my code?

**Comment by adamtal3** [comment]
@Catlite91 - did you find a way to make `convertFromHtml` understand colors?

**Comment by Catlite91** [comment]
@adamtal3 I'v no idea this time,but #358 may help you.
