### ISSUE TITLE
RichExample gives error: minified exception occurred

### ISSUE THREAD

**Issue by conor909** [facebook/draft-js#434]
I'v rewritten the Rich Example using reactClasses as oppose to components but Im getting the following error:

`invariant.js:13: `
`Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.`

I have a normal JSPM setup, so I believe I'm not using minified versions of draft or react.
My config maps:
`"draft-js": "npm:draft-js@0.7.0"`
`"react": "npm:react@0.14.8"`

Here is a link to my code on gist: https://gist.github.com/conor909/2c040c1983ef42f988a45a351081429f

**Comment by mitermayer** [comment]
Worth checking to see if you have the correct UTF-8 meta tag

**Comment by conor909** [comment]
Thanks for the reply @mitermayer.  Yes I have `<meta charset="utf-8">` in my `index.html`

**Comment by ghigt** [comment]
Could you send the error without minification?

**Comment by conor909** [comment]
I think that's the problem, I have a normal JSPM setup, so I believe I'm not using minified versions of draft or react.

My config maps:
`"draft-js": "npm:draft-js@0.7.0"`
`"react": "npm:react@0.14.8"`

**Comment by conor909** [comment]
It seems even though I'v typed text into the input box, my `contentState` never updates and never has text inside it.

**Comment by spicyj** [comment]
It sounds like you're using react/dist/react.min.js; please use react/dist/react.js instead. I don't know jspm so I can't tell you how to do that.

**Comment by conor909** [comment]
I believe there is an issue with JSPM pulling the minified version of react, so I need to upgrade JSPM.
