### ISSUE TITLE
block.getKey is not a function

### ISSUE THREAD

**Issue by joshdmiller** [facebook/draft-js#440]
Updating from v0.5 to latest seems to break the block API's `getKey` method. I was able to work around it in our code, but the following fails because of an internal call to the same method:

```js
ContentState.createFromBlockArray( convertFromRaw( value ) );
```

The API docs still show this method. I'll try to hunt this down later, but for now am just dropping the note here.

**Comment by hellendag** [comment]
As of v0.6, `convertFromRaw` will provide a `ContentState` directly, and you do not need to use `createFromBlockArray` to perform the conversion.

https://github.com/facebook/draft-js/releases/tag/v0.6.0

**Comment by joshdmiller** [comment]
I appreciate the response and I'll try that for `convertFromRaw`, but it doesn't quite solve this issue.

`block.getKey` is in the API docs and there is a function in the current version of `draft-js` that calls it. Yet this method does not exist.

**Comment by joshdmiller** [comment]
Strike that. Very odd coincidence, but a third-party piece of code cause the exact same error elsewhere. Thank you for the help, I'm sorry for missing the changelog entry, and I consider the issue closed.

**Comment by samelie** [comment]
Found that immutable 4.0.0 was causing this as of draft-js 0.10.5.

**Comment by JacobIRR** [comment]
@samelie I'm getting this error in  immutable 4.0.0 / draft-js 0.10.5. What is the fix?

**Comment by maikelmclauflin** [comment]
also happening in immutable@3.8.2, draft-js@^0.10.5

**Comment by funJia** [comment]
immutable@3.7.6, draft-js@^0.10.5 is ok

**Comment by ddelrio1986** [comment]
Is anyone able to provide an example that triggers this issue?

**Comment by joecervino** [comment]
Also happening in draft-js@^0.11.4 upon minification

**Comment by Canna71** [comment]
Also with draft-js@0.11.5 and various immutable versions. Any idea?

**Comment by Hyvor** [comment]
I had the same problem. Removing immutable from devDependencies solved the problem. But not sure why - it just works.

**Comment by dperetti** [comment]
Suddenly started to experience this issue as well 🤔

**Comment by dfyz011** [comment]
Me too

**Comment by KumarAbhirup** [comment]
I reverted to immutable@3.7.6 it is working now!

**Comment by mathura333** [comment]
> immutable@3.7.6, draft-js@^0.10.5 is ok
Not working for me
