### ISSUE TITLE
Get selection as text

### ISSUE THREAD

**Issue by SamyPesse** [facebook/draft-js#442]
I was not able to find any method like `getTextSelection(contentState: ContentState, selection: SelectionState, blockDelimiter: String) -> String`.

Is there one that I missed?

**Comment by guitardave24** [comment]
Maybe it's early and I'm not fully awake yet, but what is your use case? (what is blockDelimiter for?)

**Comment by SamyPesse** [comment]
My use case is to get the selected text in the editor to write it in a custom clipboard (precise use case is hard to describe).

Here is a basic (non tested) implementation that I come up with, but I was wondering if Draft already includes something like this since it has `ContentState.getPlainText`:

```js
/**
 * Get current selected text
 * @param  {Draft.ContentState}
 * @param  {Draft.SelectionState}
 * @param  {String}
 * @return {String}
 */
function _getTextSelection(contentState, selection, blockDelimiter) {
    blockDelimiter = blockDelimiter || '\n';
    var startKey   = selection.getStartKey();
    var endKey     = selection.getEndKey();
    var blocks     = contentState.getBlockMap();

    var lastWasEnd = false;
    var selectedBlock = blocks
        .skipUntil(function(block) {
            return block.getKey() === startKey;
        })
        .takeUntil(function(block) {
            var result = lastWasEnd;

            if (block.getKey() === endKey) {
                lastWasEnd = true;
            }

            return result;
        });

    return selectedBlock
        .map(function(block) {
            var key = block.getKey();
            var text = block.getText();

            var start = 0;
            var end = text.length;

            if (key === startKey) {
                start = selection.getStartOffset();
            }
            if (key === endKey) {
                end = selection.getEndOffset();
            }

            text = text.slice(start, end);
            return text;
        })
        .join(blockDelimiter);
}
```

**Comment by guitardave24** [comment]
Nope, that's pretty much a good way to do it. :)

**Comment by hellendag** [comment]
This is a case where [`getContentStateFragment`](https://github.com/facebook/draft-js/blob/master/src/model/transaction/getContentStateFragment.js) would be useful if exposed.

```js
const fragment = getContentStateFragment(contentState, selectionState);
const plainText = fragment.map((block) => block.getText()).join(delimiter);
```

I think I'm fine with exposing it -- there's a PR to expose pretty much all of the transaction modules anyway.

**Comment by Robert-Christopher** [comment]
@hellendag Any idea when the PR is getting merged ?

**Comment by robinmaben** [comment]
@SamyPesse I was able to piece together something like the following - 
```
// Get block for current selection
let selection = editorState.getSelection();
const anchorKey = selection.getAnchorKey();
const currentContent = editorState.getCurrentContent();
const currentBlock = currentContent.getBlockForKey(anchorKey);

//Then based on the docs for SelectionState -
const start = selection.getStartOffset();
const end = selection.getEndOffset();
const selectedText = currentBlock.getText().slice(start, end);
```

It works, but I'm looking to forward to hearing why/if this is not the best the way to do it. @hellendag  @davidbyttow

**Comment by ericbiewener** [comment]
@robinmaben Your solution assumes the selection doesn't span more than a single block. If it does, you need to grab all the selected blocks, e.g.

```
function getSelectedBlocks(editorState) {
  let selection=editorState.getSelection()
  let content = editorState.getCurrentContent()
  let startKey = selection.getStartKey()
  let endKey = selection.getEndKey()
  let blockMap = content.getBlockMap()

  let blocks = blockMap.toSeq().skipUntil(function (_, k) {
    return k === startKey
  }).takeUntil(function (_, k) {
    return k === endKey
  }).concat([[endKey, blockMap.get(endKey)]]).map(function (block) {
    return block
  })

  return blocks
}
```

From there, you would grab the selected text of the starting block with something like `startBlockText.slice(start)`, the text of the ending block with `endBlockText.slice(0, end)`, and all the text of the blocks in between.

**Comment by bimalgrg519** [comment]
window.getSelection().toString()

**Comment by liesislukas** [comment]
@hellendag any update on exposing `getContentStateFragment`?
