### ISSUE TITLE
How to clear content on return?

### ISSUE THREAD

**Issue by psachs21** [facebook/draft-js#445]
I'd like to clear the content state after enter is pressed. 

Something like this:

```js
<DraftEditor editorState={this.state.editorState} handleReturn={onReturn}/>
...
handleReturn = () => {
  this.setState({
    editorState: EditorState.createEmpty()
  });
}
```

This clears the input but the next key input doesn't properly move the text cursor. 

Any ideas?

**Comment by guitardave24** [comment]
There are several ways to do this, you could just create a new content state altogether and push it in the editor, but you'd need to reset the selection to the new block key and offset 0. Alternatively, you could use `Modifier.replaceText` on the block you wish to clear by creating a selection from 0 to the length of the block, then use `EditorState.push` with the new content state and `EditorState.forceSelection(editorState, contentState.getSelectionAfter());`

**Comment by psachs21** [comment]
I'm still pretty new to draft-js, how would i reset the selection to the new block key and offset? The APIs are a little bit more complex than one would hope.

**Comment by guitardave24** [comment]
Sure, sorry about that. It's still early days for the API that's for sure!

Disclaimer: I didn't test this, and there are certainly other ways to achieve the same effect. This makes no assumptions about the length of the document and clears the entire thing.

```js
handleReturn = () => {
  let {editorState} = this.state;
  let contentState = editorState.getCurrentContent();
  const selection = editorState.getSelection();
  const firstBlock = contentState.getFirstBlock();
  const lastBlock = contentState.getLastBlock();
  const allSelected = new SelectionState({
    anchorKey: firstBlock.getKey()
    anchorOffset: 0,
    focusKey: lastBlock.getKey(),
    focusOffset: lastBlock.getLength()
    hasFocus: true
  });
  contentState = Modifier.removeRange(contentState, allSelected, 'backward');
  editorState = EditorState.push(editorState, contentState, 'remove-range');
  editorState = EditorState.forceSelection(contentState, contentState.getSelectionAfter());
  this.setState({editorState});
}
```

**Comment by psachs21** [comment]
Alright, that seems to have worked. It looks kinda cumbersome to just clear the content. May fit as a utility method in EditorState. 

Thanks!
