### ISSUE TITLE
handleBeforeInput and deletions

### ISSUE THREAD

**Issue by paulyoung** [facebook/draft-js#448]
I'm currently making some changes to the editor state in `handleBeforeInput`.

One issue I'm seeing is that `handleBeforeInput` doesn't get called for deletions, which leads to undesirable results.

While I could possibly work around this by using `handleKeyCommand` for the `delete` and `backspace` commands, that still doesn't account for text removed by cutting (⌘ + x) on OS X.

What would be the recommended way to address this?

**Comment by hellendag** [comment]
Right, `handleBeforeInput` is only intended to handle character insertions, not removal. For deletion behavior, `handleKeyCommand` is the approach I would recommend.

The Cut command is trickier. One option could be to add the command to the key binding and allow the caller to handle it manually, though this delegates a lot of responsibility and risk -- see the complexity of [editOnCut](https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnCut.js). :)

Can you provide more details about the behavior of your editor? What kinds of state changes do your `handleBeforeInput` and `handleKeyCommand` make?

**Comment by paulyoung** [comment]
@hellendag I'm handing off the input to a lexer, parser, (and soon type checker) then providing syntax highlighting by updating the `CharacterList` and using `replaceText` or `replaceBlockFragment`. I'm also underlining the text at the error position and providing error information.

I initially used a decorator as mentioned in https://github.com/facebook/draft-js/issues/47#issuecomment-223049922 but it was too limiting. So far using `handleBeforeInput` I can:

- surface error messages beyond the decorated text in a reasonable way
- access the previous lexemes and potentially only update a subset of the text, instead of processing everything again on every keystroke

It also seems like a better approach for adding more features such as autocomplete.

**Comment by hellendag** [comment]
Interesting!

One question: would it be overkill to always perform your highlighting behavior in `onChange` if the `ContentState` has changed?

If not, you'd then always be able to know that some content is different, regardless of how it changed. Perhaps you could compare the `blockMap` objects of the distinct `ContentState` objects to identify differing lines, then perform your processing on only those lines.

FWIW, for Facebook mention autocomplete, we always trigger autocompletion in the parent component's  `componentDidUpdate` if the selection is collapsed. Then we just pay attention to the selected block (at the selection offset, of course) and can ignore everything else. Further, we can use information about when the selection state changes so that we can trigger autocompletion if the user just moves the cursor to another position in the editor.

**Comment by paulyoung** [comment]
> One question: would it be overkill to always perform your highlighting behavior in `onChange` if the `ContentState` has changed?

Not at all! I tried that and we discussed my attempts to use `onChange` in https://github.com/facebook/draft-js/issues/427 :)

It does sound like `onChange` is what I want, but I couldn't figure out how to prevent the issue I described in https://github.com/facebook/draft-js/issues/427. I'd love to figure that out somehow.

Thanks for the tips on autocomplete!

**Comment by paulyoung** [comment]
@hellendag in #427, you said: 

> The inability to intercept and change `EditorState` for a native `onBeforeInput` event is a known problem, and one that I'd really like to resolve. It's a notable limit on customizable insertion behavior.

if you have any ideas on how to make this happen I'd be happy to work on it and submit a pull request.

**Comment by paulyoung** [comment]
@hellendag I think I have a solution to this. Will try and put a pull request together.

**Comment by phuczeero** [comment]
As you guys discussed, in **onChange** handler, I detect the `remove-range` of **lastChangeType**, and use **handleKeyCommand** property to distinguish `cut` command and `delete`, `backspace` commands by set a flag.
Is there any better way to prevent `cut` event, like `handlePastedText` prop?

**Comment by afcjunior** [comment]
I'm just trying to disable it, so a handleCutText prop would be much welcome.
