### ISSUE TITLE
Document how to create a targetRange.

### ISSUE THREAD

**Issue by kristoferjoseph** [facebook/draft-js#451]
In the Entities documentation there is a reference to `targetRange` but there is no documentation on what is required to create one.

https://facebook.github.io/draft-js/docs/advanced-topics-entities.html#content
```
const key = Entity.create('LINK', 'MUTABLE', {href: 'http://www.zombo.com'});
const contentStateWithLink = Modifier.applyEntity(
  contentState,
  targetRange,
  key
);
```

This has been brought up previously in #409

**Comment by kristoferjoseph** [comment]
Reason I ask is I assumed this was the blockKey with start and end as the offsets. I get a "record undefined" error when I do this.

**Comment by hellendag** [comment]
The key values should be block keys, so that's fine.

`Modifier.applyEntity` accepts a `ContentState` as its first parameter, not an `EditorState`. https://github.com/facebook/draft-js/blob/master/src/model/modifier/DraftModifier.js#L214

Also, when calling `EditorState.push`, you must include an `EditorChangeType` for the third parameter.  I should really add an invariant for this.

**Comment by kristoferjoseph** [comment]
Thanks for the reply. I am using content state if you look: `editorState.getCurrentContent()` _updated the example_ I also have a 'apply-entity' type. This was copy/pasted/edited from actual code into a reduced case so I would not be dismissed off hand. _which seems to have backfired_

The error I am getting is that the record is undefined. When internally `Modifier.applyEntity` calls `applyEntityToContentBlock` and the `CharacterMetadata.applyEntity(characterList.get(start), entityKey)` fails to return a `record`

What am I missing?

![screenshot 2016-06-08 11 06 23](https://cloud.githubusercontent.com/assets/76308/15905264/1d70d3ac-2d69-11e6-8dd2-7519a4688513.png)

**Comment by hellendag** [comment]
Can you verify that the `targetRange` object has valid key/offset values, and that there is a relevant text range for that range?

**Comment by kristoferjoseph** [comment]
Looks like it. What else can I do to validate this?
![screenshot 2016-06-08 13 01 50](https://cloud.githubusercontent.com/assets/76308/15909000/3ab6b638-2d79-11e6-8617-8892b6af538a.png)

**Comment by kristoferjoseph** [comment]
My whole plan here was to update the Tweet example to demo how to create an entity range from user input, but alas. Maybe it doesn't work this way?

**Comment by kristoferjoseph** [comment]
Closing due to dead end conversation.
