### ISSUE TITLE
Bug in example

### ISSUE THREAD

**Issue by oeddyo** [facebook/draft-js#463]
Hi, 

I just found a bug in one example:

https://github.com/facebook/draft-js/blob/master/examples/media/media.html

If you click the button "add image" and don't type anything, this.state.editorState will be set to null because the lines: 

 _addMedia(type) {
          const src = window.prompt('Enter a URL');
          if (!src) {
            return;
          }

          const entityKey = Entity.create(type, 'IMMUTABLE', {src});

          return AtomicBlockUtils.insertAtomicBlock(
            this.state.editorState,
            entityKey,
            ' '
          );
        }

will return null if src is not set (specifically if(!src) line). Then afterwards you can't upload any images since the whole thing is broken, because this.state.editorState is set to null already. 

I 'd change

to:
      if (!src) {
            return this.state.editorState;
        }

I can submit a PR if this is not my illusion

**Comment by hellendag** [comment]
We shouldn't be using `window.prompt` in that example, since it causes problems with selection state.

It should be an input instead, like in the link example. Or just buttons.
