### ISSUE TITLE
Can't limit maxDepth of list when pasting.

### ISSUE THREAD

**Issue by houkanshan** [facebook/draft-js#474]
Since `RichUtils` has provided `onTab(event, editorState, maxDepth)` to change the depth of a list item, with the ability of limiting max depth. I think there should also be a method to limit  the max depth when pasting, for consistency and for preventing unexpected depth.

Currently I'm fixing it by rewriting the depth with the these code, in `Editor.props.onChange`.

```js

  onChange = (editorState) => {
    let contentState = editorState.getCurrentContent()

    if (contentState !== this.state.editorState.getCurrentContent()) {
      if (editorState.getLastChangeType() === 'insert-fragment') {
        let blockMap = contentState.getBlockMap()
        const blocks = blockMap
          .filter((block) => block.getDepth() > MAX_LIST_DEPTH)
          .map((block) => block.set('depth', MAX_LIST_DEPTH))

        blockMap = blockMap.merge(blocks)
        contentState = contentState.merge({ blockMap })
        editorState = EditorState.set(editorState, {
          currentContent: contentState
        })
      }
    }

    this.setEditorState(editorState)
  }
```

I think it could be costly by searching through the whole `blockMap`.

Thanks!

-------

Edit: It might be a problem of paste, which is so powerful and its generated fragment is not changeable. If I want to limit the using of  some default styles (e.g. list, bold, header-*) , I should also limit them when pasting. `blockRenderMap` and  `handlePastedText` will help, but they're not enough.

**Comment by hellendag** [comment]
There could potentially be a configuration prop for paste handling behavior, with this field included. Right now `MAX_DEPTH` is hardcoded in paste processing code, which is certainly not ideal. I assume you're aiming to have a smaller depth value?

**Comment by houkanshan** [comment]
Thanks for reply!

> I assume you're aiming to have a smaller depth value?

Yes, sorry for not making it clear.

I just found there are already discusses on it, either a configuration prop (#166) or post process ability for  `converFromHTMLToContentBlocks` (#380) will help. 

I'm closing it, thanks.
