### ISSUE TITLE
Creating new line and triple clicking on previous line(s) to select creates empty selection

### ISSUE THREAD

**Issue by paulxuca** [facebook/draft-js#478]
I noticed that when I created two lines, and triple clicked on the first line, it would select the content of the first line, as well as an empty character at the end of the first line. 
![draft js bug](https://cloud.githubusercontent.com/assets/7885473/16198364/af74644e-36d3-11e6-8a7d-ad701ff0444d.gif)

**Comment by hellendag** [comment]
Not a bug. Try the same behavior on a textarea. :)
