### ISSUE TITLE
Pasting Bold Text from Google Docs Bolds Everything

### ISSUE THREAD

**Issue by casesandberg** [facebook/draft-js#481]
I copy this text from a google doc:

**Lorem ipsum dolor sit amet,** _Vivamus vel felis_ at nunc tincidunt pharetra.

The output in draft.js editor is entirely bold:

![image](https://cloud.githubusercontent.com/assets/4633636/16246596/bb6c402c-37ba-11e6-8f1b-ce4a507c1765.png)

**Comment by hellendag** [comment]
I think @clowbrow might be taking a look at this. Can you provide the HTML of your paste?

**Comment by CLowbrow** [comment]
Ok I have a repro for this from a google doc with some stuff bolded and some stuff not: 

```
<b style="font-weight:normal;" id="docs-internal-guid-6f1865c9-8eb1-67c8-db93-37392ae7dfc7">
  <span style="font-size:14.666666666666666px;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Get Images </span>
  <span style="font-size:14.666666666666666px;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">This isn't enough!</span>
</b>
```

Looks like the whole thing is wrapped in a <b> tag. Then an internal tag sets the font-weight back to 400 (normal). We never test if something is "un-bolded" so I guess we can do that.

**Comment by casesandberg** [comment]
WOOT 🐼

**Comment by dimicuss** [comment]
Nothing changes on Draft.js@0.11.1. "B" tag with font-style = "normal" still detects as bold style range.
