### ISSUE TITLE
Support for non-React applications?

### ISSUE THREAD

**Issue by puopg** [facebook/draft-js#489]
Just was wondering if there is some way to take advantage of this without React. My application is Angular and sorta was hoping I could use this somehow hehe. Thanks!

**Comment by spicyj** [comment]
You can build an editor in React and use it inside of your Angular app, but Draft is a framework for building editors, not an editor – so you'll need to learn enough React to customize it to your needs. There's no way to use Draft without React.

**Comment by strogonoff** [comment]
In case someone finds it useful, here’s Draft.js wrapped as an Angular library: https://github.com/strogonoff/ngx-draft-js
