### ISSUE TITLE
Example in overview section is not working

### ISSUE THREAD

**Issue by iroy2000** [facebook/draft-js#50]
http://facebook.github.io/draft-js/docs/overview.html#content

I'm pretty new to this component and want to try it out,  so I just basically reuse what is in the overview section.

But the following error is what I get

`Cannot read property 'editorState' of null`

What suppose to be the initial editor state ?

Since the example just have  `const {editorState} = this.state;`

**Comment by davisml** [comment]
EditorState.createEmpty() will create an empty EditorState object

**Comment by brandondurham** [comment]
If you add this to your component you should be good to go:

```javascript
export default class YourComponent extends Component {

	state = {
		editorState: EditorState.createEmpty()
	};
	…
}
```

**Comment by iroy2000** [comment]
Ah, thanks a lot, I see, I wish that was in the documentation.
