### ISSUE TITLE
Immutable entity broke with IME

### ISSUE THREAD

**Issue by RaoHai** [facebook/draft-js#503]
* First, we create an `IMMUTABLE` Entity
* Then we type an letter, for example, `E`
* We could see the letter `E` is not in last entity. It's perfect.

![image](https://cloud.githubusercontent.com/assets/566097/16512888/87d28d36-3f92-11e6-921a-e12565d7d410.png)

When using IME:

* Create an `IMMUTABLE` Entity
* Then type letters with IME..
* We could see the letters is in this immutable entity. Is seems incorrect.

![image](https://cloud.githubusercontent.com/assets/566097/16512944/ef9aab4c-3f92-11e6-9afd-68c27664f9e5.png)

Sometime I use immutable entity to create something , e.g. , an emoji. I will alter its font size, so this issue may be causing some unexpected bug 😆 , such as: 

![image](https://cloud.githubusercontent.com/assets/566097/16512994/627c7f5a-3f93-11e6-81c2-c49c4c7e406c.png)

Did I misapply immutable entity? Can you give me a suggestion? 

Draft.js is wonderful. Thank you !

**Comment by hellendag** [comment]
This is not your fault at all. If I understand this correctly, it is a browser issue, and I'm not sure there's anything we can do to fix it. :(

When the IME composition begins, the cursor is within the text node of the immutable entity. During the composition, the text *within that text node* is updated to include the composed characters. The visual output styles those characters accordingly, which makes them look like they are part of the decorated entity.

Upon confirming the IME composition, hopefully you should see the confirmed string revert back to being undecorated, as Draft will force a re-render to decorate only the appropriate ranges of text.

In the case of the emoji, can you try setting the decorator to be `contentEditable={false}`? That may kick the cursor out of the text node.

**Comment by RaoHai** [comment]
Thanks for your suggestion and it works.
