### ISSUE TITLE
I need some advice!!!

### ISSUE THREAD

**Issue by lawjoy114** [facebook/draft-js#505]
attached screenshot is what I'm gonna build with this Editor.
<img width="381" alt="1467203547" src="https://cloud.githubusercontent.com/assets/19499963/16526413/73eceec8-3fb1-11e6-8748-30345fae241b.png">

when I select answer from the dropdown at the top right,the custom block "01.What ...?" should be put to the editor with the style according to attached screenshot.
and should able to type text next or prev of it.

I've checked the https://facebook.github.io/draft-js but can't make the direction.
Could you please advice me shortly how to implement this?

**Comment by hellendag** [comment]
You'll want to use a decorator for this, probably in conjunction with an entity that represents the "token". When the dropdown is clicked, you can create an entity and insert the text with that entity applied to it.

With a decorator that maps to the entity type you choose (perhaps `'TOKEN'` or something like that), you can render the desired string. You can then use `display: inline-block` and `contentEditable={false}` on the decorated component to make the cursor (more or less) do what you want.

**Comment by lawjoy114** [comment]
Hi 
thanks for your help.
I have insert the text with the entity with decoration.
It works fine when I select the option from dropdown based on I set the focus in the middle of the string on editor.
https://www.dropbox.com/s/3zydejms54qjwbb/Screenshot%202016-07-04%2018.43.53.png?dl=0
https://www.dropbox.com/s/b5jaeuleh3pvnn1/Screenshot%202016-07-04%2018.44.22.png?dl=0
But when I do dropdown click based on at the last position of the string like below.
https://www.dropbox.com/s/z7264atz2v4o64j/Screenshot%202016-07-04%2018.43.10.png?dl=0
The cursor position is breaking and can't control.
https://www.dropbox.com/s/lb4dlbmjqbh11pj/Screenshot%202016-07-04%2018.38.12.png?dl=0
And when I do command+a 
https://www.dropbox.com/s/s3detv1an1o4p1z/Screenshot%202016-07-04%2018.39.22.png?dl=0
I got this error.
https://www.dropbox.com/s/bei8ro1atdl6jap/Screenshot%202016-07-04%2018.40.04.png?dl=0



This is the code that I use for the insert entity.


    const answerEntity = Entity.create('ANSWER_BLOCK', 'IMMUTABLE', value);
    const { editorState } = this.state;
    var newEditorState = null;
    if (editorState.getSelection().isCollapsed()) {
      newEditorState = EditorState.createWithContent(
        Modifier.insertText(editorState.getCurrentContent(), editorState.getSelection(),
        value, null, answerEntity), answerBlockDecorator);
    } else {
      newEditorState = EditorState.createWithContent(
        Modifier.replaceText(editorState.getCurrentContent(), editorState.getSelection(),
        value, null, answerEntity), answerBlockDecorator);
    }
    this.setState({
      editorState: newEditorState
    });

but seems like this is not good practice.I think I need to use push() for the update of EditorState.
Is the above cursor issue related with this?

and in case I use push() ,could you let me know how to set the "changeType: EditorChangeType" for the insert entity.
I can't see enough description about this.

Also hope to know how to manage cursor position after I insert the entity.
I want to set the cursor next to the entity after insert it.
Should I use forceSelection() for this?

I really appreciate your help.
Regards..
