### ISSUE TITLE
Best way to sync with Firebase (or any other Database)

### ISSUE THREAD

**Issue by LFra** [facebook/draft-js#507]
Hello,
first of all thanks for sharing this great framework with the community!

I am currently trying to sync the editorState with a Firebase Database. The converting to Raw works great, however fetching the data and updating the editorState doesn't really work (tried convertFromRaw with getBlockMap)

**Comment by spicyj** [comment]
You'll have to give more info. What behavior do you see?

**Comment by LFra** [comment]
Thanks for the super fast answer.

` convertToRaw ` returns an Obj similar to ` { blocks: Array[n] } `.
Whats the best way to turn this into a new editorState (convertFromRaw seems to be the wrong method)?

**Comment by spicyj** [comment]
convertFromRaw gives you a ContentState, then you can use EditorState.createWithContent.

**Comment by 1j01** [comment]
`convertFromRaw` returns a `ContentState`. You probably need to use [EditorState.createWithContent](https://facebook.github.io/draft-js/docs/api-reference-editor-state.html#createwithcontent)

**Comment by LFra** [comment]
Ok I think the problem is that firebase ditches the entityMap(when it is empty) and thats why Draft is not able to create a ContentState, is this possible?

Getting "Cannot convert undefined or null" Exception.
