### ISSUE TITLE
How do I retrieve the content in its current state?

### ISSUE THREAD

**Issue by brandondurham** [facebook/draft-js#51]
I’d like to allow for users to save their content in a way that Draft will recognize when loaded again. What is the recommended way to retrieve the content in its current state? I assume the content would look something [like this](https://github.com/facebook/draft-js/blob/06891490069d3ccfb89caf53f33a7545d39fc3ec/examples/tex/js/data/content.js)?

**Comment by davisml** [comment]
To retrieve the raw data call this:

`var rawData = Draft.convertToRaw(editorState.getCurrentContent())`

To create an EditorState from the raw data:

```
var contentState = Draft.ContentState.createFromBlockArray(Draft.convertFromRaw(rawData))
var editorState = Draft.EditorState.createWithContent(contentState)
```

**Comment by brandondurham** [comment]
Fabulous. Thanks so much!

**Comment by hellendag** [comment]
:)

**Comment by cogell** [comment]
Is there a way to get `rawContent` mapped to HTML with our already defined `decorators`, `styleMap`s, `blockStyleFn`s, etc

**Comment by hellendag** [comment]
Since we don't use markup or markdown to store rich content at Facebook, I haven't built any such utilities for this repo. (Since I wouldn't want to build and release something we aren't using in prod on FB.)

Feel free to create such a utility, though -- I'm sure there will be others who need it too.

If you just need to render your content statically within React, you can use the `readOnly` prop on `Editor`.

**Comment by cogell** [comment]
Thanks for your quick reply. Will do!

**Comment by zhang-z** [comment]
@cogell , +1 for retrieve HTML content util
@hellendag , wondering how you handle rich content at FB :)

**Comment by brwr** [comment]
@hellendag @cogell I'm going to start working on conversion utilities for both Markdown and HTML this evening. I'll submit a PR when they're done, in case they are useful for the project.

**Comment by cogell** [comment]
@brwr Thanks, I haven't had time to start anything on that utility. Happy to review and be of assistance since I'll need this moving forward on my project as well.

**Comment by davisml** [comment]
Here is a gist that converts DraftJS raw block data to HTML:

https://gist.github.com/davisml/2b5184f64c59eb3745fd

Supports H1, H2, blockquote, ul, ol, strong, em and underline styles mapped to the rich text example. Uses AttributedString.js (https://github.com/cohitre/attributedString.js) to format the style ranges.

**Comment by c-h-** [comment]
Not sure why but the only way I was able to restore state was by skipping the middle step in the above comment like so:

```javascript
var rawData = Draft.convertToRaw(editorState.getCurrentContent())
var editorState = Draft.EditorState.createWithContent(Draft.convertFromRaw(rawData))
```

Just in case anyone else comes here and has issues when trying to use `Draft.ContentState.createFromBlockArray`!

**Comment by Rahulgarg30591** [comment]
Hello, I have also tried draft-Js-export stateToHtml function, but the function is not working in IE is there any other way to get HTML from DraftJS editor?

**Comment by gopal151295** [comment]
@davisml 

To retrieve the raw data call this:

var rawData = Draft.convertToRaw(editorState.getCurrentContent())

To create an EditorState from the raw data:

var contentState = Draft.convertFromRaw(rawData) // convertFromRow already returns contentState, no need to 'createFromBlockArray()'
var editorState = Draft.EditorState.createWithContent(contentState)

**Comment by dmanohar2k9** [comment]
Manohar D
