### ISSUE TITLE
How to retrieve html content with inline styles or classnames of the editor?

### ISSUE THREAD

**Issue by igorpreston** [facebook/draft-js#520]
Hello,

I want to save html of the editor content preserving all styles upon button click. How can I access it or serialize the data?

Thanks.

**Comment by butchmarshall** [comment]
The editor doesn't actually represent the content as HTML internally, but rather using it's own representation.

What you'll need to do is write something to convert that representation into HTML.

The quick way to do it is...

1) Get the Current Content (ContentState) 

editorState.getCurrentContent()

2) Pass it to something like [draft-js-export-html](https://github.com/sstur/draft-js-export-html)

import {stateToHTML} from 'draft-js-export-html';
let html = stateToHTML(contentState);

**Comment by igorpreston** [comment]
@butchmarshall great advice, thank you!

**Comment by nikhildaga** [comment]
Isnt it surprising that this function is not present in draft-js and we have to use external module for it?

**Comment by satyadeeproat** [comment]
@butchmarshall : I am having some problem while displaying the html content. Here is what I am doing
let htmldata = stateToHTML(contentState)
return (
<div>
{htmldata}
</div>
)

but I am getting complete HTML content like this.
<p> Hello World </p>
How to remove these <p>

**Comment by sauravskumar** [comment]
@satyadeeproat if you are getting something like `<div>Hello World</div>`, then use `dangerouslySetInnerHTML` like eg below

`<div dangerouslySetInnerHTML={{__html: stateToHTML(convertFromRaw(data))}}/>`

**Comment by zeeshanjan82** [comment]
I am not able to export the styles. I am using the code like this:
`    var content = stateToHTML(this.state.content.getCurrentContent()); `
This exports everything except there is no style like color e.t.c

**Comment by jignesh04** [comment]
fghfgh  fgdfgdfg**dfgdfg** fghfghfgh fghfgh

**Comment by thatsmeamal** [comment]
@zeeshanjan82 I am having the same issue.
How to export the inline styles of the editor content

**Comment by KumarAbhirup** [comment]
same issue here, just as @zeeshanjan82

**Comment by thibaudcolas** [comment]
This is the same issue as #319. See https://github.com/facebook/draft-js/issues/319#issuecomment-395996499 for suggestions of solutions:

> If you want to convert Draft.js content to HTML reliably, have a look at one of the many helper libraries that do this: https://github.com/nikgraf/awesome-draft-js#common-utilities

**Comment by jacobokoenig** [comment]
Has anyone figured out how to include styles on the exported HTML? No matter my configuration of stateToHTML or convertToHTML, styles are not included.

**Comment by jakubgrzelak** [comment]
Hey! I export editor content as html. In the exported html I see inline styles. But when I try to import them from html into editor they are lost.
Code from importing looks like that: 
`     
 const blocksFromHTML = convertFromHTML(props.gift.description);
 const contentStateFromHtml = ContentState.createFromBlockArray(blocksFromHTML.contentBlocks,  
 blocksFromHTML.entityMap);
 editorState = EditorState.createWithContent(contentStateFromHtml);
`

**Comment by crusoexia** [comment]
seems like we can only use a ref to the editor and get `innerHTML` from a certain node inside?

**Comment by mdaffan** [comment]
I have this problem too, @jakubgrzelak you say in your exported HTML you see inline styles. Can you please show me the code you're using?

**Comment by alqamabinsadiq** [comment]
For those who want to export inline styles please have a look at the documentation of `draft-js-export-html`. You can pass a second argument called options. Check this out: https://github.com/sstur/draft-js-utils/tree/master/packages/draft-js-export-html

**Comment by bogdancss** [comment]
has anyone managed to get styles out from `stateToHtml` ?

**Comment by RAMKUMARDANE** [comment]
> has anyone managed to get styles out from `stateToHtml` ?
https://github.com/sudipta-pran/react-draft-wysiwyg-blogger/tree/master/client/src/components/admin/EditPost.js

[EditPost.txt](https://github.com/facebook/draft-js/files/5364686/EditPost.txt)

not confident for all styles but sure most will be resolved and then you can further implement on your own logic

**Comment by dounai1306** [comment]
> Hey! I export editor content as html. In the exported html I see inline styles. But when I try to import them from html into editor they are lost.
> Code from importing looks like that:
> ` const blocksFromHTML = convertFromHTML(props.gift.description);`
> 
> `const contentStateFromHtml = ContentState.createFromBlockArray(blocksFromHTML.contentBlocks, blocksFromHTML.entityMap);`
> 
> `editorState = EditorState.createWithContent(contentStateFromHtml);`
> 
> Did you find any solutions? @jacobokoenig?

**Comment by dounai1306** [comment]
> Hey! I export editor content as html. In the exported html I see inline styles. But when I try to import them from html into editor they are lost.
> Code from importing looks like that:
> ` const blocksFromHTML = convertFromHTML(props.gift.description);`
> 
> `const contentStateFromHtml = ContentState.createFromBlockArray(blocksFromHTML.contentBlocks, blocksFromHTML.entityMap);`
> 
> `editorState = EditorState.createWithContent(contentStateFromHtml);`
> 
> Did you find any solutions? @jacobokoenig @jakubgrzelak?

**Comment by BiancaArtola** [comment]
> Hey! I export editor content as html. In the exported html I see inline styles. But when I try to import them from html into editor they are lost.
> Code from importing looks like that:
> ` const blocksFromHTML = convertFromHTML(props.gift.description);`
> 
> `const contentStateFromHtml = ContentState.createFromBlockArray(blocksFromHTML.contentBlocks, blocksFromHTML.entityMap);`
> 
> `editorState = EditorState.createWithContent(contentStateFromHtml);`
> 
> Did you find any solutions? @jacobokoenig?

Same issue here

**Comment by oshosanya** [comment]
Issue is the same for me?

**Comment by BugraTuncer** [comment]
Same issue here

**Comment by kamilslusarczyk** [comment]
Why this issue has been closed?

**Comment by Developer-53** [comment]
I do not get the inline styles like text align, when I convert the data to HTML using stateToHTML. Could someone please provide some help getting the styles with HTML?

**Comment by abduleichiba** [comment]
+1,
could any one please let us drive to a correct way, for inlineStyles issue when converting html with htmlToDraft (html-to-draftjs library)

**Comment by Developer-53** [comment]
I am using import draftToHtml from 'draftjs-to-html';
import htmlToDraft from 'html-to-draftjs'; for applying inline styles and it is working like charm.
Hope it helps!

**Comment by Developer-53** [comment]
Can someone please help me with how to add a horizontal rule or divider in draftjs toolbar? I didn't get any toolbar option for the same.
P.S: I am using react-draft-WYSIWYG editor

**Comment by q453773874** [comment]
> Can someone please help me with how to add a horizontal rule or divider in draftjs toolbar? I didn't get any toolbar option for the same. P.S: I am using react-draft-WYSIWYG editor

may be you can set a "toolbarClassName" and overwrite existed css for each tool

**Comment by abduleichiba** [comment]
> I am using import draftToHtml from 'draftjs-to-html'; import htmlToDraft from 'html-to-draftjs'; for applying inline styles and it is working like charm. Instead of using stateToHTML / covertToHTML use draftToHtml(convertToRaw( this.state.editorState.getCurrentContent() ));
> 
> and for converting HTML to raw data use: this.setState({ editorState: EditorState.createWithContent( ContentState.createFromBlockArray(htmlToDraft(data)) ), });
> 
> Hope it helps!

not working, This thing strips the all inline styles. @Developer-53

**Comment by Developer-53** [comment]
> > I am using import draftToHtml from 'draftjs-to-html'; import htmlToDraft from 'html-to-draftjs'; for applying inline styles and it is working like charm. Instead of using stateToHTML / covertToHTML use draftToHtml(convertToRaw( this.state.editorState.getCurrentContent() ));
> > and for converting HTML to raw data use: this.setState({ editorState: EditorState.createWithContent( ContentState.createFromBlockArray(htmlToDraft(data)) ), });
> > Hope it helps!
> 
> not working, This thing strips the all inline styles. @Developer-53

Yes, I am also facing the same issue. It copies the basic styles but not inline styles

**Comment by Developer-53** [comment]
> > I am using import draftToHtml from 'draftjs-to-html'; import htmlToDraft from 'html-to-draftjs'; for applying inline styles and it is working like charm. Instead of using stateToHTML / covertToHTML use draftToHtml(convertToRaw( this.state.editorState.getCurrentContent() ));
> > and for converting HTML to raw data use: this.setState({ editorState: EditorState.createWithContent( ContentState.createFromBlockArray(htmlToDraft(data)) ), });
> > Hope it helps!
> 
> not working, This thing strips the all inline styles. @Developer-53

It is working fine for me, when I select any inline style from toolbar and save it. I see the styles being saved and able to render the saved content with inline styles using this

**Comment by ks-krimi** [comment]
> > Hey! I export editor content as html. In the exported html I see inline styles. But when I try to import them from html into editor they are lost.
> > Code from importing looks like that:
> > ` const blocksFromHTML = convertFromHTML(props.gift.description);`
> > `const contentStateFromHtml = ContentState.createFromBlockArray(blocksFromHTML.contentBlocks, blocksFromHTML.entityMap);`
> > `editorState = EditorState.createWithContent(contentStateFromHtml);`
> 
> Did you find any solutions? @jacobokoenig @jakubgrzelak @dounai1306 @BiancaArtola
