### ISSUE TITLE
Docs: Saving / Reading / Viewing 

### ISSUE THREAD

**Issue by nbrady-techempower** [facebook/draft-js#526]
Let me start by saying thank you for open sourcing this project. It looks amazing so far.

As someone who is fairly new to React, but feel like I caught up quickly, draft-js still seems a little hard to piece together. I think the most important aspect for a lot of people is getting the data into the database and back out for viewing. I'm a little confused by what to do with the raw data when converted, as it seems to get pretty nested and serializing that seems like it might not be the best idea. 

Are there any best practices or an API that isn't already in the docs for this process? And if not, is this something that draft-js plans on doing by v1?

**Comment by J22Melody** [comment]
+1

**Comment by mercury2269** [comment]
yes, there is a section about data conversion for storage in the docs 
https://facebook.github.io/draft-js/docs/api-reference-data-conversion.html

Once you have raw a JS object it can be serialized for storage.

**Comment by tylercraft** [comment]
Thanks for helping answer @mercury2269. @nbrady-techempower, please let us know if you have any other questions.
