### ISSUE TITLE
Give option for fixed height Editor

### ISSUE THREAD

**Issue by d4nyll** [facebook/draft-js#528]
This is a feature request/question.

**What is the current behavior?**
Right now, if the content exceeds the current editor height, the editor will increase its height to match the content.

**What is the expected behavior?**
It would be great if there's an option to set a fixed height for the editor, if the content requires more space, a scrollbar will appear on the right. This is similar to the default WordPress editor:

![default-wordpress-editor](https://cloud.githubusercontent.com/assets/9997953/16724185/1044f6ba-4784-11e6-8f9f-6bfeedbecb97.png)

**Comment by joshmarinacci** [comment]
Couldn't this be done with CSS?

**Comment by spicyj** [comment]
Try adding a max-height and overflow: auto on `.public-DraftEditor-content`.

**Comment by grifx** [comment]
If you are using css-modules:
```
.editor {
  :global(.public-DraftEditor-content) {
    max-height: 200px;
    overflow: auto;
  }
}
```

**Comment by tarjei** [comment]
I'm not happy with the suggested solutions to this problem because they depend on knowing the editor height. I need to change it depending on the height of another element, thus I am forced to use js to set the height.

**Comment by tarjei** [comment]
I ended up with the following hack:

```js

function createStyleSheet() {
  let style = document.getElementById('extra-sheet')
  if (style) {
    return style.sheet
  }
  // Create the <style> tag
  style = document.createElement('style')
  style.id = 'extra-sheet'
  // WebKit hack :(
  style.appendChild(document.createTextNode(''))
  document.head.appendChild(style)
  return style.sheet
}
function addCSSRule(sheet, selector, rules, index) {
  if ('insertRule' in sheet) {
    sheet.insertRule(selector + '{' + rules + '}', index)
  } else if ('addRule' in sheet) {
    sheet.addRule(selector, rules, index)
  }
}

    const sheet = createStyleSheet()
    addCSSRule(
      sheet,
      '.LessonPageVideoSection .Note .DraftEditor-root',
      'height: ' + (height) + 'px;'
    )

```

**Comment by przemek-nowicki** [comment]
You could also try to use editorClassName attribute and provide your class with e.g. max-height
` 
import style from 'editorStyle.css'

<Editor
          editorClassName={this.style.editorClassName}/>` 

And css 
`
.editorClassName  {
  min-height: 250px;
  max-height: 500px;
  overflow: auto;
}

**Comment by sseidel16** [comment]
@przemek-nowicki is this attribute still available? I can't seem to find it. Maybe it was removed.
