### ISSUE TITLE
convertFromHTML - handle additional attributes (e.g. anchor target)

### ISSUE THREAD

**Issue by afhole** [facebook/draft-js#529]
Feature request: handle additional attributes for links, currently only `href` is supported as `url`.

We would like to be able to import links such as:
`<a href="http://example.com" rel="noindex" target="_blank" title="Example">Example</a>`

We currently use this library to achieve this:
https://github.com/sstur/draft-js-import-html

Our particular use case needs only `rel` and `target` on `a` to allow a CMS user to specify "No follow" and "Open in a new window" behaviour, though I imagine a more general solution that captures more attributes (maybe even all supported by HTML spec? with option to define custom additions) for more tags would be very useful.

**Comment by mitermayer** [comment]
This issue has already been fixed by https://github.com/facebook/draft-js/pull/374
