### ISSUE TITLE
Warning: A component is `contentEditable` and contains `children` managed by React

### ISSUE THREAD

**Issue by iroy2000** [facebook/draft-js#53]
The following is an example editor component

`
import React from 'react';
import {Editor, EditorState} from 'draft-js';

export default class MyEditor extends React.Component {

    constructor(props) {
        super(props);

        this.state = {
            editorState: EditorState.createEmpty()
        };
    }

    onChange = (editorState) => {
        this.setState({editorState});
    }

    render() {
        const {editorState} = this.state;
        return <Editor editorState={editorState} onChange={this.onChange} />;
    }
}
`

And in my parent component

`import MyEditor from './MyEditor'`

....  // in the render() method
`
    render() {
        let error = this.getError();

        return (
            <form className="post__form">
                {error}
                <div className="form-group">
                    <label htmlFor="title">Title</label>
                    <input type="text" ref="title" className="form-control" id="title" placeholder="Title" />
                </div>
                <div className="form-group">
                    <label htmlFor="description">Description</label>

                    <MyEditor />

                </div>
                <button type="submit" onClick={this.onClickHandler.bind(this)} className="btn btn-default">Submit</button>
            </form>
        );
    }

`

**And I see this warning**

Warning: A component is `contentEditable` and contains `children` managed by React. It is now your responsibility to guarantee that none of those nodes are unexpectedly modified or duplicated. This is probably not intentional.

**Comment by tasti** [comment]
You aren't doing anything wrong.

This a known issue (http://facebook.github.io/draft-js/docs/advanced-topics-issues-and-pitfalls.html#react-contenteditable-warning) and it's being tracked in the react repo: https://github.com/facebook/react/issues/5837

**Comment by hellendag** [comment]
Yep, really looking forward to eliminating this warning. :)

**Comment by davisml** [comment]
I ended up adding this code to my project as a temporary solution:

`console.error = (function() {
    var error = console.error

    return function(exception) {
        if ((exception + '').indexOf('Warning: A component is `contentEditable`') != 0) {
            error.apply(console, arguments)
        }
    }
})()`

**Comment by jarsbe** [comment]
@davisml crazy, I was just looking for a way to do this.

**Comment by davisml** [comment]
@jarsbe I'm glad I could help! :)

**Comment by jarsbe** [comment]
@davisml That's some speedy tech support, cheers!

**Comment by sdoomz** [comment]
As an alternative you can set your console filter to regexp mode with the value: `^((?!contentEditable).)*$`

**Comment by RTeran** [comment]
With the suppressContentEditableWarning prop you can solve this issue

**Comment by lazysergey** [comment]
@RTeran this is real solution

**Comment by nikhil-bacancy** [comment]
<span id="activeLayerName" className="name" suppressContentEditableWarning={true} onClick={this.toggleLayerNameInEditMode} onBlur={this.toggleLayerNameInEditMode} contentEditable={this.state.isLayerNameEditable}>xyz</span>

**Comment by nikhil-bacancy** [comment]
` <span id="activeLayerName" className="name" suppressContentEditableWarning={true} onClick={this.toggleLayerNameInEditMode} onBlur={this.toggleLayerNameInEditMode} contentEditable={this.state.isLayerNameEditable}>{this.state.layerList[this.state.selectedlayerIdIndex].name}</span>`
