### ISSUE TITLE
Remove eslint-loader from Tex example

### ISSUE THREAD

**Issue by zpao** [facebook/draft-js#536]
We're linting at the top of the repo and I don't think using the loader adds any value. It probably even detracts as it just adds another thing to decipher.

**Comment by SecurityInsanity** [comment]
@zpao So is it okay to just :nuke: the eslint from the example, and not lint that example at all? Or, do we want to start linting the examples?

**Comment by zpao** [comment]
Ideally we end up linting the examples using the same config (ie. just remove the path from .eslintignore). First step is to just stop using eslint-loader in the example so we don't end up with duplicated lint efforts. Then if you're interested in running lint after that and fixing anything that is showing up, that would be cool!
