### ISSUE TITLE
Trying to create two entities for the same block not working

### ISSUE THREAD

**Issue by vnovick** [facebook/draft-js#537]
I'm trying to add two different entities to the same block. To be specific trying to do the following:
```
const entityKey = Entity.create('ALIGNMENT', 'IMMUTABLE', { alignment: direction });
const entityKey2 = Entity.create('LINK', 'IMMUTABLE', { url: urlValue });
const fullblock = new SelectionState({
      anchorKey: startBlock.getKey(),
      anchorOffset: 0,
      focusKey: endBlock.getKey(),
      focusOffset: selectionState.getEndOffset()
    });
let newEditorState = RichUtils.toggleLink(editorState, fullblock, entityKey);
newEditorState = RichUtils.toggle(newEditorState, editorState.getSelection(), entityKey2)
this.changeState(newEditorState)
```

I see that only second entity is added to entityMap.
Also tried the following instead of `RichUtils.toggleLink`:

`EditorState.push(editorState, Modifier.applyEntity(contentState, fullblock, entityKey));`

Still the same.

The question is how I can possibly add two entities to the same block. Is it even supported?

Running on Chrome: Version 51.0.2704
DraftJS: 0.7.0

It also didn't work with previous versions of DraftJS

**Comment by vnovick** [comment]
Figured out that the problem was with entity being immutable. passed 'MUTABLE' to entity and it works.

**Comment by samikarak** [comment]
@vnovick 

I could't come up with how you get this to work, since the issue #246 (regarding the same problem) is still open and is still a big issue. Is there a mistake on your description or did you really resolve this on anyway ? 

 note : on the newest version of draftjs RichUtils.toggle is not supported anymore
