### ISSUE TITLE
Removing block style for code-block

### ISSUE THREAD

**Issue by tasti** [facebook/draft-js#54]
What's the reasoning behind preventing a `code-block` entity from becoming unstyled by backspacing when it's empty. Right now it behaves differently from the other entities (all the other block types can be unstyled).

Related code: https://github.com/facebook/draft-js/blob/master/src/model/modifier/RichTextEditorUtil.js#L418

**Comment by hellendag** [comment]
IIRC, it caused confusion in cases like this:

```
function helloWorld() {
^
}
```

Where the caret is at the start of the second line. In this case, when users backspaced, they didn't want to strip the block type -- they wanted to delete the line and move the cursor back to the previous line.

One way to resolve this would be to check whether the line above is `code-block`, and if not, make the current block `unstyled`.
