### ISSUE TITLE
Documentation for blockRendererFn props is incorrect

### ISSUE THREAD

**Issue by joshmarinacci** [facebook/draft-js#541]
On this page about the blockRendererFn function:

https://facebook.github.io/draft-js/docs/advanced-topics-block-components.html#content

it says that "the optional props object includes props that will be passed through to the rendered custom component".   This is not completely correct. These props will be passed through not in the props object, but in the props.blockProps sub property object.  

A few paragraphs later the code snippet demonstrates pulling the 'foo' property from the props.blockProps, but the text does not explain this.  

This bug bit me when I wasn't getting the props where I thought I was supposed to, and found the answer by looking at the Tex example.

**Comment by flarnie** [comment]
Thanks for flagging this @joshmarinacci! Looks like it will be fixed when #881 lands.
