### ISSUE TITLE
Question - how do I get a ContentBlock's direction, so I can serialize it to HTML properly?

### ISSUE THREAD

**Issue by GabiGrin** [facebook/draft-js#549]
Hey,
First of all, a huge thanks for this beautiful piece of software. Can't stop praising it enough.

I'm dealing with mixed content, RTL and LTR, and Draft.js handles it perfectly.

My problem is that when I get to serialize the editor's state into HTML (requirement of our app), I can't see to know whether a block was rendered as RTL or not (at least not without scrapping rendered block classes from the editor, which I see get '-rtl' appended to when text is RTL).

Is there any way  to know via the API what is the direction of a given block? or any workarounds?

Thanks!

**Comment by davidchang** [comment]
@GabiGrin - wow, I'm really sorry for such a slow response. We are trying to work on being more responsive.

As for the HTML conversion, are you currently using something like https://github.com/sstur/draft-js-export-html ?

We should expose DirectionMap on EditorState, here's some code showing it's a map of the block key to either the string 'RTL' or 'LTR':

https://github.com/facebook/draft-js/blob/5a36195d124990a082498665f6824ca96ab51e09/src/component/contents/DraftEditorContents.react.js#L106-L126

**Comment by tylercraft** [comment]
Going to close this out since it looks like this isn't an issue anymore. Please reopen if that's not the case.
