### ISSUE TITLE
BlockData is not being removed after deleting atomic block

### ISSUE THREAD

**Issue by delijah** [facebook/draft-js#554]
When the cursor is placed immediately after an atomic block and the user presses the backspace button, the preceding atomic block is removed, but the block data for that atomic block is kept resp. assigned to the following block. Example:

Cursor is placed at the very beginning of TextBlock2
```
|-----------------|
| TextBlock1      |
| AtomicBlock     |
| |TextBlock2     |
|-----------------|
```

User is pressing backspace, atomic block is being removed
```
|-----------------|
| TextBlock1      |
| |TextBlock2     |
|-----------------|
```

Now TextBlock2 has got the block data that was previously attached to the atomic block, which is wrong in my opinion. TextBlock2 has no use for the data, that was meant for use by the atomic block.

I am using RichUtils.onBackspace resp. RichUtils.handleKeyCommand (which takes care of removing atomic blocks).

**Comment by qrohlf** [comment]
I can confirm this - entities that belonged to an atomic block are appended to an adjacent block when backspacing to delete an atomic block. The expected behavior seems like the entity should be deleted along with the atomic block.
