### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [facebook/draft-js#555]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like _draft-js_, deleted their software history.

https://github.com/facebook/draft-js/commit/342576bf7186d07c82a41d9ca8169130669747d6

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask draft-js developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by zpao** [comment]
1. History can be hard to keep as it gets extracted from a product or another repository. For us, that's a fairly common practice, and the internal history is often riddled with fixes that are product specific or contain references to internal codenames or even unlaunched or yet-to-be launched products. The easiest & safest thing is sometimes to just pick a specific point and open source from there. It's not so much that we deleted the history, just that it would be extremely painful to extract in a good way.

2. There hasn't been too much pain yet. It's a relatively small code base with an involved primary author. Internally at FB we can still trace back through and follow the history to some extent so it hasn't been a problem.

3. Maybe, but haven't seen any major issues. Again, the maintainer/author is quite active and helpful.

4. Not to my knowledge. Code comments are invaluable.

**Comment by gustavopinto** [comment]
Hi @zpao,

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
