### ISSUE TITLE
How can I implement "Read more" feature for long text in Draftjs?

### ISSUE THREAD

**Issue by nguyenhhien** [facebook/draft-js#557]
When the text is too long, I want display only first 30 characters and append a button "see more" into  drafts editor. When the button is clicked, full text is displayed.

Have anyone done that before? Please help. Thank you in advance!

**Comment by gabriel-miranda** [comment]
As far as I understand you're using it in `readOnly` mode to display your content, am I right?
If that's the case: You can use `EditorState.createWithContent({contentHere})` and update it when clicked `view more` to fetch the rest of the data and fill your component with it.

**Comment by nguyenhhien** [comment]
Thank @gabriel-miranda for the suggestion. You're right, I'm using Editor in _readOnly_ mode. To be clearer, my question can be broken down into 2 parts:
1) How add "see more" link to the end of editor's content state in summary mode?
2) How to shorten the text while preserving styling?
E.g. 
===Full text===
{"entityMap":{},
"blocks":[
{
   "key":"vm8k",
   "text":"**123456789**",
   "type":"unsettled",
   "depth":0,
   "inlineStyleRanges":[
      **{"offset":0,"length":4,"style":"red"},
      {"offset":4,"length":5,"style":"blue"}**
   ],
   "entityRanges":[],
   "data":{}
}
]
}
===Summarized text===
{"entityMap":{},
"blocks":[
{
   "key":"vm8k",
   "text":"**12345**",
   "type":"unsettled",
   "depth":0,
   "inlineStyleRanges":[
      **{"offset":0,"length":4,"style":"red"},
      {"offset":4,"length":1,"style":"blue"**}
   ],
   "entityRanges":[],
   "data":{}
}
]
}

Do you have any idea?

**Comment by aem** [comment]
It seems like this isn't a Draft issue, but rather a View issue. I would figure out the space that your content can occupy, and apply a `max-height` to the editor, as well as a "See more" button with an absolute position to overlay the editor, and then when the "See more" button is clicked just remove the `max-height`

**Comment by tylercraft** [comment]
Looks like this has been resolved so I'm closing it out. Feel free to reopen if that's not the case.

**Comment by saheelsapovadia** [comment]
> 
> 
> It seems like this isn't a Draft issue, but rather a view issue. I would figure out the space that your content can occupy, and apply a `max-height` to the editor, as well as a "See more" button with an absolute position to overlay the editor, and then when the "See more" button is clicked just remove the `max-height`

But if you have an array of articles and only if an article exceeds the defined height you want "see more" to appear below it and toggle it. How can you calculate the height can decide whether it will exceed and should have "see more" or not even before it will render ?

**Comment by saheelsapovadia** [comment]
The most logical approach would be the one which will be based on the text size/length of the draft editorState content. Is there any property to capture the size/length of the editorState
