### ISSUE TITLE
Focus selection did wrong in firefox

### ISSUE THREAD

**Issue by RaoHai** [facebook/draft-js#562]
Hello !
- Input some text in editor, for example, `abcd`.
- Click outside the editor. 
- Move mouse cursor next to letter `b`, then click. The editor will get focus, and the cursor should position after letter `b`. 

In Chrome, the cursor position is correct.
But in Firefox, the cursor will keep last position before blur.

If we remain focus, Both them work well.

I've try to debug, it seems here: 

https://github.com/facebook/draft-js/blob/67c5e69499e3b0c149ce83b004872afdf4180463/src/component/selection/getDraftEditorSelection.js#L29

In Chrome, `global.getSelection()` could return correct position, in this case,  `{..., anchorOffset:2}`.

But in Firefox,  `global.getSelection()` returned incorrect position: `{..., anchorOffset: 4}`.

-- but i have no idea how to fix it 😢

**Comment by afc163** [comment]
+1

Run into this too.

**Comment by donlian** [comment]
some too. but i fixed it . 
check the global styles set, whether there is  'user-select:none';

**Comment by tylercraft** [comment]
Looks like this has been resolved so I'm closing it out. Feel free to reopen if that's not the case.
