### ISSUE TITLE
babel-polyfill free build?

### ISSUE THREAD

**Issue by butchmarshall** [facebook/draft-js#568]
Draft-JS requires babel-polyfill to be loaded in order to support IE9+.  

This pollutes the global namespace which is not an option for us.  One of our supported platforms is [Igloo Software](https://www.igloosoftware.com/) which uses mootools 1.1.7... which monkeypatches the Array method with a non ES6 standards method we cannot clobber.  

A few library changes seem to easily fix this.  Would these ever be considered?

I've forked and added the relatively few changes required for this to work polyfill-free via core-js virtual methods.

[fbjs](https://github.com/butchmarshall/fbjs/tree/ie-support) 
- String startsWith

[draft-js](https://github.com/butchmarshall/draft-js/tree/ie-polyfill-free-compatibility)
- Array [from,fill]
- String [startsWith,endsWith]

Side note.  I had no idea how to get the builds with the required lib/ folders working... so I modified the .gitignore files - obviously this is wrong but I couldn't figure out how to get the references working otherwise.

**Comment by spicyj** [comment]
Sorry, draft-js (and react) don't support working with old versions of Mootools: https://github.com/facebook/react/issues/2400#issuecomment-60336783. If you can't upgrade Mootools, you might be able to get around this by loading and running all the scripts in an iframe that has its own context.

**Comment by butchmarshall** [comment]
Thanks for the quick response @spicyj!  Looks like I'm not the only one who's hit this issue.

I'll attempt to keep my own fork up-to-date until those versions are dead.
