### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by pnmsharma** [facebook/draft-js#576]
Hi  guys, 
I am getting following error , working with react +node +gulp .Please help me with this.
**vendor.bundle.js:23764 Uncaught Invariant Violation: _registerComponent(...): Target container is not a DOM element.**

**Comment by iandoe** [comment]
This is most likely not an error related to draftjs. Please verify you are using `ReactDOM.render` correctly by supplying it a valid DOM Node eg `document.getElementById('app')` when a `<div id="app"></div>` exists in your html. 
Also verify that you are using valid html tags in your JSX.

Use the developper tools in chrome to track where your js error comes from. and use source maps as part of your gulp compile to js workflow to help you pinpoint where exactly errors are coming from.
