### ISSUE TITLE
convertFromHTML doesn't preserve <br>s inside <div>s

### ISSUE THREAD

**Issue by gdehmlow** [facebook/draft-js#578]
Let's say I have some text in the editor:

```
hello

we're separated by a line


and us by two
```

In the editor, when creating this text, I end up with 6 blocks, with the 2nd, 4th, and 5th having empty text.

The HTML I generate from this text looks like this (which is very similar to the HTML outputted during editing):

```html
<div>hello</div>
<div><br></div>
<div>we're separated by a line</div>
<div><br></div>
<div><br></div>
<div>and us by two</div>
```

If I use `convertFromHTML()` on this HTML, I would expect to get 6 content blocks back. Instead, I only get 3, and all of the empty lines get collapsed. So after I load the 3 blocks, the text in the editor ends up like this:

```
hello
we're separated by a line
and us by two
```

**Comment by benbriggs** [comment]
This was discussed a bit in https://github.com/facebook/draft-js/issues/231:

> This was on purpose to keep pastes of long text from having a lot of extra spaces between paragraphs. The content coming in can be pretty messy sometimes and this is one of the things we try to do to clean it up.

**Comment by facilitator999** [comment]
I have the exact issue; what trick did you use to fix it without using another module?

**Comment by asif-alam** [comment]
> This was discussed a bit in #231:
> 
> > This was on purpose to keep pastes of long text from having a lot of extra spaces between paragraphs. The content coming in can be pretty messy sometimes and this is one of the things we try to do to clean it up.

To do the cleanup removing the users input which is not right

**Comment by scottfr** [comment]
I think this is not good default behavior and should be changed. The current behavior also does the align with most other RTE's.

**Comment by Smaxor5** [comment]
This is awful default behavior.
