### ISSUE TITLE
How to append text to the end

### ISSUE THREAD

**Issue by ufo22940268** [facebook/draft-js#58]
```javascript
  _insertText() {
    const editorState = this.state.editorState;
    const selection = editorState.getSelection();
    const contentState = editorState.getCurrentContent();
    const ncs = Modifier.insertText(contentState, selection, "wefoiwjoefjwoiefjoiwjefio");
    const es = EditorState.push(editorState, ncs, 'insert-fragment');
    this.setState(es);
  }
```
With above codes, i can't get the `wef....` to be append to the end. I have work on this problem for hours, but still can't found the solution. The above code is written according to `Tex` sample.

**Comment by ufo22940268** [comment]
It's not a bug.

**Comment by ufo22940268** [comment]
I found the solution.

My init method is 

```
  getInitialState() {
    return {
      editorState: EditorState.createEmpty()
    };
  },
```

So when i want to update `editorState` i need to call `this.setState({editorState: es})`, not `this.setState(es)`. Really love this framework, thank you.

**Comment by sibelius** [comment]
how to append to the end?

**Comment by jawblia** [comment]
For folks who found this thread from Google but are not having the state issue above—how to append text to the end:

`````
   // get current editor state 
    const currentContent = editorState.getCurrentContent();

 // create new selection state where focus is at the end
    const blockMap = currentContent.getBlockMap();
    const key = blockMap.last().getKey();
    const length = blockMap.last().getLength();
    const selection = new SelectionState({
        anchorKey: key,
        anchorOffset: length,
        focusKey: key,
        focusOffset: length,
      });

   //insert text at the selection created above 
    const textWithInsert = Modifier.insertText(currentContent, selection, 'text to be inserted', null);
    const editorWithInsert = EditorState.push(editorState, textWithInsert, 'insert-characters');

    //also focuses cursor at the end of the editor 
    const newEditorState = EditorState.moveSelectionToEnd(editorWithInsert, textWithInsert.getSelectionAfter());
    setEditorState(newEditorState);
`````

**Comment by chenjiashrimp** [comment]
> ```js
>   _insertText() {
>     const editorState = this.state.editorState;
>     const selection = editorState.getSelection();
>     const contentState = editorState.getCurrentContent();
>     const ncs = Modifier.insertText(contentState, selection, "wefoiwjoefjwoiefjoiwjefio");
>     const es = EditorState.push(editorState, ncs, 'insert-fragment');
>     this.setState(es);
>   }
> ```
> 
> With above codes, i can't get the `wef....` to be append to the end. I have work on this problem for hours, but still can't found the solution. The above code is written according to `Tex` sample.

my code is the same as yours, but only can insert the text once, i don't know why
