### ISSUE TITLE
Android does not fire onChange for every input event like desktop/iOS

### ISSUE THREAD

**Issue by butchmarshall** [facebook/draft-js#580]
Every input does not fire an onChange event in Android (it does in desktop/iOS).

It looks like these events come through onCompositionUpdate which aren't yet handled.

I've taken an initial stab at the issue in my [android-on-change-fix](https://github.com/butchmarshall/draft-js/commit/64a465b897007d3bde259666376639d033e7e6a0) branch but still need to understand how to incorporate `DraftEditorCompositionHandler.resolveComposition` into each `onCompositionUpdate` call.

**Comment by flarnie** [comment]
Merging this into a general Android bug issue - see https://github.com/facebook/draft-js/issues/1895
