### ISSUE TITLE
Are Modifier.setBlockData, block.getData() and all other functions dealing with block data,  removed from API?

### ISSUE THREAD

**Issue by vnovick** [facebook/draft-js#583]
I have this weird bug, or It's just misunderstanding. Currently on draft-js 0.7.0 version any functions dealing with blockData are just not there. Were they removed from API? if so, how can I set block data properly.

**Comment by vnovick** [comment]
Ok. So I noticed that setBlockData and getData were added on July 1 together with docs update, however these changes are present only on master branch and are not released with version 0.7.0.

When this functionality will be published to npm with next version?

**Comment by eddievagabond** [comment]
+1

**Comment by apfelfabrik** [comment]
There is a 0.8.1 now.

**Comment by grrowl** [comment]
https://github.com/facebook/draft-js/issues/684

**Comment by coinfork** [comment]
I'm using 0.9.1 and setBlockData still doesn't seem to exist in Modifier. Why?

**Comment by niveditc** [comment]
Not sure why these changes were excluded back then, but happy to report that it's there in the current API :)
