### ISSUE TITLE
Component's children should not be mutated- draft-js@0.7 react@15.3.0

### ISSUE THREAD

**Issue by mzbac** [facebook/draft-js#590]
when try to toggle blockType to ordered-list-item, unordered-list-item, code-block. getting error :

VM16882 bundle.js:1302 Warning: Component's children should not be mutated.
    in pre
    in div (created by DraftEditorContents)
    in DraftEditorContents (created by DraftEditor)
    in div (created by DraftEditor)
    in div (created by DraftEditor)
    in div (created by DraftEditor)
    in DraftEditor (created by PluginEditor)
    in PluginEditor (created by KeyPathEditor)
    in div (created by KeyPathEditor)

it occurred for all those block that have wrapper element..

it caused by mutation checking  
`if (element._shadowChildren.length === element.props.children.length) `

**Comment by blade254353074** [comment]
Me too

**Comment by feliperohdee** [comment]
+1

**Comment by vinhlh** [comment]
+1

**Comment by haridusenadeera** [comment]
+1

**Comment by walter0331** [comment]
+1

**Comment by meiyouqing** [comment]
+1

**Comment by vagusX** [comment]
+1

**Comment by zaklampert** [comment]
+1

**Comment by jsiebern** [comment]
+1

**Comment by houkanshan** [comment]
+1, 
react@15.3.0 
draft-js@0.8.1

And I didn't get this error while using b5d87c2765f7a6e72cd0ae6618682e8d0c5556a3 (> 0.7.0 & < 0.8.0, 11 commits before [0.8.0](https://github.com/facebook/draft-js/commit/0b26f6bdf1249594897fabc2f3477d742a2b11ff))

**Comment by sleeper** [comment]
+1

**Comment by delijah** [comment]
+1

**Comment by html5webster** [comment]
+1

**Comment by jjkavalam** [comment]
+1

**Comment by bradbirnbaum** [comment]
+1

**Comment by blackcater** [comment]
+1 
How to fix it?

**Comment by echenley** [comment]
@blackcater The fix is in the master branch, but it hasn't been published to npm yet. Hopefully that happens soon. As a temporary measure, you could try using the master branch directly:

```
  "draft-js": "https://github.com/facebook/draft-js.git"
}
```
