### ISSUE TITLE
use an example jsfiddle in the doc template

### ISSUE THREAD

**Issue by stopachka** [facebook/draft-js#598]
**Do you want to request a *feature* or report a *bug*?**

A feature, for this template :) 

**What is the current behavior?**

Currently, the template asks the user to set up a jsfiddle, without providing an example. 

**What is the expected behavior?**

We could provide the user a basic jsfiddle that they can fork, to more easily repro the behavior. 

Here's a basic one we could use as a base:

https://jsfiddle.net/stopachka/m6z0xn4r/

**Comment by davidchang** [comment]
(y) this has been done! closing.
