### ISSUE TITLE
Error after installing draft-js with webpack

### ISSUE THREAD

**Issue by cinder92** [facebook/draft-js#599]
Hello i just have install draft-js (last version) and i'm getting this hole errors!

i have installed react-dom and in my component i have imported react, react-dom and draft-js like this

```
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import Radium from 'radium'
import Calendar from './Calendar'
import IconLabel from '../../commons/IconLabel'
import moment from 'moment'
//draft-js
import {Editor, EditorState} from 'draft-js';

.....

render(){
       return (<div><Editor /></div>)
}


```

Errors in console

![captura de pantalla 2016-08-14 a las 12 53 57 a m](https://cloud.githubusercontent.com/assets/4725556/17647527/a3f8be24-61b9-11e6-9f4d-df5c19209f6d.png)

React version : 15.3.0
Draft version : 0.8.0
fbjs version : 0.8.0
Webpack version : 1.13.1

How can i fix this?

**Comment by adrianmc** [comment]
This sounds like a dependency issue. Try deleting your node_modules folder and running `npm install` again.

**Comment by cinder92** [comment]
Thanks for you quick replay @adrianmc after install draft-js i need to restart hole webpack server, thanks! so issue is closed
