### ISSUE TITLE
about table support

### ISSUE THREAD

**Issue by guotie** [facebook/draft-js#600]
**Do you want to request a *feature* or report a *bug*?**

feature: table support

**What is the current behavior?**

I have not see any table support.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

no.

**What is the expected behavior?**

table support.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

all versions.

**Comment by sauravskumar** [comment]
+1 for table support

**Comment by stopachka** [comment]
Hey @guotie -- table support is not currently on the roadmap.

It might be possible to use a custom block component to do this.
