### ISSUE TITLE
console warning reported by immutable

### ISSUE THREAD

**Issue by kinglywork** [facebook/draft-js#607]
Because of the current version (3.7.4) of immutable in dependencies, there will be warning in console: "Iterable.length has been deprecated, use iterable.size or iterable.count()".

this warning is removed in immutable@3.8.0

could you please update the immutable version in your dependencies.

**Comment by kinglywork** [comment]
The warning problem will cause serious performance issues in IE(tested in IE11), please consider to fix it.

**Comment by alfonsoperez** [comment]
@kinglywork it does for me in Chrome as well, for now I have monkey patched `console.warn`, I wish I had the bandwidth to open up a PR.

**Comment by hardywu** [comment]
Just a reminder to `yarn` users. 

In `yarn` configuration, updating immutable.js does not fix this syntax issue. Because `yarn` install a nested `immutable.js` copy under `node_modules/draft-js/node_modules`.  Have to remove this nested copy to walk around the current warning hell.

**Comment by mitermayer** [comment]
we will be tracking this issue in here: https://github.com/facebook/draft-js/issues/950
