### ISSUE TITLE
Context-oriented behaviour

### ISSUE THREAD

**Issue by DenisIzmaylov** [facebook/draft-js#61]
Hello and thank you for your yet another awesome solution.

Just watched the demo on [project page](https://facebook.github.io/draft-js/) and noticed it doesn't have context-oriented behaviour. What does it mean?

+ When I switch to H1-H5 mode I'd like to turn off this mode by Enter (new line) key.
+ When I switch to list mode I'd like to create a new level by Tab key.

It seems the good example for improving UX is focusing on Apple Pages to get good ideas and inherit user expectations.

**Comment by tasti** [comment]
You're absolutely right. The context-orientation behavior is really useful, which hasn't been implement in the `rich` demo.

We actually do this in Facebook Notes. It seems like this will be a really common question and could be  provided through the `RichTextEditorUtil`.

**Comment by hellendag** [comment]
For resetting block type, you can use https://github.com/facebook/draft-js/blob/master/src/model/modifier/RichTextEditorUtil.js#L406 within a `handleReturn` prop function.

We could create a `RichUtils` function to bake this in, though my thinking was that the expected rules for return and backspace behavior might vary for different use cases. Apple Pages might be a good UX model, but people have a broad range of expectations from their editors -- it can be hard to prescribe one for all.

For nested lists, see http://facebook.github.io/draft-js/docs/advanced-topics-nested-lists.html#content.

**Comment by hellendag** [comment]
Going to close this because I think we can allow clients to define this behavior themselves. If it comes up more and it seems there is an obvious default, then we can reassess. :)
