### ISSUE TITLE
Multiple Entities per character

### ISSUE THREAD

**Issue by bryanph** [facebook/draft-js#619]
The need for this occurs in the following scenario:

I have character ranges with entities of type 'unstyled' and 'INLINE-TEX' in succession.
I want to apply a 'LINK' entity to the complete range and hence have a link comprised of the text and the inline TeX, but this changes the 'INLINE-TEX' range to 'LINK', breaking the behaviour.

Is there some other way I can get this type of behaviour working properly?

**Comment by olmg-justin-ligman** [comment]
I saw where someone apparently solved this by using a single Entity wrapper that had the list of types as part of its metadata, and then would render each one in turn for the range during its own render.  This sounds like it would work, but I haven't tried it myself, nor do I still have the link where they were discussing this, but it was just a comment in a forum somewhere anyways and didn't go into any great detail.

**Comment by stopachka** [comment]
hey @bryanph 

@olmg-justin-ligman idea would be a possible solution.

Essentially, you would use 1 entity, but through the entity's metadata, you would keep track of what transformations you want on it. 

There is a downside there, where pressing backspace will no longer fully delete what you want, but if this is not a large tradeoff for your case, it could be worth considering.

The discussing on composite entities is happening here -> 

https://github.com/facebook/draft-js/issues/246
