### ISSUE TITLE
Draft.js emit double click event, which work not nicely with extensions

### ISSUE THREAD

**Issue by milushov** [facebook/draft-js#622]
It's kind of bag I think

Draft.js not work nicely with popular chrome extension (2.5M users) [Google Dictionary](https://chrome.google.com/webstore/detail/google-dictionary-by-goog/mgijmajocgfcbeboacabfgobmjgjcoja?hl=en)

Wrong behaviour on the gif below:
![bad_draft](https://cloud.githubusercontent.com/assets/424326/18050609/558aa310-6df8-11e6-97fb-fd75573627fd.gif)

**Comment by stopachka** [comment]
Hey @milushov, this definitely sucks, but there are so many ways plugins could mutate the dom, that it could be hard for us to build defenses for each scenario.

If you do some more research, and have found an issue with draft, we would be happy to look over a PR
