### ISSUE TITLE
The convertFromHTML() method currently strips inline style attribute from HTML string.

### ISSUE THREAD

**Issue by ademars94** [facebook/draft-js#623]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
The `convertFromHTML()` method strips inline style attribute from HTML strings.

When importing this HTML string (via `convertFromHTML()`):
`"<p>This is some <span style="color: #f0ad4e">colorful</span> text.</p>"`

The line is converted to this:
`"<p>This is some colorful text.</p>"`

**What is the expected behavior?**
Keep inline style attribute when using `convertFromHTML()`

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Draft JS v0.8.1 running in Chrome

**Comment by ademars94** [comment]
Just to elaborate,  we want to replace our old RTE with Draft, but I think this may be too much of an issue to move forward, since our database returns content in HTML string format.  I'm not sure why Draft doesn't offer the ability to convert inline CSS style to it's own native style format, but it seems like it would be absolutely necessary in order to integrate with existing projects and databases.  Doesn't this severely limit the use case for Draft?  I mean, unless you are storing Draft ContentBlocks in your database, how would you be able to use a Draft editor to edit existing content?

**Comment by robbertbrak** [comment]
You can provide your own function for converting HTML to Draft, see for example https://github.com/sstur/draft-js-import-html. You can also use such a function when pasting html into the editor: http://facebook.github.io/draft-js/docs/api-reference-editor.html#handlepastedtext.

**Comment by ademars94** [comment]
@robbertbrak 

Thanks for the reply.

I have tried using the `draft-js-import-html` package. As far as I can tell it has the same behavior as the native `convertFromHTML` method in that it strips away any inline style I add (same way as I mentioned above).  I am using the `draft-js-export-html` package to export HTML, and that works to preserve the inline style, but when I try to import the HTML, the style is stripped away.

**Comment by robbertbrak** [comment]
The reason it does that is because these converters don't know how to interpret your custom style attributes. Draft itself doesn't use HTML as internal representation; it knows only about block types, inline styles and entities.

The Draft Way would therefore be to parse the HTML yourself and transform any HTML attributes you care about to inline styles or entities.

Note that this can be quite a tough challenge, because HTML can be almost arbitrarily nested, whereas the Draft Block structure is basically flat. For my own project (not open-source unfortunately) I wrote my own converter, but you may be able to adjust the `draft-js-import-html` to your liking.

**Comment by ademars94** [comment]
Looks like I will have to figure out some sort of workaround.  Thanks for the info @robbertbrak!

**Comment by thesolotraveller** [comment]
Hi !
I am facing the exact same issue right now. All my styles are stripped off when I load the same content from DB, the same content has all the styles in the returned HTML but converFromHTML strips off everything.

Please let me know if anybody has figured out a solution for this.
Thanks.

**Comment by andersryanc** [comment]
What I don't quite understand is that this seems to be a WYSIWYG editor for using on a web page, but it doesn't quite have an easy way built in to convert the rich text to/from HTML (even though it appears to be doing it internally for displaying within the editor window itself)... why not just expose those methods? why only expose `convertFromHtml()`? Is the idea that you would just `convertToRaw()` then `JSON.stringify()` that into your database? Then `JSON.parse()` that back to JS to dump back into the editor and/or render to your desired format?

I chose this solution, because I thought it might play nicely as an editor for generating content for a React Native app I'm building. I started out building a component to convert HTML to nested <Text /> components at which point I found DraftJS. So I played around with the [RichText editor example](https://github.com/facebook/draft-js/blob/master/examples/draft-0-10-0/rich/rich.html) and got it to the point of being able to convert to HTML via `draft-js-export-html` but as mentioned above, also ran into the issue of the inline styles being stripped when using either `convertFromHtml()` or `draft-js-import-html` (even when passing the same export options to import, in the case of `draft-js-import-html`).

I then thought, ok, well maybe I need to use the raw blocks to render directly to React Native components instead of using HTML as a go between and storage mechanism... which led me to `react-native-draftjs-render`, which I'm unable to even try because their `import` immediately breaks my web app...

Any suggestions on where to go from here? I just want a way to create content in a WYSIWYG editor, save that to a database, then load it up in my react native app. Nothing too fancy like horizontal rules, or links or anything... just plain text, bold, italic, and one custom style where I can change the font-family to another one.... That's actually the most complicated part since I'm trying to use inline styles to define that custom typeface for those spans of text. Do I need to just hack this to use an `<em>` as my custom typeface and the `<i>` for italics?

**Comment by KumarAbhirup** [comment]
every damn thing in universe is unclear

**Comment by Sauloxd** [comment]
For everyone still looking for a solution, this [converter](https://www.draftail.org/docs/importing-and-exporting-html ), from Draftail, provides callbacks to customize the creation of entities, given an HTML node. So you can manually access those inline-styles, and add them as data to your entity:
For example:
``` javascript
  import { convertFromHTML } from 'draft-convert';
  convertFromHTML({
    htmlToEntity: (nodeName, node, createEntity) => {
      if (nodeName === 'img') {
        const entityConfig = {};
        entityConfig.src = node.getAttribute ? node.getAttribute('src') || node.src : node.src;
        entityConfig.alt = node.alt;
        entityConfig.height = node.style.height;
        entityConfig.width = node.style.width;

       return createEntity(
          'IMAGE',
          'MUTABLE',
          entityConfig,
        );
      }
    }
  });
```

**Comment by AkyunaAkish** [comment]
This code worked for me when I wanted to convert HTML as a string to draftjs code and load it in the editor's state without stripping the HTML attributes:

[https://github.com/jpuri/react-draft-wysiwyg/blob/master/stories/ConvertFromHTML/index.js](https://github.com/jpuri/react-draft-wysiwyg/blob/master/stories/ConvertFromHTML/index.js)

**Comment by jakubgrzelak** [comment]
@AkyunaAkish Saved my life! Thank you

**Comment by rishu1824** [comment]
@AkyunaAkish Actually its not working for my case. My requirement is:
html = <span style="color:'red'">Hello</span>. I want to convert this html into draft state. with same styling. I tried lot of methods but got nothing.

**Comment by memsenpai** [comment]
@AkyunaAkish  you save me

**Comment by bbb324** [comment]
> This code worked for me(particularly lines 12-16) when I wanted to convert HTML as a string to draftjs data and load it in the editor's state without stripping the HTML attributes:
> 
> ```js
> import htmlToDraft from 'html-to-draftjs';
> const contentBlock = htmlToDraft(htmlString);
> const contentState = ContentState.createFromBlockArray(contentBlock.contentBlocks);
> const editorState = EditorState.createWithContent(contentState);
> ```
> 
> https://github.com/jpuri/react-draft-wysiwyg/blob/master/stories/ConvertFromHTML/index.js

thanks bro, you save my ass lol

**Comment by BiancaArtola** [comment]
> This code worked for me(particularly lines 12-16) when I wanted to convert HTML as a string to draftjs data and load it in the editor's state without stripping the HTML attributes:
> 
> ```js
> import htmlToDraft from 'html-to-draftjs';
> const contentBlock = htmlToDraft(htmlString);
> const contentState = ContentState.createFromBlockArray(contentBlock.contentBlocks);
> const editorState = EditorState.createWithContent(contentState);
> ```
> 
> https://github.com/jpuri/react-draft-wysiwyg/blob/master/stories/ConvertFromHTML/index.js

This solution works for HTML, but not for HTML with inline styles :'( 
Any solution?

**Comment by BiancaArtola** [comment]
@ademars94 Do you find any solution for your problem?

**Comment by beevekmgr** [comment]
Any solution guys?

**Comment by NishargShah** [comment]
Hello guys,

In the below Code,

1. Raw HTML works fine
2. Raw HTML inline styles work fine
3. Image is not working

```javascript
import htmlToDraft from "html-to-draftjs";
import { ContentState, EditorState } from "draft-js";

const blocksFromHTML = htmlToDraft(data.notes);
const contentState = ContentState.createFromBlockArray(
  blocksFromHTML.contentBlocks,
  blocksFromHTML.entityMap
);
const editorState = EditorState.createWithContent(
  this.customContentStateConverter(contentState)
);
```

In the below Code,

1. Raw HTML works fine
2. Raw HTML inline styles not working
3. Image works fine

```javascript
import { ContentState, convertFromHTML, EditorState } from "draft-js";

const blocksFromHTML = convertFromHTML(data.notes);
const contentState = ContentState.createFromBlockArray(
  blocksFromHTML.contentBlocks,
  blocksFromHTML.entityMap
);
const editorState = EditorState.createWithContent(
  this.customContentStateConverter(contentState)
);
```

Does anyone have a solution where all the above 3 will work fine??

**Comment by phamvutinh** [comment]
@AkyunaAkish  Good solution, Thank you!

**Comment by rsnsmf** [comment]
Thankyou @AkyunaAkish

**Comment by PierreTurnbull** [comment]
For anyone for who AkyunaAkish solution doesn't work: you may check the name of your inline style.

From [the source code](https://github.com/jpuri/html-to-draftjs/blob/b91ba0be2cb8b4c5a635335641d499725ce181cc/src/library/processInlineTag.js#L24-L51), you can see that only a few properties are supported, and they must be formatted in a specific way. For example, a font size inline style must be named `fontsize-${value}`, eg: `fontsize-12`. Naming it `FONT-12` or `fontSize12`, for example, simply won't work.
And I guess that if you need to use a property that is not among the few supported by the lib, you'll have to fork the project and add it yourself.

**Comment by lomeat** [comment]
@NishargShah your solutions seems to be work, but inline styles with "border" or "outline" do not work :(
It supports 'color' or 'background' and other simple styles

P.S. I try to create component with inserting custom tables in draft js. And I do not like ready solutions in internet.

**Comment by kamilslusarczyk** [comment]
Why this issue has been closed? It still does not work.

**Comment by ronenl** [comment]
this issue should be reopened. 
the problem still occurs

**Comment by nikollanik17** [comment]
Reopen this issue again please, the problem still occurs.

**Comment by C-Cos** [comment]
> Hello guys
> 
> In the below Code,
> 
> 1. Raw HTML works fine
> 2. Raw HTML inline styles work fine
> 3. Image is not working
> 
> ```js
> import htmlToDraft from "html-to-draftjs";
> import { ContentState, EditorState } from "draft-js";
> 
> const blocksFromHTML = htmlToDraft(data.notes);
> const contentState = ContentState.createFromBlockArray(
>   blocksFromHTML.contentBlocks,
>   blocksFromHTML.entityMap
> );
> const editorState = EditorState.createWithContent(contentState);
> ```
> 
> In the below Code,
> 
> 1. Raw HTML works fine
> 2. Raw HTML inline styles not working
> 3. Image works fine
> 
> ```js
> import { ContentState, convertFromHTML, EditorState } from "draft-js";
> 
> const blocksFromHTML = convertFromHTML(data.notes);
> const contentState = ContentState.createFromBlockArray(
>   blocksFromHTML.contentBlocks,
>   blocksFromHTML.entityMap
> );
> const editorState = EditorState.createWithContent(contentState);
> ```
> 
> Does anyone have a solution where all the above 3 will work fine??

I confirm that the first solution works for all inlineStyle (textalign, font, fontFamily, colors...) + images added via url. Did not try with local images. But thanks a lot !

**Comment by RichMatthews** [comment]
> This code worked for me(particularly lines 12-16) when I wanted to convert HTML as a string to draftjs data and load it in the editor's state without stripping the HTML attributes:
> 
> ```js
> import htmlToDraft from 'html-to-draftjs';
> const contentBlock = htmlToDraft(htmlString);
> const contentState = ContentState.createFromBlockArray(contentBlock.contentBlocks);
> const editorState = EditorState.createWithContent(contentState);
> ```
> 
> https://github.com/jpuri/react-draft-wysiwyg/blob/master/stories/ConvertFromHTML/index.js

for me when I use this it's returning `<p>SIMPLE &lt;b&gt;TEST&lt;/b&gt;</p>` in the console onload and in the editor it shows `<p>SIMPLE <b>TEST</b></p>`

neither is what I want. I just want "SIMPLE TEST" and test to be in bold font. not sure why this is so difficult

**Comment by sudiparyal185** [comment]
I manage to get around with this issue by doing the following: 
Whenever applying inline style you might be passing styleOptions for `stateToHTML (editorState, styleOptions)`, 
Let's assume, you have the option as following: 
````
const styleOptions = {
inlineStyles: {
RED: {
attributes: {'data-inlinestyle' : 'RED'},
style: {color : 'red'},
}
}
}
````
Now, this will make sure you export the html from editorstate correctly. 
Now when you are about to convert the content from html to editorState, I am using `convertFromHTML` from `draft-convert` 
I have the following code to retain the inline styles

```
import { convertFromHTML as htmlToState } from 'draft-convert';

export const convertFromHTML = (html, metadata = {}) => {
  return htmlToState({
    htmlToStyle: (nodeName, node, currentStyle) => {
      if (nodeName === 'span' && node.dataset.inlinestyle) {
        return currentStyle.add(node.dataset.inlinestyle);
      }
      return currentStyle;
    },
  })(html);
};
```
On top of this you can use various util actions as htmlToEntity as well. In this example, I am only dealing with inline styles.  Now you can use this function to convert your html content to editorState. Hope this will be helpful.
