### ISSUE TITLE
Can I prevent editing when clicking a link?

### ISSUE THREAD

**Issue by thesunny** [facebook/draft-js#625]
I have an atomic block that contains a link.

When I click the link, I want it to open the link but I do not want to start editing.

If I use e.preventDefault() on the <a> element, then the editor will not start editing but it will also not open the link.

I tried using e.preventDefault() on a container <div> around the link but editing would still start.

I've also tried setting contentEditable={false} both on the link and the container but editing would still start.

Any help would be appreciated if anybody has solved this issue.

**Comment by stopachka** [comment]
Hey @thesunny, could you provide a fiddle reproing the issue you are having? We could try to edit it there and think of a solution.

Here is something you can start with: 

https://jsfiddle.net/stopachka/m6z0xn4r/

**Comment by thesunny** [comment]
Hi @stopachka, thanks for the starting fiddle and offering to help find a solution.

Here is the updated fiddle:

https://jsfiddle.net/m6z0xn4r/11/

Basically, I've pre-populated the editor with two blocks, the second of which is an atomic block that renders a link.

I want to be able to click that link to open a new page without having the editor start editing.

I've set it up so that start of editing, which calls the onFocus method, does a `console.log` of a message so that you can easily tell when the editor has set its focus. The goal is to be able to click the link without having the message logged; however, clicking the text should console.log the message.

**Comment by jan4984** [comment]
not a clean way, calling [blur](https://facebook.github.io/draft-js/docs/api-reference-editor.html#blur) in the `Link` click listener can leave the editing state.

**Comment by mzbac** [comment]
set content editable false

**Comment by thesunny** [comment]
@jan4984 Unfortunately, not a great solution because of the way my app works. Basically, I need it to not call focus at all.

@mzbac. Already tried setting contentEditable to false but that didn't work. It's already in the fiddle.

**Comment by thesunny** [comment]
Okay, I found a solution. basically, what you have to do is on the <a> tag, set onMouseDown only to stopPropagation and preventDefault. You do not do anything to onClick.

I assume what's happening is that the focus is being set somewhere during the onMouseDown phase but the link opening handling of the browser is done during the onClick. I ran across it accidentally but seems to be working.

Here is the updated fiddle where it is working.

https://jsfiddle.net/m6z0xn4r/22/

**Comment by jan4984** [comment]
great，I will change my "blur after focus" way to your solution in my project. Thanks for sharing.
