### ISSUE TITLE
Allow Draft.js editor to attach more that one entity to a same text-range

### ISSUE THREAD

**Issue by Tommy10802** [facebook/draft-js#637]
Hellou i just one question 
Allow Draft.js editor to attach more that one entity to a same text-range?
because when i use RichUtils.toggleLink method to add entity to selection which allready contains another entity, the old entity is replaced with new one.
Thanks a lot.

**Comment by stopachka** [comment]
Hey @Tommy10802 -- we are currently discussing composite entities here -> 

https://github.com/facebook/draft-js/issues/246

In the meantime, an approach you can take to achieve similar effects as composite entities is: 

1. Use a single Entity, to represent muliple entities via metadata 

```
  i.e entity -> meta -> ['Link', 'something-else']
```

2. Use inline styles alongside entities
