### ISSUE TITLE
Allow spell check for Internet Explorer 11

### ISSUE THREAD

**Issue by robbertbrak** [facebook/draft-js#640]
Currently, Draft explicitly excludes IE11 (and below) from the spell check feature. The reason is that the input event is not fired when a misspelled word is corrected, so Draft doesn't know that it needs to update its internal state.

Technical reasons notwithstanding, it's still a shame that this doesn't work. Isn't there some way to work around this?

**Comment by stopachka** [comment]
Hey @robbertbrak 

It sucks that we lack support for spellcheck in IE11, but so far we haven't be aware of a good solution for it.

We'd be open to a patch if there is a technical path someone sees that doesn't add a lot of overhead

**Comment by butchmarshall** [comment]
Just hitting this limitation now.

I wonder how the Gmail editor gets around this?  It seems to be contentEditable=true + spellchecker enabled with no issues?
