### ISSUE TITLE
“eslint-plugin-flowtype” is not in the dev dependencies

### ISSUE THREAD

**Issue by mostafah** [facebook/draft-js#645]
Cloned the repo. Did `npm i` and then `npm run lint`. `eslint` complained about `eslint-plugin-flowtype` not being available.

A simple `npm i eslint-plugin-flowtype` solved the issue. Shouldn’t `eslint-plugin-flowtype` be in the dev dependencies?

### Information:

- Reporting a dev-related bug
- OS X 10.11.6, Node v6.4.0, npm 3.10.7
- Draft.js is current git HEAD (commit a16bc55)

**Comment by zpao** [comment]
This is my fault, sorry. Thanks for the heads up! I'll fix this.
