### ISSUE TITLE
click event doesn't fire when blockRendererFn return a decorated component 

### ISSUE THREAD

**Issue by mzbac** [facebook/draft-js#647]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
when return a decorated component from blockRendererFn. e.g.
```js
if (block.getType() === 'atomic') {
        return {
          component: decorateComponentWithProps(TeXBlock,{}),// decorated component returns to component
          editable: false,
          props: {
            onStartEdit: (blockKey) => {
              var {liveTeXEdits} = this.state;
              this.setState({liveTeXEdits: liveTeXEdits.set(blockKey, true)});
            },
            onFinishEdit: (blockKey) => {
              var {liveTeXEdits} = this.state;
              this.setState({liveTeXEdits: liveTeXEdits.remove(blockKey)});
            },
            onRemove: (blockKey) => this._removeTeX(blockKey),
          },
        };
      }
```
on the editor, click the decorated component the click event does not fire occasionally.. mostly happened when editor didn't focus  
  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

in current tex example,
change blockrenderFn to 
```js 
this._blockRenderer = (block) => {
      if (block.getType() === 'atomic') {
        return {
          component: decorateComponentWithProps(TeXBlock,{}),
          editable: false,
          props: {
            onStartEdit: (blockKey) => {
              var {liveTeXEdits} = this.state;
              this.setState({liveTeXEdits: liveTeXEdits.set(blockKey, true)});
            },
            onFinishEdit: (blockKey) => {
              var {liveTeXEdits} = this.state;
              this.setState({liveTeXEdits: liveTeXEdits.remove(blockKey)});
            },
            onRemove: (blockKey) => this._removeTeX(blockKey),
          },
        };
      }
      return null;
    };
```
the decorateComponentWithProps.js as below
```js
import React, { Component } from 'react';

/* eslint-disable space-before-keywords */
export default (EmbeddedComponent, props) => (class extends Component {
  render() {
    return (
      <div className="test">
        <EmbeddedComponent { ...this.props } { ...props } />
      </div>
    );
  }
});
```
**What is the expected behavior?**
the click event should be always fire up in decorated component
**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
chrome51,  no

**Comment by stopachka** [comment]
hey @mzbac -- 

From an initial look, it may be that the component is unmounting and remounting each time you click into it, which is what is causing the flash to occur. 

One way that could be fixed, is to make sure you are creating a new component once, rather then each time the blockRenderer is called .

Could you confirm that this is the case?

**Comment by mzbac** [comment]
@stopachka  thanks for your reply, it really helps. by removing decorated component out of blockRenderFn solves the problem..
