### ISSUE TITLE
Missing doc on undo redo

### ISSUE THREAD

**Issue by buley** [facebook/draft-js#65]
The `EditorState`'s `push()` method seems really important since it controls all state changes. I'm looking to get a mental map of which `EditorChangeType` strings to use on `EditorState` after the various `Modifier` methods (e.g. "insert-character" or what). 

There's a [reference](https://github.com/facebook/draft-js/blob/06891490069d3ccfb89caf53f33a7545d39fc3ec/docs/APIReference-EditorState.md) of an advanced topic doc on undo/redo but it [404s](http://facebook.github.io/draft-js/docs/advanced-undo-redo.html). I don't see a doc in the [repo](https://github.com/facebook/draft-js/tree/master/docs) to my knowledge.

Any chance it got missed on accident?

**Comment by hellendag** [comment]
Great catch. I didn't have it written in time for the launch, so I removed the .md file. :)

I haven't done a good job of denoting what each change type is used for. I'll spend some time getting this article written and will add it to the Advanced Topics section.

**Comment by pioul** [comment]
Hey @hellendag! I stumbled on this issue looking for the same doc, and then spotted you recently added some doc for `EditorChangeType` in #315: I'm wondering if there's more doc to come, or if this issue could be closed and the link in the [push description](https://github.com/facebook/draft-js/blob/master/docs/APIReference-EditorState.md#push) updated?
