### ISSUE TITLE
Uncaught TypeError: tempEntityMap.keyseq is not a function

### ISSUE THREAD

**Issue by prawee** [facebook/draft-js#660]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when i'm run follow example code
- entity (blank page) 
- tex ( blank page) 

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
current version ( 2016-09-16)
chrome browser
OSX

**Comment by stopachka** [comment]
indeed a bug, thanks for reporting prawee! 

The error is in https://github.com/stopachka/draft-js/blob/master/src/model/encoding/convertFromRawToDraftState.js , keyseq was miscapitalized from a recent changed.

**Comment by flarnie** [comment]
Fix landed - Thanks @prawee and @stopachka ~
