### ISSUE TITLE
typing text to draft-js editor with "Google Keyboard" in android

### ISSUE THREAD

**Issue by jan4984** [facebook/draft-js#673]
- I lost the focus(keyboard hide) after type letter "I".
- When press "space" in soft keyboard,  a “don't" append to "dont".
I have tried other input and editable content in other website, it works well. so It's not the problem of my Android phone.

I have made a screen record, please check.
https://drive.google.com/open?id=0B534QzUZ3-P6VHdtU19jbmVURms

**Comment by jan4984** [comment]
Well, seems it will be fix in  https://github.com/facebook/draft-js/pull/175
I'm going to close this issue.

**Comment by HarelDavid** [comment]
Hi,
When do you guys think this issue will be fixed?
