### ISSUE TITLE
Where can I find `Style` and `Scroll` code?

### ISSUE THREAD

**Issue by thesunny** [facebook/draft-js#692]
I've spent a fair amount of time trying to locate this source code and have been unable to do so.

In the following file:

https://github.com/facebook/draft-js/blob/5d5f1b4b89c509d17697965ce9a0d596ed220c43/src/component/contents/DraftEditorBlock.react.js

There are references to:

```javascript
const Scroll = require('Scroll');
const Style = require('Style');
```

I'm having trouble locating where the actual files are. I couldn't find them in the draft-js project itself. I couldn't find them in `package.json`. I thought they may be dependencies of the packages in `package.json` but I couldn't find them on NPM either.

In your answer, I'd appreciate it if you could tell me how you tracked it down as well. I feel like I'm missing some way in which `require` actually works.

**Comment by grrowl** [comment]
It's possible this document about the React codebase might shine some light on it? https://github.com/gaearon/react/blob/b7fa6fa37880e2f3cff7bb6967f056bc4d72e6b9/docs/contributing/codebase-overview.md

**Comment by houkanshan** [comment]
They're in fbjs https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/core/dom/Scroll.js

Directly, you can search in your `nodes_modules/draft-js/` and you'll find out it's real path:

```js
var Scroll = require('fbjs/lib/Scroll');
```

I believe they're using [`babel-preset-fbjs`](https://github.com/facebook/draft-js/blob/master/gulpfile.js#L49) with [module-map](https://github.com/facebook/draft-js/blob/master/scripts/module-map.js ) to reach this.

**Comment by davidchang** [comment]
Ahh, yes - this article recently written by Dan Abramov describes how the React codebase works, explaining Facebook's module system, fbjs, and some of the build process: https://facebook.github.io/react/contributing/codebase-overview.html

Closing as this is a question that has been answered, but feel free to reopen if further questions or to ask in the Draft Slack channel.
