### ISSUE TITLE
Typing is inserting all new characters at the beginning of a line.

### ISSUE THREAD

**Issue by andrewpatrickburns** [facebook/draft-js#700]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Every new character typed into the editor is inserted at the left of the first line, resulted in reversed input.

This is also stopping me from selecting a portion of text, and in some cases, the caret displays on the right side of the text editor.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

```
  render() {
  
  	let editorState = this.state.editorState
    let contentState = editorState.getCurrentContent()
    
    let newEditorState = EditorState.createWithContent(contentState)  
  
    return (
      <div className="container-root">
        <Editor 
          placeholder="Type away :)"
          editorState={newEditorState}
          onChange={this._handleChange}
        />
      </div>
    );
  }
```

https://jsfiddle.net/m6z0xn4r/25/

**What is the expected behavior?**

To write as is normally expected from any text editor from left to right.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

Currently using:
Draft-js 0.9.1
Chrome Version 53.0.2785.116 m
Windows 10

**Comment by andersonmat** [comment]
This seems expected as you're creating a new `EditorState` on each `render(...)` without maintaining the `SelectionState` from the editorState passed to `onChange`.

**Comment by davidchang** [comment]
Thanks for responding to this @andersonmat ! I agree, this seems like a misuse of React as you shouldn't be re-creating the editor state every time render is called. If the desire is to load content from the server, this should happen in the constructor (or a componentDidMount if not using the React.Component class).

I'm going to close this, but @andrewpatrickburns , feel free to reopen if any follow up questions or to ask in the Draft Slack channel where others are often available to offer help in real time.
