### ISSUE TITLE
how to handle custom Entity types?

### ISSUE THREAD

**Issue by michelson** [facebook/draft-js#703]
Hi , I'm trying to render more than one atomic blocks , with the `blockRenderer` 

```coffee
  blockRenderer: (block)=>
    if (block.getType() is 'atomic')
      return (
        component: ImageBlock
      )
    if (block.getType() is 'atomic:embed')
      return (
        component: embedBlock
      ) 
    return null;
```

Is there a way to label an Entity with custom name? I've tried with `Entity.create('atomic:embed', 'IMMUTABLE', {foo})` but I always get "atomic" type in `block.getType()` on the `blockRenderer`

thanks

**Comment by mzbac** [comment]
@michelson here you are checking block type ```js     studentViewState: state.studentView,``` 
Entity.create('atomic:embed', 'IMMUTABLE', {foo}) is creating type for entity.. they are different types

**Comment by michelson** [comment]
thanks @mzbac ! it works
yes, I've seen that creation of entities in master brach was mmoved to editorState, so Entity.create will be unsupported ?

best
