### ISSUE TITLE
ContentBlock initialize with text?

### ISSUE THREAD

**Issue by michelson** [facebook/draft-js#706]
Hi! I'm inserting a custom block which I want to make editable. it works if I type text on it , just wondering if it's possible to set initial content and custom styles on it ?
``` js
return(
      <span>
          <EditorBlock {...@props} 
              className="imageCaption"
              text="my initial content"
          />
      </span>
    )
```

best regards

**Comment by davidchang** [comment]
Hi @michelson - sorry for the late response! Here's a simple JSFiddle that describes sort of what it seems like you want to do: https://jsfiddle.net/rh2x1oaz/

If you have further questions, I'd encourage you to join the Draft.js Slack channel and ask for help there (there will be more people available to help answer questions or give feedback).

I'm going to close this, but feel free to re-message or re-open if further questions or issues.
