### ISSUE TITLE
Uncaught TypeError: contentState.createEntity is not a function

### ISSUE THREAD

**Issue by 960590968** [facebook/draft-js#708]
How to create media Entity。I learn from examples, but createEntity not exist in My test。

**Comment by michelson** [comment]
yup , it seems that that create entity from state is on master branch only. and is not released yet. documentation is not clear on that.

you can use something like this for now:
```coffeescript
    entityKey = Entity.create('atomic', 'IMMUTABLE', {src: "foo bar"})
    @.props.onChange(AtomicBlockUtils.insertAtomicBlock(
        @.props.editorState,
        entityKey,
        ' '
      )); 
```

**Comment by davidchang** [comment]
Closing as this was a question that was answered (thanks for answering @michelson !) This will be out with the next release, my apologies for having inaccurate documentation. we'll try to get something out sooner than later

**Comment by lucidlive** [comment]
I think the main confusion is that the documentation says to use Entity.create and has links to supporting examples that use "createEntity"

**Comment by sergiu-paraschiv** [comment]
You can still see the old version [here](https://github.com/facebook/draft-js/blob/d9a1898985549e22b9854719f85ac099e7a0ab25/examples/entity/entity.html).
Same for the "link" example, older version works on latest release.

I know this is an alpha release but people are already using it in production so rc branches might reduce the number of issues like this one I think.

**Comment by againksy** [comment]
use 0.10 still see this error 6 how to fix this?
