### ISSUE TITLE
Is it possible to insert multiple AtomicBlock in a for loop?

### ISSUE THREAD

**Issue by Superoryco** [facebook/draft-js#713]
Here is what I want:

I have a drag&drop box so that I can drag multiple image at once to the editor, I use AtomicBlockUtils.insertAtomicBlock in a for loop to do so.

However, it looks like  'insertAtomicBlock' will first delete the previous block then add the new one, so the editor will only show the 1st and the last image if user drag more than 2 images.

For example:

Input:

[1, 2, 3]

output:

[1, 3]

Is there any functions that I missed to fulfill the requirement?

**Comment by houkanshan** [comment]
Hi, `AtomicBlockUtils.insertAtomicBlock` will return a new EditorState, so the next insertion should using this new EditorState.

like:

```js
let editorState = this.state.editorState
for (...) {
  editorState = AtomicBlockUtils.insertAtomicBlock(editorState, ...)
}
```

or using `reduce`:

```js
editorState = images.reduce(function (prevEditorState, img){
  return AtomicBlockUtils.insertAtomicBlock(prevEditorState, ...)
}, this.state.editorState)
```


Hope this will help.

**Comment by Superoryco** [comment]
Thank you very much, this did solve my problem!

And I also find following:

`    for (let i = 0; i < files.length; i++) {
      setTimeout(() => this.insertImage(files[i]), 1 * i);
    }
`
will also do the job. wording why...
