### ISSUE TITLE
Prevent adding text when certain inline style is set

### ISSUE THREAD

**Issue by jaulz** [facebook/draft-js#714]
**Do you want to request a _feature_ or report a _bug_?**
feature

**What is the current behavior?**
Prevent adding text when certain inline style (e.g. custom READONLY style) is set. In my case I would like to implement a template mode where the actual document is defined and another mode where the author can change it (except for READONLY styles).

**What is the expected behavior?**
Currently I tried to implement it via the following snippet in onChange. However, it does result in a strange behaviour that scrambles the text.

``` js
    const currentStyle:Object = this.state.editorState.getCurrentInlineStyle()
    if (!this.props.templateMode && currentStyle.has('READONLY') && editorState.getLastChangeType() === 'insert-characters') {
      handleChanges = false
    }

    // If changes should be handled update the actual editor state
    if (handleChanges) {
      this.setState({
        editorState,
      })
    } else {
      this.setState({
        editorState: this.state.editorState,
      })
    }
```

**Comment by davidchang** [comment]
@jaulz, is it possible to accomplish this using the readOnly property on the Editor component? https://facebook.github.io/draft-js/docs/api-reference-editor.html#readonly

**Comment by jaulz** [comment]
@davidchang yes, but then I would put the whole editor into read only mode? In my case I would like to make only certain parts of the document as read only. Think about this:
Person A creates a questionnaire and would like to make certain parts read only (e.g. Questions but basically it could be evertything in the document) by applying a custom READONLY style. 
Person B opens the previous document in a different "mode" which prevents him to change everything except for the parts that have the READONLY style but of course he can enter answers to the questions.
Thanks!

**Comment by MarkNijhof** [comment]
I second this requirement. I am f.ex. adding custom text elements that should only be added or deleted but never changed. IMMUTABLE basically allows for that mostly, except when adding text inside the text it will basically remove the custom "styling" and just leave the text. I have tried adding ```<span contentEditable={false}>text</span>``` but if this is the first element on a line I cannot place more text before it using the plain editor controls (keyboard)

**Comment by flarnie** [comment]
This sounds to me like a case for creating an immutable entity and styling it to look like plaintext, or whatever your text should look like. I could try to throw something together based on the questionaire example but I think I might be missing something. Why is this hard to do with immutable entities?

**Comment by flarnie** [comment]
This sounds to me like a case for creating an immutable entity and styling it to look like plaintext, or whatever your text should look like. I could try to throw something together based on the questionaire example but I think I might be missing something. Why is this hard to do with immutable entities?

**Comment by flarnie** [comment]
Since I would need more info to answer this question I'm going to close this for now. Please feel free to reopen if questions remain and give more context on why immutable entities won't solve this issue.
