### ISSUE TITLE
ConvertToRaw ignores components props/state

### ISSUE THREAD

**Issue by michelson** [facebook/draft-js#718]
Hi, I've been trying to save serialized content in json to initialize editor with it.
Right now is rendering all the elements which is great, the problem is, as I can tell, when I encode data with `ConvertToRaw` those custom components which have block props or internal state are serialized without it's internal state
I have not idea on how serialize those. 
is there any way to define how a component will be encoded? 
is possible to encode entire editor state in order to preserve component blockProps/state?

an example of encode/decode methods I'm using:

```coffeescript
  encodeEditorContent: =>
    raw = convertToRaw( @state.editorState.getCurrentContent() )
    raw_as_json = JSON.stringify(raw)

  decodeEditorContent: (raw_as_json)=>
    new_content = convertFromRaw(JSON.parse(raw_as_json))
    editorState = EditorState.createWithContent(new_content, @decorator)
```

any hints? 
Best regards

**Comment by michelson** [comment]
It seems that `props.block.data` and `props.blockProps` are different things. Were `props.block.data` gets serialized and `props.blockProps` don't.
I've managed this updating `editorState` merging the internal state of my component into the block data, then I've updated the `blockMap` of  `contentState` .

so , `props.blockProps` are not serialized by design on `convertToRaw ` right ? or I'm doing something wrong ?

**Comment by N1kto** [comment]
@michelson, `props.block.data` and `props.blockProps` are indeed 2 different things.
I am not a master of explanation, but `block.data` is, well, `ContentBlock`'s metadata, something having direct relation to `ContentBlock` itself (its content), so it is serialized during conversion.
Whereas `blockProps` is an object existing only at time of rendering. Data in this object is meant to have relation to React component which renders your custom `ContentBlock` but not to `ContentBlock` itself . 

I don't know what is your exact use case, but if you want to have some data persisted with `ContentBlock` you should keep it within `ContentBlocks`'s `data` property. Or in `Entity`. But not in `blockProps`,

**Comment by michelson** [comment]
Hi @N1kto , thanks for the detailed explanation. 👍 
yes, I've solved merging the props into ContentBlock data and works fine

best!
