### ISSUE TITLE
Semantics: "Header" should be "Heading" in rich.html

### ISSUE THREAD

**Issue by rareyman** [facebook/draft-js#724]
I'd like to point out minor semantics issues I see in `rich.html`.

Currently the example refers to `h1`–`h6` as “headers”, when really they should be called “headings”.

This perpetuates incorrect semantics when referring to these tags. “Headers” are generally known to be layout blocks that contain header information, while “Headings” are defined as block-level text titles. While people casually use these two terms interchangeably, they really should be better defined to avoid confusion.

**Comment by tylercraft** [comment]
Thanks for the feedback. Would be happy to accept a pull request for this if you have time.

**Comment by jihdeh** [comment]
I can take on this @tylercraft , but to be clear does it mean changing, e.g `header-one`  to `heading-one` ?

**Comment by tylercraft** [comment]
Any reference to headers should be changed to headings. It's how the W3C refers to them as well
https://www.w3.org/TR/html-markup/h1.html

**Comment by tylercraft** [comment]
Semantically this should change, but it will be too big of an issue to migrate. Therefore this is not something we will do so I am closing it out.
