### ISSUE TITLE
blockRenderMap should not render "element" when "wrapper" is specified

### ISSUE THREAD

**Issue by macrozone** [facebook/draft-js#725]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When you specify `element` and `wrapper`, the element is rendered inside the wrapper, altough the documentation says, that `element` "...will be used during paste or html conversion to auto match your component" (https://github.com/facebook/draft-js/blob/master/docs/Advanced-Topics-Custom-Block-Render.md)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

```
const CustomComponent = ({children}) => <h1 style={myinlinestyle}>{children}</h1>

const blockRenderMap = Immutable.Map({
  'header-one': {
    element: "h1",
    wrapper: <CustomComponent />,
  },
  
});

// we result in <h1><h1 style="...">...</h1></h1>
```

**What is the expected behavior?**

It should not render the `element` or documentation should be different.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

Draft 0.9.1, OSX in Chrome

Its related to this bug here: https://github.com/facebook/draft-js/issues/406

I think that the documentation here caused confusion. Looking at the code of `DefaultDraftBlockRenderMap` i see that e.g. the `<li>` tags needs the wrapper to wrap it in a `<ul>` whereas the code-block `<pre>` would not need the wrapper (or the wrapped `element`): https://github.com/facebook/draft-js/blob/69890ed57b5f4256cc93ae8e9ea178296851a23e/src/model/immutable/DefaultDraftBlockRenderMap.js

So wich use case is correct? matching or wrapping?

**Comment by davidchang** [comment]
Wrapping is the correct behavior and the <pre> behavior is sort of a one-off anomaly/already being discussed in issue #406. I haven't read the whole discussion in 406 yet, but I believe we should be keeping the element and that we should improve the documentation.
