### ISSUE TITLE
copy and paste from word doc?

### ISSUE THREAD

**Issue by the-creature** [facebook/draft-js#728]
For my use case copy and paste from Microsoft Word ist a common task. Draft.js does not handle this very well right now,Is there any plugins or anything available to provide this functionality?

Not the whole .docx standard but Bullet point lists and base formatting.

**Comment by davidchang** [comment]
Hi @the-creature , we don't currently support this and I'm not currently aware of any plugins that support this. I think someone asked about this recently in the Draft.js Slack channel, but there was nothing that was supported. you may think about asking there again, as you may get better responses there.

**Comment by the-creature** [comment]
Thx for the quick response! Do you mind posting the slack channel? Or is a private/invite type of group?

Thx!

**Comment by davidchang** [comment]
anyone can join! the slack channel has more people in there willing to help and is more so the right place for questions/discussions like these.

i'm going to close this issue. feel free to respond or reopen if further questions/comments!

**Comment by terencechow** [comment]
For people looking at this in the future, `handlePastedText` might help you for your use case.

Pasting from word gives you some odd html which is available in the second param of the `handlePastedText` function. You will have to handle that html the way you want because there are a lot of non-standard html formatting. For example, headers are just font size differences so it makes it hard to replace with header tags. Underlines are just a class with `text-decoration: underline` instead of something like maybe `<ins>` tag. So if you are really serious about pasting from Word, you will have to do a lot of custom regexing, but hopefully this helps you.

Note: `stateFromHTML` is from `draft-js-import-html`

```
handlePastedText(text, html){
    const { editorState } = this.state
    const blockMap = stateFromHTML(html).blockMap
    const newState = Modifier.replaceWithFragment(editorState.getCurrentContent(), editorState.getSelection(), blockMap)
    this.onChange(EditorState.push(editorState, newState, 'insert-fragment'))
    return true
}

...


<EditorState
    handlePastedText={this.handlePastedText}
   />
```

**Comment by IzaGz** [comment]
@terencechow , awesome ! it works! Thank you! 
, i am returning `return "handled";`
 but i got:
 `Type 'string' is not assignable to type 'DraftHandleValue'.`

**Comment by IzaGz** [comment]
@terencechow Thank you! solved it with adding  returning type any to function
`handlePastedText(text, html): any{` 
i am using typescript*

**Comment by searene** [comment]
I do hope I could get the exactly same html as the copied one in my draft.js editor, but it seems extremely hard to do so.

**Comment by danieloprado** [comment]
Added a fallback for text if html is null: 

```js
handlePastedText(text, html){
    const { editorState } = this.state
    const blockMap = stateFromHTML(html || text /* here */).blockMap
    const newState = Modifier.replaceWithFragment(editorState.getCurrentContent(), editorState.getSelection(), blockMap)
    this.onChange(EditorState.push(editorState, newState, 'insert-fragment'))
    return true
}

...


<EditorState
    handlePastedText={this.handlePastedText}
   />
```

**Comment by luuvansinh** [comment]
How can I remove all styles of html ?

**Comment by jf97** [comment]
Your `handlePastedText()` should have three parameters: `text`, `html`, `editorState`.  If you only want to insert the text, you can insert like this: 
```

function handlePastedText (text, html, editorState) {
	var content = editorState.getCurrentContent();
	var selection = editorState.getSelection();

	var newContent = Modifier.insertText(
		content, 
		selection,
		text
	)

	var newEditorState = EditorState.push(editorState, newContent, "insert-characters")
	//Then send this to onChange()
	return 'handled'
}
```

**Comment by hiranvikas77** [comment]
@folkjc thanks your answer saved me. I wanted to have pasted text as plain text. But after sending emails, I was getting extra lines because of <p> tag. But this answer helped me to achieve what I wanted
