### ISSUE TITLE
How best to create entities after input

### ISSUE THREAD

**Issue by ericbiewener** [facebook/draft-js#730]
What's the preferred approach for creating entities in response to the editor text changing? Essentially, something like a composite decorator for entity creation. Options as I see them:

1. In the `onChange` event handler. But this fires with every type of change, such as selection changes. I only need to worry about text changes.
2. In `handleBeforeInput`, but then I'd have to insert the typed character in the right place myself.

Any other locations? I thought of sticking this into a composite decorator even though that's not what it's for, but that won't work because you need access to at least the `contentState` in order to use `Modifer.applyEntity()`, and the decorators only get fed the selected `contentBlock`.

**Comment by ericbiewener** [comment]
Nevermind, doing it in `onChange` but first checking to make sure that the `contentState` has changed appears to be a solid solution when combined with [this fix](https://github.com/facebook/draft-js/pull/667).

**Comment by aehlke** [comment]
How do you best check that `contentState` has changed? Keep track of a `lastContentState` from within `onChange`..?
