### ISSUE TITLE
How to Retrieve Metadata for a Range of Text (Get the Current Href from Existing Link)?

### ISSUE THREAD

**Issue by superKalo** [facebook/draft-js#732]
Hello,

I have a question about retrieving metadata for a range of text.

I took the [link example](https://github.com/facebook/draft-js/blob/master/examples/link/link.html). Let's say we add a link to a range of text. I want the next time when I select the text and click "Add Link" - to retrieve the current link href and to pre-fill the input.

![selection](https://cloud.githubusercontent.com/assets/2548061/19595953/f538ea64-9794-11e6-82a2-a667d9ffb568.png)

So, basically I assume I need to [hook-up additional logic to the `_promptForLink` method](https://github.com/facebook/draft-js/blob/master/examples/link/link.html#L72) - instead of always having empty string for `urlValue`, to pre-fill with the current url for this text range (if it exists).

I read about how to [retrieve entities](https://facebook.github.io/draft-js/docs/advanced-topics-entities.html#creating-and-retrieving-entities), however - I must have missed something, because I can't figure out how to retrieve it. This doesn't work:

```javascript
_promptForLink(e) {
  e.preventDefault();
  const {editorState} = this.state;
  const selection = editorState.getSelection();
  if (!selection.isCollapsed()) {

    const contentState = editorState.getCurrentContent();

    // TODO: I can't really figure out what I need to pass to getBlockForKey
    const startKey = editorState.getSelection().getStartKey();
    const blockWithLinkAtBeginning = contentState.getBlockForKey(startKey);

    const linkKey = blockWithLinkAtBeginning.getEntityAt(0);
    const linkInstance = Entity.get(linkKey);
    const {href} = linkInstance.getData();

    this.setState({
      showURLInput: true,
      urlValue: href || '', // TODO: Pre-filll with the existing value here
    }, () => {
      setTimeout(() => this.refs.url.focus(), 0);
    });
  }
}
```

Can you please advice me how to do that?

**Comment by ericbiewener** [comment]
You're almost there, but you need to grab the `url` property off `linkInstance.getData()`, not `href`. `getData` does not provide you with DOM metadata, but rather the metadata of the `Entity` at the time it was created. In the link example, you can see that this property is named `url` [here](https://github.com/facebook/draft-js/blob/master/examples/link/link.html#L93).

**Comment by superKalo** [comment]
Thank you @ericbiewener !

There was one more issue with the patch I provided. In case someone is struggling with the same use-case, here's the final solution I applied: https://github.com/facebook/draft-js/pull/735
