### ISSUE TITLE
handleKeyCommand goes wrong while two Editor in a page.

### ISSUE THREAD

**Issue by PokimLee** [facebook/draft-js#736]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
handleKeyCommand

**If the current behavior is a bug, please provide the steps to reproduce 
I got two Editor in one page, but when I  wrote something and press 「command」+「z」, there will be an UNDO operation but while I press 「command」+ 「shift」+ 「z」in the Editor, the handleKeyCommand method REDO cannot work!  here is my code: https://jsfiddle.net/xnyd3geq/8/

ps.but it just work in the only one Editor case like: https://jsfiddle.net/xnyd3geq/6/

**What is the expected behavior?** 
the REDO operation work in the two Editor page.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
"draft-js": "^0.9.1", 
browse: chrome,
OS: OS X EI Captain

**Comment by davidchang** [comment]
is it possible to provide some code? that would help us help you!

**Comment by PokimLee** [comment]
@davidchang 
I hav updated the issue and add my code on it.

**Comment by davidchang** [comment]
hi @PokimLee - in the interest in trying to keep issues manageable, I'm going to close this. when you add your code, please simply reopen the issue!

**Comment by PokimLee** [comment]
@davidchang  
sorry, I have made a bad statement.
What I want to say  is that I've add my code to the issue description updating days ago:

> I got two Editor in one page, but when I wrote something and press 「command」+「z」, there will be an UNDO operation but while I press 「command」+ 「shift」+ 「z」in the Editor, the handleKeyCommand method REDO cannot work! here is my code: https://jsfiddle.net/xnyd3geq/8/

> ps.but it just work in the only one Editor case like: https://jsfiddle.net/xnyd3geq/6/

so, you can check it on [https://jsfiddle.net/xnyd3geq/8/](url)
