### ISSUE TITLE
The final space is `nbsp` (ascii 160), internal spaces are ascii 20

### ISSUE THREAD

**Issue by rcoh** [facebook/draft-js#74]
if you type `a b ` and call `editorState.getCurrentContent().getPlainText()` the internal space is a normal space but the final space is ascii 160. This causes problems if you want to match this text against other strings. I fixed it externally with the code below, but maybe this fix should be handled internally?

```
  cleanPlainText(editorState) {
    const text = editorState.getCurrentContent().getPlainText();
    const nbsp = String.fromCharCode(160);
    const regex = new RegExp(`${nbsp}`, 'g');
    return text.replace(regex, ' ');
  },
```

**Comment by hellendag** [comment]
Hmm, this doesn't repro for me. You've typed `a`, ` `, `b`, correct? I'm not sure why there would be an `&nbsp;` there as well.

**Comment by rcoh** [comment]
There is a space after the b and that's the one that comes out as the incorrect ascii code. I'll see if I can make a tester tonight.

**Comment by hellendag** [comment]
Ah, so you typed `a`, ` `, `b`, ` `? And the two spaces are not the same character?

**Comment by rcoh** [comment]
exactly

**Comment by hellendag** [comment]
Which browser and OS?

**Comment by rcoh** [comment]
chrome 48.0.2564.109, OS X 10.11.2, 

If it isn't reproducing elsewhere, perhaps it's a weird artifact of how I was using the control.

**Comment by hellendag** [comment]
Are you able to determine whether the space bar character insertions are occurring via `editOnBeforeInput`?

**Comment by hellendag** [comment]
@rcoh just wanted to follow up on this. I haven't seen this issue before, but I'd certainly like to fix it if it's widespread.

**Comment by MindRave** [comment]
I think I'm seeing the same thing here. Chrome 48.0.2564.116 (64-bit), OSX 10.11.2. The last space is an &nbsp for me as well.

<img width="880" alt="screen shot 2016-03-02 at 23 51 17" src="https://cloud.githubusercontent.com/assets/4063406/13478640/41ae3298-e0d2-11e5-8116-ea4019dfa178.png">

**Comment by hellendag** [comment]
You didn't type that with an <kbd>option</kbd>+<kbd>spacebar</kbd>, right? Just regular spaces?

**Comment by MindRave** [comment]
Yes, just regular spaces.

**Comment by hellendag** [comment]
If you add more spaces, does it add more `&nbsp;` characters? Or does that one continue to stick to the end of the text node?

Also, are you using any Chrome extensions?

**Comment by MindRave** [comment]
It doesn't add more `&nbsp;` characters if I add more spaces, that one continues to stick to the end of the node, yes.

I am (quite a few), but I disabled all of them, shut Chrome down and retested. Same thing.

**Comment by hellendag** [comment]
Strange. Are you seeing the same thing on draftjs.org, and on Facebook comments as well?

**Comment by MindRave** [comment]
Tested. No, I'm not seeing it. Tested on the examples from the repo, they work fine as well. Wonder what is it that's going wrong here. If it's something on my end, I'll test with a fresh copy and then go from there (tomorrow, seeing as it's night here in France). Wonder if it's Flux (alt, updating the editorState from a Store) - but I can't see why.

**Comment by hellendag** [comment]
Hmm, possibly Flux. Not sure if you saw this, but it has come up a handful of times within FB: http://facebook.github.io/draft-js/docs/advanced-topics-issues-and-pitfalls.html#delayed-state-updates

**Comment by rcoh** [comment]
I was also using Redux, so that seems like a possibility.

**Comment by MindRave** [comment]
@hellendag Hi again! Just tested with a clean component - from scratch, no flux, root-level component, instant initialisation, and I'm still getting that &nbsp; at the end. If there are any more clues I can provide, give me a sign.

@rcoh have you used your function to cleanup text while a user is typing? I was able to use it and get the whole text of the Editor's state, and now looking into implementing it on the typed text, to get rid of the &nbsp; on the fly.

The issue it creates for me is that, when I delete a line using <kbd>option</kbd>+<kbd>backspace</kbd>, the caret jumps quite a bit and doesn't stop at the space, but rather right in front of the word. After that, I need to press <kbd>space</kbd> twice to get it to insert a normal space (and sometimes when I press space it gets all confused and jumps before the last letter of a word - even on a cle

**Comment by Calyhre** [comment]
@MindRave In fact, only `white-space: pre` is needed to fix the issue :)

**Comment by MindRave** [comment]
@Calyhre indeed and thank you for the pointer! I ended up going with `pre-wrap` in the end, that way the text wraps normally. ;)

**Comment by jonathanmv** [comment]
Wrapping the editor with a `pre` tag also fixed an issue I was having when setting the content of the editor with a space at the end, e.g <code>jonathanmv </code>. The space was not being taking into account when focusing the editor; the caret was next to the `v` instead of being after the space.

**Comment by hellendag** [comment]
If you're including https://github.com/facebook/draft-js/blob/master/src/component/base/DraftEditor.css, you shouldn't need any of this. `white-space: pre-wrap` is applied by default.

**Comment by hellendag** [comment]
I'm thinking I should go ahead and include `whiteSpace: 'pre-wrap'` in a style object directly within the JS, so that this doesn't happen anymore.

**Comment by MindRave** [comment]
@hellendag That is probably a good idea. Quite a few people (such as myself) will either choose to not include the styles in order to write their own, or simply forget to include them. Another solution would be pointing it out in the doc ("Issues and pitfalls" section?) but including it directly in the JS sounds better.

That said, thank you again for your time and support!

**Comment by hellendag** [comment]
I'm about to add it to the doc now. :)

The right thing to do here is to run a build step, then use the resulting Draft.css resource.

You're welcome! :)

**Comment by hellendag** [comment]
Closing because there is a resolution with Draft.css.

**Comment by andpor** [comment]
I am running into this issue myself....I am forced to overwrite styles for block public-DraftStyleDefault-block to white-space: nowrap to force the editor to behave as single line text input. If I use pre-wrap or pre the block wraps into multi-line...

If I use nowrap the block does not wrap but Undo stack is all messed up...because of the white space nbsp issues...

Any idea how to make it work?
