### ISSUE TITLE
Get all entities

### ISSUE THREAD

**Issue by bryanph** [facebook/draft-js#750]
Right now it doesn't seem to be possible to get all entities in the store.
I want to be able to get all entities in order to sync the removal of entities with a server resource. So that on removal I can make a request to the server for all removed entities.

Also, because the Entity store is separate from the editor state, there is no way to keep reference to an entity after removing it in the text.

**Comment by aehlke** [comment]
How did you solve this?

**Comment by davidchang** [comment]
you can retrieve entities using this API method on ContentBlock: https://facebook.github.io/draft-js/docs/api-reference-content-block.html#findentityranges

so something sorta like:

```
editorState.getCurrentContent().getBlockMap().forEach((block) => {
  block.findEntityRanges((character) => {
    ...
  });
});
```
