### ISSUE TITLE
Is draft-js compatible with browserify ?

### ISSUE THREAD

**Issue by mitermayer** [facebook/draft-js#77]
Can we just add a node dependency to draft-js and include it via browserify?

**Comment by spicyj** [comment]
Yes.

**Comment by maxmatthews** [comment]
@mitermayer Do you have example code of how to get this working in Browserify? I'm only familar of how to get it working when it's just a `require` not an `import`

**Comment by maxmatthews** [comment]
For anyone else who stumbles upon this, import is an ES6 thing that is not yet supported in Browersify without something like Babel. http://stackoverflow.com/questions/33042867/browserify-import-require
I didn't feel like installing Babel, so I ended up with this as a solution:
```js
DraftJS = require('draft-js');
EditorState = DraftJS.EditorState;
Editor = DraftJS.Editor;
```
Which lets you use `<Editor />`
I happen to be using Meteor with Broswerify.
