### ISSUE TITLE
use master branch in project

### ISSUE THREAD

**Issue by michelson** [facebook/draft-js#776]
how can I use master branch from npm ? I want to use the latest branch on my project

if I declare draftjs dependency from github it not came with /src or /lib 

thanks

**Comment by Pofigizm** [comment]
add in `script` section of your `package.json`:
```
"postinstall: "cd node_modules/draft-js && npm install"
```

**Comment by StevenIseki** [comment]
Currently I have been using Draft master branch in a project, as I need the convertFromHtml image support. I have had to add the `"postinstall: "cd node_modules/draft-js && npm install"` script. Then clone the Draft.js repo seperately as that gives the master branch, npm does not. Then I copy over lib from the cloned master version of Draft to the draft-js in my `node_modules` and then I can use it as follows:
`import { Editor, EditorState, convertFromHTML } from '../../node_modules/draft-js/lib/Draft'`

Surely there are some easier steps than this, but for anyone needing image support with html serialization this is how to do it, until the 0.10 version is released.

**Comment by davidchang** [comment]
Should be doable via npm, see under the "Git Dependencies section" on this link http://www.devthought.com/2012/02/17/npm-tricks/

Sorry for such late response. I'm just going to go ahead and close this, but please feel free to reopen if any more issues or questions.

**Comment by davidchang** [comment]
so this line added into package.json worked for me to pull down master:

    "draft-js": "git@github.com:facebook/draft-js.git#master",
