### ISSUE TITLE
How to deal with paste image from HTML 

### ISSUE THREAD

**Issue by ravuribabu** [facebook/draft-js#777]
I am trying to copy / paste part HTML page with an image into DRAFT. For image,  I see that DRAFT has created atomic block but no entity was attached to it,  image is not displayed in DRAFT.

I have a decorator already which looks for IMAGE type entities and renders them appropriately. 

How to handle copy/paste events and insert custom render behaviour?

**Comment by davidchang** [comment]
@ravuribabu - my apologies for such a late response. I think this should be handled by #832, can you see if this solves what you were looking for?

**Comment by flarnie** [comment]
I think this was included in the 0.10.1 release, from https://github.com/facebook/draft-js/commit/8ac72f723fb2d9102db833a9b060dfd66df65652

If any questions remain please open a new issue, thanks!
