### ISSUE TITLE
Can you get the last change to take place?

### ISSUE THREAD

**Issue by eamontaaffe** [facebook/draft-js#781]
# Get last change

Is there a way to get the last bit of text to be added? 

I see that you can `getLastChangeType()` but you can't seem to get the actual last change of text.

Would this even be possible to find without doing a string difference from the last state to the new state?

Thanks for any help :smile:

**Comment by lvarayut** [comment]
@eamontaaffe Have you found a way to get the last change? I'm facing the same issue.

**Comment by eamontaaffe** [comment]
@lvarayut I never found a good way to do it. To be honest, my project has moved to using the [slatejs editor](http://slatejs.org/). 

They have a branch which they are working on called [`expose-transforms`](https://github.com/ianstormtaylor/slate/tree/expose-transforms) which will eventually be merged into master. This provides a complete description of the last change through an operations object in the onChange method. The branch itself is still a little buggy, but if you can put up with it for a while seems like a really good option.

**Comment by lvarayut** [comment]
Thanks @eamontaaffe, I'll take a look soon.
