### ISSUE TITLE
Document Mistake :P

### ISSUE THREAD

**Issue by khacthanh244** [facebook/draft-js#784]
Go to page https://facebook.github.io/draft-js/docs/api-reference-data-conversion.html in bottom  will see:
a href="https://github.com/facebook/draft-js/blob/8ac72f723fb2d9102db833a9b060dfd66df65652/examples/convertFromHTML/convert.html">here</a.

**Comment by davidchang** [comment]
thanks for opening the issue @khacthanh244 !
