### ISSUE TITLE
Multiline Placeholder Text

### ISSUE THREAD

**Issue by Datamine** [facebook/draft-js#788]
Does Draftjs in any way support multiline placeholder text? 

Thus far, I'm under the impression that it treats all placeholders as one string, and simply wraps that string at the right boundary of the editor.

**Comment by flarnie** [comment]
I don't know of any cases of multiline placeholder text off the top of my head. Have you tried it?

**Comment by flarnie** [comment]
I'm not sure what else to say here - it's worth experimenting but I don't know of any current use cases where we do this. Thanks for asking!

**Comment by talkingtab** [comment]
I have a use case: 
'Ecrivez le francais ici ..'
'Or write English Text and select to translate'
