### ISSUE TITLE
Add custom style to inserted text

### ISSUE THREAD

**Issue by cruz02148** [facebook/draft-js#791]
Hello All,

I cannot figure out how to get what seems like a simple task to work. All I want is to have a button that when clicked will insert some text into the editor and have it styled a certain way (in my case RED and BOLD). 

I see the method `Modifier.insertText()` and I see that the 4th argument to this is `inlineStyle?: DraftInlineStyle`. However, I just can't seem to figure out how to style this text. The button does work and inserts text into the editor at the last cursor position, but my last step is the add styling.

Another common use case would be: a button that when clicked opens up a text input to allow a user to enter a URL and then when the user clicks insert, that URL is inserted into the DraftJS Editor at the last cursor position and it is underlined and colored blue (the typical URL style).

Any helps would be greatly appreciated!

**Comment by cruz02148** [comment]
So I ended up getting this work FINALLY. Here's what I did:

```
const ncs = Modifier.insertText(contentState, selection, "BOLD TEXT", OrderedSet.of('DD_HIGHLIGHT'));
```
DD_HIGHLIGHT is a custom Style Mapping that I setup using the `customStyleMap` prop on the Editor component. I did have the install Immutable.js as a module and then `import { OrderedSet } from 'immutable'`

**Comment by Raincle** [comment]
@cruz02148 Hi, Cruz. 
I just have the same problem as you. Thank you for your solution.
But I use `import { OrderedSet } from 'immutable'`, and wrote like your way.
An err occurred: `Uncaught TypeError: _immutable2.default.of is not a function`

This is my code below:
```
const { editorState } = this.state;
const currentContent = editorState.getCurrentContent();
const selection = editorState.getSelection();
const newEditorState = Modifier.insertText(currentContent, selection, '123456', OrderedSet.of('IMPORTANT'));
this.setState({
    editorState: newEditorState,
});
```

Could you help me?

**Comment by cruz02148** [comment]
@Raincle have you installed the `immutable` library?

`npm i -S immutable`

**Comment by vairamuthu16** [comment]
Hi  @cruz02148 

Could you please share sample code for Add custom style to inserted text

I follow the  your steps i face another issue 

Please refer the below screen shot
![image](https://user-images.githubusercontent.com/62050495/86099514-30ef2200-bad5-11ea-9c76-7dd01a167aba.png)
