### ISSUE TITLE
Modifier.removeRange removes block but fails at removing its entity.

### ISSUE THREAD

**Issue by tobiasandersen** [facebook/draft-js#793]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Modifier.removeRange removes blocks but fails at removing their entities.

**What is the expected behavior?**
When a block that has an entity is removed, its entities should also be removed.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
I'm using the master branch (where the EntityMap lives under ContentState).

I'm having an attempt at #203, and while working on implementing backspace behavior, I found what I believe is a bug. I'm using the [keyCommandPlainBackspace](https://github.com/facebook/draft-js/blob/a16bc55bf8297af627e8a4cfe5f283f88e7fc8bd/src/component/handlers/edit/commands/keyCommandPlainBackspace.js#L26) method (which is not yet exposed) to remove the currently selected (atomic) block. I'm calling it like this: `keyCommandPlainBackspace(state)`, where state.selection is:

```
{
  anchorKey: "5vbiq"
  anchorOffset: 0
  focusKey: "5vbiq"
  focusOffset: 0
  hasFocus: true
  isBackward: false
}
```

When it reaches the `removeRange` method, the `rangeToRemove` parameter looks like this:
```

{
  anchorKey: "9u2im"
  anchorOffset: 0
  focusKey: "5vbiq"
  focusOffset: 0
  hasFocus: true
  isBackward: true
}
```

Now, since the range contains two blocks, it will pass `contentState` and `rangeToRemove` to [removeEntitiesAtEdges](https://github.com/facebook/draft-js/blob/a16bc55bf8297af627e8a4cfe5f283f88e7fc8bd/src/model/transaction/removeEntitiesAtEdges.js), and **expect back a contentState without any entities belonging to the blocks in rangeToRemove**. This doesn't happen however, `removeEntitiesAtEdges` fails at removing the entity corresponding to the block with `key: 5vbiq`. 

Next, the returned contentState is passed to [removeRangeFromContentState](https://github.com/facebook/draft-js/blob/a16bc55bf8297af627e8a4cfe5f283f88e7fc8bd/src/model/transaction/removeRangeFromContentState.js), which successfully removes the block (5vbig).

I might be doing things wrong here, but either way, shouldn't these methods guarantee that a removed block's entity is also removed?

**Comment by LeoBakerHytch** [comment]
Just wanted to second this. I’m having problems with cutting atomic blocks — `editOnCut` also uses `Modifier.removeRange` without removing the entity.

**Comment by tobiasandersen** [comment]
I don't do it like this anymore, and don't know if it's (still) a bug or not. I'll close it for now...

**Comment by plonko** [comment]
@tobiasandersen How do you do it? thnx

**Comment by tobiasandersen** [comment]
Sorry, I'm not using Draft anymore and can't remember :(
