### ISSUE TITLE
Show examples of deprecated *and* updated API for entities

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#816]
**Problem:**

The examples included on the current master use the updated-but-undocumented API for Entity state.

We are in the process of releasing a version of Draft that supports both, which will be followed by a version which only supports the new API.

In the mean time, having 'examples' that don't match the current version or documentation is creating confusion. See issues #805, #794, and #778.

**Solution:**
1. Comment here and tell us you are working on this - otherwise I'll do it sometime soon.
2. Create two directories under 'examples' - 'draft-0-9-1' and 'draft-0-10-0'
3. Move the examples present on the latest 'master' branch into the 'draft-0-10-0' directory.
4. Copy [the examples that were present in version 0.9.0](https://github.com/facebook/draft-js/tree/4e4ad9805d3e112ae30df20becbd3f0ba0de5683/examples) into the 'draft-0-9-1' directory.

Note that some examples may currently be buggy - see issue #815.

**Comment by tobiasandersen** [comment]
I've created a PR for this now, see #824.

**Comment by flarnie** [comment]
Thanks again for fixing this @tobiasandersen
