### ISSUE TITLE
Feature requests/discussion: Expose more handlers for clipboard events

### ISSUE THREAD

**Issue by tobiasandersen** [facebook/draft-js#823]
I have quite a few thoughts about this, but I'm not really sure what I want to do with it. So I'll just write down what I want to be able to do, and maybe we can have a discussion about it. 

### Set data on ClipboardEvent.clipboardData
**Why?**
It'll give us more control over what's going to be pasted in the future, both inside and outside of Draft.

**Possible solution:**
Exposing handlers for copy and cut, e.g. `handleCopy` and `handleCut` (related: #721).

### Hook into onPaste
**Why?**
I want to use Draft's implementation of `onPaste`, but I need the ability to go into each pasted block's data record and change a property. That is, I want Draft to create copies of the copied blocks and add them to the BlockMap, but I need access to the BlockMap before it reaches the handleChange method since we have keys inside some block's data records that must be unique across our application.

**Possible solution:**
The simplest and most consistent solution is (mostly) already in place, i.e. expose a handler for `onPaste`, which would return either` 'handled'` or `'not-handled'`. But this means I have to re-implement everything myself. Currently we don't have access to the full clipboardData object (only the values of `data.getText()` and `data.getHTML()`), so I can't read custom data from it. 

Some other possibilities would be: 

- Set a different `changeType` in the onPaste method, e.g.` 'paste-fragments'`. That way I can check for it in my change handler, do a diff and change whatever I want in the new blocks.

- Add a handler for things that are about to be inserted, e.g. `handleBeforeInsertFragment` (in regard to [this](https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnPaste.js#L191).

- Let me manipulate the `internalClipboard` instance. This would allow me to just change a few props in the `internalClipboard` and give it back to Draft and let it continue with the pasting. Nothing else seems to work like this though, so it would add more complexity and probably be more error prone. 

---

What are your thoughts on this? I'd be happy to create PRs for it once we agree on something.

**Comment by thibaudcolas** [comment]
This is now implemented since v0.11.0 with `onPaste`, `onCopy`, `onCut`, and `formatPastedText` since v0.11.7. Unfortunately there doesn’t seem to be any documentation for those new props.

**Comment by thibaudcolas** [comment]
A word of warning – having spent a bit more time with those new additions, they feel like a pretty poor API compared to the original suggestions from this issue. For both `onCopy` and `onCut`, there is no way to add custom behavior while retaining the Draft.js internals that make copy-paste work ([`editOnCopy`](https://github.com/facebook/draft-js/blob/f348098c4f3bb6eaba7253886013b1709655ec4f/src/component/handlers/edit/editOnCopy.js), [`editOnCut`](https://github.com/facebook/draft-js/blob/f348098c4f3bb6eaba7253886013b1709655ec4f/src/component/handlers/edit/editOnCut.js)). So effectively those internals either need to be re-implemented, or code that uses onCopy/onCut needs to import those internal APIs and use them alongside any custom logic.
