### ISSUE TITLE
editorState.getCurrentContent is not a function.

### ISSUE THREAD

**Issue by Catorpilor** [facebook/draft-js#825]
> #621 did not solve my problem.

I am using draft-js in my react-redux app. 
In my component's constructor i dispatch an action to set the state of editorState.
```
// initialState
// initState = {}

// EditorComponent

class EditorComponent extends React.Component {
  constructor(props) {
     super(props)
     this.props.dispatch({
            type: CHANGE_TEXT,
            payload:  EditorState.createWithContent(ContentState.createFromText(
                this.props.sometext))
     })
  }

  render() {
     return (
           <div className="someclass">
                   <Editor editorState={this.props.editorState} onChange={this.handleChange} /> 
           </div>
    )
  }
}

mapStateToProps({ sometext, editorState }) {
       return { sometext, editorState }
}

export default connect(mapStateToProps)(EditorComponent)
``` 
My editor reducer is like this 
```
export function EditorReducer(state={}, action) {
    switch(action.type){
        case CHANGE_TEXT:
            return Object.assign({}, state, action.payload)
        default:
            return state
    }
}
```

I always get the `editorState.getCurrentContent is not a function` when the component is rendered.

**Comment by RaoHai** [comment]
maybe you can try to create an initial empty editorState in reducer.

**Comment by tobiasandersen** [comment]
Could you show the reducer and component as well?

**Comment by flarnie** [comment]
Thanks for reporting this - if you could help us create an example to reproduce the bug that would be helpful. Starting to look into this.

**Comment by Catorpilor** [comment]
@RaoHai i tried but still same problem.

**Comment by davidchang** [comment]
@Catorpilor would you be able to point to your codebase or provide more information? or wherever you are getting the error, maybe investigate what the value of editorState is

**Comment by davidchang** [comment]
closing for lack of correspondence (but not meaning to be a jerk about it). please reopen if you can offer more information, or just ask in the Draft Slack channel.

**Comment by Catorpilor** [comment]
Sorry, for the late reply. I just solve my problem. Seems that when using `Object.assing()` did not deeply copy the content of `editorState`  that's why i always got the not function error. Again thanks for the reply.
