### ISSUE TITLE
missing  "contentState" in the strategy callback function

### ISSUE THREAD

**Issue by neove** [facebook/draft-js#829]
I try to write a link decorator,but in the strategy callback function ,i can only get "contentBlock" and 'callback' arguments ,but miss 'contentState'，here is my code
`link component`:
![image](https://cloud.githubusercontent.com/assets/18530075/20791548/7bba8632-b7f8-11e6-8fdd-79cdaf0a343e.png)
i carry out `console.log(arguments)`and here is the result:

![image](https://cloud.githubusercontent.com/assets/18530075/20791472/287133e0-b7f8-11e6-8311-a4e0ae144bbb.png)

`compositeDecorator`:
![image](https://cloud.githubusercontent.com/assets/18530075/20791587/b4ed85e4-b7f8-11e6-91bf-e8c82f9f0e87.png)

`editor`:
![image](https://cloud.githubusercontent.com/assets/18530075/20791632/ec33188e-b7f8-11e6-8f89-d938398ceecd.png)

i can not find where the reason  is ,any help would be great :)

**Comment by tobiasandersen** [comment]
Which version of Draft are you running? If you're on 0.9.1 (which is the latest published to npm), the examples found here in the master branch unfortunately won't work. The EntityMap has been moved into the ContentState on the master branch, and the examples have been updated accordingly. 

There's currently an open PR (see #824) to re-add the old examples that work for 0.9.1. I believe it'll be merged soon, but in the meantime, here's how the link strategy looked before the EntityMap was moved: https://github.com/facebook/draft-js/blob/af3a37c5d9398cb886704f7802d56e931cb37108/examples/draft-0-9-1/link/link.html#L176

Hope it helps!

**Comment by neove** [comment]
@tobiasandersen thank you very much,
