### ISSUE TITLE
Doesn't currently work in IE11

### ISSUE THREAD

**Issue by mmmdreg** [facebook/draft-js#83]
On IE11, Facebook.github.io/draft-js doesn't show the editor. Similarly for a basic editor running locally. 

if (!query.startsWith(name)) --> Object doesn't support property or method 'startsWith'

**Comment by zpao** [comment]
Ah right, we'll need to include some polyfills.

**Comment by brwr** [comment]
[Issues and Pitfalls: IME and Internet Explorer](https://facebook.github.io/draft-js/docs/advanced-topics-issues-and-pitfalls.html#ime-and-internet-explorer) should be updated to reflect these issues.

**Comment by buley** [comment]
@zpao can you give me an idea of which polyfills might one need to include?

**Comment by zpao** [comment]
Based on the above failure, something that implements
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith,
pretty much any ES6 polyfill should work.

**Comment by kim3er** [comment]
I've created a pull request, that fixes the test site for IE9+. https://github.com/facebook/draft-js/pull/130

**Comment by kim3er** [comment]
Sorry, just noticed the existing pull request. Never mind!
