### ISSUE TITLE
Insert Img tag? Examples? 

### ISSUE THREAD

**Issue by stagfoo** [facebook/draft-js#832]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I have a button to insert an img tag into draft, but I only get a blank span.
I am currently using the draft process paste to insert html.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

**What is the expected behavior?**
Insert the img tag and as an tag into the content. Not as nothing
**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Mac 9.01

**Comment by StGeass** [comment]
You can share full code, along with a button?

**Comment by tobiasandersen** [comment]
I think the support for converting `img` tags into Draft `contentBlocks` was added just recently and therefore hasn't made it to npm yet.

**Comment by flarnie** [comment]
@tobiasandersen is correct - Image support in convertToHTML will be part of the next release. It was added in https://github.com/facebook/draft-js/commit/8ac72f723fb2d9102db833a9b060dfd66df65652. Also thanks @tobiasandersen for updating the docs and example - just merged #833 so the docs should be updated automatically soon.
