### ISSUE TITLE
Broken links for examples in documentation page

### ISSUE THREAD

**Issue by rodolfobarretoweb** [facebook/draft-js#836]
Like in this page: https://facebook.github.io/draft-js/docs/quickstart-rich-styling.html

**Comment by flarnie** [comment]
This should be fixed - for me the link on that page to the example works.[1] We did recently move the examples so it could be that they broke during the time the website was being updated. 
Please let me know if I am missing something here, and thanks for reporting this! 

[1]: Screenshot of the example page that was linked to there:
![screen shot 2016-12-03 at 3 16 22 pm](https://cloud.githubusercontent.com/assets/1114467/20862852/870ab95c-b96b-11e6-8da5-9ed75061cb34.png)

**Comment by davidchang** [comment]
thanks for reporting @rodolfobarretoweb - I'm going to close this, but feel free to reopen if any issue!
