### ISSUE TITLE
how to apply the result of the color picker to the inline style

### ISSUE THREAD

**Issue by neove** [facebook/draft-js#837]
i use a color picker and want to apply the result (such as "#000") to the text, but the props :`customStyleMap`  receive an Object rather than a function ,i can't get  the  value of the style , i have no idea how to solve it , my version is 0.9.1, any suggestion is great ,thank you(i am from China, and my english is not so good)

**Comment by neove** [comment]
resolved

**Comment by mqyqingfeng** [comment]
how resolved? @neove
