### ISSUE TITLE
request support: inline-block

### ISSUE THREAD

**Issue by LiaoSept** [facebook/draft-js#84]
example of use: emoji, @, tag, hashtag, etc

**Comment by gscottolson** [comment]
Have you explored the documentation regarding [entities](https://facebook.github.io/draft-js/docs/advanced-topics-entities.html)? The **tweet example** also has [sample code for handling `@mentions` and hashtags](https://github.com/facebook/draft-js/blob/master/examples/tweet/tweet.html#L79-L136).

**Comment by brwr** [comment]
+1 @gscottolson. Inline-block is just a styling thing. Shouldn't have any effect on your JS.

**Comment by hellendag** [comment]
Exactly. Rendering output is an implementation detail for your decorator.

I'd actually be cautious about using `inline-block` for your decorators, in fact. Cross-browser behavior for inline-block spans within CE can be quirky, and I haven't ironed out really good solutions for them.
