### ISSUE TITLE
Image pasting in Firefox thows error

### ISSUE THREAD

**Issue by nkt** [facebook/draft-js#840]
There is `handlePastedFiles` callback in DraftEditor. When I paste image in Chrome, everything working fine. But in Firefox i got: `TypeError: appendToHead is undefined`.

As I know, FF doesn't support pasting images by default. But using contenteditable element you can handle `paste` event, lookup images inside pasted html and convert them to blobs.

**Comment by flarnie** [comment]
Thanks for reporting this! A fix was merged and will be released in 0.10.0 - https://github.com/facebook/draft-js/pull/654

We are currently creating and testing the 0.10.0 release; thanks for your patience.
