### ISSUE TITLE
Prevent Merging of Blocks When hitting backspace from the beginning of the second block

### ISSUE THREAD

**Issue by subeesh** [facebook/draft-js#846]
*Question*

Currently, when we hit backspace from the beginning of a paragraph, if it is not the first paragraph, its merged to the previous paragraph. This is expected, but the underlying block is also merged with the first block. 

I have created a simple JS Fiddle. 
https://jsfiddle.net/subeesh_85/t8k8uow3/

To reproduce the problem, 

- Type something in the text box and hit enter
- you will see that a new empty block is generated for the new line in the JSON preview below the textbox
- type something in the second line and you will see that the preview is getting updated
- move the cursor the beginning of the second line and hit backspace.
- The second line is moved up and blocks are merged into one

Is it possible to prevent the merging of blocks in such scenarios? I would like the second line to be moved up, but it should stay in the same block instead of getting merged to the previous block.

**Comment by flarnie** [comment]
Thanks for reporting this! I believe a fix was merged and will go out in the 0.10.0 release - https://github.com/facebook/draft-js/pull/613

We are currently testing the 0.10.0 release - thanks for your patience.
