### ISSUE TITLE
Hi, now I want to copy something from a webpage and paste it to the editor. The content includes some images. Is there a perfect way to achieve it ?  Thanks!

### ISSUE THREAD

**Issue by geng890518** [facebook/draft-js#854]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

**What is the expected behavior?**

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

**Comment by geng890518** [comment]
the returnValue of convertFromHTML is different from the demos in the draft-js-master.....

**Comment by tobiasandersen** [comment]
The version on master handles pasted images better (there's no support for this in 0.9.1) and will be available when v0.1.0 lands. I believe the Draft team is doing their best to release it asap!

**Comment by geng890518** [comment]
But I npm update draft-js, it said valid install targets is 0.0.0 to 0.9.1...

**Comment by geng890518** [comment]
@tobiasandersen thanks！谢谢！

**Comment by smtheard** [comment]
@tobiasandersen can you direct me toward the PR that resolved this? I have tried searching for it and cannot find it. I want to try to patch this locally since we don't have v0.1.0 yet.

**Comment by tobiasandersen** [comment]
@smtheard Sure! This should be it: https://github.com/facebook/draft-js/pull/734

**Comment by flarnie** [comment]
Thanks for answering this @tobiasandersen ! We are indeed working on testing the 0.10.0 release currently. Hoping to put it out there very soon, and to have more frequent small released going forward.
