### ISSUE TITLE
Enable dangling comma lint

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#862]
It doesn't seem that ESLint has been catching missing dangling commas, and we would like to be consistent with the Facebook ESLint configurations.
Edit: It would be also nice to warn for lines over 80 characters long.

**Comment by davidchang** [comment]
looks like comma-dangle is OFF and maxLen is set to 120 here: https://github.com/facebook/fbjs/blob/master/packages/eslint-config-fbjs/index.js#L310

we could specifically change these in draft's own eslintrc, but not sure if we would want to do that. quick glance around other FB JS projects shows everyone's kinda doing their own thing, not just using eslint-config-fbjs

@zpao - can you advise?

**Comment by mmmoussa** [comment]
Once #1126 gets merged I think this issue can be closed.
