### ISSUE TITLE
DraftEntityType needs to be loosened

### ISSUE THREAD

**Issue by jmzhang** [facebook/draft-js#868]
From the [doc](https://facebook.github.io/draft-js/docs/advanced-topics-entities.html#introduction) that introduces Entities, it said

> type: A string that indicates what kind of entity it is, e.g. 'LINK', 'MENTION', 'PHOTO'

But in the source code, the type of an Entity is limited to `LINK`, `TOKEN `, `PHOTO ` or `IMAGE`, as seen in `src/stubs/ComposedEntityType.js`. 

So my questions:
- Is the entity type supposed to be customizable?
- I'm considering using Flow in my projects, will a custom entity type, say `VIDEO`, break Flow's type checking?
- What's the difference between `PHOTO` and `IMAGE`? I didn't find any explanations on that.

**Comment by ericbiewener** [comment]
Agreed. Not only does it appear that you can specify any custom entity type you want, it seems like this is what you're supposed to do, that it is the primary identifier of what your entity is. The Draft JS Plugins project [uses custom ones (e.g. sticker, emoji)](https://github.com/draft-js-plugins/draft-js-plugins/search?utf8=%E2%9C%93&q=createEntity&type=).

**Comment by akomm** [comment]
I came to the same conclusion. Typing is "broken", but it works as intended, when I use custom type. 

I have a `FONT_COLOR` entity type. 
I want my colors to be dynamic and not predefined (for the later, inline styles would be sufficient), so I need to store selected color data.

So I think it is a doc & typing issue.

**Comment by cedricmessiant** [comment]
Same issue here, I have to add `// $FlowFixMe` to be able to use what I want for entity type. I guess `DraftEntityType` should be changed to `string`.

**Comment by juliankrispel** [comment]
yep. This flowtype is wrong imo, will bring this up :+1:

**Comment by niveditc** [comment]
Thanks for raising this! Loosening the Flow type here seems reasonable to me, so going to merge @juliankrispel's PR :)

**Comment by katz12** [comment]
This change is mentioned in the [release notes for 0.10.5](https://github.com/facebook/draft-js/releases/tag/v0.10.5) but it seems like it did not [make it into](https://github.com/facebook/draft-js/blob/v0.10.5/src/model/entity/DraftEntityType.js) the release.
