### ISSUE TITLE
Question: Custom Block component blockProps AND children possible?

### ISSUE THREAD

**Issue by coinfork** [facebook/draft-js#878]
I've been trying to create a simple block component that looks like a quote box:

---
"Quote by: Foo"
This is some **styled** text _inside_ the block
---

I defined my custom component "Quote" inside the a blockRendererFn:
`export default function customBlockRenderer(block) {
	const type = block.getType();

	switch (type) {
		case 'quote':
			const dataMap = block.getData();
			return {
				component: Quote,
				editable: true,
				props: {
					author: dataMap.get('author'),
				},
			};
	}	
}`

...As well as blockRenderMap:

```
['quote']: {
	element: 'div',
	editable: true,
},
```

Problem is I cannot render the children of the block (any styled text, emoticons, etc) inside the Quote component, the only available prop is props.block.getText() which is the unstyled text.

I've also tried specifying <Quote /> as the wrapper in the block, which gives me access to props.children as intended, but then I can't access any "author" prop that I was passing in my blockRendererFn.

So how can I display both the Author at the top of the block, and the editable rich text inside the block?

**Comment by mzbac** [comment]
@coinfork  no sure if I understand your question correctly, but you should be able to find your author from  blockProps in props
```
props.blockProps.author
```
