### ISSUE TITLE
Bold Text not visible in the Editor

### ISSUE THREAD

**Issue by rboorgapally** [facebook/draft-js#899]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When I select a text and make it bold either by using a button or key board controls (Ctrl+B) by following facebook examples, the state is updated but the editor doesn't display bold text. When I do the same for italics it works though.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

**What is the expected behavior?**

If I bolden some text it should be reflected in the editor and be visible

![image](https://cloud.githubusercontent.com/assets/933545/21447467/e3b3d2f6-c889-11e6-9fd9-f2e347def3c7.png)

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

"draft-js": "^0.9.1",

Windows 10

Chrome - Version 55.0.2883.87 m (64-bit)

**Comment by davidchang** [comment]
@rboorgapally - this is pretty concerning. In what sort of environment are you running into this bug? Did you check out the source and are running the examples?

**Comment by rboorgapally** [comment]
I am running an app built with Play framework and React. I read the example code on the draftjs site and integrated it into my app, I ran into this issue. I was initially suspicious that my call back function for Bold is not invoked. But when I put break points and also displayed the raw text of the state of the editor (as shown in the picture in my earlier post) it was clear that it is a draftjs issue.

**Comment by davidchang** [comment]
hmm, do you know if just using the font-weight: 'bold' CSS rule works? this working for italics but not for bold suggests maybe something's up with the environment you're running in.

https://github.com/facebook/draft-js/blob/69890ed57b5f4256cc93ae8e9ea178296851a23e/src/model/immutable/DefaultDraftInlineStyle.js defines the default style rules

**Comment by mezod** [comment]
also, probably not helpful, but make sure the fonts you are using can be bolded. I used a font-family that can't and obviously you see no change.

**Comment by rboorgapally** [comment]
Yes font-weight: 'bold' works.

**Comment by tobiasandersen** [comment]
If you could create a reproducible example somewhere, e.g. using [this jsfiddle](https://jsfiddle.net/stopachka/m6z0xn4r/) as a base, or in a github repo, I (and probably others too) could take a look!

**Comment by flarnie** [comment]
Looks like we need more info in order to reproduce this bug. If it is still happening please open a new issue; for now I'm closing this because it has gotten stale.
