### ISSUE TITLE
Export FlowTypes in npm package

### ISSUE THREAD

**Issue by nikgraf** [facebook/draft-js#90]
I tried to use Flow in combination with Draft, but couldn't get it up & running. Maybe I missed something,  but there seem not any flow related files when downloading the package on npm.

As Draft has flowtypes it should be just a change in the build process. Im happy to do a PR in case you would want to see this as well.

Background info:
https://twitter.com/lbljeffmo/status/702928158518091782
http://flowtype.org/blog/2015/12/01/Version-0.19.0.html#declaration-files

**Comment by zpao** [comment]
Yea, I mostly opted to not do this yet as we're still facing an issue with fbjs related to that and it would impact this too (https://github.com/facebook/fbjs/issues/118). But I think getting that fixed and shipping the flow files here is the plan.

**Comment by ajhyndman** [comment]
Is there anything still holding this back?  Are you open to PRs?

**Comment by Blackrush** [comment]
These would allow to fix broken typing with newer versions of Flow (eg 0.36.0).

**Comment by mxstbr** [comment]
Since this `fbjs` issue was fixed, any chance we could get better Flowtype support in DraftJS?

**Comment by mitermayer** [comment]
This has been fixed on https://github.com/facebook/draft-js/issues/366
