### ISSUE TITLE
Design Question regarding: handleKeyCommand

### ISSUE THREAD

**Issue by valorize** [facebook/draft-js#901]
Regarding: https://facebook.github.io/draft-js/docs/quickstart-rich-styling.html#content
Wouldn't it be cooler if handleKeyCommand returns null if the command is handled and the command itself if it isn't? Then you would have the possibility that a custom command does some stuff and additionally rewrites the custom command to a default one (like selecting all, or so).

**Comment by davidchang** [comment]
@valorize - thanks for the idea/opening the issue! Honestly, I'm skeptical that it is a common enough use case to allow this sort of command rewriting. I'm not sure that this is really worth implementing in the core, and I think you could still get this sort of behavior with the current handleKeyCommand if you really wanted (for example, if you wanted every key press of the letter "a" to register as having typed the word "dog", handleKeyCommand doesn't block you from doing this).

That said, I'm going to close this. If you feel strongly and want someone else to consider this enhancement, feel free to reopen.

**Comment by valorize** [comment]
Alright
