### ISSUE TITLE
Focusing in componentDidMount

### ISSUE THREAD

**Issue by peasemaker** [facebook/draft-js#902]
I try to make focus when component is loaded. This doesn't work.
`componentDidMount() {`
`  this.refs.editor.focus();`
`}`
And this also doesn't help:
`componentDidMount() {`
`  setTimeout(() => this.refs.editor.focus(), 1);`
`}`

**Comment by davidchang** [comment]
@peasemaker - thanks for opening this issue. For issues like this, you can also post in the Draft.js Slack channel, as you're more likely to get a quicker response there (there are usually at least a handful of people hanging out there throughout the day).

What you're looking for should be represented in this jsfiddle: https://jsfiddle.net/n1qkw6kh/

I'm going to close, feel free to reopen if any issue (or post in the Slack channel :) )
