### ISSUE TITLE
Insert images into draft.js articles?

### ISSUE THREAD

**Issue by vikramjakkampudi** [facebook/draft-js#904]
1- Since draft.js is being pitched as a long form article writing editor, how can we include images (both uploaded from local or URL)?

2- Is react-native support coming soon?

**Comment by davidchang** [comment]
hi @vikramjakkampudi - thanks for opening the issue.

For 2, React-Native support is not currently being prioritized; for more info, see https://github.com/facebook/draft-js/issues/138

For 1, a good example is [medium-draft](https://github.com/brijeshb42/medium-draft). This [code snippet](https://github.com/brijeshb42/medium-draft/blob/73cadc09bf6c41b0a12654f62c2acfbb50a5949f/src/components/sides/image.js#L34-L68) shows a button that uploads the image, and [here](https://github.com/brijeshb42/medium-draft/blob/13372c9d3d5cacea6e1042b7a9e77e923fbc5708/src/components/customrenderer.js#L31-L37)'s where the custom block rendering is delegated to an [ImageBlock component](https://github.com/brijeshb42/medium-draft/blob/13372c9d3d5cacea6e1042b7a9e77e923fbc5708/src/components/blocks/image.js).

I hope this helps. I'm going to close, but feel free to reopen if you have further questions.

**Comment by Hongbo-Miao** [comment]
And also check https://www.draft-js-plugins.com/plugin/image

**Comment by bufordtaylor** [comment]
The draft js plugin image library is as of today not working correctly. draft-js-drag-n-drop-upload-plugin does not exist and therefore you cannot upload.
