### ISSUE TITLE
Link editor example breaks after adding a `link`

### ISSUE THREAD

**Issue by cogell** [facebook/draft-js#91]
When using the current link example `examples/link/link.html` the editing experience after adding a link breaks. If the user does any type of editing the link is removed, even if the user edits a piece of the content that is not the link.

screen capture of the issue:
![link-example-error](https://cloud.githubusercontent.com/assets/1653832/13331435/789c389c-dbcb-11e5-96bd-a1e02a326973.gif)

In that example I added a link, moved my cursor to the end of the content and tried to enter a space which was actually added back in the link entity

**Comment by brwr** [comment]
I've noticed this as well. It's not just the example. After adding a similar feature locally, I saw the same thing. Was looking into what caused this, but then I had to go to work. Boo, work. :-1:

**Comment by hellendag** [comment]
Interesting, thanks for the report. I'll check it out.

**Comment by hellendag** [comment]
Seems like using `window.prompt` causes `onSelect` events to stop firing until the user manually sets the cursor with the mouse. Firefox also flips out, but in stranger ways.

We could invest time in figuring out why this is happening, but I'm just going to hope that most engineers aren't using `window.prompt` in their applications. My hunch is that something may need to change within React's `SelectEventPlugin` to straighten this out.

We have a layer abstraction we use at FB for this kind of thing, so I don't know if I've hit this bug before. I'm just going to go ahead and create a different way to supply the URL for the example.
