### ISSUE TITLE
[Bug] Android auto suggestion: inserts duplicate characters, hides content

### ISSUE THREAD

**Issue by EmpireJones** [facebook/draft-js#911]
When I select a suggestion via the android keyboard, sometimes it inserts duplicate characters or temporarily hides the content. Reproduced on https://facebook.github.io/draft-js/ 

It seems to more consistently occur when you start with no text.

In this first example:
1. Typed "Wh"
2. "Pressed "What" suggestion
3. "Editor showed "WhatW"
![videotogif_2017 01 02_18 36 46](https://cloud.githubusercontent.com/assets/15959998/21599063/7ce17caa-d11b-11e6-9d0a-8a823b8db702.gif)

In this second example:
1. Typed "The following"
2. deleted it
3. opened keyboard
4. pressed "The" suggestion (editor was blank)
5. opened keyboard
6. pressed "Hi" suggestion  (editor was blank)
7. opened keyboard
8. typed "asdf"
9. pressed "ASDF" suggestion
10. editor showed "ASDFHiTheT"

![videotogif_2017 01 02_18 49 33](https://cloud.githubusercontent.com/assets/15959998/21599120/9704b0ce-d11c-11e6-94d2-c85f91b0fdfb.gif)

**What is the expected behavior?**
No invisible text or duplicate characters

draft-js 0.9.1
Android chrome version 55.0.2883.91

**Comment by EmpireJones** [comment]
Here's a general description of a case very similar to the first example above:

1. Type something
2. Delete it via backspace
3. Type a word
4. Press space key

Results in:
* word from step 3 + space + first letter of step 1
* keyboard auto-closed (not desired) -- I've only seen this result on a local site, not https://facebook.github.io/draft-js/, but on https://facebook.github.io/draft-js/ it happens when pressing a suggestion

**Comment by will-hart** [comment]
I think some of the behaviour, i.e. the keyboard closing is related to #888 which has an un-merged PR #907. 

I've also found it doesn't like adding text at the very start of the document sometimes, which is what appears to be happening in your second gif.

On Android when the word is underlined it doesn't *actually* appear to be in the editor - i.e. the word is not sent to my server from the `onChange` callback until I hit space or select an autocorrect option. I wonder if this is contributing.

**Comment by flarnie** [comment]
Merging this into a general Android bug issue - see https://github.com/facebook/draft-js/issues/1895
