### ISSUE TITLE
Applying styles to future text through a HTML select option

### ISSUE THREAD

**Issue by luccitan** [facebook/draft-js#912]
I want to apply a color style to the text through **HTML select option elements**
Since opening a select menu needs the focus, the editor loses it so I can't apply the **inline-style** to the _Editor State_ for the upcoming text.
It would only work for a text already selected. 

Is there any sort of _hack_ to handle this case or is it just impossible ?

**Comment by luccitan** [comment]
I've been tricking my editor components by keeping in local state the `selectionState` when the `select` element gets the focus.  The `hasFocus` has been manually changed to `true` in order to properly put the inline styles at the collapsed cursor position

Then, when a select value is toggled (`onToggle`), the **modified** editorState with the memorized `selectionState` are used to apply the inline styles

**Comment by Tommy10802** [comment]
Hello, can i ask you for some example code of this problem? I have same problem as you had and it will be very helpfull for me when i will see your solution.
Thanks a lot

**Comment by luccitan** [comment]
Sorry, I don't have access anymore to the piece of code related to this issue. 
I can't help 😞
