### ISSUE TITLE
Bug when remove one editor from multiple editors

### ISSUE THREAD

**Issue by dzuncoi** [facebook/draft-js#916]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Currently I'm using multiple TeX editors, follow exactly example from the source, structured as:
```javascript
this.state.arrayOfData.map(function(data, index){
    return 
        <MyContainer>
            <TeXEditor />
        </MyContainer>
})
```
Then when I remove 1 element from my data, like: `this.state.arrayOfData.splice(0,1)`, the remain editor show the content of 1st editor, not 2nd editor.

**Expected**
The first editor will be removed from the DOM, there will be only 1 editor (the 2nd) with its content

I notice that the remain editor has the `data-editor` attribute same as the 1st editor (which should be removed).

Another question: why changes from 1 editor trigger all editor's render function? Am i missing something?

I'm using Draftjs v0.9.1

Here is an example to reproduce this issue: https://jsfiddle.net/m6z0xn4r/109/
I follow exactly TeXEditor example.

**Way to reproduce:**

Type anything on first editor
Click Add Part button
Type anything on 2nd editor
Click Remove Part button on the 1st part
Now you can see the description of remaining part is "Description for part 2" but editor's content remains unchanged.

So is it a bug or am I missing something?

Thank you for your time.

**Comment by davidchang** [comment]
@dzuncoi - thanks for opening this issue. Depending on how you're doing the splice(0, 1) call, you may be seeing some unexpected side effects. Referring to the JS documentation, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice says it returns the deleted entries

so if you're doing

this.setState({
  arrayOfData: this.state.arrayOfData.splice(0, 1),
}),

you'd be saving the first entry instead of everything else. could this be what you're seeing?

**Comment by dzuncoi** [comment]
@davidchang I don't think the problem is about `splice` method. My method to remove is exactly like:
```javascript
this.state.arrayOfData.splice(0,1);
this.setState({arrayOfData: this.state.arrayOfData})
```

After checking `state` from debug, I confirm that `this.state.arrayOfData` is right, 1st element is removed, except the TeXEditor.

I will try to provide a minimal example to reproduce this issue

**Comment by dzuncoi** [comment]
@davidchang  (sorry for tagging you twice)
Here is an example to reproduce this issue: https://jsfiddle.net/m6z0xn4r/109/
I follow exactly TeXEditor example.

**Way to reproduce:**

1. Type anything on first editor 
2. Click `Add Part` button
3. Type anything on 2nd editor
4. Click `Remove Part` button on the 1st part

Now you can see the description of remaining part is "Description for part 2" but editor's content remains unchanged. 

So is it a bug or am I missing something?

Thank you for your time.

**Comment by zencephalon** [comment]
I've seen this problem in different contexts if U have a `key` prop that lacks sufficient uniqueness. I.E. if U have `key`s that come straight off an iterator, for instance, removing the third element will cause the former fourth element to have the same key as the former third element, which will confuse React into display the same data.

Not sure if that applies to your situation.
