### ISSUE TITLE
How to use flow with draft-js?

### ISSUE THREAD

**Issue by jatins** [facebook/draft-js#924]
Draft uses immutable models for most part, and the docs present type information for all the API. However, there is no flow typed definition for draft in [flow-typed](https://github.com/flowtype/flow-typed) repo. 

I do see some `*.js.flow` files in the `node_modules/draft-js/lib` directory however I am not sure if/how they can be used for type checking. 

**So, other than typing own type definition, is there some way I can use flow with draft-js?** Here's what my current configuration looks like (click to expand):

<details>
 <summary> package.json (dependencies) </summary>

```
...
"dependencies": {
  "draft-js": "^0.9.1",
  "immutable": "^3.8.1",
  "react": "^15.4.2",
  "react-dom": "^15.4.2"
},
"devDependencies": {
  "flow-bin": "^0.37.4"
}
```

</details>

<details>
<summary>.flowconfig</summary>

```
[ignore]
.*\/node_modules\/draft-js\/lib\/.*.js.flow.*

[include]

[libs]
.*\/node_modules\/draft-js\/lib\/.*.js.flow.*

[options]
esproposal.class_static_fields=enable
suppress_type=$FlowIssue
suppress_comment=\\(.\\|\n\\)*\\$FlowIssue
```
</details>
<br>

**index.js** (file I am trying to typecheck)

```js
// @flow
import React from 'react';
import ReactDOM from 'react-dom';
import {Editor, EditorState} from 'draft-js';

class MyEditor extends React.Component {
  state: {
    editorState: EditorState
  }

  onChange: Function;

  constructor(props) {
    super(props);
    this.state = {editorState: EditorState.createEmpty()};
    this.onChange = (editorState) => this.setState({editorState});

    // gives type error, as expected
    let a :string = 10;

    const editorState :EditorState = this.state.editorState;

    // should be a type error, editor.getCurrentContent() returns type ContentState
    const content :string = editorState.getCurrentContent(); 
  }

  render() {
    return (
        <Editor editorState={this.state.editorState} onChange={this.onChange} />
    );
  }
}

ReactDOM.render(
  <MyEditor />,
  document.getElementById('container')
);
```

**Comment by awestroke** [comment]
Remove draft-js from your flow ignore to make it work

**Comment by jatins** [comment]
It tries to run `flow` on `.js.flow` files for draft and throws errors. So, I had included that in ignore.

**Comment by awestroke** [comment]
Yes, there is some configuration needed to make flow work with draft.
You can take inspiration from this issue: [issues/661#issuecomment-248846071](https://github.com/facebook/draft-js/issues/661#issuecomment-248846071)

**Comment by awestroke** [comment]
Did this solve your issue?

**Comment by jatins** [comment]
I actually ended up not using flow at all. One of my main reasons for flow was being able to get type aware autocompletions, which I am now using VSCode for (doesn't require flow, just the @types/ definition files)

Will close this issue, though.

**Comment by Dakuan** [comment]
Still very much broken!

**Comment by steida** [comment]
@flarnie Should we use master somehow (I don't know how), or wait for a new relase? Thank you.
