### ISSUE TITLE
`EditorState.moveFocusToEnd(editorState)` doesn't behave correctly when the content ends with a period character

### ISSUE THREAD

**Issue by paulyoung** [facebook/draft-js#930]
**Do you want to request a *feature* or report a *bug*?**

This is a bug report.

**What is the current behavior?**

I've observed that if some initial content ends with a period character, the cursor will be at the beginning of the editor and not the end. This is despite the selection state appearing to be correct (after logging it via `this.state.editorState._immutable.toJS()`).

```javascript
this.state = {
  editorState: EditorState.moveFocusToEnd(
    EditorState.createWithContent(
      ContentState.createFromText('Cursor will not be at the end.')
    )
  )
};
```

If I remove the period character from the end of the initial content, the editor is focused and the cursor appears at the end as expected.

```javascript
this.state = {
  editorState: EditorState.moveFocusToEnd(
    EditorState.createWithContent(
      ContentState.createFromText('Cursor will be at the end')
    )
  )
};
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

The issue is not apparent in the jsfiddle because the iframe (and therefore, the editor) is not focused at all. A similar thing happens in Chrome if the devtools are open and focused, and a page is refreshed.

https://jsfiddle.net/m6z0xn4r/112/

**What is the expected behavior?**

Using `EditorState.moveFocusToEnd(editorState)` results in the cursor appearing at the end of the editor regardless of the content.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

I'm seeing this with the following setup:
* Draft.js 0.9.1
* Google Chrome Version 55.0.2883.95 (64-bit)
* OS X El Capitan Version 10.11.6 (15G1108)

**Comment by awestroke** [comment]
The editor has no focus in the beginning, so I could not reproduce your issue.

Adding focus() to componentDidMount makes the editor focused on load, but without your described problem:
https://jsfiddle.net/a382ywsk/

**Comment by paulyoung** [comment]
This turned out to be an issue with the `Editor` in `draft-js-plugins-editor`.

Sorry for the confusion.
