### ISSUE TITLE
How to edit entity data?

### ISSUE THREAD

**Issue by cbothner** [facebook/draft-js#933]
First off, I'm using 0.10, so let's talk about that Entity API.

Does `mergeData` still exist? I'm gonna assume so. I know how to get the Entity, and I can merge new data, which returns a new Entity. But how do I merge that entity back into my `editorState`?

**Comment by awestroke** [comment]
There is an example here: [examples/draft-0-10-0/tex/js/components/TeXBlock.js#L95](https://github.com/facebook/draft-js/blob/b17eb8bb2844e3070b8232523ab4cd125fb6329f/examples/draft-0-10-0/tex/js/components/TeXBlock.js#L95)

**Comment by cbothner** [comment]
Ah! `mergeEntityData` is on ContentState now, so there is no explicit “merge the new Entity with the old ContentState” step. Thank you.
