### ISSUE TITLE
Can't paste header, blockquote and code-block

### ISSUE THREAD

**Issue by J22Melody** [facebook/draft-js#935]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

If I paste header, blockquote and code-block from a webpage into my editor based on draft-js, those all become unstyled block.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.** 

**What is the expected behavior?**

Those become header, blockquote and code-block and if `blockRenderMap` provided like:

```
'header-two': {
  element: 'h2',
  aliasedElements: ['h1', 'h3', 'h4', 'h5', 'h6'],
},
```

all header tag will become  'header-two'

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

draft-js 0.9.0
macOS 10.12.2 / Chrome 55.0.2883.95 (64-bit)

**Comment by thibaudcolas** [comment]
I can't reproduce this, at least in recent versions of Draft.js (v0.10.4). It highly depends on the markup of the source you're copying from of course, but if the heading tags are used they are retained in my experience. I haven't tried blockquote, and as far as I can tell the `code-block` is only retained if `code` style isn't active.

Here's the Dropbox Paper doc I used for testing: https://paper.dropbox.com/doc/Draft.js-paste-test-document-njfdkwmkeGQ9KICjVwLmU
