### ISSUE TITLE
Why not publish the new version to npm

### ISSUE THREAD

**Issue by MinJieLiu** [facebook/draft-js#936]
Why not publish the new version to `npm`, and now I can only install the 0.91 version.

**Comment by davidchang** [comment]
@flarnie - can you respond to this? related tasks: #839 and #835

**Comment by flarnie** [comment]
Thanks for flagging this and linking to those other issues @davidchang - I hope that reading those two gives some context and partially answers your question @MinJieLiu. 

In issue #839 we address the question **"What's taking so long???"** with two points:
>  - Since we are improving the API in a breaking way, we are doing extra testing and preparing documentation to make the 0.10.0 and 0.11.0 releases run smoothly.
>  - We are a tiny team with other projects, and so thanks for everyone's patience! We are actively working on catching up, and there are discussions ongoing for how to improve the state of this project. See #835.

We are in the process of testing 0.10.0 with the many and varied Facebook use cases of Draft.js, and writing an upgrade guide for the API changes that are coming in 0.10.0 and 0.11.0. That will take at least another couple of weeks, and if we discover any serious bugs then those have to be fixed before we release the 0.10.0 version. Fingers crossed though! :four_leaf_clover:

Thanks for your patience and interest in the project!

**Comment by mkhazov** [comment]
There's a published package [zj-draft-js](https://www.npmjs.com/package/zj-draft-js), that reflects draft-js 0.10.0

In my webpack-based project I simply aliased it using webpack [config](https://webpack.github.io/docs/configuration.html#resolve-alias):
```js
resolve: {
    alias: {
      'draft-js': "zj-draft-js"
    }
}
```

**Comment by MinJieLiu** [comment]
@mkhazov Thank you!
