### ISSUE TITLE
Missing copyright notice?

### ISSUE THREAD

**Issue by markalanrichards** [facebook/draft-js#944]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Missing copyright notice?
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
See https://facebook.github.io/draft-js/lib/Draft.js
**What is the expected behavior?**
Module 145 looks like https://github.com/defunctzombie/node-process/blob/master/browser.js does this need a copyright statement?
**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Current all browsers, no idea about old versions.

**Comment by flarnie** [comment]
I'm not sure I understand - looks like the copyright statement is there in https://facebook.github.io/draft-js/lib/Draft.js

Maybe it was missing and got added back since this was opened?

Please tag me or open a new issue if this is still a concern, and thanks for reporting.
