### ISSUE TITLE
Add support for h3, h4, and h5

### ISSUE THREAD

**Issue by mitermayer** [facebook/draft-js#95]
Hi there,

Was wondering if you guys have support for other heading types, If not are you open for PRS ? I am attempting to migrate a project to use draft js as a replacement for tinymce

thanks,
miter

**Comment by hellendag** [comment]
Sure, send a PR. :) You'll want to add these values to `DraftBlockType` as well as `getElementForBlockType.js`.

**Comment by mitermayer** [comment]
Just created a PR for it https://github.com/facebook/draft-js/pull/96
