### ISSUE TITLE
remove React and ReactDOM from devDependencies

### ISSUE THREAD

**Issue by FourwingsY** [facebook/draft-js#951]
peerDependencies contains react and react-dom.
When react and react-dom are both declared in devDependencies and peerDependencies, Yarn will install them in it's own `node_modules`. It makes error #296

**Comment by apuntovanini** [comment]
Is it https://github.com/facebook/react/issues/8026 ?

**Comment by hellendag** [comment]
Not able to repro this with a fresh project and `yarn add`ing `draft-js`, `react`, and `react-dom`. My `node_modules` dir looks correct.

**Comment by flarnie** [comment]
It looks like this is no longer repro'ing - closing but please reopen or open a new issue if this is still a problem.
