### ISSUE TITLE
Almost invisible bold style on Korean

### ISSUE THREAD

**Issue by pueue** [facebook/draft-js#953]
![](http://i.imgur.com/IdbLI6w.png)

If you apply bold style on Korean, it isn't bolder as much as English.

**Comment by tobiasandersen** [comment]
That has to with the typeface being used though, right?

**Comment by goodhyun** [comment]
Apple Myungjo is notorious for not having bold typeface as a default setup. [[*](https://hyeonseok.com/soojung/apple/2007/01/07/334.html)]

**Comment by spicyj** [comment]
As other folks said, this is just due to the font chosen and is not specific to Draft. You can change the font to another one that shows it more clearly.
