### ISSUE TITLE
Bug: Select all action on mobile devices breaks editor on Android

### ISSUE THREAD

**Issue by bugrakaan** [facebook/draft-js#954]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Doing select all action on android device results in different issues, on some devices editable area becomes uneditable, when tapped on editable area it opens keyboard but it's not possible to type anyting. On some devices trying to select all with double tap ends up text deselecting itself and/or appending the replaced text to the end.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
This can be reproducable at the [draft-js](https://facebook.github.io/draft-js/) homepage or can be seen from [here](https://gfycat.com/SoulfulQuarterlyJunco).

**What is the expected behavior?**
Editor working without hiding keyboard and allowing user to type. 

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Latest version of Draft.js and latest version of Chrome for Android. Not sure if this issue was present in earlier versions.

**Comment by tobiasandersen** [comment]
I don't know if this will fix your problem or not, but you could take a look at [this PR](https://github.com/facebook/draft-js/pull/907) and see if it helps.

**Comment by flarnie** [comment]
Merging this into a general Android bug issue - see https://github.com/facebook/draft-js/issues/1895
