### ISSUE TITLE
handlePastedText - returning true or false has no impact on editor

### ISSUE THREAD

**Issue by lucidlive** [facebook/draft-js#961]
I'm not sure what the problem is but the return from handlePastedText has no impact on the editor. On paste, I'm able to insert an entity using the handlePastedText handler but even though I return true I can't prevent the default pasted text. 

By returning "true" I was expecting nothing to be pasted into the editor. Am I wrong?

**Comment by tobiasandersen** [comment]
Returning `'handled'` or `true` should work. If it doesn't, can you post a fiddle where it's not working?

**Comment by Budaa** [comment]
The same problem here. Copying Hyperlink from text editor and pasting inside Draftjs editor output nothing. 
` handlePaste(text, html) {
    if(html && html.indexOf('href=') > -1) {
      return true;
    } else {
      return false;
    }
  }`

**Comment by tobiasandersen** [comment]
@Budaa What is that fiddle supposed to show?

**Comment by Budaa** [comment]
From docs.
> Handle text and html(for rich text) that has been pasted directly into the editor. Returning true will prevent the default paste behavior.

If I'm understanding this correct it should remove all information, except plaintext from pasted content. As the default is `stripPastedStyles={false}`

**Comment by tobiasandersen** [comment]
Yes, setting `stripPastedStyles={true}`, will remove everything except plaintext when pasting. This issue however, was about `handlePastedText` not functioning according to [its specification](https://draftjs.org/docs/api-reference-editor.html#handlepastedtext) (although I think it does). 

**Just to clarify:** 
If you return `'handled'` or `true` from `handlePastedText`, _nothing should happen_, since what you're essentially doing is telling Draft that you have taken care of the paste instead.

**Comment by hellendag** [comment]
@lucidlive, do you have a jsfiddle with a repro?

**Comment by flarnie** [comment]
Looks like this may be stale, and we need more info in order to reproduce the bug. Closing for now, feel free to reopen if this is still a problem.

**Comment by icd2k3** [comment]
Still seeing the issue here:

```
handlePastedText(text, html) {
    this.setState({
      editorState: EditorState.push(
        this.state.editorState,
        ContentState.createFromText('testing'),
        'paste-text',
      ),
    });
    return true;
  }
// ...
<Editor
  blockRendererFn={this.renderBlock}
  editorState={editorState}
  handleKeyCommand={this.handleKeyCommand}
  handlePastedText={this.handlePastedText}
  keyBindingFn={keyBindingFn}
  onChange={this.handleChange}
/>
```

According to the docs, no matter what I paste into my editor, it should just add "testing" right? This is not working currently and whatever I paste into the editor shows up.
