### ISSUE TITLE
Documentation page titles don't help content navigation

### ISSUE THREAD

**Issue by everyonesdesign** [facebook/draft-js#965]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
All the titles of documentation pages say "Draft.js | Rich Text Editor Framework for React", which is really annoying when you open multiple documentation tabs.
![image](https://cloud.githubusercontent.com/assets/3520704/22364252/2c3718ae-e481-11e6-8092-b46d92fc7883.png)
It seems that there's also no any favicon for the docs.

**What is the expected behavior?**
Informative beginning of the titles, e.g. "Custom Block Components | Draft.js | Rich Text Editor Framework for React" would be great in my opinion.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
N/A

Thank you.

**Comment by flarnie** [comment]
Great idea! Hope someone picks it up - I'm pretty focused on releasing 0.10.0 and 0.11.0 but after that is done I will pick this up if nobody has done it.

Thanks @everyonesdesign

**Comment by kedromelon** [comment]
Opened https://github.com/facebook/draft-js/pull/972 for this! 

Let me know if you've got any suggestions! 😄

**Comment by kedromelon** [comment]
Just realized that the [og:title](https://github.com/facebook/draft-js/blob/master/website/core/Site.js#L26) meta should probably be updated as well. I'll try to get around to making a PR for this later!

**Comment by kedromelon** [comment]
Is there any appropriate favicon that should be used? That's the only aspect of this issue that's still unresolved.

**Comment by flarnie** [comment]
Good question @kedromelon - ideally we will get a logo soon but we don't have one yet. Until then, my first guess would be to use a 'D' with the same colors as the documentation, like the screenshot below. 
![screen shot 2017-02-10 at 7 39 26 am](https://cloud.githubusercontent.com/assets/1114467/22832787/41b2d306-ef64-11e6-8cce-22aa46208743.png)
We could also close this issue and open a separate one for a logo to use in the favicon, docs, twitter, etc.

**Comment by kedromelon** [comment]
eek tough to get this to look right given the visual weight of the letter -- but something like this?

![draftjs-draft](https://cloud.githubusercontent.com/assets/5393571/22868055/39807024-f15f-11e6-93f5-634291866daa.png)

**Comment by baldwmic** [comment]
@flarnie @kedromelon I added the above favicon to the website in #1526. Let me know what you think!

**Comment by niveditc** [comment]
So it looks like the migration to Docusaurus fixed the page titles. But the favicon is currently broken - #1857 in case someone wants to take a stab at it!
