### ISSUE TITLE
Can we remove notice about issues with Korean input in IE?

### ISSUE THREAD

**Issue by flarnie** [facebook/draft-js#967]
Can we remove the warning in our docs about Korean input bugs in IE, since some significant issues were fixed with https://github.com/facebook/draft-js/pull/820?

https://facebook.github.io/draft-js/docs/advanced-topics-issues-and-pitfalls.html#ime-and-internet-explorer

@spicyj @hellendag wondering what you think

**Comment by robbertbrak** [comment]
Hi @flarnie, I think this warning should *not* be removed yet. As far as I can see, typing Korean on IE11 still doesn't work properly. For example, typing 'dufma<space>' using the Microsoft IME should result in 여름, but the actual result in IE11 on Win10 is 여르름. Definitely a show stopper, if you ask me...

@spicyj notes in #359 that IE11 doesn't fire the proper events when the Korean Microsoft IME is used, so it is rather difficult to get this working in Draft. I took a shot at fixing it, but the result is so hacky that I wouldn't recommend merging it to the Draft core.

**Comment by flarnie** [comment]
Thanks @robbertbrak - we'll leave it then, and I'm glad to understand more about why it's an issue.

**Comment by spicyj** [comment]
Yeah, unfortunately my changes were to fix problems primarily in non-IE browsers.
