### ISSUE TITLE
Deleting a word doesn't delete extra space

### ISSUE THREAD

**Issue by kassens** [facebook/draft-js#97]
On OSX if you select words using double click (and optional drag) and press backspace it deletes the selected word(s) and the beginning of the selection.

Expected behavior on OSX (`[]` is the selection):
1. `foo [bar] baz` (selected by double clicking)
2. <kbd>backspace</kbd>
3. `foo[] baz`

Actual:
1. `foo [bar] baz`
2. <kbd>backspace</kbd>
3. `foo [] baz` (notice space before the selection)

Notice, the current behavior is correct if the selection was made using the keyboard or selection by characters. Not sure it's possible to detect the difference.

**Comment by hellendag** [comment]
Oh interesting, I'd never noticed this. I'll have to check whether the double-click results in a different DOM selection, but my guess is that it doesn't.

(I notice that the <kbd>delete</kbd> key does the same, even though it should in theory be a forward change.)

**Comment by johanneslumpe** [comment]
It looks like the triggered selection events are the same. This might require tracking around mouse events in combination with selection events to figure out whether a selection was made via a double or triple click, drag selecting or something else. But sounds like it could get messy pretty fast.

**Comment by mitermayer** [comment]
Closing this for now as the complexity involved on implementing this feature seems to outweigh the benefits this can provide, as some users (including myself) was not even aware of the differences in behavior of double click backspace.

If anyone is keen on tackling this issue and can come up with a simple solution for it, please feel free to submit a PR
