### ISSUE TITLE
Characters are rendered twice

### ISSUE THREAD

**Issue by jatins** [facebook/draft-js#970]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If I process the `editorState` like this, the final editorState has characters duplicated
```
const createWithContent = EditorState.createWithContent;
const moveFocusToEnd = EditorState.moveFocusToEnd;

function process(editorState) {
  const content = editorState.getCurrentContent()
  return  moveFocusToEnd(createWithContent(content))
}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
https://jsfiddle.net/m6z0xn4r/115/

**What is the expected behavior?**
Character should be typed once

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

`"draft-js": "^0.9.1"`
Chrome Version 55.0.2883.95 (64-bit)
macOS El Capitan

**Comment by jatins** [comment]
I tried the solution given in #667 but even that doesn't seem to work.

**Comment by maratgaip** [comment]
@jatins  it's been fixed on new version.
if you use 0.10.0 version it doesn't do that anymore...
