### ISSUE TITLE
CompositeDecorator callback arguments incorrect in docs.

### ISSUE THREAD

**Issue by jvaill** [facebook/draft-js#973]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

The 0.10.0 migration guide at https://facebook.github.io/draft-js/docs/v0-10-api-migration.html#content lists the composite decorator callback arguments as: `(contentState, contentBlock, callback)`

**What is the expected behavior?**

The actual composite decorator callback arguments as per https://github.com/facebook/draft-js/blob/master/src/model/decorators/CompositeDraftDecorator.js#L71 are `(contentBlock, callback, contentState)`.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

0.10.0

**Comment by flarnie** [comment]
You're absolutely right - will fix.

We had proposed the order be different in the original updates to the code, and I was looking at that version. Thanks for catching this.
