### ISSUE TITLE
Key-repeat does not work for letters

### ISSUE THREAD

**Issue by andsens** [facebook/draft-js#99]
On OSX 10.11.3 key repeat works for everything except normal letters.

Expected behavior:
When holding down a letter key (with or without shift) the editor repeats the letter according the rate and delay set for key-repeat in the OS

Actual behavior:
The letter is only output once and the key has to be hit again to repeat the letter. The mouse cursor flashes in sync with the expected key-repeat but nothing happens.

**Comment by spicyj** [comment]
Interesting, works in both Chrome and Safari on 10.10.5 for me.

**Comment by gscottolson** [comment]
This also didn’t work for me initially, but…

It‘s probably an OS settings issue. Try doing the same key-holding behavior in the browser’s URL bar. My guess is that it doesn’t work there either.

I had to make a change to my system settings via Terminal. Just paste this line, hit enter, then restart any app that is misbehaving:
```defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false```

After this change, the example on the Draft.js homepage works for key-repeat.

**Comment by andsens** [comment]
You're right! I am using chrome and the omnibar didn't work with key-repeat either. Running your `defaults write` worked. Thanks @gscottolson :-)
Closing as a non-issue.
